### ISSUE TITLE
Installing with Composer is not possible because of Monolog

### ISSUE THREAD

**Issue by bonakor** [wp-media/wp-rocket#4900] opened 2022-04-06 10:50 UTC
**Describe the bug**
When I try to install Wp Rocket using Composer, I get this error:
```
Problem 1
    - Root composer.json requires wp-media/wp-rocket v3.11.0.2 -> satisfiable by wp-media/wp-rocket[v3.11.0.2].
    - wp-media/wp-rocket v3.11.0.2 requires monolog/monolog ^1.0 -> found monolog/monolog[1.0.0-RC1, ..., 1.x-dev] but the package is fixed to 2.4.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

**Additional context**
I'm using Bedrock in its latest version and php 8.0

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2022-04-06 13:11
Duplicate of #4105

**Closed as completed by remyperona** 2022-04-06 13:11 UTC
Labels: duplicate
