### ISSUE TITLE
Preview page is coaching by wp rocket .

### ISSUE THREAD

**Issue by eric-ppt** [wp-media/wp-rocket#4659] opened 2022-01-17 08:01 UTC
Page Builder with Elementor . 

**Describe the bug**
Check the preview page . the latest updata can not by update . and changed style can not works . 
I must check the update via forced refresh with the normal page url , 

https://s3.bmp.ovh/imgs/2022/01/52d69c2bf8670332.png

**Comment by eric-ppt** [comment] 2022-01-17 08:04
Sometime i must use "clear coach" to check the update by normal page url .  in preview page "clear coach" can not make the update and style works .

**Comment by piotrbak** [comment] 2022-01-17 12:32
Hello @eric-ppt thank you for creating the issue.

Please contact our [Support team](https://wp-rocket.me/support/), in order to move forward with investigation of this issue. I wasn't able to reproduce it.

I'm going to close it, since it doesn't contain any steps nor using our bug template. As soon as the bug is confirmed, we may want to open a new one with all the steps and correct template.

**Closed as completed by piotrbak** 2022-01-17 12:32 UTC
