### ISSUE TITLE
Compatibility with GIFs and WP Bakery Builder

### ISSUE THREAD

**Issue by cooltronicpl** [wp-media/wp-rocket#4687] opened 2022-01-26 01:22 UTC
The images added as a background image in WP Bakery on the potacki.com website are not lazy-loaded.
Add GIF support to Lazy Load with Webp Support of these files.
Many styles from WP Bakery tag <style> added to a webpage also are not loaded with an option, are old option to add a Critical CSS generated from websites is possible, because now on potacki.com site I'm using Autoptimize to insert Critical CSS, all styles in the body tag which are custom are deleted with Unused CSS option.
There were many problems with Unused CSS with WP Bakery, when I try to remove all style tags, the site is identical like after the Unused CSS option, it is possible to add Fallback CSS with the format from online tools like:
https://pegasaas.com/critical-path-css-generator/

**Comment by piotrbak** [comment] 2022-01-26 11:18
Hello @cooltronicpl we use GitHub to collect confirmed bugs in a specific template that you could see while creating the issue. This template helps us with reproducing the issue and finding the root cause.

You mentioned three different issues, please contact our Support Team to see which of them can be resolved without any changes to the core and which ones need a patch.

**Closed as completed by piotrbak** 2022-01-26 11:18 UTC
