### ISSUE TITLE
Delay JavaScript execution jQuery and jQuery Migrate new regex not working

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5970] opened 2023-06-10 08:44 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The new Delay JavaScript execution regex for jQuery and jQuery Migrate doesn't work.
It works when removing the $ at the end:
\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?

**Expected behavior**
The new regex should work in all cases

**Additional context**
hs: https://secure.helpscout.net/conversation/2262624813/423129
slack: https://wp-media.slack.com/archives/C08N8J6VC/p1686203571360919

**Comment by webtrainingwheels** [comment] 2023-06-14 19:15
This can be replicated by: 
- Activate SG Optimizer
- Go to SG Optimizer → Frontend → General
- Enable: Remove Query Strings from Static Resources

The regex will no longer exclude `jquery.min.js` and `jquery-migrate.min.js`
It will work when removing the $ at the end.

**Comment by joejoe04** [comment] 2023-06-15 00:24
I think I have found a solution for this issue @worldwildweb found with the new default jQuery and jQuery migrate exclusion:
https://wp-media.slack.com/archives/C08N8J6VC/p1686203571360919

I did some logging of `$match` in the `/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php` file [here](https://github.com/wp-media/wp-rocket/blob/53c8e99b6cef65b36fc14ed9b78b00ed07a21985/inc/Engine/Optimization/DelayJS/HTML.php#L206) and I noticed that it's searching the entire `<script>` element as a string rather than just the file name: https://i.imgur.com/NBL4njF.png

So the character at the end of the string for each script will always be the closing tag's `>` character. If you use `jquery.min.js(.*)>$` as an exclusion, it will actually work to exclude the jQuery script (with or without a query string).

This also explains why the regex worked when there was a query string. `(\?(.*))?$` matches either a literal question mark and any characters that follow until the end of the string, OR whatever precedes it (in our case the `s` character from `.js`) as long as it's directly at the end of the string. In the latter case, it was looking for `.js` to be at the very end of the string, but as noted above, the closing `>` is at the end in all cases.

So instead, we need to be looking for the closing single or double quotes after the script file name, and so I think something like this will need to be the updated default exclusion (changed the `$` at the end to `('|")` )

`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?('|")`

We could also take it a step further for edge cases, like if no quotes are used (we look instead for a space between the `src` attribute and another attribute) and if there are no other attributes (we search for the closing tag's `<` character):

`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?('|"| |<)`

This appears to work whether scripts are using single or double quotes, while also not inadvertently excluding files like `jquery.jslint.js`:

https://regex101.com/r/5gtYIw/1
https://i.imgur.com/CIvL7jq.png

Although one issue with using the `<` character is that it gets encoded once you save settings, so not sure we could use that actually: https://i.imgur.com/owUerCL.png

EDIT: I tested some more, and now it seems if I use the following, the `<` is not getting encoded after being saved:

`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?( |'|"|>)`

So maybe this is what we could use. I can confirm it works on my site to exclude jquery scripts with no quotes and no other attributes and/or with other attributes, and avoids excluding scripts with the same edge case that should be excluded (like jquery.jslint.js):
https://i.imgur.com/UiVVC0p.png

**Comment by piotrbak** [comment] 2023-07-02 11:30
It's related to this change:
https://github.com/wp-media/wp-rocket/issues/4371#issuecomment-1513415742

Acceptance Criteria:
1. Regex needs to meet the following patterns: 
- https://regex101.com/r/5gtYIw/1 
- https://regex101.com/r/1qZn7W/1

**Comment by joejoe04** [comment] 2023-07-03 12:30
I did some more testing of my proposed updated default exclusion from my comment above and found that when using it for the Load JavaScript Deferred option, it does not work.

I think the reason is that in this part of the code:
https://github.com/wp-media/wp-rocket/blob/fee96d7c1cc6d18ee07994f0c48ee92b58646660/inc/Engine/Optimization/DeferJS/DeferJS.php#L77

The regex for Load JavaScript Deferred exclusion is being compared only to each script's URL (rather than the entire HTML content like Delay JavaScript Execution): https://i.vgy.me/FbAaMB.png

If I use the regex I that was previously approved as the updated default exclusion (with the $ at the end):
`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?$`

It works to exclude the jquery file from the Load JavaScript Deferred option whether there are query strings present or not:
https://i.vgy.me/FPu2Bu.png
https://i.vgy.me/m36P0t.png

This is all to say that I think we'll need slightly different default exclusions for Load JavaScript Deferred and Delay JavaScript Execution.

Because only the URL for the scripts is used for matching with Load JavaScript Deferred, this would need to be the default exclusion for it:
`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?$`

And because the entire script content is used for matching with Delay JavaScript Execution, this would need to be the default exclusion for it:
`\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?( |'|"|>)`

**Comment by jeawhanlee** [comment] 2023-07-04 09:44
### Scope a solution ✅
From my tests, The REGEX pattern provided by @joejoe04 matches all possible cases for excluding delayJS.
We will update https://github.com/wp-media/wp-rocket/blob/53c8e99b6cef65b36fc14ed9b78b00ed07a21985/inc/Engine/Optimization/DelayJS/Admin/Settings.php#L148 to become: `\/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?( |'|"|>)`

Estimate the effort ✅
[XS]

**Closed as completed** 2023-07-10 13:58 UTC
Labels: type: bug, priority: medium, needs: documentation, effort: [XS], severity: moderate, module: delay JS
