### ISSUE TITLE
RUCSS - wp_wpr_rucss_resources database table was 463MB on a site

### ISSUE THREAD

**Issue by lukecav** [wp-media/wp-rocket#4304] opened 2021-08-31 13:39 UTC
**Describe the bug**
The remove unused CSS feature was enabled on the site which caused the `wp_wpr_rucss_resources` database table to grow to be 463MB in size. On another site, the `wp_wpr_rucss_resources` database table was over 200MB in size.

WP Rocket's current version is being used is 3.9.2 on WordPress version 5.8.

**Comment by lukecav** [comment] 2021-09-02 16:57
Looks related to
https://github.com/wp-media/wp-rocket/issues/4161

**Comment by iCaspar** [comment] 2021-10-18 15:14
Duplicate of #4161

**Closed as completed by iCaspar** 2021-10-18 15:14 UTC
Labels: duplicate
