### ISSUE TITLE
Preload links - The non-webp page is fetched when our WebP feature is used.

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3134] opened 2020-09-21 09:05 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the following features are enabled:
1. **Preload links**
2. **Enable WebP caching**

prefetching a URL will fetch the version of the page that doesn't contain WebP images. This is because WP Rocket prefetches the `index-https.html` file, not the `index-https-webp.html`.

**To Reproduce**
1. Use `.webp` images on a page.
2. Enable **Preload links**.
3. **Enable WebP caching**
4. Visit the URL. You should see WebP images.
5. Navigate to another page, and hover over the same URL, as in step 4. Then click on it.
6. The page will not use WebP images.

**Expected behavior**

The `-webp.html` page should be fetched.

**Screenshots**

Screencast pf the issue: https://youtu.be/Z5AFAHP8euM

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1285380102/195678?folderId=3864740

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment] 2020-09-23 20:24
### Reproduce the problem
Reproduced on local installation

### Identify the root cause
This is happening because the prefetch request sent by the browser doesn't contain the same `Accept` header value than a normal request.

Example of a normal request from Chrome:
`text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9`

Example of a prefetch request from Chrome:
`application/signed-exchange;v=b3;q=0.9,*/*;q=0.8`

Since the header is missing the `webp` value, the cache file served during the prefetch request is the default one, not the one for webP.

### Scope a solution

The issue with that is that we have no control over the headers sent by the browser when doing a prefetch request. This means it's not fixable on the plugin side.

This looks like a `wontfix` for me @arunbasillal

**Comment by arunbasillal** [comment] 2020-09-24 14:34
Thanks for the test @Tabrisrp, that explains why it fails. 

I did some digging and as per this doc - https://www.w3.org/TR/resource-hints/#prefetch
>The as attribute can be used by the application to communicate the resource destination context, such that the user agent can optimize the fetching process - e.g. set appropriate request headers, transport priority, and so on.

I tried to test this using the list here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Attributes
But couldn't produce a `webp` in the request header. 

I will remove this from the sprint for now and keep this as something that needs investigation. Maybe we can figure out a work around. I couldn't think of anything yet. As Lucy would say, some things needs to marinate.

**Comment by Tabrisrp** [comment] 2020-09-24 14:52
We are fetching a whole HTML page, not a specific type of resource, so the `as` attribute doesn't work for this type of request here.

To note that webP is now supported in all major browsers, as the latests version of Safari (14) is available and included in the latest iOS version. So having a separate cache file for webp version is going to be much less needed.

**Comment by arunbasillal** [comment] 2020-09-25 07:41
Really good point @Tabrisrp 🙌 - https://caniuse.com/?search=webp

**Comment by DahmaniAdame** [comment] 2020-11-15 08:16
Related ticket - https://secure.helpscout.net/conversation/1337258043/211712

**Comment by GeekPress** [comment] 2021-02-05 21:04
I'm closing this issue as as @Tabrisrp explained we don't seem to have any way to fix that problem.

**Closed by GeekPress** 2021-02-05 21:04 UTC
Labels: module: preload, priority: medium, type: bug, wontfix
