### ISSUE TITLE
RUCSS missing Chaty widget markup

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5799] opened 2023-03-07 11:11 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The [chaty.app](https://chaty.app/) has a setting that will restrict viewing their chat widget on specific URLs. 

![image](https://user-images.githubusercontent.com/1289174/223404760-b4b78489-fd4e-4132-a54f-265e9fc92707.png)

The URL won't allow the chat widget to show up on URLs with query strings, like the ones used to check the page by the RUCSS SaaS (with `?nowprocket=1&no_optimize=1` at the end of URLs). 

This will cause the chat widget style not to get processed, as we don't see any related markup to extract selectors from, and we don't see any stylesheet to shake. 

Checking with the plugins developers to automatically propagate the visibility to whatever URLs are included as well as `?nowprocket=1&no_optimize=1`. 

Alternatively, we can preserve the chat widget styles (file and inline style). 

The temporary fix is to add a batch of visibility rules with the `?nowprocket=1&no_optimize=1` URL parameters. 

**To Reproduce**
1. Use the Chaty.app
2. Restrict visibility to specific pages
3. See that the chat widget won't show up

**Expected behavior**
chaty.app should be visible out of the box. 

**Screenshots**
Added to description. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2159789504/401888/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2023-03-13 13:08
@DahmaniAdame Do you know if there's any filter there that we could use to add our query strings to the 'displayed' list?

**Comment by DahmaniAdame** [comment] 2023-03-14 10:45
@piotrbak I couldn't see any usable code for that in their plugin's code.

**Comment by piotrbak** [comment] 2023-04-14 15:13
I've just contacted their team.

**Comment by piotrbak** [comment] 2023-04-25 12:00
The issue is fixed on their end 🚀

**Closed as completed by piotrbak** 2023-04-25 12:00 UTC
Labels: type: enhancement, waiting for feedback, 3rd party compatibility, priority: low, module: remove unused css
