### ISSUE TITLE
Proposal: Fix incorrectly entered prefetches

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2255] opened 2020-01-15 21:23 UTC
I see incorrect prefetch entries all the time: 

![wrong_prefetch](https://user-images.githubusercontent.com/1043076/72472818-30b6d080-379a-11ea-824d-fde8c3e9d2ce.jpg)

Could we automatically fix them?

**Steps to Reproduce:** 

- In `Preload` tab > `Prefetch DNS Requests`
- Add an incorrect prefetch entry like `http://example.com` (or `https://example.com`)
- This should be automatically corrected to `//example.com` (i.e. no protocol) when a user clicks `Save Settings`

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment] 2020-02-28 16:47
**Reproduce the issue** ✅ 
Reproduced on my local test site

**Identify the root cause** ✅ 
In the `sanitize_callback()` method, we sanitize the field but we don't have anything to remove the scheme from the entries: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/classes/admin/settings/class-settings.php#L250

**Scope a solution** ✅ 
We can add an additional sanitize to remove the `http(s)` scheme from each URL in the textarea field.

**Estimate the effort** ✅ 
The code change itself is very low effort. The current state of the sanitize_callback() method though might make writing automatic tests for this change very complicated.

**Comment by Tabrisrp** [comment] 2020-02-28 21:50
@hellofromtonya will need your input for the testing part of `sanitize_callback()`

**Comment by arunbasillal** [comment] 2020-03-06 09:28
**Acceptance criteria**

Customer inputs any of these: 
- `http://domain.com`
- `https://domain.com`
- `http://domain.com/example`

WP Rocket converts this to: 
- `//domain.com`

**What if:**

- customer inputs `http:///domain.com` (triple or more slashes) 
^ My suggestion is that we ignore this for now. This is invalid input. The output will be `///domain.com`

- customer inputs `http://domain.com/` (trailing slash)
^ We keep the trailing slash. It's okay for `dns-prefetch` to have trailing slash. 

- customer inputs `ftp://domain.com` (other protocols)
^ we can ignore all other protocols for now and do nothing. Just as we do in WP Rocket 3.5.0.x

**Comment by hellofromtonya** [comment] 2020-03-16 17:24
Moving this one to 3.5.2 for us to do the following requirements:

- Detect malformed URLs, such as `http:///domain.com` or more more `\`
- Repair these URLs.

**Closed** 2020-03-31 09:29 UTC
Labels: effort: [S], module: preload, priority: low, type: enhancement
