### ISSUE TITLE
RegEx issue with malformed HTML in addLazyloadClass

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2706] opened 2020-02-25 15:47 UTC
In `Image::addLazyloadClass`, the RegEx used can fail when parsing malformed HTML: https://regex101.com/r/ojjr00/2.

Possible improvement: https://regex101.com/r/ojjr00/3.

**Comment by crystinutzaa** [comment] 2020-06-15 15:37
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
@Tabrisrp made a good investigation and that regex seems to be off with malformed HTML.

**Scope a solution** ✅ 
Solution proposed by Remy is valid and seems much more suitable than the current one

**Effort** ✅ 
Effort `[XS]`

**Comment by crystinutzaa** [comment] 2020-06-25 21:20
Issue will be fixed in https://github.com/wp-media/rocket-lazyload-common PR  https://github.com/wp-media/rocket-lazyload-common/pull/76

**Closed** 2020-07-02 16:02 UTC
Labels: effort: [XS], module: lazyload, priority: low, type: bug
