### ISSUE TITLE
PHP Warning: Attempt to read property "id" on bool in /inc/Engine/Optimization/RUCSS/Database/Queries/ResourcesQuery.php on line 144

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4207] opened 2021-07-29 11:55 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.1.1.
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
The following PHP error appear when Remove Unused CSS option is enabled:
```
PHP Warning: Attempt to read property "id" on bool in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/ResourcesQuery.php on line 144
PHP Warning: Undefined array key "external" in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php on line 123
PHP Warning: Undefined array key "path" in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php on line 123
PHP Fatal error: Uncaught ValueError: Path cannot be empty in /wp-admin/includes/class-wp-filesystem-direct.php:39
Stack trace:
#0 /wp-admin/includes/class-wp-filesystem-direct.php(39): file_get_contents('')
#1 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/UrlTrait.php(125): WP_Filesystem_Direct->get_contents(NULL)
#2 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php(123): WP_Rocket\Engine\Optimization\RUCSS\Warmup\ResourceFetcherProcess->get_file_content(NULL)
#3 /wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php(183): WP_Rocket\Engine\Optimization\RUCSS\Warmup\ResourceFetcherProcess->get_resource_contents(Array)
#4 /wp-content/plugins/wp-rocket/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php(315): WP_Rocket\Engine\Optimization\RUCSS\Warmup\ResourceFetcherProcess->task(Array)
#5 /wp-content/plugins/wp-rocket/inc/classes/dependencies/wp-media/background-processing/wp-background-process.php(175): WP_Rocket_WP_Background_Process->handle()
#6 /wp-includes/class-wp-hook.php(303): WP_Rocket_WP_Background_Process->maybe_handle('')
#7 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#8 /wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#9 /wp-admin/admin-ajax.php(202): do_action('wp_ajax_nopriv_...')
#10 {main}
thrown in /wp-admin/includes/class-wp-filesystem-direct.php on line 39
```

**To Reproduce**
Reproduced on the customer's site where Mod PageSpeed was enabled.
Ticket: https://secure.helpscout.net/conversation/1585279114/283557

Could be reproduced on sites with dynamic CSS.

**Expected behavior**
No errors should be logged.

**Additional context**
From @engahmeds3ed 

> This error means that there are unprocessed CSS files but not in the local database.
> We can add a check there if the row is on the DB.

Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1627552530047100

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment] 2021-08-16 08:42
The customer from the ticket @NataliaDrause worked on reported issues with the error being logged even though the feature was deactivated. This is because there were more than 193.000 `rucss_warmup_resource_fetcher` entries in the `options` table, that were "processed".

This looks similar to the following preload issue:
https://github.com/wp-media/wp-rocket/issues/3680

**Comment by remyperona** [comment] 2021-08-25 20:24
Duplicate of #4243

**Closed as completed by remyperona** 2021-08-25 20:24 UTC
Labels: duplicate
