### ISSUE TITLE
"Disable Emojis" causes Caldera Forms error

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1720] opened 2019-05-15 16:52 UTC
Just moving this into a separate issue for clarity, from here: https://github.com/wp-media/wp-rocket/issues/1561#issuecomment-491105459

This error occurs when Disable Emojis is active:
![caldera_test_–_WordPress_Themes](https://user-images.githubusercontent.com/1043076/57493375-76b9ad00-7279-11e9-9eb4-de8e766ae22b.jpg)

Commenting out this line resolves it :
https://github.com/wp-media/wp-rocket/blob/master/inc/common/emoji.php#L11

HS tags: `disable emojis` + `caldera forms`

**Comment by vmanthos** [comment] 2019-05-16 08:38
Another ticket with the issue:
https://secure.helpscout.net/conversation/845945917/106763?folderId=2135277

**Comment by evolluti0n** [comment] 2019-05-16 18:09
I confirm that the issue is present in my testing site. 
WordPress version: 5.2
PHP version: 7.3
Caldera Forms version: 1.8.4
WP Rocket version: 3.3.3

Before WP Rocket 3.3.3 version, forms failed to submit if 'Disable WordPress embeds' was enable. To submit the form, I had to disable this option. The 'Disable Emoji' option was active. 

Now, after the update. I had to swap the options. Un-tick 'Disable Emoji' and tick 'Disable WordPress embeds'.

Please check the following error in browser console:

```
Uncaught ReferenceError: wp is not defined
    at Object.<anonymous> (index.min.js?ver=1.8.4:30)
    at Object.782 (index.min.js?ver=1.8.4:30)
    at t (index.min.js?ver=1.8.4:1)
    at calderaForms.render.0 (index.min.js?ver=1.8.4:1)
    at index.min.js?ver=1.8.4:1
caldera-forms-front.min.js?ver=1.8.4:1 Uncaught TypeError: Cannot read property 'CF5cd1b712d0e07_1' of undefined
    at Object.init (caldera-forms-front.min.js?ver=1.8.4:1)
    at HTMLFormElement.<anonymous> (jquery-baldrick.min.js?ver=1.8.4:1)
    at HTMLFormElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLFormElement.r.handle (jquery.js?ver=1.12.4:3)
```

**Comment by pixelbrad** [comment] 2019-05-16 21:42
This issue only triggers for me if **both** Disable WordPress embeds and Disable emoji options are checked. If I uncheck Disable WordPress embeds but leave Disable emoji checked, the issue is not present. If I uncheck Disable Emojis but leave Disable WordPress embeds checked, the issue is not present.

WordPress 5.2
PHP 7.3.2
Caldera Forms 1.8.4
WP Rocket 3.3.3

**Comment by Shelob9** [comment] 2019-05-28 16:42
I opened a core trac ticket for this: https://core.trac.wordpress.org/ticket/47419#ticket

**Comment by arunbasillal** [comment] 2020-09-28 06:17
It seems this issue is taken care of by  - https://github.com/CalderaWP/Caldera-Forms/pull/3202

We also do not have recent tickets about the same. Closing this issue.

**Closed by arunbasillal** 2020-09-28 06:17 UTC
Labels: 3rd party compatibility, module: media, priority: low, type: bug
