### ISSUE TITLE
Add Delay JS exclusion related to Revolution Slider 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4037] opened 2021-06-11 14:01 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
[x] Made sure you’re on the latest version
[x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
If a user keeps our default list of Delay JS exclusion, a JS error will be triggered related to Revolution Slider. It's because an inline script isn't inserted by using `wp_add_inline_script`.

**Expected behavior**
Automatically add this pattern `setREVStartSize` to our default exclusion list. It's safe to exclude as it contains onlyused to declare a function.

**Additional context**
The complete inline script:

```
<script type="text/javascript">function setREVStartSize(e){ 
try { 
var pw = document.getElementById(e.c).parentNode.offsetWidth, 
newh; 
pw = pw===0 || isNaN(pw) ? window.innerWidth : pw; 
e.tabw = e.tabw===undefined ? 0 : parseInt(e.tabw); 
e.thumbw = e.thumbw===undefined ? 0 : parseInt(e.thumbw); 
e.tabh = e.tabh===undefined ? 0 : parseInt(e.tabh); 
e.thumbh = e.thumbh===undefined ? 0 : parseInt(e.thumbh); 
e.tabhide = e.tabhide===undefined ? 0 : parseInt(e.tabhide); 
e.thumbhide = e.thumbhide===undefined ? 0 : parseInt(e.thumbhide); 
e.mh = e.mh===undefined || e.mh=="" || e.mh==="auto" ? 0 : parseInt(e.mh,0); 
if(e.layout==="fullscreen" || e.l==="fullscreen") 
newh = Math.max(e.mh,window.innerHeight); 
else{ 
e.gw = Array.isArray(e.gw) ? e.gw : [e.gw]; 
for (var i in e.rl) if (e.gw[i]===undefined || e.gw[i]===0) e.gw[i] = e.gw[i-1]; 
e.gh = e.el===undefined || e.el==="" || (Array.isArray(e.el) && e.el.length==0)? e.gh : e.el; 
e.gh = Array.isArray(e.gh) ? e.gh : [e.gh]; 
for (var i in e.rl) if (e.gh[i]===undefined || e.gh[i]===0) e.gh[i] = e.gh[i-1]; 
var nl = new Array(e.rl.length), 
ix = 0, 
sl; 
e.tabw = e.tabhide>=pw ? 0 : e.tabw; 
e.thumbw = e.thumbhide>=pw ? 0 : e.thumbw; 
e.tabh = e.tabhide>=pw ? 0 : e.tabh; 
e.thumbh = e.thumbhide>=pw ? 0 : e.thumbh; 
for (var i in e.rl) nl[i] = e.rl[i]<window.innerWidth ? 0 : e.rl[i]; 
sl = nl[0]; 
for (var i in nl) if (sl>nl[i] && nl[i]>0) { sl = nl[i]; ix=i;} 
var m = pw>(e.gw[ix]+e.tabw+e.thumbw) ? 1 : (pw-(e.tabw+e.thumbw)) / (e.gw[ix]); 
newh = (e.type==="carousel" && e.justify==="true" ? e.gh[ix] : (e.gh[ix] * m)) + (e.tabh + e.thumbh); 
} 
if(window.rs_init_css===undefined) window.rs_init_css = document.head.appendChild(document.createElement("style")); 
document.getElementById(e.c).height = newh; 
window.rs_init_css.innerHTML += "#"+e.c+"_wrapper { height: "+newh+"px }"; 
} catch(e){ 
console.log("Failure at Presize of Slider:" + e) 
} 
};</script>
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2021-06-11 14:05
@iCaspar Do you think you can add this one into your current PR exclusion? 😇

**Comment by iCaspar** [comment] 2021-06-14 13:04
@GeekPress I am not able to reproduce this. On my install, the script loads correctly. Do you have a page where the issue was found that I could look at?

**Comment by GeekPress** [comment] 2021-06-14 13:15
> @GeekPress I am not able to reproduce this. On my install, the script loads correctly. Do you have a page where the issue was found that I could look at?

Sorry, I didn't keep the website's URL and I don't remember which one it was.

Are you using the default exclusion list?

**Comment by iCaspar** [comment] 2021-06-14 13:19
I have DelayJS activated and everything is default locally -- including the new default exclusions on the previous PR issue.

**Comment by GeekPress** [comment] 2021-06-14 13:24
By exclusion, I mean the exclusion in the field, not in the code.

**Comment by GeekPress** [comment] 2021-06-14 13:25
This one 👇

```
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.]*(.min|.slim|.slim.min)?.js
js-(before|after)
```

**Comment by iCaspar** [comment] 2021-06-14 15:07
Both @Mai-Saad and I have been unable to reproduce an issue using the default exclusions.
@Mai-Saad did note the following:
```
HYG what I found there (tested on 2 sites with rev slider)
with default exclusion  sent by Remy or Jonathan, there is no error on console and slider displayed normally
when we exclude only jquery  the error displayed in console and slider not displayed => in this case, if we excluded setREVStartSize the error will be removed but slider still won't be displayed
tested on https://new.rocketlabsqa.ovh/revslider/  (this with default execlusion) and https://rocketlabsqa.ovh/rev/ (this with jquery)
```
So there is an issue with REVSlider when excluding `jquery` by itself, but at least under otherwise default conditions the current exclusions seem ok.

Going to add `needs r&d` for now. If we can find some sites where the issue is happening, we may be able to pinpoint better what is happening.

**Comment by GeekPress** [comment] 2021-06-15 07:40
@Mai-Saad @iCaspar I noticed a new pattern to auto-exclude since the last Revolution Slider version (6.5.0), it's `window.RS_MODULES`

If we don't exclude it by default and if we keep the default exclusion list, the slider won't be displayed until user interaction.

Please check this video:
https://share.getcloudapp.com/2Nuqjomm

**Comment by Mai-Saad** [comment] 2021-06-15 09:22
@GeekPress Yes I can see that slider won't be displayed until user interaction using the last Revolution Slider version (6.5.0) with/without default exclusion here https://new.rocketlabsqa.ovh/revslider/.
Agree to exclude `window.RS_MODULES` so it works correctly.

**Comment by iCaspar** [comment] 2021-06-15 13:22
### Grooming Notes (Round 2)

### Reproduced: ✅ 
With new version, `window.RS_MODULES` causes display to delay to user interaction on our test site.

### Cause ✅ 
The new `window.RS_MODULES` is inserted outside of the normal WP enqueue process.

### Solution ✅ 
1. Add `window.RS_MODULES` to default exclusions.
2. Add Script sample to tests.

### Effort Estimate
`[XS]`

(Should have this ready to go for 3.9.0.2)

**Comment by piotrbak** [comment] 2023-02-14 10:54
Closing it, default exclusion is present in the backend, `window.RS_MODULES` is added already to the 3rd-parties in 3.13

**Closed as completed by piotrbak** 2023-02-14 10:54 UTC
Labels: 3rd party compatibility, priority: high, effort: [XS], module: delay JS
