### ISSUE TITLE
WP rocket still loads the Elementor JS files that are disabled with the new Elementor asset loading experiment enabled

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#3544] opened 2021-02-01 23:59 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
X Made sure you’re on the latest version
X Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Tested: occurs with minification and concentation, as well delay javascript are on. These are the settings that give me the best performance, so that's what i tested it with. It seems to be an issue with wp-rocket concentating and including the swiper js even when it is not supposed to be loaded.

The number of assets that should be loaded has decreased on all pages, this is confirmed via asset cleanups js/css files list, there are numerous js files that are supposed to no longer load on the page. The largest of these js files is swiper.js, with over 100+ kb of unnecessary data loaded on every page that does not contain a slider. The homepage does not have a slider on it, or anything that uses the swiper js library at all. The asset does not show up in the loaded list of assets in asset cleanup at all. It should by all accounts not load on the page. 

Even on pre 3.1, if you disable the swiper.js file via asset cleanup with the ignore dependencies option checked, the file is always loaded. This only occurs with Elementor based js files. I'm not sure why. The issues with dequeuing these files seems to only apply to elementor js files regardless of how they're dequeued(asset cleanup or the new elementor update). Other js/css files I've dequeued with asset cleanup ARE removed from the page weight and improve the sites load time.

However, when I run the site through pagespeed insights, gtmetrix or any other speed scanner, the page weight is identical and the site loads in exactly the same time, no performance increase. This leads me to believe that WP-Rocket still loads and compresses the file regardless of whether the experiment in elementor is active or not.  Swiper ALWAYS loads.

**To Reproduce**
1. Install elementor
 
2. Activate Wp-rocket and enable minification and concentation for css and js, as well as delay javascript.

3. Activate an both elementor and elementor pro with the latest version under 3.1(the version just before 3.1 was released), as it does not have the asset loading experiment

4. Build a page that does not include a slider so that the swiper js file shouldn't be relevant to the page's functioning. (This ensures the asset does not appear in the loaded asset list in asset cleanup once you activate the asset loading experiment in 3.1.1 AFTER building the page in the elementor version PRE 3.1 first.)

5. Run it through a speedtest and notate the page size

6. Update elementor to 3.1.1

7. Enable the asset loading experiment

8. Check asset cleanup to confirm/ensure the file no longer appears in the list for a page, it should appear to not be loading at all.

9. Clear the cache to ensure old cache files that should contain the swiper js file due to elementor pre 3.1 loading it on the page and including the asset regardless of whether it was being utilized. This ensures new cache files are generated for 3.1.1 with the asset loading experiment enabled.

10. Speed test the site again, the page weight has not decreased, and the loading time scores have not improved. WP-Rocket still loads the JS file even though it is not supposed to be included in the minified/compressed files.

**Expected behavior**
A page weight reduction equal to the size of the files no longer being loaded. WP-Rocket should automatically detect the experiment has been activated and exclude the files that are not supposed to be loaded on the page from minification and concentation, so the expected page size reduction happens and performance of the site improves. The new elementor update with the experiment enabled is supposed to decrease page weight by up to 177 KB, my site should have between 480-550 KB loaded after enabling the experiment.

My mobile pagespeed insights score is in the 60's-70 range(there's variance between tests. Make sure you run at least 12 tests, 6 at a time in multiple tabs to accurately measure the pagespeed. I recommend running the test 3 times in all tabs for a total of 18). 70 is my top end score for pagespeed insights mobile. After enabling the asset loading feature, my scores should jump to always be in the 70's or 80's range due to the expected gigantic reduction in page size. 

Once you run the first test, you can just copy paste the url into a new tab and it will automatically re-run the test, i just open it in 6 different tabs at a time and run the tests at the same time. There's zero chance of my site being overloaded, i've run load tests with 10k users within 15 seconds and my site can handle the load with zero failures.

Testing multiple times on pagespeed insights gives you a much more accurate picture of the loading times if you average the scores together. That's why I listed a range of scores that average from 60-70.

**Screenshots**
![wp rocket](https://user-images.githubusercontent.com/31750063/106533066-4599fb00-64a6-11eb-8b94-184ea5f570e7.PNG)

The page weight does not change whatsoever after elementor is updated and the asset loading experiment has been enabled. The page weight size does not decrease at all from the older elementor that does always load swiper, to 3.1.1 with the feature enabled. The values remain identical. WP-Rocket should auto-detect the asset loading changes and reduce the size of the page accordingly. 

**Additional context**
I even tried using a file manager plugin and deleted all the files out of the cache>min>1 folder, and they regenerated after visiting the homepage, so I know they are fresh cache files.

Additionally, If I use the older version of elementor and try to disable the swiper.js file from loading on the page with ignore dependencies checked, the page weight remains the same. It seems there is an issue specific to that file, that it is always included in the minified/concentated files, regardless of if it is supposed to be disabled or not. This applies to both the new elementor 3.1.1 update and the version pre 3.1, the file is ALWAYS loaded regardless of whether it is supposed to be active or not. Swiper ALWAYS loads.

I'm not sure why this is specific to swiper or additionally the other elementor js files that are supposed to not load on this page, but I would assume it's due to not being compatible with the way elementor dequeues the file to be loaded.

I know this is for js files, but i've even tried the elementor regenerate css option just in case, didn't fix it.

Supporting dequeuing elementor js files, especially when the experiment is active, is imperative. This is supposed to massively increase the performance of elementor and I'm completely unable to take advantage of the reduction in page weight size while wp-rocket is active. I should be able to take advantage of this feature. It would significantly improve load times and conversion rates on my ecommerce site. Elementor is traditionally considered one of the slower page builders, and it's in part due to these unnecessary js files that are loading on every page.

Please test this and do not just close the issue. This is a real problem and I've tried to go to great lengths to explain and document the why, what and how of what's happening. I would sincerely appreciate if you could give this bug the attention it deserves. Please at least respond and let me reply before closing. I assure you this issue IS happening to me, and I would really love it if you could fix it. The elementor asset loading is currently an experiment, but it will become the standard behavior in a future update.

Seeing as Elementor has over 5 million users, that's a ton of people that do not get any benefit from the feature with wp-rocket active. I've tested this extensively, and this is reproducible for me on a fresh wordpress install and a default theme.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by patche81** [comment] 2021-02-06 02:03
please fix this asap, this is extremely annowing

**Comment by jazir555** [comment] 2021-02-06 22:07
@GeekPress @Tabrisrp

**Comment by jazir555** [comment] 2021-02-07 04:52
https://developers.elementor.com/experiment-optimized-asset-loading/

I found this article on their developers subdomain which explains the change in how they handle asset loading. You may have to contact the elementor devs.

**Comment by piotrbak** [comment] 2021-02-16 17:54
@jazir5 I wasn't able to reproduce this. After enabling the Asset Loading experiment, the following Elementor files were not added to the combined JS file:
`preloaded-elements-handlers.min.js`
`swiper.min.js`
Also, the combined file was smaller. To find out what are the scripts included in the Combined JS file, you can use WP Rocket's debug log:
1. Disable Cache Preload feature
2. Enable JS combination, keep CSS combination disabled and enable Elementor's experimental feature, clear cache
3. Add `define( 'WP_ROCKET_DEBUG', true);` to your `wp-config.php`
4. Visit the page without slider in incognito mode
5. Remove  `define( 'WP_ROCKET_DEBUG', true);` as it creates many entries
6. Visit the following URL: `yourdomain.com/wp-content/wp-rocket-config/wp-rocket-debug.log.html`
7. Search for "tag(s) remaining." This is the list of scripts included in the Combined file.

You can compare the list to the one when the Asset Loading experiment is disabled to see the difference.

**Comment by GeekPress** [comment] 2021-02-24 12:10
@jazir5 We are closing this issue for now. Nobody else reported a bug like between WP Rocket and the new Elementor version. Feel free to comment if you still have the problem.

**Closed as completed by GeekPress** 2021-02-24 12:10 UTC
Labels: community, invalid, 3rd party compatibility

**Comment by takemeoutevents** [comment] 2021-03-15 13:17
@piotrbak 

I am debugging a somewhat different problem. Whenever i enable improved asset loading i notice that js files coming from elementor like the ones u mentioned

/swiper.min.js
.bundle.min.js ( 5 different files that have text editor, nav menu, gallery etc in the file name)

are not in the combined js file coming from wp rocket anymore but are loaded on my page as seperate files.

So instead of having 1 js file loading i have now got 6 js files.

Is that also what you experienced when you were saying: 

he following Elementor files were not added to the combined JS file:
preloaded-elements-handlers.min.js
swiper.min.js

Or were you saying that there was still 1 combined js file loaded however when you inspected debug log you could see these files were not added to the combined js file anymore?

Kind regards,

Dominic

**Comment by piotrbak** [comment] 2021-03-15 13:37
@takemeoutevents 
> Or were you saying that there was still 1 combined js file loaded however when you inspected debug log you could see these files were not added to the combined js file anymore?

Exactly, this is what I was experiencing.

Thanks!

**Comment by takemeoutevents** [comment] 2021-03-15 16:09
@piotrbak 

I hope you don't mind me following up on this but i am currently asking wp rocket support about this:

**my question: Can you tell me if the js files can be combined by wp rocket even with Improved Asset Loading active?**

**Their answer: If the JavaScript files are combined, you won't be able to dynamically load the parts that you need because all the code in one file.**

This seems to be conflicting with your experience right?

I think they are saying if improved asset loading is enabled i can't have 1 combined js file since improved asset loading means it loads the elementor js files only when needed when visitor scrolls down the page therefor loading seperate files right?

Does wp rocket support have the wrong idear what improved asset loading does?

I hope you will help me out here because i am not at all an expert here. Just a guy owning a website with an obsession for caching and speed :)

Kind regards,

Dominic

**Comment by piotrbak** [comment] 2021-03-15 16:31
@takemeoutevents This doesn't seem to be related to this specific issue on GitHub.

Elementor's feature is supposed not to load specific files when they're not used on the page.

WP Rocket simply adds to the combined file whatever JS it finds in the HTML source. The exception here is when the scripts are excluded or **loaded by other scripts**, and this is what's happening in your case. We combine everything we have in the HTML but the Elementor's JS is loading further scripts.

**Comment by Salimoh** [comment] 2021-06-23 10:28
I also had the same issue on my [website](https://iranbatri.com) which uses Betheme - wprocket and elementor page builder. This problem needs to be addressed because Betheme is a really popular plugin.

**Comment by zachnicodemous** [comment] 2021-08-04 18:27
> So instead of having 1 js file loading i have now got 6 js files.

I am having this same issue on one of my client sites; the Elementor JS files you mentioned are not being combined by WP-Rocket. Did you ever find a fix for this?

**Comment by Salimoh** [comment] 2021-08-10 22:15
It was my mistake that I added elementor to wp-rocket exclusion list. Maybe that is your problem as well. check js exclusion field. Any way with the introduction of js delay by wp-rocket 3.9 merging js is not important anymore.
________________________________
