### ISSUE TITLE
Cache folder cleanup necessary on plugin deactivation

### ISSUE THREAD

**Issue by JanThiel** [wp-media/wp-rocket#2500] opened 2020-04-01 07:49 UTC
**Describe the bug**
Using the suggested nginx integration ( rocket-nginx ) you can get a stale cache when deactivating the WP-Rocket plugin. The nginx config is not accessable by PHP / WordPress and thus can only rely on static files existance or not. The nginx config cannot be changed  on plugin deactivation like one could do with .htaccess files for apache.
Even on apache, disabling the plugin will leave stale copies of the cached pages within the cache/wp-rocket/ folder. Wasting storage and might pose a risk of unwanted access to content one might believe changed / deleted.

**To Reproduce**
1. Activate the Plugin
2. Have some page cache files created (wp-content/cache/wp-rocket/[DOMAIN]/...)
3. Disable (do not delete) the plugin
4. The cache files (step 2) remain on disk
5. Changing the cached pages in WordPress will not change the delivery to the user  because nginx will serve the existing cached files and they will not be updated when WP-Rocket is disabled

**Expected behavior**
- When disabling the plugin a similar cleanup should happen as on deletion ( https://github.com/wp-media/wp-rocket/issues/2352 ). 
- At a minimum all cached files (page, css, js, etc. => wp-content/cache/wp-rocket/[DOMAIN]/ ) on the disk have to be deleted.
- The deletion has to be SITE specific to work well on Multisites.

**Additional context**
Setup:
- WordPress 5.3.2
- WP-Rocket 3.5.2
- Multisite
- nginx

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by GeekPress** [comment] 2020-04-01 08:38
Hi @JanThiel 🤚

Thanks for your contribution.

@arunbasillal @Tabrisrp @hellofromtonya What are your thoughts about this suggestion?

**Comment by arunbasillal** [comment] 2020-04-01 12:00
This is a duplicate of #2210 (we could close one of these)
I had added my thoughts here: https://github.com/wp-media/wp-rocket/issues/2210#issuecomment-570348284

**Comment by Tabrisrp** [comment] 2020-04-01 12:16
The issue I see with this is that if the deactivation is temporary, everything has to be regenerated after reactivation. It's not uncommon for someone to deactivate for testing, and that would be very annoying for them.

It's also a side-effect caused by a third party, not by the plugin itself. While we acknowledge the rocket-nginx integration, it's not our role to support and fix issues created by it.

**Comment by JanThiel** [comment] 2020-04-01 13:03
@arunbasillal You are correct. I missed that ticket, sorry!

@Tabrisrp 
We could consider different deactivation handling based on the used Webserver which could be kindoff guessed by checking `$_SERVER['SERVER_SOFTWARE']` ? Like: On nginx, delete cache. Do other things on others.

> While we acknowledge the rocket-nginx integration, it's not our role to support and fix issues created by it.

I do get your point, but that means that WP-Rocket does not officially support nginx at all based on your feedback - do you? 
I honestly believe that you should not consider this as "fixing issues created by (rocket-nginx)" but creating  a setup which works on nginx and apache, especially if the required changes are minor. Which they are at least in my oppinion.

> .... and that would be very annoying for them

I agree, this would be **just** _annoying_. But for nginx users having stale cache is a real blocker. So weighting both, I would argue in favour for solving a blocker instead of not to annoy apache users. Especially as most users will not even realize that the cache has to be built up again which anyway happens each and every x (10 by default?) hours.

As far as I can see, the other ticket ended up discussing about wether WP-CLI triggers the activation / deactivation hooks. Which seems not to be the case. Which matches our experiences as well.

Should we move the discussion to the other ticket or vice versa?

Best regards,

Jan

**Comment by JanThiel** [comment] 2020-05-04 06:34
Hey guys, happy StarWars day ;-)
Any updates / thoughts on this one?

While re-reading the thread, I believe I missed an important statement, I would like to comment on.

> It's also a side-effect caused by a third party, not by the plugin itself.

@Tabrisrp I strongly disagree. The side effect is caused by the plugin neglecting the way nginx works and only focussing on techniques which are from apache-only land. Especially "being able to configure the webserver from PHP code - by using the .htaccess file". 
nginx relies on the "truth" of the filesystem. Based on things being there or not being there it deliveres one thing, or something else. 

Just to get a quick understanding of the nginx challenges, please take this 5 minute read: https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#check-if-file-exists
https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

Based on the nginx design patterns, this issue is currently close to **impossible** to solve using sane and recommended nginx configs. Because there is **no** way for an outside entity (nginx) knowing whether the plugin is active or not. There is nothing on the filesystem based on that nginx could determine a cache being active or stale.
The single best practice approach remains to be to only put cached files into the wp-rocket cache folders, if the cache is active and should be delivered. 

If you still do not agree, then having at least a "flag" file (```/wp-content/cache/wp-rocket/[DOMAIN]/.cache-active```) could solve this issue also as a workaround / hack. But this is absolutely bad practice in nginx land and a no-go performance-wise due to an additional ```if file exists``` check which could and should be easily avoided.

If - after all - you still do not see any need for change. Please at least be fair and honest with your customers and add a "We do not officially support nginx" to your website / docs and the marketing comparism charts. Because other caching solutions work very well with nginx and also do that out of the box with official configs. If WP-Rocket does not and you do not want to - be honest with your customers.

Have a great start into the week!

Jan

**Comment by maximejobin** [comment] 2020-05-04 17:54
The team at WP-Rocket was kind enough to add a "dot file" in the past so that Rocket-Nginx could detect if mobile cache was active. Having such file (aka `.cache-active`) would make Rocket-Nginx know if files must be served or not.

It seems like a good option where they don't break their way of doing things and also enable Rocket-Nginx to track if the plugin is activated or not.

**Comment by GeekPress** [comment] 2020-05-04 19:50
@Tabrisrp @hellofromtonya What do you think about @maximejobin solution? It seems to be a good compromise?

**Comment by arunbasillal** [comment] 2020-05-05 12:53
@GeekPress Wouldn't this mean that existing NGINX users will have to update their NGINX config to see the impact? 

Since NGINX users are are minority, why not delete the entire cache on WP Rocket deactivation (as suggested here: https://github.com/wp-media/wp-rocket/issues/2210#issuecomment-570348284) and keep things simple? 

Cache gets regenerated on cache lifespan anyway. It happening on plugin deactivation and subsequent activation isn't that big of a deal. 

**Another idea**: On Nginx, what if we rename the `wp-content/cache/wp-rocket/domain.com` folder to `wp-content/cache/wp-rocket/domain.com-deactivated`? And then rename it back on plugin activation. Seems much easier and backwards compatible.

**Comment by JanThiel** [comment] 2020-05-05 13:13
@arunbasillal 
> @GeekPress (Regarding MaximeJobin's solution): Wouldn't this mean that existing NGINX users will have to update their NGINX config to see the impact?

Yes, to make this change work, a new version of nginx configs is necessary. Deleting the files will work out of the box with no required changes on the servers.

> Another idea: On Nginx, what if we rename the wp-content/cache/wp-rocket/domain.com folder to wp-content/cache/wp-rocket/domain.com-deactivated? And then rename it back on plugin activation.

True and also correct. This will also work for nginx and I would prefer it over the ".cache-active" solution.
Still, as you don't know how old the cache is after reactivation, you might end up deleting and recreating it anyway.

**Comment by arunbasillal** [comment] 2020-05-06 07:53
> Still, as you don't know how old the cache is after reactivation, you might end up deleting and recreating it anyway.

This is a good point. Once WP Rocket is deactivated, we no longer know if the cache is current or not. None of our automatic cache clearing works. Thanks @JanThiel 

Imho, we should simply delete the entire cache on plugin deactivation. Trying complicated solutions simply to avoid inconvenience to some customers and possibly end up serving stale cache is unnecessary work. Deactivating the plugin is a manual action after all and customers deactivate it for a reason (e.g.: either to update something in the theme or when some change they made is not visible).

**Comment by maximejobin** [comment] 2020-05-06 15:36
I would say I have to agree that deleting the directory when the plugin is deactivated is what makes more sense to me. Having old cache makes no sense to me. I don't understand why it would make sense to keep it because you never know how long the plugin was deactivated.

I might not have all use cases in mind though. This is my 2 cents.

**Comment by GeekPress** [comment] 2020-05-13 21:33
Let's go with the cache folder cleanup after deactivation. As the entire cache will be deleted, we will also trigger an automatic preload after plugin activation. 

@Tabrisrp I suppose that we will also need to clear the minified / concatenated file folder?

**Comment by crystinutzaa** [comment] 2020-05-18 20:48
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
The root cause is in here:
https://github.com/wp-media/wp-rocket/blob/1d17d9be39d06c92059dc5b9081a551e2262ab5e/inc/main.php#L107
During deactivation WP Rocket cache is not deleted.

**Scope a solution** ✅ 
The solution will be to delete all cache files at deactivation.
@Tabrisrp , @hellofromtonya I think minified / concatenated JS , CSS files needs to be cleaned too.
What about busting and critical css files? Should also be deleted?

At plugin activation, if Preload option is active, it needs to trigger the automatic preload.

Also shouldn't we move these 2 functions in the new structure:
`inc/Engine/WPRocketActivate.php`
`inc/Engine/WPRocketDeactivate.php`
which should be hooked into:
`do_action( 'rocket_activation' );`
`do_action( 'rocket_deactivation' );`


**Effort** ✅ 
Effort `[S]` up to an [M] , I think Unit & Integration tests will need almost all the effort.
Should it be an S or an M?

**Comment by Tabrisrp** [comment] 2020-05-19 12:52
If go we from the logic that we can't know how long the plugin is deactivated, and that everything could be stale when reactivated, we would need to clear everything on deactivation.

My concern is about CPCSS files, because they take a long time to generate, and with CPCSS for posts, it could be very annoying for our customers to have to regenerate them all.

For the structure change, we have to be careful, because the activation/deactivation hooks don't behave the same way than the rest at all.

**Comment by arunbasillal** [comment] 2020-05-19 13:09
> For the structure change, we have to be careful, because the activation/deactivation hooks don't behave the same way than the rest at all.

Thanks for the heads up Remy. If we are doing this, I think its safer to make this part of a major release so that we can take advantage of the staggered release process.

**Comment by NataliaDrause** [comment] 2021-06-27 07:28
similar request: https://secure.helpscout.net/conversation/1553247086/274379

**Comment by piotrbak** [comment] 2024-06-26 10:56
Not enough feedback here to be implemented in the nearest future.

**Closed by piotrbak** 2024-06-26 10:56 UTC
Labels: type: enhancement, community, module: cache, priority: medium, needs: documentation, effort: [M]

**Comment by JanThiel** [comment] 2024-06-26 11:42
@piotrbak What kind of feedback did you miss? Wasn't aware that you asked for any?!

**Comment by piotrbak** [comment] 2024-06-26 11:54
@JanThiel Basically, our backlog currently is around 700 items. We're cleaning it a bit to make sure it's easier manageable by closing the issues which will not be implemented in the mid term. It doesn't mean that it'll not be implemented in general, but the impact of this issue on our customers is pretty low. That's why it's being moved to the "queue"
