### ISSUE TITLE
PHP fatal error with PHP 8.1, repo / Composer installation and WP Rocket's debugging enabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5918] opened 2023-05-11 12:49 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13.2`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When:
1. PHP cli `8.1.*` is used & the server is running PHP `8.1.*`.
2. Installing WP Rocket from our repo and running `composer install`.
3. WP Rocket's debugging is enabled  `define( 'WP_ROCKET_DEBUG', true);`.

the following PHP Fatal error is logged to the `debug.log`:

```PHP
PHP Fatal error:  Uncaught Error: Interface "Psr\Log\LoggerInterface" not found in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/vendor/monolog/monolog/src/Monolog/Logger.php:34
Stack trace:
#0 /shared/httpd/wprocketest/htdocs/wp-content/advanced-cache.php(51): require()
#1 /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php(187): {closure}('Monolog\\Logger')
#2 /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php(83): WP_Rocket\Logger\Logger::get_logger()
#3 /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-abstract-buffer.php(120): WP_Rocket\Logger\Logger::info('CACHING PROCESS...', Array)
#4 /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php(60): WP_Rocket\Buffer\Abstract_Buffer->log('CACHING PROCESS...', Array, 'info')
#5 /shared/httpd/wprocketest/htdocs/wp-content/advanced-cache.php(75): WP_Rocket\Buffer\Cache->__construct(Object(WP_Rocket\Buffer\Tests), Object(WP_Rocket\Buffer\Config), Array)
#6 /shared/httpd/wprocketest/htdocs/wp-settings.php(95): include('/shared/httpd/w...')
#7 /shared/httpd/wprocketest/htdocs/wp-config.php(137): require_once('/shared/httpd/w...')
#8 /shared/httpd/wprocketest/htdocs/wp-load.php(50): require_once('/shared/httpd/w...')
#9 /shared/httpd/wprocketest/htdocs/wp-blog-header.php(13): require_once('/shared/httpd/w...')
#10 /shared/httpd/wprocketest/htdocs/index.php(17): require('/shared/httpd/w...')
#11 {main}
  thrown in /shared/httpd/wprocketest/htdocs/wp-content/plugins/wp-rocket/vendor/monolog/monolog/src/Monolog/Logger.php on line 34
```

According to @engahmeds3e:
> the problem is coming from the PSR/Log, with php 8.1 they have the following structure:
`/vendor/psr/log/src/LoggerInterface.php`
https://github.com/php-fig/log/blob/master/src/LoggerInterface.php
>
>but with php 7.4 they have the following structure in v1.1.4
`vendor/psr/log/Psr/Log/LoggerInterface.php`
https://github.com/php-fig/log/blob/1.1.4/Psr/Log/LoggerInterface.php
>
> So, the problem is coming from our advanced_cache.php file template exactly here:
https://github.com/wp-media/wp-rocket/blob/cfe483d7f55934bc912c71628d95fe7dce751d85/views/cache/advanced-cache.php#L49

**To Reproduce**

The steps are described in the **Describe the bug** section.

**Expected behavior**

No PHP fatal error should occur when PHP `8.1.*` is used alongside WP Rocket's debugging when the installation was performed using Composer. 

**Additional context**

[Slack discussion (internal link)](https://wp-media.slack.com/archives/GUT7FLHF1/p1683802670918819)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment] 2023-05-13 18:10
I have a case with the same error where WP Rocket was not installed via Composer, and without the debug being active. 
The only thing in common is PHP `8.1`.
https://secure.helpscout.net/conversation/2241671075/419738
I will ask for creds. 
@engahmeds3ed would you mind having a look on Monday if you have a chance? 
@vmanthos do you know if the same issue is there on PHP `8.2` as well?

**Comment by Mai-Saad** [comment] 2023-05-15 07:46
Duplicated with https://github.com/wp-media/wp-rocket/issues/5386

**Comment by Miraeld** [comment] 2023-11-20 04:52
## Reproduce the problem
To reproduce the issue, follow the step given the problem explanation.

## Identify the root cause
The issue is that, as stated in the problem explanation: 
> the problem is coming from the PSR/Log, with php 8.1 they have the following structure:
> `/vendor/psr/log/src/LoggerInterface.php`
> https://github.com/php-fig/log/blob/master/src/LoggerInterface.php

> but with php 7.4 they have the following structure in v1.1.4
> `vendor/psr/log/Psr/Log/LoggerInterface.php`
> https://github.com/php-fig/log/blob/1.1.4/Psr/Log/LoggerInterface.php

> So, the problem is coming from our `advanced_cache.php` file template exactly here:
> https://github.com/wp-media/wp-rocket/blob/cfe483d7f55934bc912c71628d95fe7dce751d85/views/cache/advanced-cache.php#L49


## Scope a solution
To solve the issue, we could change this line : https://github.com/wp-media/wp-rocket/blob/cfe483d7f55934bc912c71628d95fe7dce751d85/views/cache/advanced-cache.php#L49
to 
```php
if (version_compare(PHP_VERSION, '8.1.0', '>=')) {
	$file = $rocket_path . 'vendor/psr/log/src/' . str_replace('\\', '/', $class) . '.php';
} else {
	$file = $rocket_path . 'vendor/psr/log/' . str_replace('\\', '/', $class) . '.php';
}
```

## Development steps:

## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

**Comment by CrochetFeve0251** [comment] 2023-11-20 09:44
@Miraeld The path to the to files is depending on the PSR version and not the PHP version.
I think we should a fallback system for the monolog as we did here: https://github.com/wp-media/wp-rocket/blob/400dcb7c1e9905f92d40102fa7b636fd93628fe3/views/cache/advanced-cache.php#L42

**Comment by Miraeld** [comment] 2023-11-20 11:44
## Reproduce the problem
To reproduce the issue, follow the step given the problem explanation.

## Identify the root cause
The main issue here is the version of the librairie which changes the path. Depending on the version we need to load a path or another one. 

## Scope a solution
To fix this issue, we can add 
```php
'WP_Rocket\\Dependencies\\Psr\\Log' => [
	$rocket_path . 'inc/Dependencies/Psr/Log/' . str_replace( '\\', '/', $class ) . '.php',
	$rocket_path . 'vendor/psr/log/src/' . str_replace('\\', '/', $class) . '.php',
],
``` 
to `$rocket_classes` here : 
https://github.com/wp-media/wp-rocket/blob/400dcb7c1e9905f92d40102fa7b636fd93628fe3/views/cache/advanced-cache.php#L33

And do not forget to delete 
https://github.com/wp-media/wp-rocket/blob/400dcb7c1e9905f92d40102fa7b636fd93628fe3/views/cache/advanced-cache.php#L70

At the same time, we could refactor this one 
https://github.com/wp-media/wp-rocket/blob/400dcb7c1e9905f92d40102fa7b636fd93628fe3/views/cache/advanced-cache.php#L63
with the same method. 

## Development steps:

## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

**Comment by CrochetFeve0251** [comment] 2023-11-20 12:36
Seems good to me

**Comment by Mai-Saad** [comment] 2023-11-27 14:53
The issue isn't reproducible using 3.15.5, Will close it for now. We can reopen it once it happens.

**Closed as completed by Mai-Saad** 2023-11-27 14:53 UTC
Labels: type: bug, module: Logger, priority: medium, effort: [XS], severity: major
