### ISSUE TITLE
RUCSS: stylesheets without .css extension are not being processed

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4252] opened 2021-08-18 13:18 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.1.1.
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When a stylesheet is added to a site without the `.css` extension as in example here:
`<link rel='stylesheet' type="text/css" href='https://example.com/wp-content/themes/twentytwentyone/mystyle' media='all' />`
this stylesheet is not warmed-up by our tool and it remains on the site unprocessed.

This can cause broken layout (wrong styles being applied) due to the stylesheet being out of order, because it is added after the Used CSS and it overwrites Used CSS styles.

**To Reproduce**

1. Create two stylesheets with identical CSS content: one with `.css` extension, another one without. Save them on the server. Example:
/wp-content/themes/twentytwentyone/mystyle.css
/wp-content/themes/twentytwentyone/mystyle

2. Enqueue both stylesheets in the head as following:
```
<link rel='stylesheet' type="text/css" href='https://example.com/wp-content/themes/twentytwentyone/mystyle' media='all' />
<link rel='stylesheet' type="text/css" href='https://example.com/wp-content/themes/twentytwentyone/mystyle.css' media='all' />
```

3. Enable _Remove Unused CSS_
4. When the process is completed check the site. `https://example.com/wp-content/themes/twentytwentyone/mystyle` stylesheet will be present on the site unprocessed.

**Expected behavior**
All stylesheets have to be processed

**Additional context**
Manual warmup of the resource is returning the error "_Warm-up request received with some invalid resources_".
![image](https://user-images.githubusercontent.com/60236665/129905037-31e413dd-f687-4170-8558-7dcb4266627b.png)

Ticket: https://secure.helpscout.net/conversation/1591179277/285201?folderId=3864740#thread-4666083408
Slack thread: https://wp-media.slack.com/archives/C029G1B5HD2/p1629011918007500

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment] 2021-10-01 05:34
Related ticket: https://secure.helpscout.net/conversation/1646634460/298171/

**Comment by CrochetFeve0251** [comment] 2022-04-26 15:09
@piotrbak I tried with the SAAS in local and my local Wordpress and the file was process.
Look like it has been fixed with the new SAAS.

**Comment by CrochetFeve0251** [comment] 2022-04-27 15:31
### Identify the root cause
The  problem come from the regex in the [method `remove_used_css_from_html`](https://github.com/wp-media/wp-rocket/blob/6f905396f43c1831c370848e9c36bf14e72ab545/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L300) from the class `RUCSS\Controller\UsedCSS`.
### Scope a solution
A solution would be to change [this regex](https://github.com/wp-media/wp-rocket/blob/6f905396f43c1831c370848e9c36bf14e72ab545/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L300) to a new one to include file not finishing with .css:
`'<link\s+([^>]+[\s"\'])?href\s*=\s*[\'"]\s*?(?<url>[^\'"]+(?:\?[^\'"]*)?)\s*?[\'"]([^>]+)?\/?>'`
### Estimate effort
Effort `XS`

**Closed as completed** 2022-05-19 13:43 UTC
Labels: type: enhancement, priority: low, effort: [XS], module: remove unused css
