### ISSUE TITLE
CSS Critical Path is too high in the source code blocking Facebook/Twitter bots

### ISSUE THREAD

**Issue by wp-seopress** [wp-media/wp-rocket#2636] opened 2020-05-12 09:56 UTC
Hi,
some CSS critical path generated by WP-Rocket are too large.

**Problem**: some metadata like title/open graph / twitter cards tags are too low in source code.

Bots like FB bot stop reading source code after 60KB to get social metadata like OG Image.

**Solution**:
- hook later
- limit the number of lines of the CSS critical path (on some clients sites, we have hundred CSS lines).

We would like to avoid to hook earlier our metadata to have, first, the default meta title, then the social meta tags and the other ones.

**Comment by GeekPress** [comment] 2020-05-15 08:21
@wp-media/wprocketplugin What are your thoughts about that?

**Comment by Tabrisrp** [comment] 2020-05-15 11:46
The critical CSS in inserted right after the 1st closing `</title>` tag found on the page. We can't use a different anchor, because we have no guarantee it would be there (title is pretty much a given).

About the solutions:
>Hook later

We can't really do that, we currently hook on `rocket_buffer`, not on `wp_head`, because we need to know we're in the caching context. Which means we already go after all other plugins, which have already inserted their code.

We also have to make sure it's inserted before any CSS files, else it defeats the purpose. For example, our combined CSS is inserted right after the `</title>` tag too.

> limit the number of lines of CPCSS

it's a risk of having display/PageSpeed issues if we remove important CSS from it

I understand the issue, but there we both need to be as early as possible on the page. So I don't have a solution right now, but we can discuss it with the dev team.

**Comment by arunbasillal** [comment] 2020-05-15 12:15
How common is this issue? 60KB of CSS for the view port seems a lot. 

What if these bots are excluded from cache? The user agents of these bots can be added to the `Never Cache User Agent(s)` are in WP Rocket Advanced tab. 

Would be an easy case-by-case solution if the issue isn't too common.

**Comment by GeekPress** [comment] 2020-05-21 08:57
@hellofromtonya @cristianuibar @engahmeds3ed If you have any ideas too about this one, you're welcome :)

**Comment by GeekPress** [comment] 2021-02-11 20:26
As CPCSS needs to be loaded as soon as possible, I'm afraid that on our side we aren't going to change the placement after the </title> tag.

**Closed by GeekPress** 2021-02-11 20:26 UTC
Labels: module: critical-path, type: bug, wontfix
