### ISSUE TITLE
Enhancement - Exclude PDF From gzip

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#772] opened 2018-02-21 13:39 UTC
Add PDF to the excluded list in the core by default, for three reasons:

1. PDF is not a loaded during a page load and doesn't really affect the page load performance.
2. While it isn't mandatory, PDF's are often compressed and additional GZIP compression might not be required. 
3. PDF's have the potential to be bigger than the max file size for gzip as set by webservers and will not be gzipped anyways.
4. Users who sold PDF's via WooCommerce had issues with file download when gzip was enabled. 

Notes to self: 
Function: `get_rocket_htaccess_mod_deflate()`
Line: `$rules .= '\\.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g|mp4|webm|webp)$ no-gzip dont-vary' . PHP_EOL;`

**Comment by WordPresseur** [comment] 2019-04-01 13:45
This issue seems to be back:
- https://secure.helpscout.net/conversation/750953894/92541
- https://secure.helpscout.net/conversation/813690109/102031
- https://secure.helpscout.net/conversation/801601758/100256
- https://secure.helpscout.net/conversation/813690109/102031
- https://secure.helpscout.net/conversation/614871151/73153/

**Comment by arunbasillal** [comment] 2019-04-03 08:00
Going to re-open this issue so that we can test this and see what is up.

**Comment by WordPresseur** [comment] 2019-06-04 12:34
Another case: https://secure.helpscout.net/conversation/867491305/109996?folderId=1213662

**Comment by WordPresseur** [comment] 2019-06-05 13:06
Another case: https://secure.helpscout.net/conversation/869603107/110270?folderId=1213662

**Comment by WordPresseur** [comment] 2019-06-14 11:58
Another case: https://secure.helpscout.net/conversation/877598587/111358?folderId=1213662

**Comment by WordPresseur** [comment] 2019-08-28 09:10
Another case: https://secure.helpscout.net/conversation/941043749/120753/

**Comment by WordPresseur** [comment] 2019-09-30 14:34
Another case: https://secure.helpscout.net/conversation/968273618/124833?folderId=1213662

**Comment by WordPresseur** [comment] 2019-10-09 12:15
Another case: https://secure.helpscout.net/conversation/975253145/125918?folderId=1213662

**Comment by WordPresseur** [comment] 2020-01-10 08:45
Another case: https://secure.helpscout.net/conversation/1050961476/140059?folderId=1213662

**Comment by Tabrisrp** [comment] 2020-03-23 14:10
I'm not able to reproduce the issue as presented on the different tickets.

- Deflate rules are present in the `htaccess`
- I created a new downloadable PDF product with WooCommerce, and tested the download link with 3 browsers: Chrome, Safari & Firefox. For all of them, the PDF dowloaded correctly.
- The download link uses the following format:

`https://tests.local/?download_file=1820&order=wc_order_EvyfJWWsZUGON&email=remperona%40gmail.com&key=54127056-b699-4c34-baa4-3f78f8010495`

Did the same test with WP Download Manager, still working as expected.

We will need more details there to understand what is happening

**Comment by GeekPress** [comment] 2020-03-23 14:33
@Tabrisrp We know the issue with a special configuration on OVH.

As we know that PDF don't have an impact on the loading time, I guess we can make the change without trying to replicate the problem.

**Comment by Tabrisrp** [comment] 2020-03-30 14:29
@GeekPress The change in the initial post is already in the plugin since version `2.11.7`.

The working solution for tickets above is to remove the deflate rules, but I don't think we have a way to know that we are currently on an OVH server? And that wouldn't be a good solution to remove it for everyone on OVH either anyway.

**Comment by GeekPress** [comment] 2020-03-30 14:55
@Tabrisrp Good to know, I didn't know that we already did the change. 

As the initial demand was to include PDF in the excluded list, and it's included since 2.11.7, I'm closing this one.

About OVH, you're right. It won't be a good solution to remove the deflate rules for everybody.

**Closed by GeekPress** 2020-03-30 14:55 UTC
Labels: module: htaccess, priority: low, type: enhancement

**Comment by WordPresseur** [comment] 2020-04-10 11:57
Another case: https://secure.helpscout.net/conversation/1125592122/155191?folderId=1213662

**Comment by DahmaniAdame** [comment] 2021-03-19 06:41
Related - https://secure.helpscout.net/conversation/1451140329/246781/
Our PDF exclusion from GZIP still had file download issues. 
The customer reported disabling manually that particular section + adding custom GZIP directives fixed the issue for them.

**Comment by webtrainingwheels** [comment] 2025-01-03 16:27
https://secure.helpscout.net/conversation/2805750051/532677?viewId=377611
same issue on ovh, here with .ics calendar file. 
removing gzip rules fixes it.

**Comment by jekayode** [comment] 2025-01-21 20:05
Same issue here> https://secure.helpscout.net/conversation/2825062671/536272?viewId=273766
Could not download WPR Settings. 

Error on Firefox: C:\Users\Me\Downloads\NQ51ono6.json.part cannot be saved because the source file cannot be read.

Error on Chrome: "Download Settings" first fail and then when I click on (resume) it works

**Comment by webtrainingwheels** [comment] 2025-04-02 01:13
https://secure.helpscout.net/conversation/2886001506/548273

The issue affects other file types, not just PDf. We updated our doc about this recently:
https://docs.wp-rocket.me/article/1661-can-t-download-pdf-files-when-wp-rocket-is-active
