### ISSUE TITLE
WP Rocket Plugin Update Message: "Compatibility with WordPress Unknown"

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4127] opened 2021-07-03 17:18 UTC
**Describe the Bug**

WP Rocket plugin update message does not indicate if it's compatible with the latest version of WordPress.

**To Reproduce**

Steps to Reproduce the Behavior:

1. Check for plugin updates.
2. Before updating plugin, review update message. Message currently states: "**Compatibility with WordPress 5.7.2: Unknown**"
 
**Expected Behavior**

Plugin update should indicate latest compatibility version with WordPress (like most plugins do) . Example: "**Compatibility with WordPress 5.7.2: 100% (according to its author)**"

**Screenshots**

<a href="https://postimg.cc/YjxvhRCW" target="_blank"><img src="https://i.postimg.cc/ZYGpsDkV/wp-rocket-wordpress-compatibility-message.png"></a>

**Comment by remyperona** [comment] 2021-07-15 22:36
Duplicate of #3570

**Closed as completed by remyperona** 2021-07-15 22:36 UTC
Labels: duplicate
