### ISSUE TITLE
Optimize inline and external JavaScript with Minify JavaScript option

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1118] opened 2018-08-09 18:13 UTC
**Is your feature request related to a problem? Please describe.**
Customer sites on HTTP/2 who don't want to combine JS would like to take advantage of this feature.

**Describe the solution you'd like**
The ability to optimize inline and external JavaScript with the Minify JavaScript file option

**Describe alternatives you've considered**
N/A

**Additional context**
Customer wanted to use the feature introduced in 3.1 for Combine JavaScript files with their site on HTTP/2

**Comment by arunbasillal** [comment] 2020-09-09 13:18
@Tabrisrp Isn't this a duplicate of #2810?

**Comment by GeekPress** [comment] 2021-02-10 16:51
Indeed, it seems to be a duplicate of #2810 for the external JS files, but I'm not sure to understand the enhancement on inline scripts.

**Closed by GeekPress** 2021-02-10 16:51 UTC
Labels: duplicate, module: file optimization, type: enhancement
