### ISSUE TITLE
Tiktok (ttclid) and touch() File name too long

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#6113] opened 2023-08-21 12:03 UTC
Hello
Recently we are noticing big query string due to tiktock click IDs, and touch fails
touch(): Unable to create file ..... because File name too long

Is there any way to skip the ID or rename it to something smaller, so it can fit?

**Comment by piotrbak** [comment] 2024-07-15 13:28
It's a duplicate of this issue:
https://github.com/wp-media/wp-rocket/issues/2440

**Closed as not planned by piotrbak** 2024-07-15 13:28 UTC
Labels: type: enhancement, 3rd party compatibility, module: cache, priority: medium, needs: r&d, needs: product cleanup

**Comment by danieliser** [comment] 2024-12-26 20:46
@piotrbak Please see my comments on #2440, this should not even be an error, and is simple enough to check for before you try writing to a specific path. Please for the love of clean logs just add a check on the lenght of a path before attempting to write it. Max 255 bytes on `NIX.
