### ISSUE TITLE
WP rocket preferd load non webp cache although I use supported webp browser

### ISSUE THREAD

**Issue by thanh25896** [wp-media/wp-rocket#2329] opened 2020-02-20 11:48 UTC
**Describe the bug**
WP rocket preferd load non-webp.html although on supported webp.html if non.webp.html exits
**To Reproduce**
1. Enable webp caching via wp-rocket setting
2. Only "webp.html" cache was automatically generated
3. When I used support webp browser to access my site it loaded webp images (nothing error here)
4. When I used unsupported webp browser to access my site , A "non-webp.html" was generated
5. I used supported browser to access my site again and it loaded png/jpeg images instead of webp images

P/S :I though wp-rocket preferd loading "non-webp.html" for all browser if "non-webp.html" is exist

**Backlog Grooming**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2020-02-28 10:44
Hi @thanh25896 🤚

Thanks for your contribution.

To help us working on this issue, it will be awesome if you can edit your initial post by respecting our template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by thanh25896** [comment] 2020-02-28 11:15
Edited content

**Comment by GeekPress** [comment] 2020-02-28 15:15
@GeekPress Thanks a million 🙏

**Comment by Screenfeed** [comment] 2020-03-10 15:31
Hello @thanh25896, thanks for your report.

1- Could you tell us which webp-compatible browser do you use?
2- Is it the same browser you describe in your 3 and your 5?

**Comment by thanh25896** [comment] 2020-03-11 02:54
1 - I used latest chrome browser
2 - Yes

P/S : I use EWWW plugin for created webp img

**Comment by Screenfeed** [comment] 2020-03-11 15:51
Thank you @thanh25896.

**Comment by Tabrisrp** [comment] 2020-03-16 19:50
I'm not able to reproduce the issue when testing with the current `develop` branch.
- Homepage contains a jpg image, the webp version of the image exists
- WebP cache is enabled
- Visit homepage with firefox: `index-webp.html` is created
- Visit homepage with Safari: `index.html` is created
- Reload homepage with firefox: `index-webp.html` is directly served

This issue is either `invalid` or got fixed with the changes we made during 3.5.1 sprint

**Comment by thanh25896** [comment] 2020-03-16 20:08
Oh I'm sorry ! I Recheck it and realized it problem cause of "rocket nginx" module prefer non_webp html if It exist . It problem maybe old code not update for 2.5 years

**Comment by Tabrisrp** [comment] 2020-03-16 20:17
Thank you for the feedback! I'm going to close this issue then.

**Closed by Tabrisrp** 2020-03-16 20:17 UTC
Labels: community, invalid
