### ISSUE TITLE
Cloudflare Flexible SSL compatibility - Potential redirect loop on WP Rocket deactivation

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2153] opened 2019-12-04 17:32 UTC
- Cristina has fixed the compatibility issue at our end in 3.4.1 #1922 
- Customers will be prompted to deactivate the official Cloudflare plugin and when they do, the redirect issue won't happen.

However: 
- If the customer deactivate WP Rocket without enabling Cloudflare's plugin first, they are back to this problem

Proposed solution #1:

- During deactivation, show a warning (as we show when when writing permissions are missing - https://jumpshare.com/v/RrcZxoAmgVJkKqjOOCVB ) that warns customers of the issue and ask them to activate the Cloudflare plugin first.
- Then have a button that activates Cloudflare plugin for them and deactivates rocket.
- The issue is that the customer might have deleted the Cloudflare plugin by now but we can detect it.

Proposed solution #2:

- Show the warning during deactivation to the customer and warn them as before. Suggest to disable Flexible SSL to avoid the issue.
- The button disables Flexible SSL and then deactivates WP Rocket.

**In fact, the above two solutions could be combined:**

- During WP Rocket deactivation, suggest to activate Cloudflare plugin or disable Flexible SSL.
- If we can detect a Cloudflare plugin installed, our button in the admin notice can enable it and then deactivate WP Rocket.
- If Cloudflare plugin isn't detected, the button disables Flexible SSL and then deactivates WP Rocket.

Reading: 

- Slack conversation - https://wp-media.slack.com/archives/G8L4EE8N9/p1570748466057900
- https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options
- https://support.cloudflare.com/hc/en-us/articles/115000219871-Troubleshooting-redirect-loop-errors

**Comment by vmanthos** [comment] 2020-01-31 06:52
A related ticket: https://secure.helpscout.net/conversation/1069003239/143477/

**Comment by webtrainingwheels** [comment] 2020-04-24 17:43
Related ticket: https://secure.helpscout.net/conversation/1145208086/160258/

**Comment by webtrainingwheels** [comment] 2020-06-22 19:18
https://secure.helpscout.net/conversation/1201696304/174792?folderId=377611

**Comment by webtrainingwheels** [comment] 2020-06-23 19:37
https://secure.helpscout.net/conversation/1197469695/173572/

**Comment by webtrainingwheels** [comment] 2020-06-23 19:46
https://secure.helpscout.net/conversation/1092103250/147737/

**Comment by webtrainingwheels** [comment] 2020-06-23 19:50
@GeekPress I've added this to the Support Wishlist because: 
1. I think we have more cases than linked on this issue
2. It's a really nasty experience for users when it does happen!
There's some stuff we can do in the documentation in the meantime, but would be ideal to address it in the plugin too
(cc: @danijacome )

**Comment by GeekPress** [comment] 2020-06-26 13:55
> If the customer deactivate WP Rocket without enabling Cloudflare's plugin first, they are back to this problem

@arunbasillal Can you please elaborate on the why here? I'm not sure to understand why we have the problem.

What about if Flexible SSL is on, and the user doesn't use CF plugin? Does the redirection loop happens too?

**Comment by GeekPress** [comment] 2020-06-26 13:59
From Kinsta blog:

> This is due to having SSL setup on your web server already and then having Flexible SSL enabled with Cloudflare. If you have an SSL certificate with your web host (Kinsta) already, then you will want to switch the SSL mode to full.

https://kinsta.com/knowledgebase/install-cloudflare/

I'm even more interesting about my question 👆

**Comment by piotrbak** [comment] 2020-06-26 14:12
@GeekPress 

Flexible SSL is securing only the route from the browser to Cloudflare. If you have a certificate on the server, you should use the Full mode in Cloudflare.

The problem with redirection happens when (mostly on shared servers) `$_SERVER` array is set to `HTTP`, basically, the customer's site is installed as HTTP and they're switching to HTTPS in a not very clean way. The workaround is to set the `$_SERVER` array value to `HTTPS`, that's what we're doing with our Cloudflare Add On and that's also the same Cloudflare plugin is doing, as far as I know:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/common/cloudflare-flexible-ssl.php#L108

Maybe we could somehow check the value of the `$_SERVER['HTTPS']` (without our code being applied) before deactivation?

Hopefully, it helps.

**Comment by arunbasillal** [comment] 2020-07-01 14:49
@GeekPress Sorry I missed your ping from before. I am not exactly sure of the why any more than what @piotrbak said. 

Let me ping @crystinutzaa here so that she can pitch in. She knows this the most I believe.

**Comment by crystinutzaa** [comment] 2020-07-01 20:29
@GeekPress yes you are correct. The issue is present without WP Rocket.
However the issue appears only when WP Rocket is deactivated.

The user flow is like this: it has Cloudflare (which has the fix inside) -> installs WP Rocket plugin. WP Rocket asks the user to deactivate Cloudflare plugin. WP Rocket has the fix of Flexible SSL inside too. So everything works.

However at deactivation of WP Rocket, the fix is not present. So the user will report that deactivating WP Rocket plugin their website is broken. Even if is not related to WP Rocket, the user experience is bad because is connected to WP Rocket.

I think that at deactivation we can apply this fix in their `wp-config.php` file automatically and inform the client, so that the user will not remain with a "broken" website when WP Rocket is deactivated. 

The know-how of Flexible SSL is explained by @piotrbak very well.

**Comment by GeekPress** [comment] 2020-07-02 06:55
Thanks everybody for explanation, it's totally clear now :)

@arunbasillal Does having Cloudflare plugin just turned on fix the Flexible SSL issue? Without needing to configure the plugin.

> If Cloudflare plugin isn't detected, the button disables Flexible SSL and then deactivates WP Rocket.

How can we disable Flexible SSL?

**Comment by arunbasillal** [comment] 2020-07-02 16:47
@GeekPress I believe the plugin needs to be configured, but the assumption was that the plugin was already configured before installing WP Rocket. It's an assumption, so we could be wrong. 

> If Cloudflare plugin isn't detected, the button disables Flexible SSL and then deactivates WP Rocket.

This was a proposal. I am guessing since we have the API access we could disable it in Cloudflare. Just as we enable it via our UI. If we can do this, this (and letting the user know that we are doing this via a notice) would be ideal I think.

**Comment by GeekPress** [comment] 2020-07-06 07:59
>  I believe the plugin needs to be configured

@arunbasillal Can we check to be sure? If the plugin don't need to be configure, we could automatically install / activate this plugin to avoid the issue.

**Comment by Tabrisrp** [comment] 2020-07-13 14:53
I'd like to use this issue to open this conversation: Should it be WP Rocket role to handle Cloudflare SSL configuration?

To me, it feels out of scope of our plugin goals. It's not related to any performance optimization Cloudflare applies, and forces us to manage this in the code with various hacks & hoops, which have side-effects (See issues #2156 & #2421).

It also generates support tickets for our support on something that is not related to the website performance itself, but the configuration of a 3rd party service.

**Comment by GeekPress** [comment] 2020-07-24 08:25
@Tabrisrp If we remove this to WP Rocket, we are going to have a problem with all users which rely on us to have Flexible SSL.

If we remove this, we will have to automatically installed and forced the activation of Cloudflare Flexible SSL plugin to be sure our users won't have an infinite redirect loop.

**Comment by juricazuanovic** [comment] 2021-03-13 11:10
Related ticket: https://secure.helpscout.net/conversation/1450555652/246460/

**Comment by webtrainingwheels** [comment] 2021-08-17 21:02
https://secure.helpscout.net/conversation/1602450963/287737?folderId=377611

**Comment by viobru** [comment] 2022-10-04 10:42
Related: https://secure.helpscout.net/conversation/2021206825/371239
In this case, the customer tried deactivating WP Rocket to troubleshoot another issue and the site crashed.

**Comment by viobru** [comment] 2022-11-04 16:15
Related: https://secure.helpscout.net/conversation/2053179903/378311
In this case, the too many redirects error was displayed after the customer rolled back to a previous version of WPR.

**Comment by piotrbak** [comment] 2024-06-25 13:33
This doesn't seem to be implemented. We don't have feedback for a while, feel free to reopen

**Closed by piotrbak** 2024-06-25 13:33 UTC
Labels: type: bug, needs: testing, module: cloudflare, priority: medium, needs: grooming, severity: critical
