### ISSUE TITLE
UI issue after clear cache and apply LRC with certain template

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6959] opened 2024-09-08 10:47 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => feature/lrc and fix/6953-lrc-replace-DOM-output-with-regex-injection
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When remove hash and apply `data-wpr-lazyrender="1"` the UI of page is changed compared to nowprocket

**To Reproduce**
1. Visit the page
2. Clear cache 
3. Revisit the page

**Expected behavior**
UI is same as nowprocket

**Screenshots**

**Additional context**
- template mentioned here https://wp-media.slack.com/archives/CUT7FLHF1/p1725782109648589?thread_ts=1725624439.071799&cid=CUT7FLHF1

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment] 2024-09-08 11:25
@DahmaniAdame It would be good to have your inputs on this: For 3279_template, that looks like some unexpected interaction between the new style we inject and dynamic content on the page from the div class="parallex".
This seems to be a particular behavior, not a generalized broken layout issue.

Visible here: http://mathieu.e2e.rocketlabsqa.ovh/3279_template

**Comment by DahmaniAdame** [comment] 2024-09-09 06:12
Good catch @Mai-Saad.

Upon investigation, this seems to be caused by the paint containment added by `content-visibility:auto`. 

It's like if the element had a forced `position:relative` and `overflow:hidden`. 

We should also skip `content-visibility:auto` and `content-visibility:hidden` while we are at to avoid re-applying `content-visibility` in items manager by the user manually. 

This will influence how children elements dependent on the parent's containment render. 

We have two main design practices that will be impacted: 

- Parallax, though when used below the fold, it will generally be generally contained to its parent element by design, which should reduce occurrences
- Absolute elements with negative potions, like when making an element over step it's container using a negative `top` or `bottom`

Possible conflicting children `position` values are `fixed` and `absolute`. 

Negative margins as also affecting LRC both in parent elements and children elements if they go beyond the parent LRCed element. Since the fix is urgent, we will just skip anything that has a negative margin from any side. 

If a better way to handle negative margins is found, we will add it later as an enhancement. 

We can prevent all those cases by skipping LRC candidates if they have any child with one of the values (and parents too when dealing with negative margins). 

When an element is skipped, children should be checked in this case and added as LRC as long as they don't have a conflicting children on their own. 

Verified here by skipping the parent and still applying LCR to children: https://gist.github.com/DahmaniAdame/35f6dc0b7ebc16f3c50a650ffb7bcb7f

Maybe something like (provided to support to detect potential conflicts): 

```

// Get all elements with the attribute data-wpr-lazyrender="1"
const lazyRenderElements = document.querySelectorAll('[data-wpr-lazyrender="1"]');

// Check if element is conflicting with LCR
function check_lcr_conflict(element) {
    const child_elements = element.querySelectorAll('*');
    const conflicting_elements = [];

    const parentComputedStyle = window.getComputedStyle(element);

    // Check for contentVisibility conflicts
    if (
        parentComputedStyle.contentVisibility === "auto" || 
        parentComputedStyle.contentVisibility === "hidden"
    ) {
        conflicting_elements.push({
            level: 'Parent',
            element: element,
            conflict: 'contentVisibility ' + parentComputedStyle.contentVisibility
        });
    }
    
    // Check for negative margins, but exclude "auto"
    if (
        parentComputedStyle.marginTop !== 'auto' && parseFloat(parentComputedStyle.marginTop) < 0 ||
        parentComputedStyle.marginRight !== 'auto' && parseFloat(parentComputedStyle.marginRight) < 0 ||
        parentComputedStyle.marginBottom !== 'auto' && parseFloat(parentComputedStyle.marginBottom) < 0 ||
        parentComputedStyle.marginLeft !== 'auto' && parseFloat(parentComputedStyle.marginLeft) < 0
    ) {
        conflicting_elements.push({
            level: 'Parent',
            element: element,
            conflict: 
                (parentComputedStyle.marginTop !== 'auto' && parseFloat(parentComputedStyle.marginTop) < 0 ? 'negative margin-top' : '') + 
                (parentComputedStyle.marginRight !== 'auto' && parseFloat(parentComputedStyle.marginRight) < 0 ? ' negative margin-right' : '') +
                (parentComputedStyle.marginBottom !== 'auto' && parseFloat(parentComputedStyle.marginBottom) < 0 ? ' negative margin-bottom' : '') +
                (parentComputedStyle.marginLeft !== 'auto' && parseFloat(parentComputedStyle.marginLeft) < 0 ? ' negative margin-left' : '')
        });
    }

    // Check for child elements' conflicting properties
    child_elements.forEach(child => {
        const computedStyle = window.getComputedStyle(child);
        
        if (
            computedStyle.position === 'absolute' || 
            computedStyle.position === 'fixed'
        ) {
            conflicting_elements.push({
                level: 'Child',
                element: child,
                conflict: 'position ' + computedStyle.position
            });
        }
        
        if (
            computedStyle.contentVisibility === "auto" || 
            computedStyle.contentVisibility === "hidden"
        ) {
            conflicting_elements.push({
                level: 'Child',
                element: child,
                conflict: 'contentVisibility ' + computedStyle.contentVisibility
            });
        }
        
        // Check for negative margins in children, excluding "auto"
        if (
            computedStyle.marginTop !== 'auto' && parseFloat(computedStyle.marginTop) < 0 ||
            computedStyle.marginRight !== 'auto' && parseFloat(computedStyle.marginRight) < 0 ||
            computedStyle.marginBottom !== 'auto' && parseFloat(computedStyle.marginBottom) < 0 ||
            computedStyle.marginLeft !== 'auto' && parseFloat(computedStyle.marginLeft) < 0
        ) {
            conflicting_elements.push({
                level: 'Child',
                element: child,
                conflict: 
                    (computedStyle.marginTop !== 'auto' && parseFloat(computedStyle.marginTop) < 0 ? 'negative margin-top' : '') + 
                    (computedStyle.marginRight !== 'auto' && parseFloat(computedStyle.marginRight) < 0 ? ' negative margin-right' : '') +
                    (computedStyle.marginBottom !== 'auto' && parseFloat(computedStyle.marginBottom) < 0 ? ' negative margin-bottom' : '') +
                    (computedStyle.marginLeft !== 'auto' && parseFloat(computedStyle.marginLeft) < 0 ? ' negative margin-left' : '')
            });
        }
    });

    console.log(conflicting_elements);
}

// Loop through each element to check if there is a conflicting element with LCR
lazyRenderElements.forEach(function(element) {
    check_lcr_conflict(element);  
});

```

It's preferable to log that a candidate has been skipped + why on the database to help customers and support understand the behavior when it happens. The same should apply to any future conflicting condition we find and we test for LCR candidates. 

We also need to manage cases with negative margin. That applies to parents and children alike.

**Comment by johan-las** [comment] 2024-09-19 14:49
New related case (off-canvas popup from Avada) : https://secure.helpscout.net/conversation/2710957350/512868/

**Comment by alfonso100** [comment] 2024-09-19 15:04
related case off-canvas menu from Rehub Theme:
 https://secure.helpscout.net/conversation/2710901338/512846?folderId=424682

GH issue (Closing it in favor of this one)
https://github.com/wp-media/wp-rocket/issues/6979

**Comment by DahmaniAdame** [comment] 2024-09-19 19:13
@piotrbak this is affecting cookie banners too. Complianz and Borlabs so far, but it's likely affecting others as they all use containment on child elements as well.

**Comment by johan-las** [comment] 2024-09-20 12:56
Another case with Off-canvas (as a menu) from Avada : https://secure.helpscout.net/conversation/2713109712/513321/

**Comment by WordPresseur** [comment] 2024-09-23 11:33
Another case with Astra menu : https://secure.helpscout.net/conversation/2714821081/513631/

**Comment by webtrainingwheels** [comment] 2024-09-23 15:44
Another case here: https://secure.helpscout.net/conversation/2713677632/513420?folderId=273766

**Comment by markonikolic985** [comment] 2024-09-25 07:27
One more case with Astra menu here https://secure.helpscout.net/conversation/2714186633/513509?folderId=424682

**Comment by webtrainingwheels** [comment] 2024-09-25 20:07
Borlabs case: https://secure.helpscout.net/conversation/2717084570/514081?folderId=377611

**Comment by webtrainingwheels** [comment] 2024-09-25 20:27
Avada case: https://secure.helpscout.net/conversation/2717117441/514092/

**Comment by suzoutlet** [comment] 2024-09-26 06:19
Related case with Avada Off-canvas menu: https://secure.helpscout.net/conversation/2717168965/514105/

**Comment by markonikolic985** [comment] 2024-09-27 08:45
Related Borlabs case - https://secure.helpscout.net/conversation/2712944654/513258?folderId=424682

**Comment by webtrainingwheels** [comment] 2024-09-27 23:47
elementor case: https://secure.helpscout.net/conversation/2719413453/514675/

**Comment by suzoutlet** [comment] 2024-09-30 10:44
Float Menu Lite case: https://secure.helpscout.net/conversation/2719333333/514636/

**Comment by webtrainingwheels** [comment] 2024-10-01 16:15
Another case: https://secure.helpscout.net/conversation/2722037725/515213?folderId=377611
In this one, the screen was moving from side-to-side: https://jmp.sh/3A02mxZF
[Related theme](https://themeforest.net/item/lemon-limes-food-blog-wordpress-theme/33905464?srsltid=AfmBOorK6SmhYCMxv58YmjMl1mGB9jCXMGGwCf1bqnyPBE7_IrW8pTLO)

**Comment by girlie** [comment] 2024-10-01 16:59
Two more cases:

1. Elementor Floating Button goes missing: https://secure.helpscout.net/conversation/2719467353/514689/
2. Login modal doesn't pop up: https://secure.helpscout.net/conversation/2715988639/513866/

**Comment by webtrainingwheels** [comment] 2024-10-02 19:43
Case related to Rey theme: https://secure.helpscout.net/conversation/2722627569/515352?folderId=377611

**Comment by johan-las** [comment] 2024-10-03 08:24
Related cases:

1. Product filter off-canvas : https://secure.helpscout.net/conversation/2723063952/515437?folderId=8127840
2. Astra Theme login form off-canvas: https://secure.helpscout.net/conversation/2723429306/515489/
3. Elementor floating buttons : https://secure.helpscout.net/conversation/2723579136/515534/

**Comment by viobru** [comment] 2024-10-03 14:31
Related Elementor case (3 sites affected): [https://secure.helpscout.net/conversation/2720753500/514930](https://secure.helpscout.net/conversation/2720753500/514930)
In this case, the footer was not loading.

**Comment by webtrainingwheels** [comment] 2024-10-03 22:18
Bridge theme + Elementor: https://secure.helpscout.net/conversation/2723520241/515521/

**Comment by WordPresseur** [comment] 2024-10-04 07:47
Another case: https://secure.helpscout.net/conversation/2725480089/515888?folderId=1213662

**Comment by remyperona** [comment] 2024-10-04 13:46
@wp-media/engineering-plugin-team Ideally it would need to be groomed by someone who is comfortable with the JS beacon

**Comment by webtrainingwheels** [comment] 2024-10-04 19:38
Fusion Builder case: https://secure.helpscout.net/conversation/2724940730/515823?folderId=377611

**Comment by Miraeld** [comment] 2024-10-07 02:20
## Reproduce the problem
1. Visit the page: https://new.rocketlabsqa.ovh/3279_template/
2. Clear the cache.
3. Revisit the page.
4. Observe the rendering issues caused by paint containment, similar to having `position: relative` and `overflow: hidden`.

## Identify the root cause
The issue is that elements with `content-visibility: auto` or `content-visibility: hidden` are causing rendering conflicts. These properties should be skipped to avoid re-applying them in the items manager, which affects how child elements dependent on the parent's containment render.

## Scope a solution
To solve the issue, we must create the `_checkLcrConflict` function to handle `content-visibility: auto` and `content-visibility: hidden` properties, and also check for `position: relative` and `overflow: hidden`. Additionally, we should skip elements with `content-visibility: auto` and `content-visibility: hidden` to avoid re-applying these properties. And also negative margins.


`_checkLrcConflict` could look like: 
``` javascript
_checkLcrConflict(element) {
        const conflictingElements = [];
        const computedStyle = window.getComputedStyle(element);

        const negativeMargins = ['marginTop', 'marginRight', 'marginBottom', 'marginLeft']
            .filter(margin => parseFloat(computedStyle[margin]) < 0)
            .map(margin => `negative ${margin.toLowerCase()}`);

        const conflicts = [
            ...negativeMargins,
            computedStyle.contentVisibility === 'auto' && 'content-visibility:auto',
            computedStyle.contentVisibility === 'hidden' && 'content-visibility:hidden',
            computedStyle.overflow === 'hidden' && 'overflow:hidden',
            computedStyle.position === 'relative' && 'position:relative'
        ].filter(Boolean);

        if (conflicts.length > 0) {
            conflictingElements.push({ element, conflicts });
        }

        Array.from(element.children).forEach(child => {
            const childStyle = window.getComputedStyle(child);
            const childNegativeMargins = ['marginTop', 'marginRight', 'marginBottom', 'marginLeft']
                .filter(margin => parseFloat(childStyle[margin]) < 0)
                .map(margin => `negative ${margin.toLowerCase()}`);

            const childConflicts = [
                ...childNegativeMargins,
                childStyle.contentVisibility === 'auto' && 'content-visibility:auto',
                childStyle.contentVisibility === 'hidden' && 'content-visibility:hidden',
                childStyle.overflow === 'hidden' && 'overflow:hidden',
                childStyle.position === 'relative' && 'position:relative'
            ].filter(Boolean);

            if (childConflicts.length > 0) {
                conflictingElements.push({ element: child, conflicts: childConflicts });
            }
        });

        return conflictingElements;
    }
```

And add [here](https://github.com/wp-media/rocket-scripts/blob/8e25bbfddce70e1c142bb879f9467061f6696dd7/src/BeaconLrc.js#L84-L83) the call to this newly created function:
            
``` javascript
const conflicts = this._checkLcrConflict(element);
if (conflicts.length > 0) {
       this.logger.logMessage('Skipping element due to conflicts:', conflicts);
       return;
}
```

## Development steps:
- [x] Define the function `_checkLrcConflict` within the BeaconLrc class
- [x] Implement the logic to check for content-visibility: auto, content-visibility: hidden, position: relative, overflow: hidden properties, and negative margins.
- [x] Ensure that elements with `content-visibility: auto` and `content-visibility: hidden` are skipped to avoid re-applying these properties.
- [x] Test the changes to confirm that the rendering issues are resolved.

## Effort estimation: S
## Is a refactor needed in that part of the codebase?
No

**Comment by DahmaniAdame** [comment] 2024-10-07 06:26
@Miraeld `position:relative` and `overflow:hidden` were just to described what's happening. Both properties shouldn't be excluded. To be removed as conflicting.  

The root cause is when children have a `position:fixed` or `position:absolute` or a negative margin. Need to be included as conflicting. 

Conditions are different. Some are applied to the current LCR candidate, and others are related to its children, except for the negative margins. 

To sum up, here are the scenarios where an element needs to be skipped: 

- If the current element where the LCR will be applied has: 
  - any negative margin
  - `content-visibility:hidden`
  - `content-visibility:auto`
 
- If one of the current element's children has: 
  - any negative margin
  - `position:absolute`
  - `position:fixed`

The behavior should be skipping the element but still processing its children if they are within the allowed depth.

**Closed as completed** 2024-10-10 10:26 UTC
Labels: type: bug, priority: high, severity: moderate, module: ALR
