### ISSUE TITLE
PHP Fatal error On rocket_clean_post

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#1933] opened 2019-09-03 04:23 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

Wp-rocket version: 3.3.7

**Describe the bug**

**To Reproduce**
Edit the post, change the default size and color, add attribute then it hung out.

**Expected behavior**
Should not be hang out. 

`2019/09/02 22:05:01 [error] 20609#20609: *1432000 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function WP_Rocket\Subscriber\Third_Party\Plugins\Ecommerce\rocket_clean_post() in /home/domain/public/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/ecommerce/class-woocommerce-subscriber.php:133
Stack trace:
#0 /home/domain/public/wp-includes/class-wp-hook.php(288): WP_Rocket\Subscriber\Third_Party\Plugins\Ecommerce\WooCommerce_Subscriber->clean_cache_after_woocommerce_save_product_variation(148377)
#1 /home/domain/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /home/domain/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/domain/public/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(532): do_action('woocommerce_sav...', 148377, 0)
#4 /home/domain/public/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2084): WC_Meta_Box_Product_Data::save_variations(148335, Object(WP_Post))
#5 /home/domain/public/wp" while reading response header from upstream, client: 184.170.247.2, server: domain.com, request: "POST /wp-admin/admin-ajax.php?_fs_blog_admin=true HTTP/2.0", upstream: "fastcgi://unix:/var/run/php72.sock:", host: "www.domain.com", referrer: "https://www.domain.com/wp-admin/post.php?post=148335&action=edit"`

Site Status:

``
### WordPress Environment ###

WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.3.7
PHP Post Max Size: 10 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.52.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.16-MariaDB-1:10.3.16+maria~stretch-log
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: mug_
MaxMind GeoIP Database: ✔
Total Database Size: 651.00MB
Database Data Size: 416.75MB
Database Index Size: 234.25MB
mug_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
mug_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mug_woocommerce_order_items: Data: 0.20MB + Index: 0.08MB + Engine InnoDB
mug_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.89MB + Engine InnoDB
mug_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
mug_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_abandoned_cart_statistical: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_abandoned_cart_user_add: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_ac_abandoned_cart_history: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
mug_ac_email_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
mug_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_ac_opened_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_ac_sent_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_adsw_activities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_adsw_ali_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_commentmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
mug_comments: Data: 1.52MB + Index: 0.86MB + Engine InnoDB
mug_ewwwio_images: Data: 6.52MB + Index: 9.08MB + Engine InnoDB
mug_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_iconic_woo_linked_variations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_options: Data: 10.44MB + Index: 1.48MB + Engine InnoDB
mug_postmeta: Data: 163.69MB + Index: 191.16MB + Engine InnoDB
mug_posts: Data: 27.56MB + Index: 15.06MB + Engine InnoDB
mug_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_rac_abandoncart: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
mug_rac_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_rac_templates_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_termmeta: Data: 0.14MB + Index: 0.22MB + Engine InnoDB
mug_terms: Data: 0.22MB + Index: 0.31MB + Engine InnoDB
mug_term_relationships: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
mug_term_taxonomy: Data: 0.23MB + Index: 0.28MB + Engine InnoDB
mug_usermeta: Data: 0.38MB + Index: 0.39MB + Engine InnoDB
mug_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
mug_user_ref_abandoned_cart: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_wc_customer_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
mug_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_wc_gpf_render_cache: Data: 190.52MB + Index: 0.11MB + Engine InnoDB
mug_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_wc_order_product_lookup: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
mug_wc_order_stats: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
mug_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
mug_wc_product_meta_lookup: Data: 6.52MB + Index: 10.59MB + Engine InnoDB
mug_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_wof_optins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
mug_wow_countdowns_free: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
mug_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
mug_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
mug_yoast_seo_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
mug_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pinterest_automatic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Contact Form 7: by Takayuki Miyoshi – 5.0.5
Enable WooCommerce GPF feed item cache.: by Lee Willis – 1.0 – Not tested with the active version of WooCommerce
Google Authenticator: by Ivan Kruchkoff – 0.52
WooCommerce Linked Variations by Iconic: by Iconic  – 1.0.4 – Not tested with the active version of WooCommerce
JanStudio Addons: by JanStudio – 1.2.1
PayPal for WooCommerce: by Angell EYE – 2.1.0 – Not tested with the active version of WooCommerce
PixelYourSite PRO: by PixelYourSite – 7.2.4
Prereview: by Elegant Themes – 1.0
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.0.2 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
WooCommerce Admin: by WooCommerce – 0.18.0
WooCommerce Custom Indexes: by WooCommerce – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.9.2
WooCommerce Table Rate Shipping: by Bolder Elements – 4.1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO Premium: by Team Yoast – 11.8
Wordpress Pinterest Automatic: by ValvePress – 4.10.2
WP Rocket | Deactivate WooCommerce Refresh Cart Fragments Cache: by WP Rocket Support Team –  – Not tested with the active version of WooCommerce
SEO Image Optimizer: by XfinitySoft – 2.0.0
WooCommerce Variation Swatch: by WPAddon – 1.0.8 – Not tested with the active version of WooCommerce
Yoast SEO: WooCommerce: by Team Yoast – 11.8 – Not tested with the active version of WooCommerce
YITH WooCommerce Ajax Product Filter: by YITH – 3.7.1
YITH WooCommerce Wishlist: by YITH – 2.2.13

### Inactive Plugins (39) ###

1 item left: by Kevin – 1.0
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 8.0.0 – Not tested with the active version of WooCommerce
AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin – 0.8.10
Bloom: by Elegant Themes – 1.3.3
CartBack - Facebook Messenger Abandoned Cart & Remarketing for WooCommerce: by Ninja Team – 1.7.1 – Not tested with the active version of WooCommerce
Checkout Address Autocomplete for WooCommerce: by eCreations – 2.0.7 – Not tested with the active version of WooCommerce
Compress JPEG & PNG images: by TinyPNG – 3.2.0
Cookie Bar: by Brontobytes – 1.8.6
Distraction-free Checkout: by Kevin – 1.0
Easy Review Reminders: by Rymera Web Co – 1.2.4 – Not tested with the active version of WooCommerce
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.11.0 – Not tested with the active version of WooCommerce
Google Address Autocomplete for WooCommerce: by MB Création – 2.3.4 – Not tested with the active version of WooCommerce
Move Email to Top of WooCommerce Checkout: by Caitlin Chou – 1.0 – Not tested with the active version of WooCommerce
PixelYourSite Pinterest: by PixelYourSite – 2.0.1 – Not tested with the active version of WooCommerce
PixelYourSite Super Pack: by PixelYourSite – 1.2.1
Prettify reviews: by Freddy Muriuki – 1.0
Recover Abandoned Cart: by Fantastic Plugins – 21.0 – Not tested with the active version of WooCommerce
Sale Count: by Kevin – 1.0
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.2 – Not tested with the active version of WooCommerce
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.5 – Not tested with the active version of WooCommerce
Tawk.to Live Chat: by Tawkto – 0.3.8
The Real Time Chat: by The Real TIme Chat – 1.0.0
Upsell on checkout: by Kevin – 1.0
WC Show All Reviews: by AppJetty – 1.5.0 – Not tested with the active version of WooCommerce
WooCommerce Facebook Conversion Pixel: by Seravo Oy – 0.1 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.6.2 – Not tested with the active version of WooCommerce
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.3.9.7 – Not tested with the active version of WooCommerce
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.3.9.2 – Not tested with the active version of WooCommerce
Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.14 – Not tested with the active version of WooCommerce
WooSwatches - Woocommerce Color or Image Variation Swatches: by woomatrix – 2.7.07 – Not tested with the active version of WooCommerce
WP Optin Wheel Pro: by StudioWombat – 3.0.5 – Not tested with the active version of WooCommerce
WP Rocket: by WP Media – 3.3.7
WP Rocket | Exclude Files from Async CSS: by WP Rocket Support Team –
WP Rocket | External Script Handler: by WP Rocket Support Team –
WP SMTP: by Yehuda Hassine – 1.1.10
XL WooCommerce Sales Triggers: by XLPlugins – 2.7.0 – Not tested with the active version of WooCommerce
YITH Product Size Charts for WooCommerce Premium: by YITHEMES – 1.1.5 – Not tested with the active version of WooCommerce
YITH WooCommerce Review Reminder Premium: by YITHEMES – 1.3.7 – Not tested with the active version of WooCommerce

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #203 - /terms-conditions/

### Theme ###

Name: Gecko Child
Version: 1.0.0
Author URL: http://www.janstudio.net
Child Theme: ✔
Parent Theme Name: Gecko
Parent Theme Version: 1.7.6
Parent Theme Author URL: http://www.janstudio.net
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: gecko-child/woocommerce/cart/cart-totals.php
gecko-child/woocommerce/cart/cross-sells.php
gecko-child/woocommerce/single-product/related.php
gecko-child/woocommerce/single-product/up-sells.php

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Bundle indicator (is_bundle): 
Condition: Defaults to "new".
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Global Trade Item Number (GTIN): 
Gender: Defaults to "unisex".
Age Group: Defaults to "adult".
Colour: Pre-populates from pa_color taxonomy.
Size: Pre-populates from pa_size taxonomy.
Size type: Defaults to "regular".
Size system: Defaults to "US".
Identifier exists flag: Defaults to "included".
Adwords grouping filter: 
Adwords labels: 
Bing Category: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No

### Action Scheduler ###

Complete: 224
Oldest: 2019-08-03 14:56:02 +0000
Newest: 2019-09-03 04:20:03 +0000

Pending: 1
Oldest: 2019-09-03 05:20:03 +0000
Newest: 2019-09-03 05:20:03 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 6
Oldest: –
Newest: –

``

**Comment by Tabrisrp** [comment] 2019-11-23 10:46
Can you please provide more feedback on the actual steps to take to reproduce this issue?
- Is it when editing a WooCommerce product with variations?
- Are you using the block editor (aka Gutenberg) or the classic editor?

**Comment by GeekPress** [comment] 2020-05-15 09:31
Hi @kevin25  🤚

We haven't back from you since @Tabrisrp asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best

**Closed by GeekPress** 2020-05-15 09:31 UTC
Labels: community, waiting for feedback
