### ISSUE TITLE
Add partnerProductlink.js to Load JavaScript deferred default exclusions

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5789] opened 2023-03-02 07:19 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version `3.12.4`
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When https://partner.bol.com/promotion/static/js/partnerProductlink.js is deferred affiliates' products are not displayed.

**Expected behavior**
https://partner.bol.com/promotion/static/js/partnerProductlink.js excluded by default from the feature Load JavaScript deferred so affiliates products are displayed as expected.

**Screenshots**

**Additional context**
hs: https://secure.helpscout.net/conversation/2158716286/0/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment] 2023-07-04 13:25
the 
https://partner.bol.com/promotion/static/js/partnerProductlink.js 
JS files are 404 now, closing for now as we cannot reproduce it.

![Image](https://github.com/wp-media/wp-rocket/assets/229406/dbc93fc1-d800-4e95-b564-a11a75d211f7)

please reopen this issue if it comes up in the future again 🙏

**Closed as completed by alfonso100** 2023-07-04 13:25 UTC
Labels: 3rd party compatibility, can't reproduce, module: defer JS, needs: backend exclusion
