### ISSUE TITLE
Delay JS Execution: PHP Warning when an unclosed parenthesis is in exclusion list

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#4136] opened 2021-07-07 01:55 UTC
**Describe the bug**
When using exclusions like `gtag(` in Delay JavaScript Execution (version 3.9.0.5) it causes the following PHP warning and the **exclusion does not work**: 

`PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 5 in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 172`

**To Reproduce**
1. Add the following type of code to your site (it's commonly used Analytics code, both inline and external file together): 
```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-11111111111-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());


	  	  gtag('config', 'UA-111111111111-1');
	  
	</script>
```
2. Ensure Delay JS is enabled, add this exclusion: `gtag(`

3. Observe on the site that the inline script is not excluded and find the warning in your error log.

**Expected behavior**
The script should be excluded without warning

**Additional context**
These types of exclusions are listed in our docs: https://docs.wp-rocket.me/article/1492-google-analytics-google-ads-tracking-issues
We can update those of course, but they should work anyway :)

This is a similar issue to this one: https://github.com/wp-media/wp-rocket/issues/3967

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by iCaspar** [comment] 2021-07-19 19:44
## Grooming Notes:

### Can Reproduce: ✅ 
Can see the warning locally by just adding the `gtag(` item to the UI exclude list. Preg-match will not be able to match this, so it follows that the script will not be excluded.

### Root cause:
The `(` character is a regex special character and needs to be escaped in order to allow `preg_match()` to work for this pattern.

### Scope a Solution:
In https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/DelayJS/HTML.php#L95L99 we are escaping certain problematic patterns that interfere with regex. We need to add `gtag(` to the array of search patterns on L:96 and `gtag\(` to the array of replace patterns on L:97.
(Note that we cannot add simply `'(' => '\('` because then we escape all the parentheses in all the patterns.)

Update test fixture for DelayJS/HTML to include the `gtag(` exclusion.

### Estimate Effort
[XS]

Also, @webtrainingwheels this is currently tagged for 3.9.2, but a workaround that _should_ solve any cases before that is released is to use `gtag\(` directly in the UI DelayJS exclusion box.

**Comment by Mai-Saad** [comment] 2021-08-10 13:02
Reproducible on newlabs test site after inserting mentioned script in the body.

**Comment by iCaspar** [comment] 2021-09-01 16:21
PR #4195 is working, but there appears to be an issue with the clear cache modifying the settings that removes the escaping in some cases. When the escaping is removed, preg_match throws a warning when evaluating malformed entries. This was observed in the Exclude JavaScript Files field, but may extend to others as well.
@Mai-Saad @iCaspar.
This issue needs to be resolved before we can merge this.

**Comment by iCaspar** [comment] 2021-09-08 12:42
The issue with clear cache is resolved here. Also, we will be able to perform the regex escaping when importing settings now as well.

**Comment by Mai-Saad** [comment] 2021-11-01 10:21
Same with Defer JS if excluded `/wp-content/rocket-test-data/scripts/test(filename.js ` will result in the following warning:
`[01-Nov-2021 07:58:32 UTC] PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 976 in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DeferJS/DeferJS.php on line 79`

Test page: https://new.rocketlabsqa.ovh/defer_js_ui_template_001/

Notes: 
- Excluding the same URL in Minify JS => URL will be auto removed from the exclusion field
- Excluding `/wp-content/rocket-test-data/scripts/test(filename).js ` from Minify JS will result in excluding `/wp-content/rocket-test-data/scripts/testfilename.js `

**Comment by NataliaDrause** [comment] 2021-11-04 15:52
Related: https://secure.helpscout.net/conversation/1686129964/305708?folderId=3864740

**Comment by Mai-Saad** [comment] 2021-11-18 08:54
Excluding `gtag(` from combine js results in the same warning `PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 928 in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/JS/Combine.php on line 914`

**Comment by piotrbak** [comment] 2021-11-19 18:36
For both issues, https://github.com/wp-media/wp-rocket/issues/3967 and this one, we'll detect faulty input data, remove it from field and display an error like we do for other fields:
https://github.com/wp-media/wp-rocket/pull/4502#issuecomment-972882504

We'll need to update our docs to explain our customers why they can not use this pattern and how they can achieve what they want to achieve.

_Acceptance Criteria:_
(While saving the settings)

1. The faulty data is not saved into the field
2. Other, correct data is preserved in the field
3. PHP warning is not appended to the logs
4. Warning is displayed with the list of faulty input data, with a link to documentation where users can read more about how to exclude assets correctly
5. When faulty data is added to a couple of fields, warning should point to all of them

**Comment by iCaspar** [comment] 2021-11-24 14:38
### Regrooming:

**Reproduced:**
As of #4314 the following acceptance criteria are already satisfied _with respect to DelayJS field_:
1. faulty data is not saved in field.
2. Other correct data is preserved in field.
3. Warning in logs is not generated.
4. Warning is displayed (but there is no link to docs.)
5. Warning references also errors in other fields
<img width="236" alt="Screen Shot 2021-11-24 at 8 53 29 AM" src="https://user-images.githubusercontent.com/7462998/143251584-3f8898d1-c32c-4734-8f1c-6460a2ef434b.png">

<img width="563" alt="Screen Shot 2021-11-24 at 8 53 20 AM" src="https://user-images.githubusercontent.com/7462998/143251670-df2dc96d-51da-4e8b-8500-fdf22a206915.png">

**At this point, then, what remains is to add a link to the warning message to the relevant documentation.**

**Root Cause**
There is no documentation link included in the current warning notice block generated at this point: https://github.com/wp-media/wp-rocket/blob/develop/inc/admin/options.php#L158-L162

**Solution Scope**
Add a small bit of HTML after the `foreach` with a link pointing to the (new) documentation concerning how to troubleshoot bad entries in pattern fields.

**Effort Estimate**
[S]

**Comment by iCaspar** [comment] 2021-11-24 14:40
@webtrainingwheels pls advise about the correct link to add for the doc here. Feel free to ping me on slack if we need to go over anything for it. :)

**Comment by webtrainingwheels** [comment] 2021-11-24 16:18
Pinging @camilamadronero because she is in charge of docs now

**Closed as completed** 2021-11-25 15:36 UTC
Labels: type: bug, priority: high, needs: grooming, needs: documentation, severity: moderate, module: delay JS
