### ISSUE TITLE
Lazy Load Images Breaks With Certain Alt Text Values

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#3502] opened 2021-01-18 16:01 UTC
Similar to a previous bug in #2873

If lazy load images are enabled and the below markup is added the image output will break. 

`<img class="hello-world" src="https://www.sertmedia.com/wp-content/uploads/2020/10/LGO-WPEngine-Mark-RGB.png" alt="Hello <br>world">`

I discovered this on a client site recently and was able to replicate it. However, oddly enough when an image is added with a srcset attribute the image renders correctly. This situation was found because they were using advanced custom fields and not outputting a srcset attribute and instead just using a straight <img> tag. 

Ideal Solution:
The image should not break when lazy load is applied. 

Note unlike #2873 this issue is present even when the optimize CSS delivery option is disabled. 

Example Page: https://www.sertmedia.com/lazy-load-images-breaks/

I included one image with the srcset attribute (using an image block) and then the secondary image I added as an HTML block to avoid the srcset attribute being added both images use the same alt text.

**Comment by engahmeds3ed** [comment] 2021-01-27 20:21
Hello @ScottTravisHartley,

I think the problem is that your markup is not valid as there is no closing double quotes for alt tag as follows, you can find this markup here: https://www.sertmedia.com/lazy-load-images-breaks/?nowprocket

```
<img class="hello-world" src="https://www.sertmedia.com/wp-content/uploads/2020/10/LGO-WPEngine-Mark-RGB.png" alt="Hello <br>world&#8221;>
```

and after applying the lazyload attributes, it became as follows:
```
<img width="274" height="275" class="hello-world" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20274%20275'%3E%3C/svg%3E" alt="Hello <br data-lazy-src=" https: www.sertmedia.com wp-content uploads 2020 10 LGO-WPEngine-Mark-RGB.png"><noscript><img width="274" height="275" class="hello-world" src="https://www.sertmedia.com/wp-content/uploads/2020/10/LGO-WPEngine-Mark-RGB.png" alt="Hello <br></noscript>world&#8221;>
```

and the browser converts it into
![image](https://user-images.githubusercontent.com/15707971/106048531-afed1d00-60ed-11eb-88b3-55a5d3b59b6c.png)

@wp-media/productrocket what do u think of that issue?

**Comment by ScottTravisHartley** [comment] 2021-01-27 22:19
In the backend, the code is as follows
![image](https://user-images.githubusercontent.com/45110039/106061734-697eca80-60bb-11eb-922c-5b9734eb23e3.png)

**Comment by engahmeds3ed** [comment] 2021-01-28 11:32
I tried now this and I can reproduce it locally, the problem is that the following regex catches till first closing `>` which here is inside the alt:

https://github.com/wp-media/rocket-lazyload-common/blob/885a540428ddcd3a7dc1ec691b90b8199f35642d/src/Image.php#L25

I will groom this issue in a while.

Thanks @ScottTravisHartley

**Comment by piotrbak** [comment] 2021-01-28 12:27
The workaround is to use a normal line break:
`<img src="image.jpg" alt="1st line`
`2nd line"/>`

And add this CSS:
`img{white-space:pre}`

**Comment by piotrbak** [comment] 2021-01-28 13:03
@ScottTravisHartley We've investigated the problem with @engahmeds3ed and there are two separate things happening.
1. Adding the `>` inside alt attribute in Gutenberg breaks the markup:
`<img src="cat.png" alt="I'm a > funny cat">`
becomes:
`<img src="cat.png" alt="I'm a > funny cat&#8221;>`
This is what is passed to WP Rocket. Moreover, the above output will break the layout of the page even when WP Rocket is deactivated (the image is loaded correctly though, the problems happen below the image).
2. When any of the above markups is passed to WP Rocket it's going to fail. It means that we can most likely guard against the correct markup:
`<img src="cat.png" alt="I'm a > funny cat">` but not against the one changed by Gutenberg:
`<img src="cat.png" alt="I'm a > funny cat&#8221;>`

In your case, if you want to add the line break to the alt attribute, please find my above comment useful.

**Comment by arunbasillal** [comment] 2021-01-28 16:35
@engahmeds3ed If the work-around Piotr suggested works and if fixing this is tricky, we can choose not to do it as well. This sounds like super edge case. With our plans to switch to native LazyLoad, this might not be needed after all.

**Comment by engahmeds3ed** [comment] 2021-02-02 12:10
@wp-media/productrocket here we are concerning only with the issue of adding > inside any attribute will break the img tag html and lazyload won't work properly for it and the solution here is to adjust the following regex not to match anything between double/single quotes and this is not an easy and regex will take more time to return specially with pages that have many images on it.

https://github.com/wp-media/wp-rocket/blob/50eca1a2613bf1b2f9ddbf2b9aff66703f14d011/inc/Dependencies/RocketLazyload/Image.php#L25

so if we are about to migrate to native lazyload soon, no need to adjust that now, decision is yours if u need me to continue grooming this one or not?!

**Comment by GeekPress** [comment] 2021-02-03 08:35
@engahmeds3ed I'm not sure to understand the relation with the switch to Native Lazyload. We will still need to use the same regex to grab all images to apply `loading="lazy"` on all images, isn't it?

**Comment by engahmeds3ed** [comment] 2021-02-03 10:29
Yes, my message was based on Arun's message and I thought he meant that we can adjust this issue while working on native lazyload.

I will groom this one today.

**Comment by NataliaDrause** [comment] 2021-10-24 17:41
Related: https://secure.helpscout.net/conversation/1664980375/301869/

The following markup breaks:
`<img src="https://www.example.com/wp-content/uploads/2020/04/image.png" alt="" title="Atendimento<br />Corporativo">`

**Comment by ffoodd** [comment] 2023-12-15 07:57
Having the same issue with other characters, currently this alternative breaks lazy loading:
`Demandes : ! = Je demande la parole, &gt; = Précision rapide, ? = Clarification, % = Recentrer la discussion - Ressenti : + = J’adhère, - = J’adhère pas, / = Déjà dit, trop long, X = J’ai une objection`.

Tried to use HTML entity for `>` but that's not enough, will continue to investigate…

**Edit:** the HTML entity messes things up just like the character itself.

**Comment by piotrbak** [comment] 2024-07-04 09:34
This is not something that can be implemented soon. We might reopen this in the future when working on lazyload specifically

**Closed as not planned by piotrbak** 2024-07-04 09:34 UTC
Labels: type: bug, priority: low, needs: grooming, severity: moderate, module: lazyload images, needs: product cleanup
