### ISSUE TITLE
WP Engine's cache isn't automatically cleared after successfully creating the used CSS

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5186] opened 2022-06-24 11:07 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.4` 
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

After the successful creation of the used CSS we are purging the URLs cache:
https://github.com/wp-media/wp-rocket/blob/635769c38d685916b97f8184bd7f9219baddefca/inc/Engine/Cache/PurgeActionsSubscriber.php#L53

When a site is hosted on WP Engine, the cache purging will not take place automatically. The used CSS will be applied only during the next cache purging of the host's cache.

**To Reproduce**

1. On a WP Engine website enable Remove Unused CSS.
2. Check the `wpr_rucss_used_css` table and pick a post/page URL for which used CSS hasn't been created already.
3. Visit the URL as a logged-out user making sure that the `x-cache` header is a `MISS` for that visit. If it isn't try a different URL or purge WP Engine's cache using their cache clearing button in the admin area - not WP Rocket's "Clear cache".
4. Hard refresh the same URL many times and notice the value of the same header, it should be e.g. `x-cache: HIT: 6`
5. Once the used CSS has been added to the database table revisit the URL in the browser.
6. The used CSS won't have been added to the source code and the number in the `x-cache` header will be higher than that of step 4.

**Expected behavior**

The cache should be cleared automatically after the successful creation of the used CSS for a URL.

**Additional context**

We could handle this the way we do it for Kinsta:
https://github.com/wp-media/wp-rocket/blob/635769c38d685916b97f8184bd7f9219baddefca/inc/ThirdParty/Hostings/Kinsta.php#L27-L28

An important thing to note is that on WP Engine it seems that there isn't a way to purge the cache of a specific URL. `after_rocket_clean_post` isn't used in the compatibility file:
https://github.com/wp-media/wp-rocket/blob/635769c38d685916b97f8184bd7f9219baddefca/inc/ThirdParty/Hostings/WPEngine.php#L22-L31

@Mai-Saad originally commented about this issue here:
https://github.com/wp-media/wp-rocket/issues/4980#issuecomment-1111791923

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment] 2022-06-30 13:31
### Reproduce the problem
I was able to reproduce this issue.

### Identify the root cause
Like @vmanthos stated, we are not clearing the url cache after generating used css on WP Engine.

### Scope a solution
After checking the WPE MU-Plugin, I couldn't find a way for us to handle url cache clearing on WP Engine like @vmanthos mentioned.
The only thing we can do hook `clean_wpengine` to `rocket_rucss_complete_job_status` and that will make the effort [XS] but I don't think we should purge the whole site cache every time we generate a used css for a url...

Another thing we can do is to wait for all pending actions to be completed then we purge the whole site cache.
What do you think @piotrbak @engahmeds3ed

**Comment by piotrbak** [comment] 2022-06-30 14:01
@jeawhanlee I can see that we could have that possibility. Take a look at the `purge_varnish_cache` function from `/wpengine-common/plugin.php`:
https://snippi.com/s/77foeca

**Comment by jeawhanlee** [comment] 2022-06-30 14:20
> @jeawhanlee I can see that we could have that possibility. Take a look at the `purge_varnish_cache` function from `/wpengine-common/plugin.php`: https://snippi.com/s/77foeca

Thanks @piotrbak I will update the grooming

**Comment by piotrbak** [comment] 2022-06-30 14:21
@jeawhanlee I'm still not sure if we'll be able to purge the page using URL, not post ID...

**Comment by jeawhanlee** [comment] 2022-06-30 14:26
@piotrbak I think we can by passing the url to the `url_to_postid()` which will return the `post_id` then we pass the related `post_id` to `WpeCommon::purge_varnish_cache( $post_id );`. This might work. what do you think?

**Comment by piotrbak** [comment] 2022-06-30 14:28
@jeawhanlee Many of our URLs are not posts, unfortunately... We need to clear the cache based on URL only...

**Comment by jeawhanlee** [comment] 2022-06-30 14:30
@piotrbak So I put a pend on this issue?

**Comment by piotrbak** [comment] 2022-06-30 15:08
I'm blocking it and let's wait for the WP Engine contact

**Comment by GeekPress** [comment] 2022-10-26 07:09
@piotrbak Any news from WP Engine?

**Comment by piotrbak** [comment] 2022-10-26 09:29
@GeekPress Unfortunately, not

**Comment by KingGrizzly** [comment] 2024-04-22 17:50
We keep running into an issue on WP Engine where clearing the WP Rocket cache doesn't regenerate the wp-content/cache folder, it gets stuck. We have to manually delete the cache folder to fix.

WPE support has no fix. I'm not sure what to do. Do we need to [disable WP Rocket caching](https://docs.wp-rocket.me/article/61-disable-page-caching) altogether on WP Engine?

**Comment by piotrbak** [comment] 2024-04-22 20:11
Hello @KingGrizzly WP Rocket's cache is disabled on WP Engine:
https://github.com/wp-media/wp-rocket/blob/635769c38d685916b97f8184bd7f9219baddefca/inc/ThirdParty/Hostings/WPEngine.php#L27C1-L28C1

Unless you're using different platform which is not handled in this compatibility.

**Comment by KingGrizzly** [comment] 2024-04-22 20:29
@piotrbak Thanks. I'm confused because WP rocket is able to generate a wp-content/cache folder on my WP Engine dedicated hosting box and the contents of this folder do impact the look of the site — to the point where I have to delete that folder to get the site appearance to fix.

**Comment by ookblah** [comment] 2024-05-30 16:23
I am also seeing this issue and it's super annoying.  I have to manually clear all pages to get the unused CSS to show up because it doesn't regenerate them all at once.  Is there any solution from your end?

**Comment by KingGrizzly** [comment] 2024-05-30 17:37
There is an extra plugin WP rocket offers for disabling its own caching abilities on WP Engine. I've installed it but it's unclear if I should need to do this and whether it works.

**Comment by piotrbak** [comment] 2024-07-11 10:49
This is not something that can be fixed by us, we'll reopen the issue when we'll have an option to clear specific URLs on this platform

**Closed as not planned by piotrbak** 2024-07-11 10:49 UTC
Labels: type: enhancement, waiting for feedback, 3rd party compatibility, module: cache, priority: medium, needs: grooming, status: blocked, module: remove unused css, needs: product cleanup, dependency issue
