### ISSUE TITLE
wp rocket unused css arabic url 

### ISSUE THREAD

**Issue by alaa-abdelsamie** [wp-media/wp-rocket#4247] opened 2021-08-15 11:56 UTC
**Describe the bug**
When you activate a "unused css" on an Arabic site that uses Arabic links
unused css files wrongly saved

check this 
https://5msh.com/%D9%83%D9%88%D8%AF-%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%B1%D9%82%D9%85-%D9%85%D9%88%D8%A8%D9%8A%D9%86%D9%8A%D9%84-%D8%A7%D9%88%D8%B1%D9%86%D8%AC

**Screenshots**
https://imgur.com/u9G2NDK

**Comment by mehedihasanziku** [comment] 2021-08-16 15:48
seems related issue #3968

**Comment by remyperona** [comment] 2021-08-23 18:22
Duplicate of #3968

**Closed as completed by remyperona** 2021-08-23 18:22 UTC
Labels: duplicate
