### ISSUE TITLE
RUCSS doesn't process or safelist preloaded CSS (rel=preload + javascript to inject it)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4137] opened 2021-07-07 06:19 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
RUCSS doesn't process or able to safelist preloaded CSS automatically switching into a stylesheet after the page loads. 

Example: 

```
<link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
```

Safelisting a used property or the whole file doesn't help. 

The temporary fix is to switch the `<link>` to be used without preload. Example: 

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
```

**To Reproduce**
1. Preload manually a CSS file using the `onload` attribute to switch it to a stylesheet
2. Use one of the CSS properties from the stylesheet to make sure the CSS there should be considered as used CSS
3. Run RUCSS with or without safe listing the file or the user CSS property
4. See that the property is not added to the used CSS (or the CSS file is not excluded)

**Expected behavior**
RUCSS should recognize that kind of CSS injection and use it to generate the used CSS. Or safelist it if needed.

**Screenshots**
N/A

**Additional context**
The warmup process seems to include the CSS file. But it doesn't seem to be processed at the SaaS end. 

RUCSS removes the file even if it doesn't consider it while building the used CSS. 

Ticket - https://secure.helpscout.net/conversation/1552656530/274223/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2021-07-16 16:19
@Tabrisrp Is it an issue that can be resolved from WP Rocket or on SaaS side?

**Comment by remyperona** [comment] 2021-08-25 19:34
Duplicate of #4284

**Closed as completed by remyperona** 2021-08-25 19:34 UTC
Labels: duplicate
