### ISSUE TITLE
Delay JS Execution: Prevent empty field

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3593] opened 2021-02-15 14:29 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- WP Rocket 3.8.4
- the bug hasn’t been reported before

**Describe the bug**
When Delay JS Execution is enable but the field is empty, the `rocket-browser-checker-js-after` inline JS is loaded unnecessarily on front and can potentially cause JS issues

**To Reproduce**
1. Go to File Optimizations tab
2. Enable the Delay JS execution option
3. Empty the field and save settings
4. Search for `rocket-browser-checker-js-after` script in the source code

**Expected behavior**
Prevent a blank field to enable this option or not load the inline script if the field is empty

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1396582738/231502/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1613397859014800

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by iCaspar** [comment] 2021-03-01 18:48
Reproduced ✔️ 

**Root cause** is that in `Engine/Optimization/DelayJS/Subscriber::add_delay_js_script()` we only check for whether the option is allowed, but we don't check for whether there are actually any entries in the rocket options `delay_js_scripts` entry.

**Solution** is to check that `delay_js_scripts` is not an empty array. This will require adding a public function to `DelayJS/HTML` class because the options in there are protected -- something like

```
public function has_delayed_items(): bool {
  return ! empty( $this->options->get( 'delay_js_scripts` ), [] );
}
```
should suffice.

Then in the subscriber, add that to the guard clause alongside the `is_allowed()` condition for early bailout if it returns false.

New unit test is needed for the new public function in `HTML`
Existing tests for `Subscriber::add_delay_js_script()` will need updated to check for the new bailout expectation.

**Estimate: [S]**

**Comment by crystinutzaa** [comment] 2021-03-01 18:53
Just a note: I think we need to check also the filter `rocket_delay_js_scripts` which might affect the option `delay_js_scripts` in `has_delayed_items()` function.

**Comment by remyperona** [comment] 2021-04-07 15:45
Closing this value, as the new approach doesn't use the inclusion field anymore.

**Closed as completed by remyperona** 2021-04-07 15:45 UTC
Labels: type: bug, invalid, priority: high, effort: [S], severity: major, module: delay JS
