### ISSUE TITLE
Issue with combining multiple Google Font requests containing multiple font families

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3099] opened 2020-09-15 01:34 UTC
When there are multiple Google Font declarations on a page and one or more of them contains multiple fonts, combining them in WP Rocket will omit some fonts. 
When multiple are declared in a single request, the first font one from each will not be included in the combined request, only the second one. 

Example: 

Original HTML - 4 fonts are referenced here: 
https://jmp.sh/Y2k8Uvm

With WP Rocket and Optimize Google Fonts - only the 2nd font from each original declaration is included in the resulting request:
https://jmp.sh/Q34PZLx

**To Reproduce**

Add the following font declarations to the HTML:
`<link href="https://fonts.googleapis.com/css2?family=Poppins&family=Rubik&display=swap" rel="stylesheet" type='text/css' media='all' />`

`<link href="https://fonts.googleapis.com/css2?family=Noto+Serif&family=Krub&display=swap" rel="stylesheet" type='text/css' media='all' />`

With Optimize Google Fonts active, notice that the request produced is: 
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rubik%7CKrub&#038;display=swap" />`

(Issue can be seen on Mega currently)

**Expected behavior**
The request that WP Rocket produces should contain all the fonts originally declared.

Additional note: there's now css and css2. [CSS2 supports variable fonts](https://developers.google.com/fonts/docs/css2). Not sure what's expected if a site is using a combination of both API versions.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment] 2020-09-23 12:14
related: https://secure.helpscout.net/conversation/1288868554/196601?folderId=3864740

**Comment by crystinutzaa** [comment] 2020-11-10 11:18
### Reproduce the problem ✅ 
Reproduced on local installation

### Identify the root cause ✅ 
Google Fonts APIs allows multiple family= in the URL: https://fonts.googleapis.com/css2?family=Poppins&family=Rubik

However wp_parse_args() will overwrite multiple GET into a single one, so always the last family will be used.
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/Engine/Optimization/GoogleFonts/Combine.php#L137


### Scope a solution ✅ 
The solution is to remove: `$font = wp_parse_args( $query );` and create a function which will allow to identify and accomodate multiple families and subsets. 

### Estimate the effort ✅ 
Effort `[S]`

**Comment by iCaspar** [comment] 2020-11-17 18:13
On further investigation, this issue is happening as a result of moving from google fonts api v1 to api v2... as indicated in the OP example urls `.../css2?...`

The old API requested multiple families as part of a single string, whereas the new one has multiple `?family=` segments in the url.

Unfortunately, we can't simply ignore the old API, because LOTS of sites will still be using it. So our solution here needs to create a way to handle the new API. Not just for this issue, but to handle selections of font weights and subsets, which are also handled differently.

API2 Docs: https://developers.google.com/fonts/docs/css2

Related #3264: Will also need to be able to handle requests formatted for either API version.

Revising estimate from [S] to [M].

**Comment by iCaspar** [comment] 2020-11-18 14:26
See [the note](https://github.com/wp-media/wp-rocket/issues/3264#issuecomment-729709884) on #3264. 

Resolving the issue of handling multiple APIs there also resolves this issue.
(Leaving this open as a duplicate for now for reference.)

**Closed** 2020-11-26 14:13 UTC
Labels: duplicate
