### ISSUE TITLE
Display a notice after a site was cloned to disable/re-enable WP Rocket

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5667] opened 2023-01-09 12:23 UTC
**Is your feature request related to a problem? Please describe.**
Not all users are aware they have to deactivate WP Rocket before a migration/clone and if a user migrate/clone their site with WP Rocket active, it can leads to issues like a non cached/optimized site due to wrong config files. 

Deactivate/re-activate WP Rocket allows to recreate the right config files and fixes the issues.

**Describe the solution you'd like**
Display a notice after a site was cloned to disable/re-enable WP Rocket. 

**Describe alternatives you've considered**
Auto-detect the new domain/site URL and deactivate/re-activate WP Rocket in background.
Woocommerce detects when a new domain/site URL is found and automatically disable functionality like Subscriptions.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2114325821/393025/
HS Doc: https://docs.wp-rocket.me/article/705-changing-domains-migrating-sites-with-wp-rocket

**Comment by piotrbak** [comment] 2023-01-09 12:40
Should be fixed together with:
https://github.com/wp-media/wp-rocket/issues/5647
https://github.com/wp-media/wp-rocket/issues/5549

**Comment by CrochetFeve0251** [comment] 2023-01-16 16:17
## Identify the root cause
The root issue is that we never check the actual URL.
## Scope a solution
A solution would be to develop a section of the code here to detect a change of domain with an action `rocket_domain_changed`.
And hook a piece of code corresponding to each issue in the corresponding part:
- A clear of the cache inside the cache part.
- A reset of the preload cache table inside the preload part.
- A clear from the config and of `advanced-cache.php`

For the detecting part we can use an option to save the last url.
If this one dismatch the current URL then we can launch the action `rocket_domain_changed` that will launch the hooked actions.
To implement that part we will have to create a subscriber inside `Engine\Admin` in a subfolder `DomainChange` with the following content:
```php
<?php
namespace WP_Rocket\Engine\Admin\DomainChange;

class Subscriber implements Subscriber_Interface {

  const LAST_BASE_URL_OPTION = 'wp_rocket_last_base_url';

   protected $filesystem;

   public function __construct($filesystem) {
     $this->filesystem = $filesystem;
   }

    public static function get_subscribed_events() {
     return [
     'admin_init'  => 'maybe_launch_domain_changed'
    ];
    }
    
    public function maybe_launch_domain_changed() {
     $base_url = trailingslashit(home_url());
     if(! get_option(self::LAST_BASE_URL_OPTION)) {
         update_option(self::LAST_BASE_URL_OPTION, $base_url);
        return;
      }
     $last_base_url = get_option(self::LAST_BASE_URL_OPTION);
    if($base_url === $last_base_url) {
     return;
    }
    update_option(self::LAST_BASE_URL_OPTION, $last_base_url);
    do_action('rocket_domain_changed');
   }
}
```
Then for the cache part we will have to add the following hook into the [subscriber from the preload](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Subscriber.php):
```php
'rocket_domain_changed' => 'on_permalink_changed'
```

For the Cache part we can add the following logic to the [AdminSubscriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Cache/AdminSubscriber.php) to the events:

```php
'rocket_domain_changed' => 'regenerate_configs'
```
with the following method:
```php
public function regenerate_configs() {
     rocket_generate_advanced_cache_file();
}
```
## Estimate the effort
Effort `S`

**Closed as completed** 2023-08-04 08:17 UTC
Labels: type: enhancement, needs: copywriting, priority: medium, needs: documentation, effort: [S], module: filesystem
