### ISSUE TITLE
RUCSS Consumes All Server Resources

### ISSUE THREAD

**Issue by markllego** [wp-media/wp-rocket#4410] opened 2021-10-07 03:45 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Version 3.9.4.1

**Describe the bug**
Upon using RUCSS, it consumes all the resources of my NGINX/Apache webserver. 

Load Average: 22.97
Memory Usage: 98.06%
Disk Usage: 45.18%

**To Reproduce**

1. Go to WP Rocket Settings
2. Click on the File Optimization Tab and check the RUCSS 
3. During or after the RUCSS generation, the resources on my webserver skyrocketed
4. Website becomes unusable

**System Info**
Machine type
n2-highcpu-4 (4 vCPUs, 4 GB memory)

CPU platform
Intel Cascade Lake

Server architecture
Linux 5.11.0-1020-gcp x86_64

Webserver
Apache/2.4.48 (Unix) OpenSSL/1.1.1f

PHP version
7.4.23 (Supports 64bit values)

PHP SAPI
fpm-fcgi

PHP max input variables
3000

PHP time limit
300

PHP memory limit
256M

Max input time
600

Upload max filesize
256M

PHP post max size
256M

cURL version
7.68.0 OpenSSL/1.1.1f

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by markllego** [comment] 2021-10-07 05:36
![Screenshot (616)](https://user-images.githubusercontent.com/9133877/136325876-270bf152-19fa-40a8-9687-1a618f4f1f1d.jpg)

Tested on a newly build Google Cloud Server, I can confidently say that RUCSS is causing a massive spike in server resources.

**Comment by GeekPress** [comment] 2021-10-07 09:01
Duplicate of https://github.com/wp-media/wp-rocket/issues/4072

**Closed as completed by GeekPress** 2021-10-07 09:01 UTC
