### ISSUE TITLE
Renewal banner is displayed while auto renew is set

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4641] opened 2022-01-11 08:53 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.6
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Renewal banner is displayed for users with auto-renewal true

**To Reproduce**
Precondition:
- Having user with license about to expire within next 30 days + auto-renew is enabled

1. Open WPR settings 
2. Renewal banner is displayed

**Expected behavior**
Renewal banner shouldn't be displayed

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2022-01-11 19:13
There is a check for the auto renew value before displaying the banner: https://github.com/wp-media/wp-rocket/blob/4549191aaf543f641d8785afbf23352ed1ebfd03/inc/Engine/License/Renewal.php#L165

Did the user tested with correctly have the `has_auto_renew` property value to `true` from the API?

**Comment by piotrbak** [comment] 2023-01-18 16:56
Closing it since we didn't get the feedback and couldn't reproduce it.

**Comment by adinaWP** [comment] 2023-02-01 11:45
This issue persists, and it is confusing especially for Infinite license users who have installed the plugin on their customers sites. 

If WP Rocket customers have the auto-renewal enabled, they should not see a expiration banner / countdown timer, but this continues happening

A new case reported the other day: https://wp-rocket.me/wp-admin/user-edit.php?user_id=230864

Auto-renewal is enabled, and the license will auto-renew on February 10th, but the banner inviting her to renew is displayed on the dashboard.

The customer has the latest plugin version installed - 3.12.5.2

**Closed as completed** 2023-02-12 19:32 UTC
Labels: type: bug, waiting for feedback, Module: dashboard, priority: medium, severity: moderate
