### ISSUE TITLE
E_ERROR: Uncaught TypeError: Argument 1 passed to UsedCSS::revert_to_pending()

### ISSUE THREAD

**Issue by w3guy** [wp-media/wp-rocket#5986] opened 2023-06-17 11:37 UTC
**Describe the bug**

We've been getting the below error intermittently. Just thought I should let you be aware. Apparently it happens during Cron request.

Error Level: E_ERROR
Message: Uncaught TypeError: Argument 1 passed to WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::revert_to_pending() must be of the type int, string given, called in /app/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 827 and defined in /app/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:444
Stack trace:
#0 /app/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(827): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->revert_to_pending()
#1 /app/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php(121): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->clear_failed_urls()
#2 /app/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\RUCSS\Cron\Subscriber->cron_remove_failed_jobs()
#3
File: /app/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2023-06-18 13:44
This is a duplicate of this issue:
https://github.com/wp-media/wp-rocket/issues/5927

**Closed as completed by piotrbak** 2023-06-18 13:44 UTC
