### ISSUE TITLE
Async css without preload

### ISSUE THREAD

**Issue by Kilbourne** [wp-media/wp-rocket#3522] opened 2021-01-26 17:45 UTC
Actually there's no way to async a stylesheet without preloading it on browsers that support preload.
The solution is to add an exclusion filter for css you want async without preloading and then toggling the media attribute instead of the rel attribute for these ones.

Yet better would be replace the currently used pattern:
```
<link rel="preload" href="mystyles.css" as="style" onload="this.rel='stylesheet'">
```
with
```
<link rel="preload" href="/path/to/my.css" as="style">
<link rel="stylesheet" href="/path/to/my.css" media="print" onload="this.media='all'"> 
```
(and opting-out the first link for styles that don't need preloading)

 Why choosing to not preload in most cases and why this way is to prefer, it's well explained in a post by filament group.

[https://www.filamentgroup.com/lab/load-css-simpler/#can%E2%80%99t-rel%3Dpreload-do-this-too%3F](https://www.filamentgroup.com/lab/load-css-simpler/#can%E2%80%99t-rel%3Dpreload-do-this-too%3F)
_In the past year or two, we’ve been using link[rel=preload] (instead of rel=stylesheet) to achieve a similar pattern as above (toggling the rel attribute once loaded instead of the media attribute, respectively). It still works fine to use that approach, however, there are a couple of drawbacks to consider when using preload. First, browser support for preload is still not great, so a polyfill (such as the one loadCSS provides) is necessary if you want to rely on it to fetch and apply a stylesheet across browsers. **More importantly though, preload fetches files very early, at the highest priority, potentially deprioritizing other important downloads, and that may be higher priority than you actually need for non-critical CSS.**
Fortunately, if you happen to want the high-priority fetch that rel=preload provides (in browsers that support it), you can combine it with the above pattern
Given the simple and declarative nature of the code above, we’d choose that over a polyfill, so the print media toggle approach is our preference again now._

**Comment by GeekPress** [comment] 2021-02-05 11:13
Duplicate of https://github.com/wp-media/wp-rocket/issues/2658

**Closed as completed by GeekPress** 2021-02-05 11:13 UTC
Labels: invalid, feature request
