### ISSUE TITLE
RUCSS problem with <noscript> tags

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3957] opened 2021-05-26 18:24 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The style that's present in the <noscript> is processed by the Treeshaker (and removed from the source).

**To Reproduce**
1. Add the following code to the `head`:
`<noscript><style id="test">div{display:none !important;}</style></noscript>`
2. Enable RUCSS
3. Visit the page

**Expected behavior**
We should:
1. Always preserve the `<noscript><style id="id"></style></noscript>` in the source
2. Exclude it from processing, so nothing from this file is added to the used CSS

**Additional context**
Adding `high` priority, as popular social [sharing plugin](https://wordpress.org/plugins/social-pug/) has `data-lazy-src` in the JS file. It ends up in a conflict with the Lazy Load, as  `[data-lazy-src]{display:none !important;}` from the <noscript> is added to the Used CSS

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by webtrainingwheels** [comment] 2021-05-26 18:32
The related ticket for this problem: https://secure.helpscout.net/conversation/1519241486/265582?folderId=377611

**Comment by jazir555** [comment] 2021-06-04 22:28
+1

**Comment by crystinutzaa** [comment] 2021-06-07 12:26
### Reproduce the issue ✅ 
Identified on my local

### Identify the root cause ✅ 
The root cause is in TreeShaker as it process the styles from noscripts.

### Scope a solution ✅ 
Even if the styles will not be processed by TreeShaker, it will be removed from HTML.
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L420
During the inline_styles parsing, we need to check if the parent of the inline style is `noscript` and bypass the removal of it. 

### Estimate the effort ✅
Effort `[S]`

**Comment by mostafa-hisham** [comment] 2021-06-07 12:48
### Reproduce the issue ✅ 
Identified on my local

### Identify the root cause ✅ 
we need  to not remove the content of NoScript tags and not send it to the tree shaker

Sorry I didn't notice that Cristina was working on this issue
but this what I found

### Scope a solution ✅ 
edit the regex in these lines to not collect the inline CSS and links inside the script tags
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L422-L425

we can do it like this
```
$link_style_pattern='<link\s+([^>]+[\s"\'])?href\s*=\s*[\'"]\s*?(?<url>[^\'"]+\.css(?:\?[^\'"]*)?)\s*?[\'"]([^>]+)?\/?>';
$inline_inline_pattern='<style(?<atts>.*)>(?<content>.*)<\/style>';

$link_styles        = $this->find('<noscript[^>]*>.*' . 
                                              '<link\s+([^>]+[\s"\'])?href\s*=\s*[\'"]\s*?([^\'"]+\.css(?:\?[^\'"]*)?)\s*?[\'"]([^>]+)?\/?>' . '.*<\/noscript> (*SKIP)(*FAIL)|'.$link_style_pattern , $html_nocomments );
$inline_styles      = $this->find('<noscript[^>]*>.*' . '<style(.*)>(.*)<\/style>' . '.*<\/noscript>(*SKIP)(*FAIL)|'.$inline_inline_pattern , $html_nocomments );
```

### Estimate the effort ✅
Effort `[S]`

**Comment by remyperona** [comment] 2021-06-07 13:02
As an addition, we would not need this exclusion anymore, as it would no longer be processed:

https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L83

**Comment by vmanthos** [comment] 2021-06-09 13:31
Potentially related: https://secure.helpscout.net/conversation/1534557135/269468/

**Comment by Mai-Saad** [comment] 2021-06-18 10:31
@vmanthos  @Tabrisrp for this URL https://onlinebutcher.co.za/product/boskruin-butchery-and-deli/beef/boerewors-flavoured/ , the problem still on this PR branch and it fixed when excluded `woocommerce.css` .. test template here https://new.rocketlabsqa.ovh/butcher/

**Comment by remyperona** [comment] 2021-06-18 11:14
The full fix is in 2 parts, one on the plugin side, and one on the SaaS side. Can you test with the staging URL to regenerate the used CSS and see if it works?

**Comment by Mai-Saad** [comment] 2021-06-18 12:17
@Tabrisrp yes I am using staging saas and the problem related to `flex-control-nav flex-control-thumbs` is not fixed unless we add `woocommerce.css` to safelist .. I think it's another issue.

https://user-images.githubusercontent.com/76941962/122559285-6de25a80-d03f-11eb-9724-2d65d24e4748.mp4

**Closed as completed** 2021-06-18 16:56 UTC
Labels: type: bug, priority: high, effort: [S], severity: major, module: remove unused css
