### ISSUE TITLE
CDN is not replacing URLs using escape characters

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4956] opened 2022-04-21 10:03 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the CDN feature is enabled, we are not replacing domains using escape characters. 

Example: 

`https:\/\/domain.ext\/wp-content\/uploads\/2022\/03\/18.jpg`

This will cause the browsers to fetch some resources from the origin server, which might impact performance and scores.

Escape characters are used on tags attributes and JavaScript codes. 

We could look for that kind of URLs using the following REGEX: 

```
'/("|\'|;| )https:\\\\\/\\\\\/(domain.ext)\\\\\/wp-content\\\\\/(.*?)\.(jpg|jpeg|png|webp|js|css|svg|avif)/'
```

And proceed with the replacement. 

The 4 `////` are needed to match `/` on the code. That is 5 `/////` total. 

**To Reproduce**
1. Use resources with an escape character
2. Enable the CDN feature
3. See that resources using an escape character are not replaced

**Expected behavior**
The CDN feature should replace all resources with the CNAME. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1853815839/338286

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment] 2023-05-12 19:25
@DahmaniAdame Could you share the helper plugin here or on the ticket? I think I have a similar case and would like to test it

**Comment by DahmaniAdame** [comment] 2023-05-13 04:40
@webtrainingwheels, the helper was to manipulate the buffer, the same as Alfonso provided on Slack.

**Comment by webtrainingwheels** [comment] 2023-05-15 16:27
>This will cause the browsers to fetch some resources from the origin server, which might impact performance and scores.

In this case: https://secure.helpscout.net/conversation/2239860817/419437?folderId=377611
This problem actually breaks a feature on the customer's site - product images don't swap as they should when a different color is selected.


If anyone else needs to solve this problem, you can use the below helper plugin. You need to edit line 23 with the relevant domains. 
[wp-rocket-manipulate-buffer.php.zip](https://github.com/wp-media/wp-rocket/files/11479882/wp-rocket-manipulate-buffer.php.zip)

**Comment by webtrainingwheels** [comment] 2023-09-29 22:30
I think this is a duplicate of https://github.com/wp-media/wp-rocket/issues/2353 ?
Should they be merged?

**Comment by piotrbak** [comment] 2024-06-27 11:10
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Closed as not planned by piotrbak** 2024-06-27 11:10 UTC
Labels: type: enhancement, module: CDN, priority: low
