### ISSUE TITLE
JS Concatenation removing trailing semicolon on empty for loop

### ISSUE THREAD

**Issue by jorgemartine00** [wp-media/wp-rocket#4054] opened 2021-06-15 17:09 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**To Reproduce**
1. turn on JS concatenation and minification
2. Enqueue the following script: `wp_enqueue_script( 'del-me', '/wp-includes/js/dist/components.min.js', [], '20120202' );`
3. Open Developer Console and see error `Uncaught SyntaxError: Unexpected token '}'`

**Expected behavior**
Script should be enqueued correctly and no error message should be displayed in the console.

**Additional context**
The enqueued code has an empty for loop which requires a trailing semicolon to be correct, since those statements are optional but semicolon is still required.
{t=[];for(var f=1+Math.round(l/c);f>t.push({value:c*t.length+r});**);}**

and after the combine, it turns into this, with a dropped semi-colon:
{t=[];for(var f=1+Math.round(l/c);f>t.push({value:c*t.length+r});**)}**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2023-06-06 12:58
We can't reproduce it and we don't have any feedback about this one. Going to close it, please feel free to reopen if it reappears

**Closed as completed by piotrbak** 2023-06-06 12:58 UTC
Labels: type: bug, can't reproduce, priority: low, needs: grooming, module: minify JS
