### ISSUE TITLE
in-progress URLs aren't reverted to pending when disabling preload

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5933] opened 2023-05-19 09:32 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.13.2`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When preload is disabled while there are URLs `in-progress` those will not be preloaded if the feature is enabled.
This is because they aren't reverted to `pending` despite having a method for that:
https://github.com/wp-media/wp-rocket/blob/f742625162e6011a153e71bf94e6bba9812c0968/inc/Engine/Preload/Database/Queries/Cache.php#L449

This runs but the actual table row isn't updated.

**To Reproduce**

1. Clear and preload the cache.
2. Check the `wpr_rocket_cache` table. When there are rows where the status is `in-progress` disable preload.
3. Check the `wpr_rocket_cache` table again. There will still be rows where the status is `in-progress`.

**Expected behavior**

The status of `in-progress` rows should be reverted to `pending` when disabling the preload feature.

**Screenshots**

N/A

**Additional context**

N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2024-06-03 19:36
The AC:
1. When disabling the preload, all the preload `in-progress` URLs need to be set back to `pending`
2. When disabling the preload, we need to be sure that the requests for the already registered jobs are not sent (either canceling them or bailing out very early and making sure that the status is `pending`)
3. For testing purposes, we need to be sure that the cache is not cleared when disabling or enabling the preload

@MathieuLamiot what's the impact of the `to-submit` status for the preload? Is it being used in this context?

**Comment by MathieuLamiot** [comment] 2024-06-04 07:49
We don't use the to-submit status on preload.

**Comment by Miraeld** [comment] 2024-06-09 21:21
I can't reproduce the issue, 
`in-progress` rows are always set back to `pending` when I disable preload.. 
Is there more specification on how to reproduce the issue ?

**Comment by remyperona** [comment] 2024-06-11 19:41
Looking at the code, everything is already implemented for the ACs of this issue.

**Comment by piotrbak** [comment] 2024-06-18 13:28
We can close the issue then

**Closed as completed by piotrbak** 2024-06-18 13:28 UTC
Labels: type: enhancement, needs: testing, module: preload, priority: low, needs: product direction
