### ISSUE TITLE
Success Message is not displayed after countdown when RUCSS is enabled until refresh

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket#6614] opened 2024-05-03 15:04 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.16
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When RUCSS is enabled and notice with the countdown is displayed, the Success notice will not be displayed after the countdown until the page is refreshed.

**To Reproduce**
1. Enable RUCSS and see the countdown starts.
2. Wait for the countdown
3. See that it stops at 1 and does not display the success notice.
4. Refresh the page and the success notice is displayed.

**Expected behavior**
The countdown notice should immediately be hidden once the countdown elapsed and the success notice should be displayed.

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment] 2024-05-16 09:56
Duplicate of:
https://github.com/wp-media/wp-rocket/issues/6633

**Closed as not planned** 2024-06-28 15:23 UTC
Labels: type: bug, module: remove unused css, module: user interface
