### ISSUE TITLE
3.8.4 breaks media library and many other plugins

### ISSUE THREAD

**Issue by fclugano** [wp-media/wp-rocket#3568] opened 2021-02-06 10:03 UTC
On our websites:
PHP 7.3 and 7.4
WP 5.5.3

After the upgrade to WP Rocket 3.8.4 we cannot browse the library anymore. No content is shown. We cannot upload new pictures too in wp articles too. Even the plugin WP Optimize is broken.

We had another website still on V3.8.3 and we used those WP-Rocket files to downgrade to V 3.8.3 and now everything is fine again.

**Comment by remyperona** [comment] 2021-02-08 14:52
Hi @fclugano,

Are you using NextGEN gallery?

**Comment by fclugano** [comment] 2021-02-09 10:31
> Hi @fclugano,
> 
> Are you using NextGEN gallery?

Yes, exactly

**Comment by WPcare** [comment] 2021-02-09 12:00
Same problem here! Using NextGen but experiencing issues on other plugins like Ninja Forms.

**Comment by vmanthos** [comment] 2021-02-09 12:32
@Tabrisrp 

We have a few similar reports, all related to the NextGEN gallery.

On a customer's website, I used the following instead of plain `is_admin()`, and the issue is fixed:
```PHP
public function deactivate_resource_manager() {
		if( is_admin() ){
			return false;
		}
		return true;
	}
```
Natalia confirmed the same on her test site.

I'm not sure why this works. ¯\_(ツ)_/¯

**Comment by remyperona** [comment] 2021-02-09 13:01
Instead of directly returning `true/false`, we should be returning the value passed by the filter:

```PHP
public function deactivate_resource_manager( $valid_request ) {
		if ( is_admin() ) {
			return $valid_request;
		}

		return false;
	}
```

Thay way, in an admin context, we preserve the behaviour set by NGG. And on the front, we continue as before to disable it to prevent the original conflict.

**Comment by fclugano** [comment] 2021-02-09 13:06
for us, it breaks a major functionality like the media library and the compatibility with a lot of other plugins. We are WP rocket customers, not developers, so it is up to you to find a solution :) thank you for your efforts

**Comment by GeekPress** [comment] 2021-02-09 13:42
@vmanthos How many tickets have been reported because of this regression?

I'm asking the question to know if this bug should be fixed in urgency to be implemented in 3.8.5

**Comment by vmanthos** [comment] 2021-02-09 14:11
Natalia mentioned 3 possibly related tickets, and with the ones that we have in this thread, the total is 5.

**Comment by GeekPress** [comment] 2021-02-09 14:56
@vmanthos You already submitted the patch, you rock :)

@Tabrisrp @wp-media/qa Can this be added to 3.8.5?

**Comment by alfonso100** [comment] 2021-02-09 14:58
another case: https://secure.helpscout.net/conversation/1418864162/237497?folderId=2683093

**Closed as completed** 2021-02-10 15:15 UTC
Labels: 3rd party compatibility, priority: high, type: regression, severity: major
