### ISSUE TITLE
Google Analytics add-on doesn't support GA code added via All in One SEO

### ISSUE THREAD

**Issue by sabrina-zeidan** [wp-media/wp-rocket#1540] opened 2019-02-14 09:33 UTC
We [check](https://github.com/wp-media/wp-rocket/blob/c92efa3a52ef285eb6230a04ac4c5e6d4e2f8e26/inc/classes/busting/class-google-analytics.php#L226) for GoogleAnalyticsObject match, but the way [All in One SEO Pack ](https://wordpress.org/plugins/all-in-one-seo-pack/) adds GA code is different, so it doesn't match

`<script type="text/javascript" >window.ga=window.ga\|\|function(){(ga.q=ga.q\|\|[]).push(arguments)};ga.l=+new Date;
  | ga('create', 'UA-XXX', 'auto');
  | // Plugins
  | ga('require', 'displayfeatures');ga('require', 'ec');
  | ga('send', 'pageview');</script> <script async src="https://www.google-analytics.com/analytics.js">
`

**Related ticket**
https://secure.helpscout.net/conversation/778255355/96553

**Comment by webtrainingwheels** [comment] 2020-04-13 19:40
https://secure.helpscout.net/conversation/1132943977/157007?folderId=377611

**Comment by GeekPress** [comment] 2020-05-21 12:38
Duplicate of #2160

**Closed by GeekPress** 2020-05-21 12:38 UTC
Labels: duplicate, module: Google tracking add-on, type: enhancement
