### ISSUE TITLE
RUCSS should preserve some <style> in some cases

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4598] opened 2021-12-17 11:15 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some themes and plugin will try to manipulate existing `<style>`. 

When RUCSS is used, the target `<style>` element will be deleted. Leaving a console error in some cases.

Example: 

```
<html>
<body>
<!--StartFragment-->

<style id='divi-style-parent-inline-inline-css' type='text/css'>
/*!
Theme Name: Divi
Theme URI: http://www.elegantthemes.com/gallery/divi/
Version: 4.14.3
Description: Smart. Flexible. Beautiful. Divi is the most powerful theme in our collection.
Author: Elegant Themes
Author URI: http://www.elegantthemes.com
License: GNU General Public License v2
License URI: http://www.gnu.org/licenses/gpl-2.0.html
*/
</style>
```
```
<script type="application/javascript">
(function() {
    var file     = ["https:\/\/www.domain.com\/ka_seite\/et-cache\/222441\/et-divi-dynamic-tb-222629-222441-late.css"];
    var handle   = document.getElementById('divi-style-parent-inline-inline-css');
    var location = handle.parentNode;

    if (0===document.querySelectorAll('link[href="' + file + '"]').length) {
        var link  = document.createElement('link');
        link.rel  = 'stylesheet';
        link.id   = 'et-dynamic-late-css';
        link.href = file;

        location.insertBefore(link, handle.nextSibling);
    }
})();
</script>
```

After processing RUCSS, the `<style>` is removed.  And the style inside `.insertBefore()` is not processed. 

In this case, it's resulting in a console error: 

```
(index):1183 Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at (index):1183
    at (index):1193
(anonymous) @ (index):1183
(anonymous) @ (index):1193
```

Safelisting selectors from inside `.insertBefore()` doesn't fix the issue.

**To Reproduce**
1. Add the above and target an element on the page using `.insertBefore()`
2. . If the script doesn't have a fallback in cache the targeted element doesn't exist, it will result in a console error.

**Expected behavior**
Ideally, we should check if `.insertBefore()` and preserve a placeholder with the selectors after Used CSS is injected. 

A broader approach would be to simply preserve placeholders for all inline `<style>` after getting processed by RUCSS. It should also work for https://github.com/wp-media/wp-rocket/issues/4554

**Screenshots**
N/A

**Additional context**
Related to https://github.com/wp-media/wp-rocket/issues/4554 but since the `<style>` wasn't empty, I added it as a separate issue.

Ticket - https://secure.helpscout.net/conversation/1727751196/314385

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment] 2021-12-23 13:44
Related - https://secure.helpscout.net/conversation/1734135948/315461/

**Comment by DahmaniAdame** [comment] 2022-01-14 08:01
Related - https://secure.helpscout.net/conversation/1747586547/317449/

**Comment by DahmaniAdame** [comment] 2022-01-15 08:51
@piotrbak  - there is an additional problem related to this issue. 

The dynamic file will override the same selectors once it loads using JavaScript since it comes after RUCSS. 

Maybe we should automatically disable Divi's Dynamic CSS when using RUCSS? 

The same would apply to Divi's Critical CSS.

It doesn't make sense to keep it anyway if we are generating the Used CSS.

Should I open a separate issue for that?

**Comment by vmanthos** [comment] 2022-03-01 12:26
Related: https://secure.helpscout.net/conversation/1788130755/326288?folderId=2135277

**Comment by vmanthos** [comment] 2022-04-07 11:51
**Related:** https://secure.helpscout.net/conversation/1837137447/335708/

There is also the following Divi selector, that's causing a JavaScript error with `3.11`, and that should be preserved:
`divi-style-inline-inline-css`

We can add it here:
https://github.com/wp-media/wp-rocket/blob/4fd09b218760d854109843528da4f148e668d42b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L60-L68

The script that's used is: https://snippi.com/s/8m82eal

After the issue is fixed on our side, the CSS file will be loaded: https://youtu.be/eyhD3d5EjpE

@wp-media/productrocket is this something we want to keep?

In [another case](https://github.com/wp-media/wp-rocket/issues/4792), with the old Remove Unused CSS, that file loading was causing issues.

Divi's options used in the customer's site:
* https://i.vgy.me/x3Djvl.jpg
* https://i.vgy.me/TaTLVK.jpg

**Ticket:** https://secure.helpscout.net/conversation/1827718685/333872/

**Comment by piotrbak** [comment] 2022-04-07 11:54
@vmanthos Yes, thank you.

@wp-media/php Can we add it to the 3.11.0.3?

**Comment by vmanthos** [comment] 2022-04-07 12:03
@piotrbak I can create the PR for this.

The real question here is if we want this behavior, i.e. still load that Divi file, given that we have already added the CSS from there in the used CSS.

FYI, on the specific site I checked, the "reduce unused CSS" recommendation isn't there despite loading that file:
![](https://i.vgy.me/jccPzp.jpg)

This is even when Divi's script (https://snippi.com/s/8m82eal) is excluded from Delay JavaScript Execution. 👍

**Comment by piotrbak** [comment] 2022-04-07 12:12
@vmanthos How big is this file?

I don't think we have any other way, we can't cause any errors in JS console.

**Comment by vmanthos** [comment] 2022-04-07 12:13
In this case, it was just ~2kb.

> we can't cause any errors in JS console.

Agreed. 

If we decide we don't want this behavior, we could disable the Divi feature that's adding the file, or - a more drastic solution, remove the script from the buffer when Remove Unused CSS is added.

**Comment by piotrbak** [comment] 2022-04-07 12:15
Let's keep it simple. If we see that this file causes PSI warnings, we'll decide what's next.

**Closed as completed** 2022-04-11 13:44 UTC
Labels: type: enhancement, 3rd party compatibility, priority: high, module: remove unused css

**Comment by twwn** [comment] 2022-04-12 10:28
yields repeated
>PHP Warning:  Undefined property: wpdb::$actionscheduler_actions in /srv/wp-includes/wp-db.php on line 740
>PHP Warning:  Undefined property: wpdb::$actionscheduler_groups in /srv/wp-includes/wp-db.php on line 740
>Wordpress database error Table 'db142257_183.a' doesn't exist for querry SELECT a.action_id FROM  a LEFT JOIN  g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='rocket-rucss' AND a.hook='rocket_rucss_pending_jobs_cron' AND a.args='[]' AND a.status IN ('in-progress', 'pending') LIMIT 0, 1 von shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Optimization\RUCSS\Admin\Subscriber->schedule_rucss_pending_jobs_cron, WP_Rocket\Engine\Optimization\RUCSS\Controller\Queue->is_pending_jobs_cron_scheduled, WP_Rocket\Engine\Common\Queue\AbstractASQueue->is_scheduled, as_has_scheduled_action, ActionScheduler_Store->query_action, ActionScheduler_DBStore->query_actions

… and I can't downgrade, neat

**Comment by DahmaniAdame** [comment] 2022-04-27 07:25
Related - https://secure.helpscout.net/conversation/1848228658/337520/

@piotrbak This one is the consequence of preserving the `divi-style-parent-inline-inline-css` to fix this - https://github.com/wp-media/wp-rocket/issues/4598

Fixing it will require preserving any stylesheet that the above overrides. 

Maybe we should have different preservation processing to fit the following: 

1. Cases where the missing inline style will cause JavaScript errors. In this case, we will process the CSS using RUCSS but we keep the empty inline style's placeholder to avoid the JS errors. 
2. Cases where preserving inline style tags is needed to avoid style issues. Like cases with highly dynamic selectors with inline style. This is where fully preserving the inline style will make sense.

**Comment by vmanthos** [comment] 2022-04-27 12:17
**Related:** https://secure.helpscout.net/conversation/1862820678/339724?folderId=2135277

In this case, `divi-style-inline-inline-css` contains inline CSS and is overriding rules from the used CSS.

**Comment by DahmaniAdame** [comment] 2022-05-21 11:12
Ticket - https://secure.helpscout.net/conversation/1890117290/344013/

Preserving `divi-style-parent-inline-inline-css` is causing style override if Divi adds more style using another inline CSS `et-divi-customizer-global-cached-inline-styles`.

Both inline styles should be preserved to avoid conflicts. 

@piotrbak should I PR that directly?
