### ISSUE TITLE
As a new user, CSS and JS minification are enabled by default

### ISSUE THREAD

**Issue by benorfaz** [wp-media/wp-rocket#6862] opened 2024-08-09 16:45 UTC
**Context**
The minification feature is mature and doesn't cause major issues. We can activate it by default so new users don't have to think about it.

**Acceptance Criteria**
- When I install WP Rocket and activate it, CSS and JS minification are enabled
- I toggle it on/off and save changes (as of today)
- When I update from a previous a version of WP Rocket, and minification was disabled, it is still disabled
- UX fix: Behavior is not consistent across features when toggling on-off. For minification, you must save settings before the exclusion box appears, which is not the case for others. Expectated behavior: when toggling on -> extra parameters (exclusion box) is immediately displayed. 

**Additional information**
*Add any additional information that could help or be relevant.*

**Comment by MathieuLamiot** [comment] 2024-11-03 18:37
Duplicate of #7038

**Closed as not planned** 2024-11-15 18:58 UTC
Labels: type: enhancement, needs: documentation, module: minify CSS, module: minify JS
