### ISSUE TITLE
3.0 Alpha - Cloudflare - Undefined index

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#857] opened 2018-03-15 04:58 UTC
Under the Cloudflare Cache section I see the following notice: 
`Notice: Undefined index: description in wp-content/plugins/wp-rocket/views/settings/page-sections/cloudflare.php on line 30`

entire output: 
![wp_rocket_ _wordpress_themes_ _wordpress](https://user-images.githubusercontent.com/1043076/37445078-d1863d0e-27d2-11e8-88eb-ea5e8a6c423e.jpg)

**Comment by Tabrisrp** [comment] 2018-03-15 13:27
duplicate of #829

**Closed by Tabrisrp** 2018-03-15 13:27 UTC
Labels: duplicate
