### ISSUE TITLE
Minification forces a relative path to the content of clip-path

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3742] opened 2021-03-31 07:56 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a CSS file containing the `clip-path` property with an ID like `#my-object`, minification will result in adding a relative path to it going from: 

`clip-path: url(#my-object)`

to 

`clip-path: url(../../../themes/storefront/#my-object)`

**To Reproduce**
1. Add a CSS file with a `clip-path: url(#my-object)`
2. Enable CSS minification/combination
3. Check the resulting CSS file to see the error.

**Expected behavior**
WP Rocket shouldn't apply a relative path to the content of `clip-path: url()`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289174/113110282-cf441b80-91fe-11eb-87d8-0c3c35a031ea.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment] 2021-03-31 07:56
Reported here https://twitter.com/pacotole/status/1376835335737520135

**Comment by remyperona** [comment] 2021-03-31 12:50
Duplicate of #3279

**Comment by pacotole** [comment] 2021-04-06 09:30
Can be fixed with this filter (for inline SVGs):

```php
function fix_path_from_inline_svg($content){
    return preg_replace('/url\([^\#]+(#[\w-]+)\)/', 'url($1)', $content);
}
add_filter('rocket_css_content', 'fix_path_from_inline_svg');
```

**Comment by wassilis83** [comment] 2021-04-13 22:51
> Can be fixed with this filter (for inline SVGs):
> 
> ```
> function fix_path_from_inline_svg($content){
>     return preg_replace('/url\([^\#]+(#[\w-]+)\)/', 'url($1)', $content);
> }
> add_filter('rocket_css_content', 'fix_path_from_inline_svg');
> ```

Where to place this code? If I put this in functions.php I got error:

```
'PHP message: PHP Warning:  strpos() expects parameter 1 to be string
 PHP Warning:  preg_match_all() expects parameter 2 to be string, array given
```

looks not related to preg_replace so maybe I'm placing the code in the wrong position

**Closed as completed** 2021-04-16 08:46 UTC
Labels: duplicate
