### ISSUE TITLE
jquery 3.5.1 compatibility and WP 5.7

### ISSUE THREAD

**Issue by kadolino** [wp-media/wp-rocket#3605] opened 2021-02-17 23:35 UTC
**- Made sure you’re on the latest version**
Yes

**Describe the bug**
The Wordpress jquery migration helper
[https://wordpress.org/plugins/enable-jquery-migrate-helper/](https://wordpress.org/plugins/enable-jquery-migrate-helper/)
report the following jquery 3.5.1 errors for
for: /wp-rocket/assets/js/wpr-modal.js

On March, 09 WP 5.7 needs jquery 3.5.1 compatibility.

wp-rocket/assets/js/wpr-modal.js: jQuery.fn.click() event shorthand is deprecated
wp-rocket/assets/js/wpr-modal.js: jQuery.fn.bind() is deprecated
wp-rocket/assets/js/wpr-modal.js: jQuery.fn.change() event shorthand is deprecated
wp-rocket/assets/js/wpr-modal.js: jQuery.fn.keyup() event shorthand is deprecated

**Solutions**
Solution: Instead of .click(fn) use .on("click", fn). Instead of .click() use .trigger("click")
Solution: Instead of .bind(fn) use .on(fn)
Solution: Instead of .change(fn) use .on("change", fn). Instead of .change() use .trigger("change")
Solution: Instead of .keyup(fn) use .on("keyup", fn)

**See also**
[https://github.com/jquery/jquery-migrate/blob/master/warnings.md](https://github.com/jquery/jquery-migrate/blob/master/warnings.md)

**Additional context**
.click() shorthand is deprecated: https://api.jquery.com/click/#click-handler
.bind() is deprecated: https://api.jquery.com/bind/
.change() is deprecated: https://api.jquery.com/change/#change-handler
.keyup() id deprecated: https://api.jquery.com/keyup/#keyup-handler

**Screenshot**
from wpr-modal.js
![coding](https://user-images.githubusercontent.com/47841723/108281918-fc71c880-7180-11eb-9920-3ee713561726.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2021-02-18 13:44
Thank you for the report @kadolino, we'll fix this before WP 5.7 release to make sure there is no issues remaining

**Comment by remyperona** [comment] 2021-02-18 14:44
### Reproduce the issue ✅ 
Reproduced on WP 5.7 beta3.

### Identify the root cause ✅ 
Our JS files loaded on the admin area, some of which use deprecated jQuery function, which won't be supported anymore once the migrate file is no longer included.

### Scope a solution ✅ 
Update all usage of deprecated jQuery functions to the appropriate replacement, in `wpr-modal.js` and `wpr-admin.js`.

### Estimate the effort ✅
Effort `[S]`

**Closed as completed** 2021-02-23 21:49 UTC
Labels: type: bug, 3rd party compatibility, Module: dashboard, priority: medium, effort: [S], severity: major

**Comment by Mai-Saad** [comment] 2021-02-26 16:07
@Tabrisrp Please notice that on develop we still have wpr warning for jQuery.fn.click() event shorthand is deprecated and  jQuery.fn.change() event shorthand is deprecated 

https://user-images.githubusercontent.com/76941962/109324457-5c413100-785d-11eb-9c3f-47227ee52928.mp4

Reproduce Steps:
1- on https://imagify.rocketlabsqa.ovh/ install develop for wpr
2- inspect and activate wpr plugin 
3- open wpr settings

As per discussion with @piotrbak, it may be related to this function
![image (2)](https://user-images.githubusercontent.com/76941962/109324327-3156dd00-785d-11eb-882b-79ff8382b91a.png)

**Comment by piotrbak** [comment] 2021-02-26 16:31
@Mai-Saad @Tabrisrp I'm not able to reproduce this, but indeed, it seems that this function might be the cause. Is there any reliable list of deprecations, so we can search our files against it?
https://jmp.sh/H6YtVMr

`change()` is not listed in the one I was checking.

**Comment by remyperona** [comment] 2021-02-26 16:36
Make sure your browser uses the latest version of the file, and not the one in browser cache, it might be the reason the warnings are still showing up on your side (and we didn't update the version number for the plugin yet)

**Comment by Mai-Saad** [comment] 2021-02-26 16:37
@piotrbak @Tabrisrp Seems it's false +ve as I tried it incognito and works fine ( seems the browser was cached)
