### ISSUE TITLE
platform.twitter.com/widgets.js gets mistakenly minified/locally hosted on 3.7.5

### ISSUE THREAD

**Issue by socialpreneur** [wp-media/wp-rocket#3370] opened 2020-11-26 14:37 UTC
**Describe the bug**
https://platform.twitter.com/widgets.js gets minified and locally hosted on 3.7.5, it causes WP Rocket to load a lot of .js files from Twitter at beginning of page load, hurting Core Web Vitals.

**To Reproduce**
1. Embed a tweet into a post/page
2. Enable minify JS on the settings
3. Add twitter or twitter.com or anything related to delay JS field

**Expected behavior**
WP Rocket should not minify/locally host widgets.js by default. It used to work fine on previous versions (3.7.3 or anything later than 3.7.0).

**Comment by Tabrisrp** [comment] 2020-12-17 19:43
I can't reproduce this issue, just tested on my local test site, with 3.8.0.1.

The delay JS process is performed before the minification process, so if there is a correct match in the delay JS field, the script is already rewritten with the `data-rocketlazyloadscript` attribute instead of the `src` one, and during the minification process, it will be skipped.

@socialpreneur Do you have the `platform.twitter.com/widgets.js` pattern in the delay JS textarea?

**Comment by socialpreneur** [comment] 2020-12-18 09:26
@Tabrisrp I usually just type twitter in the textarea. And I have not tested this with 3.8.0.1

**Comment by GeekPress** [comment] 2021-02-05 20:25
Hi @socialpreneur 

Can you please retry with the actual last version (3.8.4) and let us know if you still have the problem.

**Comment by GeekPress** [comment] 2022-10-21 13:21
I'm closing the issue since we have no reply and nobody else reported this problem.

@socialpreneur Feel free to comment if you are still facing the problem.

**Closed by GeekPress** 2022-10-21 13:21 UTC
Labels: waiting for feedback, module: minify JS
