### ISSUE TITLE
Divi compatibility: Notice to clear used CSS is missing after re-enabling RUCSS feature even when needed

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6095] opened 2023-08-09 12:34 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
This issue has been spotted by QA while testing #6074 . Notices for Divi users to clear used CSS is not displayed when the Remove Unused CSS option is switched from deactivated to activated, even though it could be needed.

**To Reproduce**
There are a couple of scenarios that are failing.

With Remove Unused CSS enabled and used CSS existing in the database:

1. Disable Remove Unused CSS.
2. Edit the global header in Divi's Theme Builder for any existing template.
3. Enable Remove Unused CSS -> the notice is displayed. ✔️
4. Disable Remove Unused CSS -> the notice isn't displayed. ✔️
5. Enable Remove Unused CSS -> the notice is NOT displayed. ❌
 
For the second scenario, with Remove Unused CSS enabled and used CSS existing in the database:

1. Disable Remove Unused CSS.
2. Delete a template using the Divi Theme Builder -> the notice is not displayed. ✔️
3. Enable Remove Unused CSS -> the notice is NOT displayed. ❌

**Expected behavior**
When activating the Remove Unused CSS options, if a Divi template has been updated since the last update of used CSS, then the notice must be displayed.

**Additional context**
This is a continuation of #6074 

**Acceptance Criteria**
- Scenarios from "To reproduce" are not failling anymore.
- Acceptance criteria of the original feature still pass:
    Whenever Divi Template is updated and Used CSS is enabled, we'll display a dismissible warning on all admin pages (just like for activation/deactivation of the plugins, lack of the CSS is major thing)
    Whenever Divi Template is updated and Used CSS is disabled, notice will not be displayed.
    Wording will be as following: WP Rocket: Your Divi template was updated. Clear the Used CSS if the layout, design or CSS styles were changed.
    After clicking on Clear Used CSS, we'll purge the Used CSS and Cache
    After clicking on Dismiss, the message will disappear
    If the Divi template will be updated in the future, the message should be displayed once again

**Comment by mostafa-hisham** [comment] 2023-08-29 10:16
I couldn't reproduce the problems in both scenarios
I provided recordings of the test


https://github.com/wp-media/wp-rocket/assets/29744252/145d3d57-4a80-49b8-bd2f-e4bafa41e134


https://github.com/wp-media/wp-rocket/assets/29744252/2cd88b0f-2ddb-435a-bcb9-4fccbc8b2024

**FYI:** The recording and testing were done on `fix/truncate-rucss-on-wp-rocket-options-changes` branch of this [PR](https://github.com/wp-media/wp-rocket/pull/6122) because the fix is required for this feature to work. and it is not merged at this time

**Comment by engahmeds3ed** [comment] 2023-09-05 11:25
@vmanthos @MathieuLamiot @piotrbak  what do u think about that?

**Comment by vmanthos** [comment] 2023-09-05 12:53
@engahmeds3ed Both me and @Mai-Saad tested this using `3.15` and the issues aren't there anymore. :tada: 
I'll close the issue.

**Closed as completed by vmanthos** 2023-09-05 12:53 UTC
Labels: type: enhancement, 3rd party compatibility, can't reproduce, priority: low, needs: grooming, module: remove unused css
