### ISSUE TITLE
PHP Warnings after update and on 1st preload

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2441] opened 2020-03-17 11:07 UTC
**Describe the bug**
The customer's debug log file is filled with PHP Warnings for `_temp` file extensions not found after updating to 3.5.0.3 and only on the 1st preload. Here's the log they shared:

```
[13-Mar-2020 08:29:55 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/0-credit-card-abroad/index-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:09 UTC] PHP Warning:  chmod(): No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 168
[13-Mar-2020 08:30:09 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/credit-card-minimum-payment/index-mobile-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:10 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/0-credit-card-abroad/index-mobile-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:21 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/about/index-mobile-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:38 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/press/index-mobile-https.html_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:41 UTC] PHP Warning:  chmod(): No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 168
[13-Mar-2020 08:30:41 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/privacy-policy/index-mobile-https.html_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:43 UTC] PHP Warning:  chmod(): No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 168
[13-Mar-2020 08:30:43 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/resources/index-mobile-https.html_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
```

- The errors did not reoccur.
- When launching a new preload, no warnings or errors were generated.
- When updating to 3.5.0.4, no warnings or errors were generated.

**To Reproduce**
1. Install 3.4.4.
2. Generate the preload.
3. Clear the debug log <- just to be sure.
4. Update to 3.5.0.3.
5. Check the debug log.

**Expected behavior**
Update and generate preload without PHP warnings.

**Additional context**
- WordPress: v5.3.2
- Rocket: 3.5.0.3
- [HS Ticket](https://secure.helpscout.net/conversation/1108808884/151489?folderId=273768)

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Screenfeed** [comment] 2020-03-17 13:44
I am not able to reproduce, but I got these ones instead:
```
[17-Mar-2020 13:37:45 UTC] PHP Notice:  Undefined variable: home_root_escaped in /****/wp-content/plugins/wp-rocket/inc/functions/options.php on line 252
[17-Mar-2020 13:37:45 UTC] PHP Stack trace:
[17-Mar-2020 13:37:45 UTC] PHP   1. {main}() /****/wp-admin/admin-ajax.php:0
[17-Mar-2020 13:37:45 UTC] PHP   2. do_action() /****/wp-admin/admin-ajax.php:45
[17-Mar-2020 13:37:45 UTC] PHP   3. WP_Hook->do_action() /****/wp-includes/plugin.php:478
[17-Mar-2020 13:37:45 UTC] PHP   4. WP_Hook->apply_filters() /****/wp-includes/class-wp-hook.php:312
[17-Mar-2020 13:37:45 UTC] PHP   5. rocket_upgrader() /****/wp-includes/class-wp-hook.php:288
[17-Mar-2020 13:37:45 UTC] PHP   6. flush_rocket_htaccess() /****/wp-content/plugins/wp-rocket/inc/admin/upgrader.php:27
[17-Mar-2020 13:37:45 UTC] PHP   7. get_rocket_htaccess_marker() /****/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:56
[17-Mar-2020 13:37:45 UTC] PHP   8. get_rocket_htaccess_mod_rewrite() /****/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:148
[17-Mar-2020 13:37:45 UTC] PHP   9. get_rocket_cache_reject_uri() /****/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:271
[17-Mar-2020 13:37:45 UTC] PHP Notice:  Undefined variable: home_root_len in /****/wp-content/plugins/wp-rocket/inc/functions/options.php on line 254
[17-Mar-2020 13:37:45 UTC] PHP Stack trace:
[17-Mar-2020 13:37:45 UTC] PHP   1. {main}() /****/wp-admin/admin-ajax.php:0
[17-Mar-2020 13:37:45 UTC] PHP   2. do_action() /****/wp-admin/admin-ajax.php:45
[17-Mar-2020 13:37:45 UTC] PHP   3. WP_Hook->do_action() /****/wp-includes/plugin.php:478
[17-Mar-2020 13:37:45 UTC] PHP   4. WP_Hook->apply_filters() /****/wp-includes/class-wp-hook.php:312
[17-Mar-2020 13:37:45 UTC] PHP   5. rocket_upgrader() /****/wp-includes/class-wp-hook.php:288
[17-Mar-2020 13:37:45 UTC] PHP   6. flush_rocket_htaccess() /****/wp-content/plugins/wp-rocket/inc/admin/upgrader.php:27
[17-Mar-2020 13:37:45 UTC] PHP   7. get_rocket_htaccess_marker() /****/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:56
[17-Mar-2020 13:37:45 UTC] PHP   8. get_rocket_htaccess_mod_rewrite() /****/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:148
[17-Mar-2020 13:37:45 UTC] PHP   9. get_rocket_cache_reject_uri() /****/wp-content/plugins/wp-rocket/inc/functions/htaccess.php:271
```

**Comment by Screenfeed** [comment] 2020-03-17 17:07
@hellofromtonya Should we contact this person to try to reproduce on their site?

**Comment by hellofromtonya** [comment] 2020-03-17 17:12
@Screenfeed The steps that I laid out _might not be_ exact to what the customer did. He noted that it happened during update and 1st preload. 

Could you try to reproduce it in different combinations of update and 1st preload?

It didn't happen for them again when updating to 3.5.0.4. What do you think might be contributing to such a problem?

**Comment by Screenfeed** [comment] 2020-03-17 23:08
**Reproduce the problem** ✅
This is not related to the update process, but happens when caching.

**Identify the root cause** ✅
This happens if the `/wp-content/cache/wp-rocket/`’s child folder is not writable. Here, it would be `/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/`.

**Scope a solution** ✅
Add some tests like `is_writable()` in `WP_Rocket\Buffer\Cache->maybe_process_buffer()` and `WP_Rocket\Buffer\Cache->write_cache_file()`.

**Estimate the effort** ✅
effort: `[S]`

**Comment by hellofromtonya** [comment] 2020-03-17 23:14
@Screenfeed 

1. Why do you think the directory was not writeable after the update? It was before the update.
2. What do you think made it writeable again after the 1st preload?

**Comment by Screenfeed** [comment] 2020-03-17 23:59
@hellofromtonya 
1. I can’t be sure but I think the site was in the middle of a caching process when the update triggered, leaving opened files/folders in an "intermediate" state. Then the upgrade from 3.4.4 to 3.5.0.3 [doesn’t include a cache refresh](https://github.com/wp-media/wp-rocket/blob/8b2a567efcab3925dba6fff72c5a622ec2d16386/inc/admin/upgrader.php#L387-L393).
2. The person probably cleared the cache before launching the next preload.

Actually none of this makes sense to me, but I have no other explanations.

**Comment by hellofromtonya** [comment] 2020-03-18 10:28
>the site was in the middle of a caching process when the update triggered, leaving opened files/folders in an "intermediate" state. Then the upgrade from 3.4.4 to 3.5.0.3 doesn’t include a cache refresh

That's a good theory. @Screenfeed test it by:

- Setting up that scenario and seeing if it produces the situation
- If you can't recreate it, ask your teammates to try it

**Comment by Screenfeed** [comment] 2020-03-23 16:20
@crystinutzaa @Tabrisrp I am not able to reproduce my hypothesis in my last message.
Do you have other ideas and/or are you able to reproduce?

**Comment by camilamadronero** [comment] 2020-03-26 20:04
Related ticket https://secure.helpscout.net/conversation/1116457464/153087/.

**Comment by GeekPress** [comment] 2020-04-04 15:33
Another related ticket: https://secure.helpscout.net/conversation/1127829424/155708?folderId=273761

**Comment by crystinutzaa** [comment] 2020-04-06 19:08
I was able to recreate this issue on my local.

The issue is that Partial Preload is running during upgrade.
This is the full stacktrace:
```
[06-Apr-2020 13:01:57 UTC] PHP Warning:  copy(/app/public/wp-content/cache/wp-rocket/wp3.local/index.html_temp): failed to open stream: No such file or directory in /app/public/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[06-Apr-2020 13:01:57 UTC] PHP Stack trace:
[06-Apr-2020 13:01:57 UTC] PHP   1. shutdown_action_hook() /app/public/wp-includes/load.php:0
[06-Apr-2020 13:01:57 UTC] PHP   2. do_action() /app/public/wp-includes/load.php:947
[06-Apr-2020 13:01:57 UTC] PHP   3. WP_Hook->do_action() /app/public/wp-includes/plugin.php:478
[06-Apr-2020 13:01:57 UTC] PHP   4. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:312
[06-Apr-2020 13:01:57 UTC] PHP   5. wp_ob_end_flush_all() /app/public/wp-includes/class-wp-hook.php:288
[06-Apr-2020 13:01:57 UTC] PHP   6. ob_end_flush() /app/public/wp-includes/functions.php:4552
[06-Apr-2020 13:01:57 UTC] PHP   7. WP_Rocket\Buffer\Cache->maybe_process_buffer() /app/public/wp-includes/functions.php:4552
[06-Apr-2020 13:01:57 UTC] PHP   8. WP_Rocket\Buffer\Cache->write_cache_file() /app/public/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php:308
[06-Apr-2020 13:01:57 UTC] PHP   9. WP_Filesystem_Direct->move() /app/public/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php:352
[06-Apr-2020 13:01:57 UTC] PHP  10. WP_Filesystem_Direct->copy() /app/public/wp-admin/includes/class-wp-filesystem-direct.php:309
[06-Apr-2020 13:01:57 UTC] PHP  11. copy() /app/public/wp-admin/includes/class-wp-filesystem-direct.php:281
```

In this file the error occurs:
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/classes/Buffer/class-cache.php#L341-L352

This is triggered by Partial Preload on maybe dispatch.
What I assume is happening is:
1. Partial Preloading is running
2. WP Rocket is being upgraded.
3. Something happens during the upgrade (a Fatal Exception) which stops the Partial Preloading.
No _temp file is created. Error is in error log.
4. When upgrade is done everything is working just fine as before. Because _temp files are available and everything runs.

The solution is:
Stop Preloading / Partial Preloading during upgrading WP Rocket.

@Tabrisrp , @Screenfeed & @hellofromtonya 

I cannot estimate how much effort this will take. 😄 Ideas?
Should this estimation be with the new Upgrading system we discussed today?

**Comment by GeekPress** [comment] 2020-04-12 13:10
Customer to follow up when fixed:
* https://secure.helpscout.net/conversation/1131879933/0/?folderId=273764

**Comment by vmanthos** [comment] 2020-05-13 09:35
**Related ticket:** https://secure.helpscout.net/conversation/1162724289/164680/

**Comment by hellofromtonya** [comment] 2020-05-24 12:09
This issue will be fixed in 3.7. It's blocked until the new Preload module is built.

**Comment by hellofromtonya** [comment] 2020-05-26 11:49
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by juricazuanovic** [comment] 2020-07-05 13:26
Related ticket: https://secure.helpscout.net/conversation/1215380071/177943?folderId=273766

**Comment by vmanthos** [comment] 2020-07-22 13:55
**Related tickets:**
https://secure.helpscout.net/conversation/1231270616/181548 (requested a refund)
WIP: https://secure.helpscout.net/conversation/1228142197/180871 (asked for credentials)
WIP: https://secure.helpscout.net/conversation/1232604979/181835 (asked for credentials)

**Comment by webtrainingwheels** [comment] 2020-09-18 21:23
https://secure.helpscout.net/conversation/1282059479/194792?folderId=377611

**Comment by alfonso100** [comment] 2020-09-26 03:12
https://secure.helpscout.net/conversation/1292817672/197645?folderId=273766

**Comment by alfonso100** [comment] 2020-10-01 21:12
https://secure.helpscout.net/conversation/1295946218/198440?folderId=2683093

**Comment by mzimma** [comment] 2020-11-23 07:32
When is the fix going to be released ? This seems to be related https://github.com/wp-media/wp-rocket/issues/3314

**Comment by arunbasillal** [comment] 2020-11-23 08:20
> When is the fix going to be released ?

@mzimma We are planning to re-write our entire preload approach (no ETA yet). This will be fixed during the rewrite.

**Comment by mzimma** [comment] 2020-11-23 17:16
Sounds good, thank you!

**Comment by vmanthos** [comment] 2020-11-24 12:05
**Related ticket:** https://secure.helpscout.net/conversation/1347367935/215413/

**Comment by vmanthos** [comment] 2021-01-13 12:56
**Related ticket:** https://secure.helpscout.net/conversation/1364738701/222493?folderId=2135277

**Comment by DahmaniAdame** [comment] 2021-05-06 06:02
Related ticket - https://secure.helpscout.net/conversation/1488090663/257184/

**Comment by quangthien27** [comment] 2021-06-07 13:04
This still happens with current version 3.9.0.1, same error, but it just happened randomly, no upgrade was performing

**Comment by olivM** [comment] 2021-07-03 21:28
i got the same random PHP Warning  with 3.9.0.x from copy() on class-wp-filesystem-direct.php

**Comment by HannesVo** [comment] 2021-07-27 11:54
I do become the warning reoccuring.
Version 3.9.0.5 on an IIS Based Azure App Service. 
It seems to be reproducable.
in some cases the cache folder 
/site/wwwroot/wp-content/cache/wp-rocket/{fulldomainname} is deleted/notexistant.
if the folder does not exists i do become the error on each page which is to be preloaded. 
if i recreate the folder manually the cache is build without these error. 
so currently my primary problem is  the domain cache folder ist deleted by some (process).

**Comment by DahmaniAdame** [comment] 2021-09-15 11:39
Related - https://secure.helpscout.net/conversation/1630916805/294657/

**Comment by alfonso100** [comment] 2021-12-15 21:08
related https://secure.helpscout.net/conversation/1728379095/314505/

**Comment by worldsdream** [comment] 2021-12-19 20:20
I confirm that I do see the same. Waiting for a fix!

**Comment by NataliaDrause** [comment] 2022-02-07 16:40
related: https://secure.helpscout.net/conversation/1779894562/324519?folderId=3864740

**Comment by twwn** [comment] 2022-04-10 10:29
Still seeing this with v3.11.0.2.

**Comment by juricazuanovic** [comment] 2022-04-15 17:17
Related: https://secure.helpscout.net/conversation/1849706811/337754/

**Comment by girlie** [comment] 2022-05-22 15:00
Related: https://secure.helpscout.net/conversation/1892468362/344331/

**Comment by NataliaDrause** [comment] 2022-06-07 08:16
Related: https://secure.helpscout.net/conversation/1907687759/346423?folderId=3864740

**Comment by NataliaDrause** [comment] 2022-06-15 13:59
Related: https://secure.helpscout.net/conversation/1896805238/344974?folderId=3864740

**Comment by NataliaDrause** [comment] 2022-07-05 10:52
Related: https://secure.helpscout.net/conversation/1938723213/352023?folderId=3864740

**Comment by girlie** [comment] 2022-07-27 14:50
Related: https://secure.helpscout.net/conversation/1961268769/358386/

**Comment by DahmaniAdame** [comment] 2022-08-11 12:00
Related - https://secure.helpscout.net/conversation/1974358566/361074/

**Comment by viobru** [comment] 2022-08-18 14:14
Related: https://secure.helpscout.net/conversation/1982154359/362477

**Comment by piotrbak** [comment] 2022-08-30 11:17
Related: https://secure.helpscout.net/conversation/1990501756/364243

**Comment by juricazuanovic** [comment] 2022-09-08 15:44
Related: https://secure.helpscout.net/conversation/1991719079/364515/

**Comment by alfonso100** [comment] 2022-09-09 21:43
related https://secure.helpscout.net/conversation/1980848784/362202?folderId=2683093
In this case, is 3.12.0.5 and is happening not only on the 1st preload

**Comment by DahmaniAdame** [comment] 2022-09-16 05:54
Related - https://secure.helpscout.net/conversation/2008053824/368221/
`3.12.0.5` as well.

**Comment by NataliaDrause** [comment] 2022-09-19 09:59
Related: https://secure.helpscout.net/conversation/2013336384/369394/
version `3.12.0.5`

**Comment by CrochetFeve0251** [comment] 2022-09-20 08:11
## Reproduce the problem ❌
I wasn't able to reproduce the problem on local.

## Identify the root cause :white_check_mark:
The root cause seems to come from the fact the temp file is not created at [this level](https://github.com/wp-media/wp-rocket/blob/3584bcca26fdee58f81269708218b48dfc9ddad8/inc/classes/Buffer/class-cache.php#L335) or [this one](https://github.com/wp-media/wp-rocket/blob/3584bcca26fdee58f81269708218b48dfc9ddad8/inc/classes/Buffer/class-cache.php#L335).

## Scope a solution :white_check_mark:
To fix this warning we can check the results of both of this function results and bail out if the result is false.

## Estimate the effort :white_check_mark:
effort: [XS]

**Comment by Nick776** [comment] 2022-09-26 16:53
actually it's just annoying

**Closed** 2022-10-07 11:31 UTC
Labels: type: bug, module: cache, module: preload, priority: medium, effort: [XS], severity: minor

**Comment by DahmaniAdame** [comment] 2022-10-19 11:16
Related - https://secure.helpscout.net/conversation/2041155254/375531/

**Comment by DahmaniAdame** [comment] 2022-11-30 11:32
Related - https://secure.helpscout.net/conversation/2081070810/385411/

**Comment by DahmaniAdame** [comment] 2023-02-17 11:22
The issue is still happening on `3.12.5.3`. 
Ticket as reference - https://secure.helpscout.net/conversation/2142926579/398669

**Comment by WordPresseur** [comment] 2023-02-22 10:12
Related: https://secure.helpscout.net/conversation/2160007374/401921?folderId=1213662

**Comment by BradFD** [comment] 2023-02-22 16:44
Seeing this also.
