### ISSUE TITLE
Auto exclude JS delay for burger icon

### ISSUE THREAD

**Issue by tommy83** [wp-media/wp-rocket#4027] opened 2021-06-09 21:01 UTC
Theme: Woodmart
Latest WordPress.
WP Rocket: 3.9.01

If you activate delay js the burger icon will not work at first click. At second click its working fine.

Any chance to auto exclude burger icon from delay js or set fallback timer to fireup js?

you can see effect here: https://gschwendtberger.com

**Comment by GeekPress** [comment] 2021-06-10 06:29
Duplicate of #3142

**Closed as completed by GeekPress** 2021-06-10 06:29 UTC
Labels: duplicate
