### ISSUE TITLE
Sites with TranslatePress on different languages are not being cached

### ISSUE THREAD

**Issue by saschabrockel** [wp-media/wp-rocket#3760] opened 2021-04-05 01:11 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**To Reproduce**
1. Install TranslatePress & WPRocket
2. Setup TranslatePress to not use subdirectories like `/en` or `/de` for translated pages
3. Remove cache if existing and preload it
4. You will see in the cache folders of wp-rocket that all default language sites are cached but the ones with a different language are not. There is just one folder named `#lang=en`. You find the example in the screenshots.

**Expected behavior**
English sites or sites with a different language then the default should be cached as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/33376463/113526885-fe220f00-95bb-11eb-8187-cfbff35836da.png)
![image](https://user-images.githubusercontent.com/33376463/113526901-0aa66780-95bc-11eb-9853-1bc80765547a.png)

**Additional context**

**Comment by sriharsha-y** [comment] 2022-01-02 08:05
Having been facing the same issue it's very annoying

**Comment by DivvyPT** [comment] 2023-01-30 21:53
Facing the same issue as well. Any fix for us, please?

**Comment by piotrbak** [comment] 2023-06-20 13:46
@saschabrockel @sriharsha-y @DivvyPT After some discussions with TranslatePress Team we were informed that using query strings in the URL to switch between language is not an option anymore. It means that the issue is not valid for the newest version of TranslatePress. Feel free to add any comments here, if we'll be fine, I'll close the issue soon

**Closed as not planned** 2024-06-26 14:37 UTC
Labels: type: bug, community, 3rd party compatibility, module: cache, priority: medium, needs: grooming
