### ISSUE TITLE
Cache HTTP Headers for 103 Early hints and others.

### ISSUE THREAD

**Issue by TokyoJump** [wp-media/wp-rocket#4452] opened 2021-10-23 06:44 UTC
'HTTP Header response' need cache.

Now we got 103 Early Hints in Cloudflare. 
BUT THIS TECHNOLOGY NEED HTTP HEADER.

Use .htaccess? conf?
No no no.... We can not do this.

We need ""responsive HTTP Header"" in PHP.
It is necessary to set the HTTP header dynamically according to the content. 

The current WP Rocket, Remove 'added by PHP HTTP Header'.
This so not cool. Very not usefull.

Adding a security header to PHP will also handle childish issues that will be deleted.

**Comment by TokyoJump** [comment] 2021-10-23 15:22
WP Super Cache supports header caching in the settings.
This should be helpful.

It's not that difficult and it's a very effective solution.

or

Stop generating "advanced-cache.php" when disabling WP Rocket's page cache with an your add-on.
That way, I can rely on "WP Super Cache" for the page cache. This is also one of the solutions.

In fact, it's not cool, 

**it's a bug to keep generating "advanced-cache.php" when stop the WP Rocket cache with an add-on.**

This addon
https://docs.wp-rocket.me/article/61-disable-page-caching

**Comment by piotrbak** [comment] 2021-11-04 15:44
Closing it, as it's a duplicate of https://github.com/wp-media/wp-rocket/issues/4433 issue which uses the correct template.

**Closed as completed by piotrbak** 2021-11-04 15:44 UTC
Labels: needs: r&d
