### ISSUE TITLE
CDN rewrite doesn't apply to lazyload attributes when using a placeholder

### ISSUE THREAD

**Issue by codetipi** [wp-media/wp-rocket#2198] opened 2019-12-17 19:26 UTC
**Describe the bug**
CDN rewrite doesn't apply to lazyload src attributes, for example: data-src, if there is a lazyload placeholder set in the src.

**To Reproduce**
1. Enable CDN for images
2. Add this to simulate lazyload with placeholder behaviour:

```
function cdn_lazy_test( $html ) {
	return str_replace( ' src="', ' src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 0 0\'%3E%3C/svg%3E" data-src="', $html );
}
add_filter( 'post_thumbnail_html', 'cdn_lazy_test' );
```

**Expected behavior**
The data-src attribute should have the url rewritten to use the CDN.

**Additional context**
If you replace the src attribute with an actual placeholder.png that is on the site's server, then the placeholder.png's url does get correctly re-written to use the CDN, so it seems WP Rocket's CDN rewrite only targets the src attribute directly. 

Ideally at the very least the plugin could have a hook that users can tell the CDN rewrite what attributes to overwrite.

**Comment by Tabrisrp** [comment] 2019-12-17 19:33
Can we get an example of the resulting HTML code after the filter has been applied?

**Comment by codetipi** [comment] 2019-12-18 11:02
Hey @Tabrisrp,

Sure thing! Here is an example of the HTML at different stages, in this example instead of a data:image as the placeholder, I've used a placeholder.png from the theme:

I tweaked the urls to make them shorter, and removed irrelevant attributes (width/height/sizes) but I didn't change the actual results:

CDN is enabled in all examples.

Lazy load disabled output (WordPress default thumbnail output):
`<img src="https://123CDN.com/wp-content/uploads/image-370x247.jpg" srcset="https://123CDN.com/wp-content/uploads/image-370x247.jpg 370w, https://123CDN.com/wp-content/uploads/image-100x66.jpg 100w, https://123CDN.com/wp-content/uploads/image-770x513.jpg 770w, https://123CDN.com/wp-content/uploads/image-1155x770.jpg 1155w">`

Lazy load enabled and src is replaced with the placeholder via the `post_thumbnail_html` filter as shown previously.
This is the HTML before JavaScript does the lazy load replacement of attributes:
`<img src="https://123CDN.com/wp-content/themes/mytheme/assets/img/placeholder.png" data-src="https://mysite.com/wp-content/uploads/image-370x247.jpg" data-srcset="https://123CDN.com/wp-content/uploads/image-370x247.jpg 370w, https://123CDN.com/wp-content/uploads/image-100x66.jpg 100w, https://123CDN.com/wp-content/uploads/image-770x513.jpg 770w, https://123CDN.com/wp-content/uploads/image-1155x770.jpg 1155w">`

Final output after JavaScript replaces the attributes and then makes the lazyload attributes empty (data ones):
`<img src="https://mysite.com/wp-content/uploads/image-370x247.jpg" srcset="https://123CDN.com/wp-content/uploads/image-370x247.jpg 370w, https://123CDN.com/wp-content/uploads/image-100x66.jpg 100w, https://123CDN.com/wp-content/uploads/image-770x513.jpg 770w, https://123CDN.com/wp-content/uploads/image-1155x770.jpg 1155w" data-src="" data-srcset="" class="lazy-loaded">`

As the src attribute was replaced with the placeholder.png, the CDN rewrite did occur to the src, but it didn't happen for the real src, which was moved to data-src. The data-srcset worked fine as the initial urls in there were never touched.

Hope this info is helpful.

**Comment by Tabrisrp** [comment] 2019-12-18 21:24
I'm not able to reproduce the issue with our automated tests and the code sample provided. Did you also open a support ticket so we can have a look directly on the website concerned?

That could help use determine the exact point where it's failing

**Comment by codetipi** [comment] 2019-12-23 17:17
Thanks - Yes, I've opened a support ticket for it now :)

**Comment by Tabrisrp** [comment] 2020-01-14 16:14
I'm going to close this for now, as it couldn't be reproduced on our internal testing, and it has gone to support.

**Closed by Tabrisrp** 2020-01-14 16:14 UTC
