### ISSUE TITLE
Uncaught InvalidArgumentException error in ServiceProviderAggregate.php

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3709] opened 2021-03-24 08:58 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The following error appears randomly:
```
An error of type E_ERROR was caused in line 47 of the file .../wp-content/plugins/wp-rocket/inc/Engine/Container/ServiceProvider/ServiceProviderAggregate.php. 
Error message: Uncaught InvalidArgumentException: A service provider must be a fully qualified class name or instance of (\WP_Rocket\Engine\Container\ServiceProvider\ServiceProviderInterface) 
in .../wp-content/plugins/wp-rocket/inc/Engine/Container/ServiceProvider/ServiceProviderAggregate.php:47
```
Previously the following errors were reported as well:
```
E_ERROR was caused in line 35 of the file .../wp-content/plugins/wp-rocket/inc/Engine/Capabilities/ServiceProvider.php. 
Error message: Uncaught Error: Call to a member function withArgument() on null 
in .../wp-content/plugins/wp-rocket/inc/Engine/Capabilities/ServiceProvider.php:35
```

**To Reproduce**
Steps to reproduce described by @Mai-Saad :
1- clone repo git clone https://github.com/wp-media/wp-rocket.git
2- switch to trunk and pull
3- composer update
4- composer install --no-dev --no-scripts
5- activate plugin in dashboard

**Expected behavior**
No errors should happen

**Additional context**
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1615884709005300

Related ticket: https://secure.helpscout.net/conversation/1453905469/247679
Possibly related: https://secure.helpscout.net/conversation/1455154954/248062/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2021-03-24 12:01
The steps to reproduce can't be used in this context, because on a customer website, the composer commands are not involved.

It's a part of the plugin where it should break all the time if there was an issue with our code itself, because it's the central part loading everything.

What I'm also seeing in the error_log provided, is that we're not the only plugin affected:
- `PHP Fatal error:  require(): Failed opening required 'public_html/wp-content/plugins/woocommerce/vendor/psr/container/src/ContainerInterface.php' in public_html/wp-content/plugins/jetpack/vendor/jetpack-autoloader/class-php-autoloader.php on line 87`
- `PHP Warning:  include_once(): Failed opening 'public_html/wp-content/plugins/woocommerce/includes/class-wc-order-factory.php' for inclusion in public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 403`
- `PHP Fatal error:  Uncaught Error: Class 'WC_Order_Factory' not found in public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php:583`
- `PHP Fatal error:  require(): Failed opening required 'public_html/wp-includes/blocks.php'`

And a lot more with Yoast SEO, Flexible checkout fields pro, Assets clean up, etc.

Even files from WordPress core. There is something not right on the website host itself when it comes to require/include, it's not specific to WP Rocket.

And the fact there is an issue with including files can explain the error we see for us, because if the file was not able to be included, its code can't be used.

Though I'm going to close this issue, because it's not something that is fixable on our side.

**Closed as completed by remyperona** 2021-03-24 12:01 UTC
Labels: invalid

**Comment by Ebeldev** [comment] 2022-04-28 18:01
I'm do get this error on all sites I do have WP-Rocket installed. 
 Fatal error: Uncaught Exception: A service provider must be a fully qualified class name or instance of (\WP_Rocket\Dependencies\League\Container\ServiceProvider\ServiceProviderInterface)
in .../wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/ServiceProvider/ServiceProviderAggregate.php on line 52

We do update our code with git with all our plugins and themes. 

The only way I found to make it work is to deactivated and delete completely WP-Rocket.
