### ISSUE TITLE
Stylesheet containing space in the filename is not processed

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4458] opened 2021-10-26 20:26 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.1
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When a stylesheet has a space in the filename, for example `/wp-content/My Folder/mycss.css` it will not be processed by the Remove Unused CSS.

**To Reproduce**
1. Add a stylesheet on the server in the folder that contains space: `/wp-content/My Folder/mycss.css`
2. Enqueue the stylesheet on the site as:
`<link rel='stylesheet' id='my-css' href='https://testsite.nataliadrause.com/wp-content/My Folder/mycss.css' media='all' />`
3. Enable the Remove Unused CSS option.
4. Once the process is completed, this stylesheet will be left out while Used CSS being added on the page.

**Expected behavior**
All CSS files should be processed.

**Additional context**
Slack: https://wp-media.slack.com/archives/C029G1B5HD2/p1635264017031400
Related ticket: https://secure.helpscout.net/conversation/1661863619/301379/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2021-11-08 18:27
### Reproduce the issue ✅ 
Reproduced the issue on local installation

### Identify the root cause ✅ 
This is happening because the regular expression we use to find links and scripts is not matching when there is a space in the URL.
`<link\s+(?:[^>]+[\s"\'])?href\s*=\s*[\'"]\s*(?<url>[^\'"\s]+)\s*?[\'"](?:[^>]+)?\/?>`
`<script\s+(?:[^>]+[\s\'"])?src\s*=\s*[\'"]\s*?(?<url>[^\'"\s]+)\s*?[\'"](?:[^>]+)?\/?>`

Removing the `\s`, the stylesheet is correctly picked-up by the resource fetcher process, sent to warmup, and saved in the DB.

The other issue at hand is that when warmup receives an URL containing a space, it returns an error with the following message `Warm-up request received with some invalid resources.`

So the file is never actually warmed-up on the SaaS side.

**Comment by piotrbak** [comment] 2021-11-08 18:44
@Tabrisrp `the file is never actually warmed-up on the SaaS side.`
Does it mean it won't be processed at all? If so, after implementing this patch we'll end up with those styles being in the source treated as unprocessed CSS, right?

To fully fix the problem we need fix here and on the SaaS side.

**Comment by remyperona** [comment] 2021-11-08 18:45
Yes indeed we need to do changes on both sides

**Comment by piotrbak** [comment] 2021-11-08 18:46
But if it'll be treated as unprocessed CSS, we can implement the plugin part now, and wait for the SaaS side safely.

**Comment by remyperona** [comment] 2021-11-09 20:29
Yes we can. I changed the effort to `[S]` for the plugin-side part.

**Comment by iCaspar** [comment] 2021-11-23 19:53
A little looking into this on the warmup side... we are using Laravel's URL validation there, not our own regex.
So it's the Laravel validation that is failing with urls having spaces. Why?
Turns out spaces in URLs are "unsafe" and should be encoded to pass validation.
See https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space#answer-497972

Given that, we may want to reconsider "fixing" this.
Also, with the new SaaS, the current warm-up will be going away.

**Comment by piotrbak** [comment] 2021-11-23 22:51
@iCaspar Can we confirm that files with spaces will be proceed correctly by the new approach?

Then we'll still need Rocket fix to handle this, right?

**Comment by iCaspar** [comment] 2021-11-24 12:48
@engahmeds3ed or @mostafa-hisham would have to confirm whether the new approach will handle spaces on the new SaaS side when treeshaking. For warmup, my understanding is that it will be totally irrelevant.

**Comment by engahmeds3ed** [comment] 2021-11-25 07:23
> @engahmeds3ed or @mostafa-hisham would have to confirm whether the new approach will handle spaces on the new SaaS side when treeshaking. For warmup, my understanding is that it will be totally irrelevant.

The new approach will use a real browser to get resources so whatever our real chrome does, it will do like it.
So I think it will easily process resources with space on its name.

**Comment by DahmaniAdame** [comment] 2021-12-18 10:56
Related - https://secure.helpscout.net/conversation/1727751196/314385/

**Comment by piotrbak** [comment] 2022-04-12 14:33
Fixed in 3.11

**Closed as completed by piotrbak** 2022-04-12 14:33 UTC
Labels: type: bug, priority: medium, status: blocked, effort: [S], severity: major, module: remove unused css
