### ISSUE TITLE
Delay JavaScript break most of all elementor widgets

### ISSUE THREAD

**Issue by tommy83** [wp-media/wp-rocket#4001] opened 2021-06-05 10:02 UTC
General:
Activate "Delay JavaScript execution". Now lets do what the most visitor will do on a website:
Load the website and scroll immediately. If you do that: The style of most elementor widgets are broken.
Also many thirdparty elements like ajax search pro are not shown.
- Also elementor widgets dynamic ooo (post grid) and many more elements are not correct shown.
- We have the same issue on all other wordpress websites with wp rocket 3.9.1. The issue is confirmed also by elementor pro stuff and dynamic ooo developer.
- You will not have any issue if you wait a little bit before start scrolling. But this is no way/no solution for live websites. ;-)

- Video/screencast of that issue:
https://streamable.com/d5r4q8

Environment:
PHP 7.4
managed server
fresh installed/latest wordpress
fresh installed/latest elementor
fresh installed/latest dynamic ooo plugin
fresh installed/latest ajax search pro
fresh installed/latest wp rocket 3.9.0.1

We already try this to solve that issue:
Excluded JavaScript Files:
ajax-search-pro
/ajax-search-pro/js/(.*)
/wp-content/plugins//ajax-search-pro/js/(.*)
(?:wp-content|wp-includes)(.*)
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
js-(before|after)
get_Dyncontel_ElementSettings
qodefAddonsCore
elementor-pro
elementor

But still not help.
We asked some users in wordpress groups to install our wp rocket and test it. They have the same issue on their website.

**Comment by piotrbak** [comment] 2021-06-07 12:32
This is a duplicate of this issue:
https://github.com/wp-media/wp-rocket/issues/3961

**Comment by GeekPress** [comment] 2021-06-07 13:53
Duplicate of #3961

**Closed as completed by GeekPress** 2021-06-07 13:53 UTC
Labels: duplicate

**Comment by jabeztadesse** [comment] 2024-04-27 16:00
+1
