### ISSUE TITLE
Remove Unused CSS: Warmup Complete, UsedCSS is present, but not inserted on page

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#4403] opened 2021-10-05 12:54 UTC
Devs are aware of a Remove Unused CSS issue where _sometimes_ Used CSS is generated and stored in the `wpr_rucss_used_css` table, and warmup has successfully completed, but the used CSS is not added to the page. Clearing Cache, Clearing Used CSS, or some combination of these, will force used CSS to be inserted, but not always immediately.

Leaving this issue **open for feedback** from Support Rocketeers and others.
Current status is looking for steps to reproduce. If you've encountered this issue, any observations about **what happened in what order**, and **what the context when you encountered**, eg.: "during a version update", "after changing a theme", "cleared cache for some other reason", etc.

**Expected behavior**
Used CSS should _always_ be added to a page when it has been properly generated and stored in `wpr_rucss_used_css` table, when the Remove Unused CSS feature is enabled.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment] 2021-10-05 13:25
Looks like this is the same case here #4350

Info: This looks like randomly happened in some sites pages or in some if cleared used css, used css not added there, we need to hit "Clear Cache" or "Clear Used" or both Once/Twice, I don't know exactly which one brings that used css in pages again, sometimes both not working and we need to regenerate used css but wpr_rucss_used_css table has all content.

Note: Still i haven't received confirmation from any of my client, so i cannot open support ticket directly.

**Comment by NataliaDrause** [comment] 2021-10-06 05:42
I had a case here: https://secure.helpscout.net/conversation/1640602306/296917

The site has dynamic CSS and JS that are likely changing once in a while - I suspect this is why the issue is frequent. After cache is cleared and then preloaded (customer uses cron), used CSS is not applied for some random pages. Clearing those pages cache for the second time resolves the problem.

From my observation, only cache has to be cleared twice, no need to clear used CSS. 

It also seemed to be a more common issue when preload is running. When I visited pages manually, I wasn't able to reproduce the problem.

**Comment by mehedihasanziku** [comment] 2021-10-06 06:09
> It also seemed to be a more common issue when preload is running. When I visited pages manually, I wasn't able to reproduce the problem.

You are right, when preload is on this issue happened much it's also mentioned on my [thread](https://github.com/wp-media/wp-rocket/issues/4350), but about manual visit:
If you visit single page after clear, the issue isn't there, but if you try to visit multiple pages at a time, the issue still happens but not often like preload

**Comment by vmanthos** [comment] 2021-10-06 12:02
Having unprocessed resources can also explain this.

The way we perform treeshaking here:
https://github.com/wp-media/wp-rocket/blob/2d23ddb8cec8d3c2ea301c5f022ca8ffb87321ae/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L179-L224

we will not insert the used CSS:
1. if there isn't used CSS yet `OR`
2. there is used CSS, but there are unprocessed resources, in which case we will try to treeshake the HTML in 30 minutes. In this case, the page will not have used CSS added.

Even if the unprocessed resources have been processed in the meantime, the used CSS will be added only after clearing the cache.

Otherwise, if there are unprocessed resources it will take `3` retries before the used CSS makes it to the HTML. This means the cached file will have to be cleared `3` times at worse for its HTML to be treeshaked and the used CSS added in the page.

If for any reason the SaaS doesn't reply with `200`:
https://github.com/wp-media/wp-rocket/blob/2d23ddb8cec8d3c2ea301c5f022ca8ffb87321ae/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L187

the actual number of cache clearing to trigger `treeshake()` will increase.

**Comment by NataliaDrause** [comment] 2021-10-20 12:29
Related: https://secure.helpscout.net/conversation/1667909746/302568/

**Comment by NataliaDrause** [comment] 2021-10-25 14:03
Related: https://secure.helpscout.net/conversation/1673654498/303547?folderId=3864740

**Comment by NataliaDrause** [comment] 2021-10-31 12:27
Related: https://secure.helpscout.net/conversation/1673127202/303501?folderId=3864740

**Comment by mehedihasanziku** [comment] 2021-12-15 13:57
**Observation:** This happening in some sites where dom changed+inline css changed on each page load like #4166
I checked this by comparing dom when it returns multiple times without rucss

Note: In most of them doesn't have random `?ver=` issue where this issue happened always.

**Comment by mehedihasanziku** [comment] 2022-02-03 17:41
I don't understand how inline css can do this ( #4683 ) . anyways i noticed changing `'timeout' => 5, ` value to higher like 15/20 or more higher, inserting css properly, so if server respond slow and rucss will not generate not even requeued that page till clear again.

> https://github.com/wp-media/wp-rocket/blob/15574e3957478c71210c315dd08488778aad5eb5/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#L33


So, i feel that, this timeout thing should be guarded with filter like [Preload Intervals](https://github.com/wp-media/wp-rocket-helpers/raw/master/preload/wp-rocket-custom-preload-intervals/wp-rocket-custom-preload-intervals.zip), so user can decide what to do with it.

**Comment by piotrbak** [comment] 2022-06-20 15:21
Closing it since the approach has changed since 3.11

**Closed as completed by piotrbak** 2022-06-20 15:21 UTC
Labels: type: bug, waiting for feedback, dev initiative
