### ISSUE TITLE
Notice: Trying to access array offset 

### ISSUE THREAD

**Issue by Grafs** [wp-media/wp-rocket#2274] opened 2020-01-22 14:23 UTC
**Describe the bug**
Notice: Trying to access array offset on value of type null in \wp-content\plugins\wp-rocket\inc\classes\optimization\class-cache-dynamic-resource.php on line 170
Show on all pages 

**To Reproduce**
PHP 7.4.1
WordPress 5.3.2
WP Rocket 3.2.5

**Comment by Tabrisrp** [comment] 2020-01-22 15:30
Hi,

This is a duplicate of #2185, which was fixed in WPR 3.4.4

You can update to this version to fix the issue on your website.

**Closed by Tabrisrp** 2020-01-22 15:30 UTC
Labels: duplicate
