### ISSUE TITLE
Elementor version 8+ - the mobile menu does not open with one click

### ISSUE THREAD

**Issue by aharonyltd** [wp-media/wp-rocket#5597] opened 2022-11-29 06:49 UTC
Hi, this is already happening on several sites, as soon as Elementor is upgraded to version 8+, the mobile menu does not open with one click

It seems that something needs to be improved in the plugin that will remember the click and execute it

I improve the performance of websites and I know how to test it in depth
I recommend you check this bug

**Comment by piotrbak** [comment] 2022-12-06 13:31
Hello @aharonyltd and thanks for creating the issue. It sounds like it could be related to the Delay JS feature, however, I'm not able to reproduce it on empty site with Elementor 3.8 nor with 3.9 beta.

Most likely the problem will be resolved by excluding some scripts from being delayed. Please check our list and look for `double` to see if any of the entries matches with what you have on your websites:
https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions

If that doesn't work, please contact our Support Team, we'll investigate this problem and reopen/create a new issue with all the steps that are needed to reproduce it.

**Closed as completed by piotrbak** 2022-12-06 13:31 UTC
