### ISSUE TITLE
Preloading not always caching the same number of pages

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2207] opened 2019-12-22 20:19 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
WordPress : 5.3.2
WP Rocket : 3.4.3
All other plugins up to date

**Describe the bug**
Whenever I change a setting, an automatic purge & preload of the cache is triggered but this preload breaks before its end.

**To Reproduce**
a) When I change an option of my WP Rocket settings, the pre-load enables automatically and generates about 50 to 170 pages.

![image](https://user-images.githubusercontent.com/51261962/71326820-82a06980-2500-11ea-94dc-0621afe830d1.png)

b) When the pre-load is done, I click again on "Pre-load" and it will then generate between 500 to 900 pages.

![image](https://user-images.githubusercontent.com/51261962/71326788-24738680-2500-11ea-80bf-2921c71401a2.png)
![image](https://user-images.githubusercontent.com/51261962/71326833-9e0b7480-2500-11ea-985c-232349d30ffd.png)
![image](https://user-images.githubusercontent.com/51261962/71326780-0dcd2f80-2500-11ea-979c-57511567714f.png)

c) When the second pre-load is done, I click again on "Pre-load" and it will then generate around 1150 pages.

![image](https://user-images.githubusercontent.com/51261962/71326763-ea09e980-24ff-11ea-8bfb-c134988c7f01.png)

**Expected behavior**
The number of pages cached shall always remain consistent.

**Screenshots**
See above in the explanations of the bug.

**Additional context**
N/A

**Backlog Grooming**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by gevcen** [comment] 2019-12-23 15:52
Dear,

Right now again, I have got another amount of pages cached. The only change I've performed was to switch the heartbeat frontend value from "Reduce" to "Disable" and it lead to an automatic pre-load of cache of only 48 pages instead of usually around 580 pages on average.

![image](https://user-images.githubusercontent.com/51261962/71367192-a0270f00-25a4-11ea-8cc5-8f7818906464.png)

Thanks

**Comment by Tabrisrp** [comment] 2019-12-23 16:39
We're aware that the preload counter might give inconsistant results sometimes, because it is stored in a transient that is supposed to be deleted when the preload is complete. If anything prevents it from finishing, it's not deleted.

This is something we want to fix in the future.

On a related note, the counter on displays the number of pages that were not yet cached, which can explain differences between preload runs too.

**Comment by Tabrisrp** [comment] 2020-03-10 16:06
@Screenfeed this issue should be solved with our recent preload counter PRs?

**Comment by Screenfeed** [comment] 2020-03-10 16:23
@Tabrisrp We don't know. The counter should be accurate now but the issue, if there is, may be located elsewhere.
1. As you said, the counter displays the number of pages that were not yet cached, so we aren't even sure there is something to fix.
2. Let's say the cache is empty before preloading, and the counter keeps displaying different values: that probably means that the preloading process stops before its expected end (lack of memory? timeout?).

**Comment by Screenfeed** [comment] 2020-03-17 13:10
@gevcen If it’s ok for you, could you contact our support team so we can investigate directly on your site please?
Thanks.

**Comment by jazir5** [comment] 2020-04-18 04:42
I have this issue as well

**Comment by hellofromtonya** [comment] 2020-05-26 11:57
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by DahmaniAdame** [comment] 2022-05-17 05:40
Related - https://secure.helpscout.net/conversation/1878460858/342084
The site has 200+ pages. 
​After a couple of tries, preload is completed after processing a range between 50 up to 150 pages.
​The website has logs with Memory Limit issues as well as [a server configuration limitation](https://stackoverflow.com/questions/33375823/apache-proxfy-fcgi-error-dispatching-request-to). It might be linked.

**Comment by piotrbak** [comment] 2022-08-30 10:50
The issue is not relevant with the 3.12 preload implementation, as we're storing URLs in the database.

**Closed by piotrbak** 2022-08-30 10:50 UTC
Labels: type: bug, module: preload, priority: medium, needs: details, status: blocked, future, severity: major
