### ISSUE TITLE
CDN rewriting doesn't work when WP_HOME/WP_SITE_URL scheme is different than the site's URLs

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2520] opened 2020-04-06 07:03 UTC
When the `WP_HOME` is using `http` but the site's URLs are using `https`, e.g. there is an htaccess redirect from `http` to `https` CDN rewriting doesn't take place.

This is because of the `str_replace()` in the `rewrite_url` method of the `CDN` class:
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/classes/CDN/CDN.php#L120

**Example:**
http://sandbox.onlinephpfunctions.com/code/1521df9f18dd8b11edf02e77f9994656078f6539

**To Reproduce**

1. Make sure the `WP_HOME` and `WP_SITE_URL` are using `http`.
2. Enable `http` to `https` redirection in the  `.htaccess` file.
3. Enable the CDN option.
4. Check the website. Static assets will not be rewritten to point to the CDN.

**Expected behavior**
Static assets should be pointing to the CDN.

**Additional context**

Using the `rocket_is_ssl_website()` function before the `string_replace()` resolves the issue:
```PHP
if( rocket_is_ssl_website() ) {
    $home_parts['scheme'] = 'https';
}
```
**Related ticket:**
https://secure.helpscout.net/conversation/1116358022/153068/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment] 2020-04-06 14:13
I think this is a duplicate of #2148

**Comment by GeekPress** [comment] 2020-04-06 14:50
It seems. I closed https://github.com/wp-media/wp-rocket/issues/2148 as this contains more details of the problem.

**Comment by ScottTravisHartley** [comment] 2020-04-06 16:10
I want to comment I noticed this issue as well working on a client site today their previous dev set it up as the issue describes I updated the home and site URLs to https and the rewrite works again.

**Comment by Tabrisrp** [comment] 2020-04-06 18:31
**Reproduce the issue** ✅ 
Issue reproduced and reported in multiple occasions

**Identify the root cause** ✅ 
As noted here and in the duplicate issue, it's happening when there is a difference between the URL set for home/site URL, and the real URL used, when the scheme is not the same.

The difference in scheme is preventing the `str_replace` from doing its job correctly.

**Scope a solution** ✅ 
`str_replace` can accept an array for the first argument `$needle`, so we can use an array under the following format to perform the replacement in all cases:
`[ 'http://example.org', 'https://example.org' ]`

**Effort** ✅ 
Effort `[S]`

**Closed** 2020-05-05 13:21 UTC
Labels: effort: [S], module: CDN, priority: high, type: bug
