### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by colomet** [wp-media/wp-rocket#564] opened 2017-11-10 21:17 UTC
To have options when we delete revisions 

https://github.com/trepmal/wp-revisions-cli/#wp-revisions-clean-keep

**Comment by colomet** [comment] 2018-01-12 09:18
Do you know that plugin? is compatible? I think some of the features can be good for wp-rocket
https://wordpress.org/plugins/above-the-fold-optimization/

**Comment by Tabrisrp** [comment] 2018-07-25 20:46
Duplicate of #88

**Closed by Tabrisrp** 2018-07-25 20:46 UTC
Labels: duplicate
