### ISSUE TITLE
Fatal Error Upon Activating

### ISSUE THREAD

**Issue by HammyHavoc** [wp-media/wp-rocket#1208] opened 2018-09-27 01:27 UTC
**Describe the bug**
Fatal error when activating.

**To Reproduce**
1. Download from GitHub
2. Upload zip to WordPress installation
3. Activate

**Expected behavior**
To activate and not get a fatal error.

**Screenshots**

**Additional context**
`
Fatal error: Uncaught Error: Class 'WP_Rocket\Admin\Options' not found in /home/yhlzhg3vlf2x/public_html/wp-content/plugins/wp-rocket-master/inc/functions/options.php:19 Stack trace: #0 /home/yhlzhg3vlf2x/public_html/wp-content/plugins/wp-rocket-master/inc/functions/options.php(495): get_rocket_option('secret_key') #1 /home/yhlzhg3vlf2x/public_html/wp-content/plugins/wp-rocket-master/inc/main.php(189): rocket_valid_key() #2 /home/yhlzhg3vlf2x/public_html/wp-includes/class-wp-hook.php(286): rocket_activation('') #3 /home/yhlzhg3vlf2x/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /home/yhlzhg3vlf2x/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/yhlzhg3vlf2x/public_html/wp-admin/plugins.php(180): do_action('activate_wp-roc...') #6 {main} thrown in /home/yhlzhg3vlf2x/public_html/wp-content/plugins/wp-rocket-master/inc/functions/options.php on line 19`

**Comment by Tabrisrp** [comment] 2018-09-27 10:57
Duplicate of #1015

**Closed by Tabrisrp** 2018-09-27 10:57 UTC
Labels: duplicate
