### ISSUE TITLE
Preload sitemap xml with parameters

### ISSUE THREAD

**Issue by grosssmutttr** [wp-media/wp-rocket#1612] opened 2019-04-03 15:46 UTC
Current wp rocket version: 3.2.6
WordPress: 5.1.1

**Steps to reproduce:**
1. create a sitemap
2. activate preload cache based on sitemap.xml
3. enter the path to the sitemap.xml
4. add additional rule ---> cache for query strings --->testattr1 and in the next line testattr2
5. clear cache
6. preload cache

**Result:**
1. URLs without parameters are cached
(e.g. `<loc>https://www.test.com/test/</loc>`)
2. URLs with parameters are not cached  
(e.g. `<loc>https://www.test.com/test/?testattr1=test1&amp;testattr2=test123</loc>`)
3. Visiting the url  with parameters in the browser triggers the cache to be generated successfully

**Expected result:**
All urls in the sitemap.xml are being cached - parameterized urls too.

**Comment by arunbasillal** [comment] 2019-04-05 11:39
@grosssmutttr Thanks for the detailed report. 

This is a duplicate of #1577 So I will close this. You can follow the conversation there as development happens.

**Closed by arunbasillal** 2019-04-05 11:39 UTC
