### ISSUE TITLE
RocketCDN Big CTA displays Campaign Name if discount is not active

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2854] opened 2020-07-08 08:14 UTC
**Describe the bug**
In RocketCDN the discount can be set as active or not. However in the Big CTA the campaign name and end date is displayed even if the discount is not active. 

The issue is in here:
https://github.com/wp-media/wp-rocket/blob/7838b137afad05907f6281d114c72f8c34423de8/inc/Engine/CDN/RocketCDN/NoticesSubscriber.php#L202-L210

**To Reproduce**
1. On dev RocketCDN insert a name for the discount and set the discount as not active.
2. Go to WP Rocket -> CDN tab (without a RocketCDN subscription) and the big CTA will display this
https://www.screencast.com/t/h1Be5hI9ho

**Expected behavior**
If RocketCDN discount is not active it should not display the campaign name even if is filled:
https://www.screencast.com/t/Rn09rBTiWPA

 
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment] 2020-11-03 18:15
Duplicate of #3033

**Closed by Tabrisrp** 2020-11-03 18:15 UTC
