### ISSUE TITLE
Praison SEO - Output buffering stops file optimization 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2330] opened 2020-02-20 13:38 UTC
The **Praison SEO** plugin:
https://wordpress.org/plugins/seo-wordpress/

clears the buffer, removing the `</html>`  tag for which we check here:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/Buffer/class-optimization.php#L85

That halts the file optimization process.

**Related ticket:** https://secure.helpscout.net/conversation/1083555846/146173?folderId=2135277#thread-3085260169 (edited) 

**To Reproduce**
1. Install the **Praison SEO** plugin: https://wordpress.org/plugins/seo-wordpress/
2. Activate CSS/JavaScript minification/combination.
3. Check the source code of the page to see the error.
4. Disabling the plugin allows WP Rocket to minify/combine files.

**Comment by Tabrisrp** [comment] 2020-03-16 19:23
**Reproduce the issue** :white_check_mark:
I was able to reproduce this issue

**Identify the root cause** :white_check_mark:
This plugin is misusing output buffering, emptying the buffer too early and preventing any of our optimization from being applied.

It's doing that to rewrite the `<title>` tag, when they could use https://developer.wordpress.org/reference/hooks/wp_title/ instead.

**Scope a solution**  :white_check_mark:
Honestly this doesn't feel like something that we should be trying to fix on our end:
1) They could be doing their rewrite the correct way
2) With their current code, we can't do much. At best we can add it to our incompatibility notice

@arunbasillal @GeekPress thoughts?

Estimate the effort ❓

**Comment by arunbasillal** [comment] 2020-03-31 16:07
I agree with @Tabrisrp that we shouldn't be trying to fix this at our end. Fixing it on the plugin's end could help other developers too. 

@webtrainingwheels Is it possible to contact the plugin author and point them to this issue please?

**Comment by webtrainingwheels** [comment] 2020-04-08 18:31
@arunbasillal I have contacted the developer here: https://secure.helpscout.net/conversation/1132078195/156734?folderId=377610

**Comment by webtrainingwheels** [comment] 2020-05-15 17:32
I never got a response from the developer, so, time for a Plan B?

**Comment by GeekPress** [comment] 2020-05-15 21:33
> I never got a response from the developer, so, time for a Plan B?

I suppose we don't have other solution than a Plan B.

@webtrainingwheels @arunbasillal @wp-media/wprocketplugin The discussion if open for any ideas / suggestions

**Comment by webtrainingwheels** [comment] 2020-05-21 16:43
My 2 cents..... For these kinds of issues (not cached/not optimized), I would check if the problem occurs with Fastest Cache (as an example of a free competitor). 

If no, we should see if we can fix on our side. (user expectation is that a premium plugin should have fewer conflicts and behave at least as well, if not better than a free one)
If FC also has an issue, we can use a notice or whatever method we agree on for alerting the customer (site health etc).

**Comment by GeekPress** [comment] 2020-05-21 20:24
+1000 for @webtrainingwheels

**Comment by arunbasillal** [comment] 2020-05-22 11:08
@webtrainingwheels @GeekPress Since there isn't much we can do here, shall we close this issue/ I have added this to our Known Conflicts doc. When we decide on how to alert the user about these things, we can add everything from that doc. 

The plugin only has 7000 active install right now to bother with anything too dramatic right now.

**Comment by GeekPress** [comment] 2020-05-26 07:21
@arunbasillal The problem here is the common problem we have with all other plugins which has the same issue.

We must fix this problem if we can for the reasons I explained here:
https://github.com/wp-media/wp-rocket/issues/2651#issuecomment-632323968

**Comment by piotrbak** [comment] 2024-06-25 16:16
It's not going to be implemented anywhere soon.

**Closed by piotrbak** 2024-06-25 16:16 UTC
Labels: type: bug, waiting for feedback, 3rd party compatibility, module: file optimization, priority: low, severity: critical
