### ISSUE TITLE
Facebook Pixel - Multiple pixels causes 404

### ISSUE THREAD

**Issue by ripplethor** [wp-media/wp-rocket#1927] opened 2019-08-29 22:42 UTC
**Describe the bug**
Some websites use multiple facebook tracking id's.
example:
```
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '123456');
fbq('init', '7891011');
fbq('track', 'ViewContent');
</script>
```
Turning on the "facebook local" in the "add-ons" section causes a 404 with the second pixel as it doesn't create the "fbpix-config" js file in the cache busting direcotry

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment] 2020-03-11 19:29
**Reproduce the issue** ✅ 
Reproduced on my local test site

**Identify the root cause** ✅ 
There are 2 scenarios and 2 root causes:

1.  Uses preg_match and matches a single block of script where fb.init() is contained.
There could be cases when multiple scripts contain fb.init().
eg: 
```<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '123456');
fbq('init', '7891011');
fbq('track', 'ViewContent');
</script>


<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '111');
fbq('init', '222');
fbq('track', 'ViewContent');
</script>
````
https://github.com/wp-media/wp-rocket/blob/c906a334e836ed8db3ebc410d6f066679deab4c7/inc/classes/busting/class-facebook-pickles.php#L359


2. Inside a script tag, multiple FB.init can be contained with different ids.
This preg_match identifies only the first one:
eg.
```
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
**fbq('init', '111');
fbq('init', '222');**
fbq('track', 'ViewContent');
</script>
```

https://github.com/wp-media/wp-rocket/blob/c906a334e836ed8db3ebc410d6f066679deab4c7/inc/classes/busting/class-facebook-pickles.php#L428

**Scope a solution** ✅ 
Solution will be to use preg_match_all to grab all FB.inits. The compute a list with all unique ids and bust all the FB ids.

**Estimate the effort** ✅ 
I would say this is a [M] size. Because a lot needs to change in there to fit multiple busted files.
Also the total lack of Unit & integration tests will increase the duration for this one.
@hellofromtonya , @Tabrisrp , @Screenfeed - do you think the effort M will be ok?

**Comment by webtrainingwheels** [comment] 2020-08-04 18:31
https://secure.helpscout.net/conversation/1244582040/184452?folderId=377611

**Comment by GeekPress** [comment] 2021-04-16 11:07
Closing this issue as Facebook Pixels add-on will be removed in WP Rocket 3.9

**Closed by GeekPress** 2021-04-16 11:07 UTC
Labels: community, effort: [M], module: Facebook Pixel add-on, priority: medium, severity: major, type: bug, wontfix
