### ISSUE TITLE
High Redis Miss rate for key wp_rocket_no_licence in the pre_get_rocket_option_remove_unused_css filter

### ISSUE THREAD

**Issue by mhodge** [wp-media/wp-rocket#5793] opened 2023-03-03 10:00 UTC
**Describe the bug**
Because the wp_rocket_no_licence transient never has a default value set in the plugin, the transient key does not exist, as such on our highly active WordPress sites running Redis it results in an extremely high redis miss rate. 

The only place it does get set is for the APIClient.php add_to_queue function, the duration is defined for the week, IF redis gets cleared in between this period again it results in high key misses.

**To Reproduce**
1. Install redis object cache in a fresh install
2. pull a report on the reds miss rate

**Expected behavior**
A default for wp_rocket_no_licence transient should be set by the plugin to avoid high redis miss rate. In the event of redis being cleared this default would need to be set again on plugin load.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment] 2023-04-26 09:05
## Identify the root cause
The root cause is said into the issue: `wp_rocket_no_licence` not having a default value.
## Scope a solution
A simple fix would be to add a value default value 0 to the transient `wp_rocket_no_licence`.
This has as an advantage to cast to false when being cast as a boolean but to be different from false when we need to check if the default value is set.

For that we will need to change the [`disable_russ_on_wrong_license`](https://github.com/wp-media/wp-rocket/blob/8befdf3f22a901749dfcdd6a1a0c980530f0d120/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L715) method from `Admin/Subscriber`:
```php
	/**
	 * Disable RUCSS on wrong license.
	 *
	 * @return bool
	 */
	public function disable_russ_on_wrong_license() {
		if ( false !== (bool) get_transient( 'wp_rocket_no_licence' ) ) {
			return false;
		}
		return null;
	}

```
Then we will have to add the default value by adding a callback on 'admin_init' event:
```php
public function set_default_wp_rocket_no_licence() {
   if(false !== get_transient( 'wp_rocket_no_licence' ) ) {
      return ;
  }
  set_transient('wp_rocket_no_licence', 0, WEEK_IN_SECONDS);
}
```

Then we will have to change tests to make it match the new logic.
## Estimate the effort
Effort `S`

**Comment by CrochetFeve0251** [comment] 2023-05-11 12:28
## Scope a solution
Another solution to prevent the value to fail is to transform it from a transient to an option.
For that we will have to change the creation of the option inside the [APIClient](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#L60).
Then we will have to change each of its usage:
- Inside [Settings/Page](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/Engine/Admin/Settings/Page.php#L597).
- Inside the Subscriber from RUCSS [at line 458](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L458) and [line 715](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L715).

Then we will have to create a logic to add the default value on install or update.
For that we will have to add the following method on the `RUCSS Subscriber`:
```php
public function on_update($version) {
                if ( version_compare( $old_version, '3.15', '>=' ) ) {
			return;
		}
               update_option('wp_rocket_no_licence', 0);
}
```
and on install `rocket_first_install_options`:
```php
public function on_install() {
               update_option('wp_rocket_no_licence', 0);
}
```

Finally we will have to remove the option when a valid license for that we will have to add the following logic inside the function [`rocket_check_key`](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/functions/options.php#LL451C10-L451C26) before the end:
```php
        update_option('wp_rocket_no_licence', 0);
	return $rocket_options;
```

@Tabrisrp or @engahmeds3ed could you check if that solution could create any problem?

**Comment by remyperona** [comment] 2023-05-11 15:10
Using an option seems to be a valid alternative for this too

**Comment by CrochetFeve0251** [comment] 2023-05-12 10:57
@piotrbak  The other option proposed by @engahmeds3ed is this one.
Instead of changing the transient to an option we will set the option inside the [`APIClient`](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#L60) by adding a else after [that if](https://github.com/wp-media/wp-rocket/blob/fb513713319fdc9aeafaf7bf078f38792ebd692a/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#LL59C1-L59C1):
```php
if ( key_exists( 'code', $result ) && 401 === $result['code'] ) {
			set_transient( 'wp_rocket_no_licence', true, WEEK_IN_SECONDS );
			update_rocket_option( 'remove_unused_css', 0 );
} else {
  set_transient( 'wp_rocket_no_licence', 0, WEEK_IN_SECONDS );
}
```

This will reduce the miss cache only to the first request instead of keep having it.

**Comment by remyperona** [comment] 2023-05-12 15:25
The thing is, if we still rely on this part of the code to be executed to set the transient, and RUCSS Is not enabled, there is still calls to get_transient( 'wp_rocket_no_licence' ) on `admin_notices` and on the settings page anyway, so the initial issue won't be fixed.

I'm assuming the high miss rate is caused by the callback on `admin_notices`, as it's probably not the settings page that is visited a lot. 

So What could be changed would be to move the get_transient() call in RUCSS\Admin\Subscriber::display_wrong_license_notice(), to RUCSS\Admin\Settings::display_wrong_license_notice(), after the check for `can_display_notice()`.

That way, the transient check will only happen if RUCSS is enabled, and in that case, the transient should/will be set as expected by the code above.

**Comment by CrochetFeve0251** [comment] 2023-05-15 08:53
> The thing is, if we still rely on this part of the code to be executed to set the transient, and RUCSS Is not enabled, there is still calls to get_transient( 'wp_rocket_no_licence' ) on `admin_notices` and on the settings page anyway, so the initial issue won't be fixed.
> 
> I'm assuming the high miss rate is caused by the callback on `admin_notices`, as it's probably not the settings page that is visited a lot.
> 
> So What could be changed would be to move the get_transient() call in RUCSS\Admin\Subscriber::display_wrong_license_notice(), to RUCSS\Admin\Settings::display_wrong_license_notice(), after the check for `can_display_notice()`.
> 
> That way, the transient check will only happen if RUCSS is enabled, and in that case, the transient should/will be set as expected by the code above.

While look at your comment in the code I think I found why we got so much miss there is a callback inside `RUCSS\Admin\Subscriber` that link to the event [`pre_get_rocket_option_remove_unused_css`](https://github.com/wp-media/wp-rocket/blob/0488426773035f37fa12fab324a305ebb853ce6b/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L111) a reference to the transient.

Due to that the second solution won't work to fix the issue. That's why I gonna implement the first one even it is more complex.

**Closed as completed** 2023-05-25 10:20 UTC
Labels: type: enhancement, priority: low, effort: [S], module: remove unused css
