### ISSUE TITLE
wp-rocket iframe and video lazyload option renders AMP version of the page invalid

### ISSUE THREAD

**Issue by bennett-md** [wp-media/wp-rocket#2644] opened 2020-05-13 10:56 UTC
Hello, we updated official AMP plugin and WP-Rocket plugin on websites that we have amp set up on.
And we get this issue:
screenshot of WordPress amp validator: https://prnt.sc/sfxom8 "The parent tag of tag 'style amp-custom' is 'noscript', but it can only be 'head'."
screenshot of google amp validator: https://prnt.sc/sfxot5
Issue seems to be in this style tag that has the id "rocket-lazyload-inline-css".

Now, if we go and disable this lazy-load option "Enable for iframes and videos", in wp rocket settings https://prnt.sc/sfxs18 , validator error goes away and page is valid, https://prnt.sc/sfxtcy .

So, at this moment we can't have lazyloading for iframes and videos enabled on websites that we have amp on.
Additional notes, Amp transitional mode is enabled.
Any help is appreciated.

**Comment by Bennet-md** [comment] 2020-05-13 10:56
Duplicate of #2523

**Closed** 2020-05-13 12:24 UTC
Labels: duplicate
