### ISSUE TITLE
Clearing cache with ManageWP Code Snippet feature

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1224] opened 2018-10-04 15:41 UTC
Several customers have wanted to clear their website(s) cache via ManageWP's[ Code Snippet feature](https://managewp.com/guide/manage/code-snippets):

![screen shot 2018-10-04 at 2 34 50 am](https://user-images.githubusercontent.com/8108643/46485642-f0079380-c7b0-11e8-808a-f16e939236f8.png)

We've provided a reference to our `rocket_clean_domain()` function:

https://docs.wp-rocket.me/article/92-rocketcleandomain

and this snippet for use:
https://gist.github.com/glueckpress/f035f249872a01db0995426cd51cf790

but the experience has not been consistently successful in testing (the code provides an empty response or the cache is not cleared). Perhaps there is a better way to clear the cache with this feature for these customers?

HS tag: `managewp`

**Comment by rumspeed** [comment] 2019-04-25 12:51
+1

**Comment by tishaoehmen** [comment] 2019-05-14 18:30
+1

**Comment by yuliyang** [comment] 2019-11-29 04:01
+1

**Comment by alfonso100** [comment] 2020-05-04 13:43
One of our users confirmed that this script worked for them. Allowing them to clear WP Rocket's cache from ManageWP console. They added it using [ManageWP's Code Snippet feature](https://managewp.com/guide/manage/code-snippets) :

```php
<?php
	
// Load WordPress.
require( 'wp-load.php' );
 
if ( function_exists( 'rocket_clean_domain' ) ) {
rocket_clean_domain();
}

$errors= error_get_last();
if( $errors ) {
echo "Error message: ".$errors['type'];
echo "<br />\n".$errors['message'];
} else {
echo "Cache cleared!";
} 
```

Related ticket: 
https://secure.helpscout.net/conversation/1152784419/162170?folderId=2683093

**Comment by apostolisem** [comment] 2021-04-02 20:39
> One of our users confirmed that this script worked for them. Allowing them to clear WP Rocket's cache from ManageWP console. They added it using [ManageWP's Code Snippet feature](https://managewp.com/guide/manage/code-snippets) :
>
> if ( function_exists( 'rocket_clean_domain' ) ) {
> // run if true
> } else {
> echo "Cache cleared!";
> }

Many people are suggesting this snippet, it's even referenced in wp-rocket's documentation, but... the only thing it is doing, is echoing "Cache cleared!". Please correct me if I am missing something.

**Comment by alfonso100** [comment] 2021-04-06 14:00
Hi @apostolisem 

The code you shared won't work. It should be also calling the `rocket_clean__domain()` function. 

```
if ( function_exists( 'rocket_clean_domain' ) ) {
   // run if true
   rocket_clean_domain();
  // display notification of cache cleared
   echo "Cache cleared!";
} 
```

**Comment by apostolisem** [comment] 2021-04-06 14:12
> Hi @apostolisem
> 
> The code you shared won't work. It should be also calling the `rocket_clean__domain()` function.
> 
> ```
> if ( function_exists( 'rocket_clean_domain' ) ) {
>    // run if true
>    rocket_clean_domain();
>   // display notification of cache cleared
>    echo "Cache cleared!";
> } 
> ```

Hi @alfonso100,

I replaced intentionally code in "if true" case with the comment "//run if true". Sorry, I had no intention to confuse anyone. I just wanted to point out that when you run the following code, what you get is only one "Cache cleared!" with no real results:
```
<?php
	
// Load WordPress.
require( 'wp-load.php' );
 
if ( function_exists( 'rocket_clean_domain' ) ) {
rocket_clean_domain();
 
$errors= error_get_last();
echo "Error message: ".$errors['type'];
echo "<br />\n".$errors['message'];
} else {
echo "Cache cleared!";
}
```
If you analyze the code, you'll notice that if statement is not true, and "rocket_clean_domain()" function never actually runs. So no cache cleaning is happening.

**Comment by alfonso100** [comment] 2021-04-06 15:11
I have updated the code above. please check: https://github.com/wp-media/wp-rocket/issues/1224#issuecomment-623472041

If `rocket_clean_domain` is not available, it means WP Rocket is not active so the function should exit.

**Comment by apostolisem** [comment] 2021-04-06 15:38
I believe the scope of the code should be to clear the cache instead of just stating "Cache cleared!".

 I am analyzing/commenting the code to show you "why" it is out of scope:

```
<?php
	
// Load WordPress.
require( 'wp-load.php' );
 
// the following IF, checks if the function rocket_clean_domain exists. If the function exists, then it is called by the next line, otherwise nothing is happening.
if ( function_exists( 'rocket_clean_domain' ) ) { 
rocket_clean_domain();
}

// the previous code will never output any rocket_clean_domain existence related error.. so the next code is irrelevant to our scope.
$errors= error_get_last();
if( $errors ) {
echo "Error message: ".$errors['type'];
echo "<br />\n".$errors['message'];

// the following else will run every time we don't have an error. The IF clause above, will never produce any errors. So the output will always be "Cache cleared!", even when "wp-rocket" is not installed.
} else {
echo "Cache cleared!";
} 
```

I am trying to explain that the code above is not working through ManageWP, but it only produces an output "Cache cleared!" every time there is no error.

In order to understand it better, run this snippet in a website without wp-rocket installed.

**Comment by alfonso100** [comment] 2021-05-10 20:00
Hi @apostolisem 
Sorry about the delay 🙏

You were 100% right about this. 
Could you please try the updated Snippet here: 
https://docs.wp-rocket.me/article/1320-managewp-how-to-clear-wp-rocket-cache

the code wasn't working because, due to the way ManageWP runs these snippets, we needed to re-load WP Rocket's environment so the functions can be triggered. 

This new snippet will also trigger Sitemap Preload if you have it enabled on your WP Rocket settings.

**Comment by piotrbak** [comment] 2022-01-20 12:52
Closing it, since the last solution mentioned by @alfonso100 is working correctly.

**Closed by piotrbak** 2022-01-20 12:52 UTC
Labels: needs: testing, 3rd party compatibility, module: cache

**Comment by vmanthos** [comment] 2022-01-20 13:03
Actually, that solution didn't work.

The updated one in our doc does:
https://docs.wp-rocket.me/article/1320-managewp-how-to-clear-wp-rocket-cache

PS: I'm adding this here in case anyone reaches this thread.

**Comment by piotrbak** [comment] 2022-01-20 13:05
@vmanthos Yes, I meant that @alfonso100 pointed to the docs in the last reply, sorry for not being clear.
