### ISSUE TITLE
Google Font Combined URL throws a 400 error

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#1713] opened 2019-05-13 19:53 UTC
**Actual behavior:**  Google Font Combined URL throws a 400 error.

**Expected behavior:** Google Font Combined URL is valid and works fine.

**Steps to reproduce the problem:**

1. Enable Combine Google Fonts.
2. Check the font of the menu items at https://effettispeciali.com/
3. See the 400 error at the Console.

**Notes:** 

- So far, we think it's related to the fact that the combined URL has a double vertical bar, `|` , in it.
- The Autoptimize Google Fonts Combine option doesn't throw the 400 error.

**Combined URL:** 

`https://fonts.googleapis.com/css?family=Lato:100,300,400,600,700,900%7COpen Sans:700,300,600,400|Raleway:900|Playfair Display||Open Sans|Jockey One:400|Abril Fatface:regular&subset=`

**Original URLs:** 

```https://fonts.googleapis.com/css?family=Lato:100,300,400,600,700,900%7COpen+Sans:700,300,600,400%7CRaleway:900%7CPlayfair+Display%7C&#038;ver=9adfdbd43f39a234a09de4319e14b851```

```https://fonts.googleapis.com/css?family=Open+Sans%7CJockey+One:400&#038;subset=latin&#038;ver=1549273751```

```https://fonts.googleapis.com/css?family=Abril+Fatface:regular&#038;ver=9adfdbd43f39a234a09de4319e14b851```

**Slack thread:** https://wp-media.slack.com/archives/C08N8J6VC/p1557770254029100.

**Related ticket:** https://secure.helpscout.net/conversation/848019263/107108/.

**Comment by arunbasillal** [comment] 2019-05-15 07:30
Looks like a duplicate of #1681

**Closed** 2019-06-10 16:15 UTC
Labels: module: file optimization, severity: minor, type: bug
