### ISSUE TITLE
Install via composer breaks site

### ISSUE THREAD

**Issue by MainAero** [wp-media/wp-rocket#3504] opened 2021-01-19 15:05 UTC
Just followed your guide and executed
`composer require wp-media/wp-rocket`.

After deployment to our AWS Beanstalk envirnment we are seeing following error:

```Fatal error: Uncaught Error: Class 'WP_Rocket\Plugin' not found in /app/foobar_com/wp-content/plugins/wp-rocket/inc/main.php:44 Stack trace: #0 /app/foobar_com/wp/wp-includes/class-wp-hook.php(287): rocket_init('') #1 /app/foobar_com/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /app/foobar_com/wp/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /app/foobar_com/wp/wp-settings.php(420): do_action('plugins_loaded') #4 /app/foobar_com/wp-config.php(25): require_once('/app/foobar_com/...') #5 /app/foobar_com/wp/wp-load.php(42): require_once('/app/foobar_com/...') #6 /app/foobar_com/wp/wp-blog-header.php(13): require_once('/app/foobar_com/...') #7 /app/foobar_com/index.php(17): require('/app/foobar_com/...') #8 {main} thrown in /app/foobar_com/wp-content/plugins/wp-rocket/inc/main.php on line 44```

Installing the plugin using your provided zip file is working.

**Comment by arunbasillal** [comment] 2021-01-21 08:05
@Tabrisrp Can you please take a look? Thanks.

**Comment by jg314** [comment] 2021-06-22 21:42
I'm also seeing this error, but I downloaded the plugin using SFTP from our web server. Here's the full error:

```
[22-Jun-2021 21:35:51 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_Rocket\Plugin' not found in C:\Users\j3k3\sites\test\app\public\wp-content\plugins\wp-rocket\inc\main.php:44
Stack trace:
#0 C:\Users\j3k3\sites\test\app\public\wp-includes\class-wp-hook.php(292): rocket_init('')
#1 C:\Users\j3k3\sites\test\app\public\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 C:\Users\j3k3\sites\test\app\public\wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#3 C:\Users\j3k3\sites\test\app\public\wp-settings.php(423): do_action('plugins_loaded')
#4 C:\Users\j3k3\sites\test\app\public\wp-config.php(85): require_once('C:\\Users\\j3k3\\...')
#5 C:\Users\j3k3\sites\test\app\public\wp-load.php(37): require_once('C:\\Users\\j3k3\\...')
#6 C:\Users\j3k3\sites\test\app\public\wp-blog-header.php(13): require_once('C:\\Users\\j3k3\\...')
#7 C:\Users\j3k3\sites\test\app\public\index.php(17): require('C:\\Users\\j3k3\\...')
#8 {main}
  thrown in C:\Users\j3k3\sites\test\app\public\wp-content\plugins\wp-rocket\inc\main.php on line 44
```

**Comment by filipesouza2** [comment] 2021-07-19 14:02
Hello, just to update this up, the problem still persist in 3.9.0.5 version when using composer require:

```code
[Mon Jul 19 13:50:28.980861 2021] [proxy_fcgi:error] [pid 2732:tid 140437612312320] [client 10.0.0.100:54166] AH01071: Got error 'PHP message: 
PHP Fatal error:  Uncaught Error: Class 'WP_Rocket\\Plugin' not found in /bitnami/wordpress/wp-content/plugins/wp-rocket/inc/main.php:44
Stack trace:#0 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(292): rocket_init()
#1 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#2 /opt/bitnami/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 /opt/bitnami/wordpress/wp-settings.php(423): do_action()
#4 /bitnami/wordpress/wp-config.php(185): require_once('/opt/bitnami/wo...')
#5 /opt/bitnami/wordpress/wp-load.php(37): require_once('/bitnami/wordpr...')
#6 /opt/bitnami/wordpress/wp-blog-header.php(13): require_once('/opt/bitnami/wo...')
#7 /opt/bitnami/wordpress/index.php(17): require('/opt/bitnami/wo...')
#8 {main}
  thrown in /bitnami/wordpress/wp-content/plugins/wp-rocket/inc/main.php on line 44'
```
Running ```composer install --no-dev --no-scripts ``` inside the wp-rocket in a test environment resolves the error, but there is something wrong with the composer package available.

**Comment by remyperona** [comment] 2021-07-26 16:08
Do you correctly have the composer autoload file loaded in your setup?

**Comment by LetterAfterZ** [comment] 2022-03-25 04:20
I'm also having this issue. I tried adding a callback script to run the installed on our server, but I get errors because we're running php 8.0:

```
  Problem 1
    - phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.13) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^7.5 -> satisfiable by phpunit/phpunit[7.5.0, ..., 7.5.20].
```

**Comment by mbmjertan** [comment] 2022-08-12 10:51
Can confirm that this is still reproducible.

If you use Composer in a project to manage plugins, and download WP Rocket as a Packagist package (which is installed using `composer/installers` as its type is set to `wordpress-plugin`), autoloaders for the WP Rocket plugin will not be dumped in the plugin folder.

This happens even if your project's autoloader is correctly included, as it does not provide autoloading for WP Rocket.

**Comment by piotrbak** [comment] 2024-06-26 13:35
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed. 

Closing this issue doesn't mean that we're abandoning it completely, it simply will not be implemented in the mid term schedule.

**Closed as not planned by piotrbak** 2024-06-26 13:35 UTC
Labels: waiting for feedback
