### ISSUE TITLE
Query string caching overrides excluded pages from cache

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4765] opened 2022-02-25 08:01 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.10.8`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a query string is set to be cached, it will be cached on pages excluded from caching as well. 

**To Reproduce**
1. Enable a specific query string to be cache
2. Exclude a specific page from caching
3. See that the page is cached when using the query string

**Expected behavior**
Page exclusions should be applied to query strings cache as well. 

**Screenshots**
N/A 

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment] 2022-03-07 16:34
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
This is happening because in the `Buffer\Tests::can_process_uri()` method, we are doing a match against the full request path including the query string, but the pattern uses the `$` token to match end of line, so it's never matching against the excluded paths in the pattern.

### Scope a solution ✅ 
Instead of using `get_clean_request_uri()` as the subject in which to match, we can use `get_request_uri_base()`, which doesn't contain the query string.

### Estimate the effort ✅
Effort `[XS]`

**Comment by webtrainingwheels** [comment] 2022-03-11 19:16
Related case: https://secure.helpscout.net/conversation/1809547889/330315?folderId=377611

This also seems related to: https://github.com/wp-media/wp-rocket/issues/296

**Comment by CrochetFeve0251** [comment] 2022-04-11 11:38
@piotrbak this issue already has a PR should I pass it to ready for QA in the project?

**Comment by piotrbak** [comment] 2022-04-11 11:40
@CrochetFeve0251 You're right, moving it there.

**Closed as completed** 2022-05-02 19:44 UTC
Labels: type: bug, good first issue, module: cache, priority: medium, effort: [XS], severity: major
