### ISSUE TITLE
Remove Unused CSS to support wildcard in safe list

### ISSUE THREAD

**Issue by wpsumo** [wp-media/wp-rocket#4148] opened 2021-07-10 11:57 UTC
**Is your feature request related to a problem? Please describe.**
It would be preferred to have wildcard so we can write 1 line instead of 50 to add safe list of dynamic classes appended, as RUCSS doesn't manage to find them right now.

**Describe the solution you'd like**
Example:
`.(.*)--is-active`

**Describe alternatives you've considered**

**Additional context**
Used in the KB as an example but not in the actual plugin and wild card doesn't seem to work during testing. Also wonder if chained selectors is suppose to work `.class-example .class-example-two:first-child` etc?
![image](https://user-images.githubusercontent.com/16893128/125162200-3e7ec380-e18f-11eb-8662-af6ba889ff32.png)

**Comment by GeekPress** [comment] 2021-07-12 11:28
Duplicate of https://github.com/wp-media/tree-shaker/issues/119

**Closed as completed by GeekPress** 2021-07-12 11:28 UTC
Labels: duplicate

**Comment by nicomollet** [comment] 2021-07-29 07:19
Any news about this?

This issue https://github.com/wp-media/tree-shaker/issues/119 is not public, so we don't know the state of it.
