### ISSUE TITLE
Several PHP errors related to CloudFlare library after activating WP Rocket

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1398] opened 2018-11-29 21:27 UTC
On a customer website, activating WP Rocket is created a White Screen of The Death. After turn on the WP Debug mode, some PHP errors are displayed:
https://cl.ly/0077b125ed84

Related ticket:
https://secure.helpscout.net/conversation/710683792/86720/

**Comment by Tabrisrp** [comment] 2018-11-29 21:30
it's related to CURL configuration directly, this needs to be fixed on a server level

**Comment by GeekPress** [comment] 2018-11-29 22:23
If we can detect on our side which cURL configuration is missing and maybe not loading stuff related to CloudFlare. A customer will prefer to not being able to use CloudFlare add-on because on his server configuration than not being able to use WP Rocket at all and getting a broken website.

**Comment by arunbasillal** [comment] 2019-07-02 13:48
@Tabrisrp Is this a duplicate of #222

**Comment by arunbasillal** [comment] 2019-11-15 10:27
We have handled this already. Closing this. Thanks @crystinutzaa for pointing this out.

**Closed by arunbasillal** 2019-11-15 10:27 UTC
Labels: module: cloudflare, type: enhancement
