### ISSUE TITLE
Critical CSS: Different CPCSS within the same content type

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#628] opened 2017-12-12 18:51 UTC
For a future iteration - how can we account for differing CPCSS within the same content type?
For example, with a page builder I can create posts that each have different CPCSS (I have examples on our test site).
Could we enable a way to pass custom URLs to our tool to crawl?

**Comment by camilamadronero** [comment] 2019-05-02 20:08
Related ticket: https://secure.helpscout.net/conversation/840358984/105994?folderId=2675957.

**Comment by GeekPress** [comment] 2020-03-06 16:54
I'm going to close as it's a duplicate of https://github.com/wp-media/wp-rocket/issues/2377

**Closed by GeekPress** 2020-03-06 16:54 UTC
Labels: module: file optimization, type: enhancement
