### ISSUE TITLE
WooCommerce, hierarchical categories not being cleared

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#2461] opened 2020-03-20 08:14 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
I've tried it on 3.5 and 3.44

**Describe the bug**
While using WooCommerce lets suppose we have a product URL at https://domains.gr/bebe/asfaleia-kai-prostasia-mwrou/asfaleia-sto-spiti/asfaleies-gia-portes-kai-parathyra/safety-1st-asfaleia-gia-portes-stopper-2-se-1-32020-03/

and updating a product (post type: product) via CRUD or API to change price (using $product->save(), the following URLs are cleared.

[ 2020-03-20 08:00:42 ] post_ID: 30360
Array
(
[0] => https://domains.gr/bebe/asfaleia-kai-prostasia-mwrou/asfaleia-sto-spiti/asfaleies-gia-portes-kai-parathyra/safety-1st-asfaleia-gia-portes-stopper-2-se-1-32020-03/
[1] => https://domains.gr/kathgories/index-https.html
[2] => https://domains.gr/kathgories/index-https.html_gzip
[3] => https://domains.gr/kathgories/page
[4] => https://domains.gr/product-category/bebe/asfaleia-kai-prostasia-mwrou/asfaleia-sto-spiti/asfaleies-gia-portes-kai-parathyra/
[5] => https://domains.gr/hlikia/0-12-mhnwn/
[6] => https://domains.gr/hlikia/12-24-mhnwn/
[7] => https://domains.gr/hlikia/2-3-etwn/
[8] => https://domains.gr/hlikia/3-4-etwn/
[9] => https://domains.gr/hlikia/5-7-etwn/
[10] => https://domains.gr/hlikia-apo/6m/
[11] => https://domains.gr/hlikia-ews/7/
[12] => https://domains.gr/kataskevasths/safety-1st/
[13] => https://domains.gr/availability/amesa-diathesimo/
[14] => https://domains.gr/2019/index.html
[15] => https://domains.gr/2019/index.html_gzip
[16] => https://domains.gr/2019/page
[17] => https://domains.gr/2019/03/index.html
[18] => https://domains.gr/2019/03/index.html_gzip
[19] => https://domains.gr/2019/03/page
[20] => https://domains.gr/2019/03/12/
[21] => https://domains.gr/author/
)

If you see the main category of the product is cleared 
[4] => https://domains.gr/product-category/bebe/asfaleia-kai-prostasia-mwrou/asfaleia-sto-spiti/asfaleies-gia-portes-kai-parathyra/

but if you visit 
https://domains.gr/product-category/bebe/asfaleia-kai-prostasia-mwrou/asfaleia-sto-spiti/
https://domains.gr/product-category/bebe/asfaleia-kai-prostasia-mwrou/
https://domains.gr/product-category/bebe/

Price will be wrong

**To Reproduce**
1) Add a sub-sub category on WooCommerce and keep that ticked only (Do not tick any of the main categories, just the child one)

**Expected behavior**
As categories is hierarchy and all have archive, all categories (parent/child) should be cleared

**Comment by Tabrisrp** [comment] 2020-03-30 15:32
**Reproduce the issue** ✅ 
Reproduced the issue on local

**Identify the root cause** ✅ 
On a post purge, only the currently assigned terms of this post are added to the purge list, not the parent terms. The parent terms pages will still show the product since it's included in one of their children, so they need to be cleared too.

**Scope a solution** ✅ 
In `get_rocket_post_terms_urls()` (`inc/functions/posts.php`), we can check for each term if:
- `is_taxonomy_hierarchical()` to determine if we need to fetch the ancestors
- `get_ancestors()` to get the ancestors for the term and add them to the purge list
- Add automated tests

**Effort**
`[S]` low complexity, most of the time will be spent on automated tests

**Comment by hellofromtonya** [comment] 2020-06-12 13:58
This issue's PR is blocked by PR: #2736. Once 2738 gets merged, then we'll unblock it and move forward.

**Comment by Tabrisrp** [comment] 2020-06-16 18:19
Unblockg as PR #2736 is now merged

**Closed** 2020-06-19 14:19 UTC
Labels: community, effort: [S], module: cache, priority: medium
