### ISSUE TITLE
Delay JS Fails to Execute Properly if Mouse is Moving While Page is Loading

### ISSUE THREAD

**Issue by thekendog** [wp-media/wp-rocket#3961] opened 2021-05-28 01:18 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: Yup, 3.9
- Used the search feature to ensure that the bug hasn’t been reported before: Don't see anything

**Describe the bug**
When loading a page, if my mouse is moving in the window while the page is loading, scripts do not execute.  I have to let my mouse remain still until the page loads in order for it to work properly.  

**To Reproduce**

Here is a video example.

https://streamable.com/vyggm6

There are 4 page refreshes in this video.  The first refresh shows it working properly.  You will know this because the OneSignal red bell icon shows in the bottom left.  The second refresh is me moving my mouse over the window while the page is loading.  Notice the bell doesn't load.  Meaning scripts aren't firing.  The third refresh shows it working properly.  Like the first refresh, I didn't move my mouse.  And finally, the fourth refresh shows me moving my mouse over the window while the page loads which causes the error to occur again.

**Expected behavior**
The scripts should always be executed.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by ldquan** [comment] 2021-05-28 04:17
I have the same issue

**Comment by thekendog** [comment] 2021-06-03 13:02
It doesn't appear that 3.9.0.1 fixed the issue.

**Comment by vmanthos** [comment] 2021-06-04 09:54
**Related ticket:** https://secure.helpscout.net/conversation/1529387360/268136/

Even excluding everything from Delay JS, the issue is there, as can be seen in the screencast: https://youtu.be/ueorlRDeHsA

I had all JavaScript-handling features disabled.

**Comment by GeekPress** [comment] 2021-06-04 14:15
Hi 🤚

Does this kind of behavior is expected from someone? Moving the mouse like this doesn't seem natural and only from someone who wants to debug the Delay JS feature.

**Comment by thekendog** [comment] 2021-06-04 14:54
I mean yeah, not everybody just sits there without ever moving their mouse on page load.  I was obviously forcing it in my example but to think that nobody would ever be moving their mouse at all is a little shortsighted.  The whole reason I discovered it in the first place was not because of forcing the issue, but through general use.

**Comment by jazir555** [comment] 2021-06-04 22:27
Agreed, having this bug occur as well

**Comment by thekendog** [comment] 2021-06-05 00:43
Yeah, I feel like this is a pretty significant bug that needs to be addressed ASAP.  Especially since this feature is turned on by default.  Not everyone knows how to test/look for these errors and the most pressing issue I can think of is sites are going to be losing out on Google Analytics data because the script is never executed.

**Comment by tommy83** [comment] 2021-06-05 10:42
@GeekPress 
our website have many visitor per day.
After installed wp rocket v 3.9.1 we got a lot of feedback like this: friend, your website is broken:
- Visitor enter our url and just using the mousewheel to scroll. This is an very normal situation and not very rear.
- After installing another cachin plugin (that also delay js) everything is fine while scrolling without moving the mouse. They debug that issue after we report it. I hope you will fix that issue also very soon.

Next general issue regarding to this option:
- We need asap timeout option: start script after x seconds.
Because if visitor open an website without prio to scroll they will not see search option in header or some other elements which are shown/correct styled after running JS. So its ver important to run scripts after x seconds like timeout. Otherwise user will dont see search options in header for example and they will asking himself: whats happend here, site is broken?!

This improvements/debug need to be addressed asap.

**Comment by NataliaDrause** [comment] 2021-06-07 05:26
Related: https://secure.helpscout.net/conversation/1533601640/269239/

**Comment by GeekPress** [comment] 2021-06-09 07:11
> We need asap timeout option: start script after x seconds.

@tommy83 I already explained to you on your support tickets that a timer is totally useless. Adding a timer is like not having the option turned on, so why should we add this?

A 2 seconds timer is required at minimum to get the benefits of it. But in the meantime, it will destroy your performance on GT Metrix...

**Comment by tommy83** [comment] 2021-06-09 09:35
@GeekPress 
https://github.com/wp-media/wp-rocket/issues/3961

Because: there is no reason to scroll on every website.
And many websites have objects in top section and user will wait for it before interacting with the shown elements. For example filter in top bar, slider and many more.

And Small sites dont have scroll. And very often mobile websites have filter, search and other controle elements in header. Visitor will wait or need to touch/scroll to see the elements. Not good UX and visitor dont understand why...

MANY JS Delay Plugins already support fallback/timeout (for example flyingpress, wp meteor). They also explain: 1 second for good performance... 2 seconds for very good performance... and no fallback/no timeout for best performance. So admin have the option to chose: set timeout or not.

**Comment by GeekPress** [comment] 2021-06-09 09:38
@tommy83 This is why by default the Delay JS excludes ALL internal JS files... We aren't forcing you to delay all your JS files.

You can do your test with WP Meteor as it's a good example. Select 1 second and you won't have any significant improvements.

It's not because other plugins are doing it means it's a good thing to do.

**Comment by GeekPress** [comment] 2021-06-09 09:40
And please check these reports:

Delay User Interaction :
https://gtmetrix.com/reports/www.qconnan-photos.fr/0NZR7vvX/

Delay 2 seconds:
https://gtmetrix.com/reports/www.qconnan-photos.fr/l3whFAwg/

What has been done on this website is to exclude some JS files from the Delay JS to have images displayed without user interaction:

The result is:
 https://gtmetrix.com/reports/www.qconnan-photos.fr/VlYXyYv1/

One more time, it's why we are excluding internal JS files by default. After that, it's up to the user to decide to delay everything, to exclude some of them, or to use the default exclusion list.

**Comment by thekendog** [comment] 2021-06-09 12:33
@GeekPress not sure what you and tommy83 have been discussing through tickets, but is this issue being looked at by the WP Rocket team?

**Comment by tommy83** [comment] 2021-06-09 18:09
@GeekPress @thekendog 

My idea is based on this information from WP Meteor Page Speed Optimization Topping by Aleksandr Guidrevitch

> According to [this source](https://httparchive.org/reports/page-weight?lens=wordpress), there are 27 scripts (31.7% of all files), worth of 461Kb (19.3%) on an average
> Wordpress page.
> 
> If user doesn't start interacting with page immediately, WP Meteor postpones loading
> and firing scripts until after page gets rendered.
> 
> This postponement in script loading greatly improves perceived load times for your visitors. It also
> significantly improves the following important SEO metrics:
> 
>     Page Speed
>     Largest Contentful Paint (LCP)
>     Time To Interactive (TTI)
>     Total Blocking Time (TBT)
> 
> We've identified 2 major breakpoints in script loading delays:
> 
>     1 second delay
>     Pros:
>         page speed improves significantly
>         none or very minor difference in experience for visitors
>     Cons:
>         page speed metric might fluctuate
>         visitors, who spend less than 1 second on your page might not be counted in analytics
>     Anything below 1 second doesn't improve page speed.
>     2 seconds delay
>     Pros:
>         maximum available improvement in scores
>     Cons:
>         there might be a noticeable delay in animations, located above the fold
>         visitors, who spend less than 2 seconds on your page might not be counted in analytics
>     Anything above 2 seconds doesn't improve scores further
> 
> In both cases, visitors will experience faster page loading times as they'll see fully rendered page a lot earlier,
> than currently. 

To have an fallback is very important. And many websites will not work if the script will wait for user interaction.
So webmaster need to setup an fallback.
Right now admin need to decide: black or white. Yes or no. 0 or 1.

Deactivated > Pagespeed: Not good. UX/Website function without user interaction: Best.
Activated > Pagespeed: Best. UX/Website function: Not best, because not all users will move the mouse from the first moment. Many visitor asked us: whats happend with your site? we wait many seconds...but nothing happend...

So my idea is: To have an fallback. Admin can setup value like x seconds. After that time the JS will be fired.
Right now we need to install WP Meteor. Do you plan to include similar options?

**Comment by GeekPress** [comment] 2021-06-11 07:08
This bug will be fixed with the new version of the Delay JS script. It will be released on 3.9.0.2.

**Comment by thekendog** [comment] 2021-06-11 12:23
@GeekPress excellent.  Thanks for looking into it.

**Closed as completed** 2021-06-11 18:21 UTC
Labels: type: bug, priority: high, module: delay JS

**Comment by FreddyEE** [comment] 2022-09-27 09:54
I still have this issue with the lastest version of wp rocket with elementor, how could that be fix ?
![image](https://user-images.githubusercontent.com/114480904/192494895-aa0854ff-e622-440c-9088-a9b4519bf97d.png)
