### ISSUE TITLE
Wrong usage of CSS safelist filter by the Plugin for Google Reviews by RichPlugins

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#6440] opened 2024-02-08 16:22 UTC
**Is your feature request related to a problem? Please describe.**
The [Plugin for Google Reviews](https://wordpress.org/plugins/widget-google-reviews/) is using our `pre_get_rocket_option_remove_unused_css_safelist` filter to set their `/plugins/widget-google-reviews/assets/css/public-main.css` file to the **CSS safelist** box.

This causes some problems:

- As soon as this plugin is active, the CSS file is added, and any pre-existing entries are wiped out
(When the plugin is deactivated, the custom safelisted values are back)
- Also, when their exclusion is set, any new values can't be added to the safelist box

**Describe alternatives you've considered**
We could add an admin notice, override this and/or contact the developers.

**Additional context**
**Ticket:** https://secure.helpscout.net/conversation/2501403893/473262/
**Slack thread:** https://wp-media.slack.com/archives/C029G1B5HD2/p1707321423627699

**Comment by richplugins** [comment] 2024-02-12 17:04
Hi,

I'm developer from RichPlugins [Plugin for Google Reviews](https://wordpress.org/plugins/widget-google-reviews/).

We use filter 'pre_get_rocket_option_remove_unused_css_safelist' to exclude the plugin's CSS main file from 'Remove Unused CSS', because some classes set up dynamically when JavaScript renders plugin's layout.

We use this filter as following:

```
<?php

namespace WP_Rplg_Google_Reviews\Includes;

class Assets {
    ...
    public function register() {
        ...
        add_filter('pre_get_rocket_option_remove_unused_css_safelist', array($this, 'rucss_safelist'));
    }

    function rucss_safelist($safelist) {
        $safelist[] = '/wp-content/plugins/widget-google-reviews/assets/css/public-main.css';
        return $safelist;
    }

    ....
}
```

The problem is that some users want to add their custom files or classes in 'CSS safelist' field, however it will always be overridden with the file '../public-main.css' from the above code.

We tried below solution:

```
    function rucss_safelist($safelist) {
        global $pagenow;
        if ('options-general.php' === $pagenow && 'wprocket' === $_GET['page']) {
            return $safelist;
        }
        $safelist[] = '/wp-content/plugins/widget-google-reviews/assets/css/public-main.css';
        return $safelist;
    }
```

However, in this case the code after IF will never execute.

How can we NOT override 'CSS safelist', but simply add plugin's CSS file there, leaving other contents untouched?

Thanks!

**Comment by sexcuk** [comment] 2024-02-13 09:32
We have the same issue. Please take a look at this.

**Comment by Rufus13apostol** [comment] 2024-02-15 09:16
We also have the same issue, is there any fix that can be add to make both plugins work?

**Comment by wordpressfan** [comment] 2024-02-20 16:16
@richplugins 
You are using the wrong filter, I'd suggest using the following snippet (I think we already sent u via email, but sharing it here for documentation)

```
add_filter('get_rocket_option_remove_unused_css_safelist', function( $safelist ) {
    $css_file = $this->get_css_asset('grw-public-main-css');
    if ( array_search( $css_file, $safelist ) ) {
        return $safelist;
    }
    $safelist[] = $css_file;
    return $safelist;
});
```

The `pre_` filter that you used is before getting the option value from the database and the default filter value is null, so when you change this null to anything else, our code will detect that the value is changed so it will not get the option from the database at all and keep getting your value olny.

Using the filter `get_rocket_option_remove_unused_css_safelist` is applied after getting the option value from the database so you can play with it as u like, I also added a guard against not adding the style multiple times by searching first in the safelist array.

**Comment by richplugins** [comment] 2024-02-20 21:20
Hi,

Thank you for this code. It will be included in the next version of the plugin this week.
It seems we can close this issue.

Thanks!

**Comment by piotrbak** [comment] 2024-02-21 10:01
Fixed by @richplugins, thank you!

**Closed as completed by piotrbak** 2024-02-21 10:01 UTC

**Comment by Rufus13apostol** [comment] 2024-02-21 10:27
Testing the plugin update 3.6, with rocket version 3.15.9 , when you save the changes the first time on that section, the rich plugin css file is added twice:
https://i.imgur.com/fxCIgme.png

**Comment by richplugins** [comment] 2024-02-21 15:59
Hi @Rufus13apostol,

Is it possible to send us credentials from your wp-admin to test that?
It's strange because in a PHP code we check the case if it's already added into the safelist array.

Thanks!

**Comment by Rufus13apostol** [comment] 2024-02-22 11:51
Yes, I will send you an email with it
