### ISSUE TITLE
Remove unused css breaks Elementor Elementors nav menu widget submenu indicator

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4006] opened 2021-06-06 02:12 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - on version 3.9.0.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Remove unused css breaks the submenu indicator on every other page that isn't the homepage, even when every elementor css file is excluded in the textbox for files to skip

**To Reproduce**
1. Place a nav menu widget with submenu items in elementor in the header
2. Exclude all Elementor CSS files
3. The submenu indicator may work on the homepage, but does not work on any other pages.

**Expected behavior**
Submenu indicator that works, and the exclusions box actually excluding the css files that are specified

**Comment by piotrbak** [comment] 2021-06-07 13:50
I wasn't able to reproduce the problem when it wasn't working for pages other than home. I created a GitHub issue, so the menu display will be handled automatically, without excluding the whole files from the feature:
https://github.com/wp-media/wp-rocket/issues/4011

**Comment by GeekPress** [comment] 2021-06-07 13:53
Duplicate of #4011

**Closed as completed by GeekPress** 2021-06-07 13:53 UTC
Labels: type: bug, duplicate, 3rd party compatibility, module: remove unused css

**Comment by jazir555** [comment] 2021-06-11 18:45
@GeekPress 

I just want to clarify, this is referring to the dropdown indicator which is a font awesome icon, an arrow/chevron down icon.

**Comment by Yahav** [comment] 2021-09-03 07:12
> Duplicate of #4011

There's no such issue though, when using the link provided by @piotrbak i get:
This issue has been moved to a repository you don't have access to.

This issue is rather quite elementary and we have no way of knowing whether or not its being worked on.

EDIT:
Meanwhile you can add the following to the safelist to solve this
```
.fa-(.*):before
.fa-(.*)
```

**Comment by berkmh** [comment] 2022-04-23 15:37
sorry to reopen this, but has a solution been found @jazir5 ? All of my submenu arrows (across the site) become huge upon activating unused css. adding to safe list: 

`.fa-(.*):before
.fa-(.*)`

as suggested by @Yahav did not fix it for me. this is the only problem I have when activating and its driving me nuts.

**Comment by jazir555** [comment] 2022-04-23 23:35
@berkmh Yes actually! Add this to the css selector exclusion list: .e-font-icon-svg. The reason your exclusions won't work is because the icon is not a font awesome icon, it is an e-icons icon.
