### ISSUE TITLE
500 error because of corrupted .htaccess file

### ISSUE THREAD

**Issue by Presskopp** [wp-media/wp-rocket#5616] opened 2022-12-08 21:35 UTC
I ran into a problem on several sites using v3.12.3.2. Got an 500 server error, possibly in connection with 3rd party plugin updates (Elementor, Yoast ..)
I did deactivate some plugins but the site only went back to life after deactivating WP Rocket.

Following https://docs.wp-rocket.me/article/110-resolve-500-internal-server-error I opened the htaccess file and I found corrupted entries in the form of double lines like that:

```
</IfModule>
</IfModule>
```

to be specific this was to be found under the following blocks:
```
<IfModule mod_headers.c>
SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
# Don’t compress images and other uncompressible content
SetEnvIfNoCase Request_URI \
\.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g|mp4|webm|webp|pdf)$ no-gzip dont-vary
</IfModule>
</IfModule>
```
and

```
<IfModule mod_headers.c>
Header append Vary: Accept-Encoding
</IfModule>
</IfModule>
```

deleting the 2nd lines brought back the site.

This happens using PHP 8.0 and PHP 8.1 btw.

That's all I can say for now, let's see if the sites will be corrupted again or not after updating to v3.12.3.3 and reactiviating all 3rd party plugins

If needed, I'd be happy to provide more details.

**Comment by piotrbak** [comment] 2022-12-09 15:58
Hello @Presskopp and thanks for creating the issue.

We have pretty old one related to this problem 🧓:
https://github.com/wp-media/wp-rocket/issues/928

Main reason why it wasn't fixed is that we can't reproduce it in a reliable way to find the root cause. Basically, it always work when you try to udpate or regenerate .htaccess for the next time. 

I'll close this issue since it's a duplicate.

**Closed as completed by piotrbak** 2022-12-09 15:58 UTC
Labels: duplicate
