### ISSUE TITLE
Table `wp_wpr_rocket_cache` doesn't exist when running WP-CLI cronjobs

### ISSUE THREAD

**Issue by simkoG** [wp-media/wp-rocket#5361] opened 2022-08-29 08:56 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
There is an error message in the log file when WP cron is called via WP-CLI. 

```log
WordPress adatbázis hiba Table 'wp_wpr_rocket_cache' doesn't exist a lekérdezésben SELECT id FROM `wp_wpr_rocket_cache` WHERE `last_accessed` <= date_sub(now(), interval 1 month) készítette include('phar:///home/***username***/wp-cli.phar/php/boot-phar.php'), include('phar:///home/***username***/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->run_command_and_exit, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Cron_Event_Command->run, Cron_Event_Command::run_event, do_action_ref_array('rocket_preload_clean_rows_time_event'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Cron\Subscriber->remove_old_rows, WP_Rocket\Engine\Preload\Database\Queries\Cache->remove_all_not_accessed_rows, WP_Rocket\Engine\Preload\Database\Queries\Cache->get_old_cache
```

_The log's language is Hungarian. Translation: "**WordPress database error Table wp_wpr_rocket_cache doesn't exist on database**"_

The mentioned table exists in the database as you can see in the image. 

![image](https://user-images.githubusercontent.com/10430702/187161992-2190831e-6bb1-4c0c-89de-f95da103a9e7.png)

**To Reproduce**
1. Install the latest WordPress / WP Rocket. 
2. Disable the WP-Cron: `define( 'DISABLE_WP_CRON' , true );`
3. Install the latest [WP-CLI](https://wp-cli.org/).
4. Call the cron events with the `wp cron event run --due-now` command. 
5. See the error log. 

**Expected behavior**
No database error when running WP-CLI cronjobs.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment] 2022-08-29 11:57
## Reproduce the problem
I couldn't reproduce the issue following that process.
## Identify the root cause
However I guess the problem can be solved by adding a guard before use the preload table as asked in #5351.
What do you think @piotrbak ?

**Comment by remyperona** [comment] 2022-08-29 14:15
It wouldn't make sense to guard the use of the table if it exists, as we want the cronjobs to run in CLI too for it

**Comment by DahmaniAdame** [comment] 2022-09-09 09:59
Related - https://secure.helpscout.net/conversation/1998433981/365950/

```
[02-Sep-2022 12:28:57 UTC] WordPress database error Table 'yosiga_NljdIjoq.w47fa_wpr_rocket_cache' doesn't exist for query SELECT  COUNT(*) FROM w47fa_wpr_rocket_cache wpr_cache WHERE wpr_cache.url = 'https://domain.ext/en/research-methods-in-anthropology' AND wpr_cache.status = 'in-progress' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ob_end_flush_all, ob_end_flush, WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer, do_action('rocket_after_process_buffer'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->update_cache_row, WP_Rocket\Engine\Preload\Database\Queries\Cache->is_preloaded, WP_Rocket\Dependencies\Database\Query->query, WP_Rocket\Dependencies\Database\Query->get_items, WP_Rocket\Dependencies\Database\Query->get_item_ids
```

The issue is not specific to CLI.

Before safeguarding it, we need to understand first why it's happening. 

I've seen it in the past targeting different plugins as well. It might be a server configuration issue. In this case, WP Rocket's table was the only one prompting the error though.

**Comment by piotrbak** [comment] 2022-09-09 12:12
@DahmaniAdame The problem with cache table that's not related to CLI is going to be fixed here:
https://github.com/wp-media/wp-rocket/issues/5351

**Comment by CrochetFeve0251** [comment] 2022-09-09 12:40
@DahmaniAdame @piotrbak  my idea when guarding the table is the fact that when we launch the preload queue from the cli it won't create the table if it is missing.
But then if we open the admin it will create it making us think the table was there.

I tried some scenarios and that for the moment the only one I can reproduce that issue.

**Comment by remyperona** [comment] 2022-09-23 15:03
I can't replicate the issue either

**Comment by piotrbak** [comment] 2022-09-25 17:56
@CrochetFeve0251 @Tabrisrp If the issue is the one described by Cyrille here:
https://github.com/wp-media/wp-rocket/issues/5361#issuecomment-1241928628

We could handle this on the CLI end maybe?

**Comment by piotrbak** [comment] 2022-09-29 11:54
@Tabrisrp What do you think about handling it inside the WP Rocket CLI itself? 🤔

**Comment by piotrbak** [comment] 2022-11-18 12:20
Moving it back to grooming as proposed solution prevents error from being triggered but doesn't resolve the initial problem. Maybe we could handle this on the CLI side? 🤔

**Comment by piotrbak** [comment] 2022-12-14 12:32
@simkoG This issue is most likely fixed as we look for the `init` hook while creating the tables, not `admin_init`. Your feedback will be very appreciated

**Comment by simkoG** [comment] 2022-12-15 12:37
@piotrbak I can't replicate the issue for now. It seems it is fixed. If not I'll write back to you.

**Closed as completed** 2022-12-15 14:51 UTC
Labels: type: bug, module: preload, can't reproduce, priority: medium, severity: major, wp-cli
