### ISSUE TITLE
3.9 - WooCommerce Multilingual compatibility change causing errors 50x

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3998] opened 2021-06-04 12:03 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.0.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The compatibility change that was introduced in WP Rocket 3.9:
https://github.com/wp-media/wp-rocket/issues/3418

is causing issues on customers' servers, e.g. error 502, when trying to open the products page.

WCML is trying to set the `wcml_client_currency` cookie numerous times by sending the `Set-Cookie` header.
In the case I worked on that took place [584 times](https://snippi.com/s/ykksqa8)! 

That caused an` ERR_RESPONSE_HEADERS_TOO_BIG` error in a ticket I debugged, and `error 502` in cases the customers reported.

When I commented out the following line in WP Rocket's compatibility code, the headers I mentioned previously were not sent, and the issue wasn't there:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/3rd-party/plugins/ecommerce/woocommerce-multilingual.php#L15

**To Reproduce**

1. Use WP Rocket 3.9.
2. Install WooCommerce Multilingual.
3. Check the headers for the HTML file. They should have several references of `Set-Cookie`.

**Expected behavior**

No error 50x or similar should occur when WP Rocket is used with WCML.

**Additional context**

 @piotrbak [suggested](https://wp-media.slack.com/archives/C43T1AYMQ/p1622800555211700?thread_ts=1622540018.164300&cid=C43T1AYMQ) we open this issue to discuss if there is anything we should be doing on our side.

**Slack thread:** https://wp-media.slack.com/archives/C43T1AYMQ/p1622540018164300

**Tickets:**
https://secure.helpscout.net/conversation/1526046602/267321
https://secure.helpscout.net/conversation/1531446262/268694
https://secure.helpscout.net/conversation/1531659256/268726

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by strategio** [comment] 2021-06-04 14:25
Thanks for pinging me @piotrbak.

It looks like we have something to improve on the way we deal with cookies.
However, I could not reproduce such a big problem locally. Indeed I have some duplicated header (14), but not as much as reported by the customer (584).

As a short-term workaround, I think commenting out `add_filter( 'wcml_user_store_strategy', 'rocket_wcml_use_cookie_storage', 10, 2 ); ` is the right solution. Or if he prefers to patch WCML, he can just edit https://git.onthegosystems.com/glue-plugins/wpml/woocommerce-multilingual/-/blob/4.11.5/classes/User/Store/Store.php#L47 and replace `apply_filters( 'wcml_user_store_strategy', 'wc-session', $key )` with `'wc-session'`.

Anyway, the counterpart code required to fix all the compatibility issues will come in WCML 4.12 which is not expected before July.

I will create an internal ticket so that we can improve our cookie handling.

**Comment by vmanthos** [comment] 2021-06-04 15:24
@strategio To clarify this, the number (584) I got was the product of the number of products on the site I debugged, and the number of languages there.

I'm guessing you have a small number of products on your local site, and this shouldn't cause a notable issue there, contrary to what happened on our common customers sites.

**Comment by strategio** [comment] 2021-06-04 17:29
Thanks @vmanthos!

I believe it's an issue with WPML Core plugin. I already prepared a fix there but I have no schedule for the next WPML version yet. Maybe we'll also add a temporary patch inside WCML.

For now, I'll let you suggest the short-term workaround.

**Comment by NataliaDrause** [comment] 2021-06-06 05:44
Related: https://secure.helpscout.net/conversation/1529829505/268232

**Comment by strategio** [comment] 2021-06-07 16:28
FYI, we added a fix in WPML Core and we are planning to release WPML 4.4.11 in the coming days (but we do not have an official date yet).

**Comment by iCaspar** [comment] 2021-06-07 20:31
Grooming Notes:

### Reproduced ✅ 

### Root Cause
Per the discussion above, returning cookie on the `wcml_user_store_strategy` filter causes WCML to generate a cookie every time the filter is called (apparently a lot of times with many products/languages) resulting in the possible header size overflow.

### Fix
Remove the Rocket filter. That said, if we remove the filter will be unable to properly resolve the current language/currency in the cached version.
Thanks to @strategio we have an advance copy of the proposed WCML fix, and can confirm that it does resolve the issue.

### Effort ✅ 
`[XS]` -- but with side effects.

### Recommend:
Add `wontfix` here and allow the better solution to be implemented in the WCML update. Meanwhile, the above mentioned work-arounds can be given to customers.

**Comment by iCaspar** [comment] 2021-06-07 20:38
After discussion w/ @Tabrisrp, moving this to `Blocked` -- Keeping it open for now in case we get close to our next release before WPML does -- we can implement this as a temporary solution if needed.

**Comment by NataliaDrause** [comment] 2021-06-10 09:15
Related ticket: https://secure.helpscout.net/conversation/1525910893/267257/

**Comment by NataliaDrause** [comment] 2021-06-17 12:10
Related: https://secure.helpscout.net/conversation/1546043861/272337/

**Comment by iCaspar** [comment] 2021-06-18 15:05
After some discussion with @wp-media/php team, we are going to implement this by _temporarily_ commenting out the filter on our end, until WCML releases the fix for the multiple cookie generation expected on their next release. We'll open a new issue to revert this change after that fix/release happens.

**Closed as completed** 2021-06-18 16:02 UTC
Labels: type: bug, priority: 🔥critical, 3rd party compatibility, effort: [XS], severity: major
