### ISSUE TITLE
WPForms compatibility with Remove Unused CSS (missing style for hidden field)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5179] opened 2022-06-23 10:44 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WPForms is used with Cleantalk (a spam protection plugin), the following hidden field is added to forms: 

```
<input id="apbct__email_id__wp_wpforms" class="apbct__email_id__wp_wpforms" autocomplete="off" name="apbct__email_id__wp_wpforms" type="text" size="30" maxlength="200">
<style> #apbct__email_id__wp_wpforms { display: none !important; } </style>
```

RUCSS doesn't pick up the `#apbct__email_id__wp_wpforms` selector. 

Preserving the inline style using `rocket_rucss_inline_content_exclusions` fixes the issue.

**To Reproduce**
1. Used WPForms with CleanTalk
2. Enable RUCSS
3. See error

**Expected behavior**
We should pick up all styles related to the form. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1919965436/348394/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2022-06-23 11:29
@DahmaniAdame The regular safelisting doesn't work, right?

This array was designed to handle mostly the dynamic CSS classes. Do we know why this CSS is not picked up?

**Comment by DahmaniAdame** [comment] 2022-06-23 11:33
@piotrbak yes, the regular safelist doesn't work. 

> This array was designed to handle mostly the dynamic CSS classes.

I see. 

> Do we know why this CSS is not picked up?

Not yet. Waiting for @mostafa-hisham feedback. 

We discussed it here - https://wp-media.slack.com/archives/C029G1B5HD2/p1655978915394059

But since this wasn't generated consistently, I went ahead and added the PR. 

Let's pause the PR until we hear back from Mostafa.

**Comment by piotrbak** [comment] 2022-06-23 11:38
@DahmaniAdame Exactly, solving the problem at the root will allow us to improve the product and decrease the future problems related to the same issue.

**Comment by GeekPress** [comment] 2022-10-26 08:14
@piotrbak Can this be added to the next sprint? First we can check why the selector isn't grabbed, and if we don't know why, let's use the back-end to exclude it.

**Comment by piotrbak** [comment] 2023-04-14 12:50
@DahmaniAdame Looks like they changed a bit the way how it works. Seems like we're able to detect it correctly now:
![image](https://user-images.githubusercontent.com/26767037/232048238-3327b244-1412-48a7-a82b-af0518ff7642.png)

Closing it for now, we'll reopen if we have any more feedback

**Closed as completed by piotrbak** 2023-04-14 12:50 UTC
Labels: type: bug, type: enhancement, waiting for feedback, priority: medium, severity: moderate, module: remove unused css
