### ISSUE TITLE
[WIP] Possible conflict with Woocommerce 4.4.0

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3003] opened 2020-08-18 16:02 UTC
We're receiving tickets from customers having a fatal error after updating Woocommerce to 4.4.0.
Still investigating this. According to Remy, it looks like they are using the same container package as us, but not the same version, they are on the new one that requires PHP 7 and that includes breaking changes.

Errors are similar to this:
`Fatal error: Declaration of League\Container\ImmutableContainerAwareTrait::getContainer() must be compatible with League\Container\Argument\ArgumentResolverTrait::getContainer(): Psr\Container\ContainerInterface in /home/446954.cloudwaysapps.com/krxgzndejz/public_html/wp-content/plugins/wp-rocket/vendor/league/container/src/Inflector/Inflector.php on line 32`

**Comment by Tabrisrp** [comment] 2020-08-18 16:06
WooCommerce 4.4 started to use the same container package as us: https://github.com/woocommerce/woocommerce/blob/b3097dbae6533efd569be95c20076a68bc146714/composer.json#L14

But they are using version 3, which is only compatible with PHP 7, while we still use version 2 (for now).

Composer being what it is, only one version of the package is loaded, during the runtime, and Since version 2 & 3 of the container are not compatible, it's preventing our code from running as expected.

**Comment by MrGKanev** [comment] 2020-08-18 16:36
Same problem with 7 clients. Any workaround except stopping the plugin?

**Comment by 101sam** [comment] 2020-08-18 17:00
Yep got it also on all my sites, just disable until new release

**Comment by MrGKanev** [comment] 2020-08-18 17:02
There is a [PR about it.](https://github.com/wp-media/wp-rocket/pull/3004/files) Hopefully, it can be merged soon.

**Comment by joshlcomstock** [comment] 2020-08-18 17:52
Same. 20+ client sites affected.

**Comment by iCaspar** [comment] 2020-08-18 17:57
PR is now in QA. Making sure we don't break anything else or have any regressions. Once we can confirm it's all good, we'll be releasing.

**Comment by hellofromtonya** [comment] 2020-08-18 18:14
Hello @MrGKanev @101sam @joshlcomstock,

WooCommerce released 4.4 earlier today which included changing the container (League Container) to a [PHP 7 only version](https://packagist.org/packages/league/container#3.3.1). Rocket also uses the League Container; however, we use a PHP 5.6 compatible version.

The fatal error occurs when either plugin loads the container first. How? Each expects a particular version.

The 3.6.4 fix that's in QA right now will be released today...very shortly. 

What did we change? 

1. The Container version we need is now packaged inside of Rocket's Engine (not loaded via Composer).
2. Th namespaces for it are renamed. 

How does this fix the problem?

1. WooCommerce uses the `League\Container` classes, traits, etc.
2. Rocket now uses the `WP_Rocket\Engine\Container` - which is a copy of the League  Container files ... renamed.

To PHP, these files of classes, traits, etc. are now different. No more fatal errors from this problem.

**Comment by ChrisSmoke1** [comment] 2020-08-18 18:25
@iCaspar @hellofromtonya 

Well, i cant downgrade wordpress/woocommerce anymore. Wp rocket now disabled during this fatal error but can i still update and re-activate it? Because it's not activated right now and if i remember well wp rocket can only we updated when it's enabled..

**Comment by ChrisSmoke1** [comment] 2020-08-18 18:29
support@wp-rocket.me is also not receiving any mails, Mail Delivery System - user over quota...

**Comment by joshlcomstock** [comment] 2020-08-18 18:29
I have just gone through and deactivated the WooCommerce 4.4.0 plugin and WP-Rocket is able to be reactivated without issue. Hopefully, WC releases their fix soon.

**Comment by hellofromtonya** [comment] 2020-08-18 18:30
>support@wp-rocket.me is also not receiving any mails, Mail Delivery System - user over quota...

Sorry about that @ChrisSmoke1. We cleared out the email server and emails are flowing again. Can you resend to us please? I apologize in advance for the inconvenience.

**Closed** 2020-08-18 18:31 UTC
Labels: 3rd party compatibility, priority: 🔥critical

**Comment by hellofromtonya** [comment] 2020-08-18 18:54
>Well, i cant downgrade wordpress/woocommerce anymore. Wp rocket now disabled during this fatal error but can i still update and re-activate it? Because it's not activated right now and if i remember well wp rocket can only be updated when it's enabled..

@ChrisSmoke1 Yes, Rocket needs to be activated in order to update it through the admin area. However, reactivating it now will cause a fatal error since WooCommerce is at version 4.4. on your site. 

What can you do? Please reach out to our Support team for guidance on how to load the Rocket 3.6.4.

**Comment by sknight80** [comment] 2020-08-18 19:40
I did this, I download the plugin and I uploaded to my webserver. That worked for me.

**Comment by hellofromtonya** [comment] 2020-08-18 19:42
@sknight80 That's wonderful!

**Comment by hellofromtonya** [comment] 2020-08-18 19:44
@MrGKanev @101sam @joshlcomstock 

We have released 3.6.4 with the fix for fatal error due to conflicts with WooCommerce 4.4 release. [Here is a document that guides you in how to update Rocket](https://docs.wp-rocket.me/article/14-updating-wp-rocket).

Thank you for your patience.

**Comment by MrGKanev** [comment] 2020-08-18 19:45
Yep, I saw it the moment it went up. Thanks! :)

**Comment by DanielRuf** [comment] 2020-08-18 20:05
Like described in https://github.com/woocommerce/woocommerce/issues/27384 namespaced / scoped dependencies should prevent such cases in the future:

Not sure if namespaced dependencies are used but this would prevent such issues in the longterm:

https://github.com/humbug/php-scoper
https://github.com/coenjacobs/mozart
https://github.com/TypistTech/imposter-plugin

So the composer autoloader will not use the wrong class / dependency with a different interface.

**Comment by hellofromtonya** [comment] 2020-08-18 20:11
Thanks @DanielRuf for sharing and looping the WC issue back here. Appreciate it. And yes, you're right. There are ways to encapsulate specific external dependencies. After this problem, we are talking that step.

**Comment by Mic2005** [comment] 2020-08-18 20:30
I want to thank WP-Rocket to sent also the "Important Information for WooCommerce Users" e-mail to all customers. Backup was done and just wanted to hit the upgrade option for wordpress Pfff ;-)
Recommendation? Just wait for next Woo upgrade/fix?

**Comment by Kipperlenny** [comment] 2020-08-18 20:33
FTP upload and re-activate WP Rocket 3.6.4 worked :-)

**Comment by PeterTemps** [comment] 2020-08-18 20:39
I still get the following error with new 3.6.4 version:

`/var/www/vhosts/starsmile.pl/httpdocs/wp-content/plugins/wp-rocket-3.6.4/inc/main.php. Komunikat błędu: Uncaught Error: Class 'WP_Rocket\Plugin' not found in /var/www/vhosts/starsmile.pl/httpdocs/wp-content/plugins/wp-rocket-3.6.4/inc/main.php:44 Stack trace: #0 /var/www/vhosts/starsmile.pl/httpdocs/wp-includes/class-wp-hook.php(287): rocket_init() #1 /var/www/vhosts/starsmile.pl/httpdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #2 /var/www/vhosts/starsmile.pl/httpdocs/wp-includes/plugin.php(478): WP_Hook->do_action() #3 /var/www/vhosts/starsmile.pl/httpdocs/wp-settings.php(409): do_action() #4 /var/www/vhosts/starsmile.pl/httpdocs/wp-config.php(114): require_once('/var/www/vhosts...') #5 /var/www/vhosts/starsmile.pl/httpdocs/wp-load.php(37): require_once('/var/www/vhosts...') #6 /var/www/vhosts/starsmile.pl/httpdocs/wp-login.php(12): require('/var/www/vhosts...') #7 {main} thrown`

**Comment by hellofromtonya** [comment] 2020-08-18 21:06
@PeterTemps That error is typically due to something with going wrong during the update process or missing or old composer files. I'd suggest using FTP/SSH to bring all of the Rocket 3.6.4 files over to your server. Check out the [FTP section of this doc](https://docs.wp-rocket.me/article/14-updating-wp-rocket).

**Comment by hellofromtonya** [comment] 2020-08-18 21:09
>Recommendation? Just wait for next Woo upgrade/fix?

@Mic2005 First of all, your welcome. What do we recommend? Update to WP Rocket 3.6.4 _before_ updating WooCommerce.

**Comment by PeterTemps** [comment] 2020-08-18 21:11
> @PeterTemps That error is typically due to something with going wrong during the update process or missing or old composer files. I'd suggest using FTP/SSH to bring all of the Rocket 3.6.4 files over to your server. Check out the [FTP section of this doc](https://docs.wp-rocket.me/article/14-updating-wp-rocket).

I'll try. Thanks!

**Comment by aniatanasova** [comment] 2020-08-18 22:22
i had the same issue. i installed now the newest wp rocket, it did activated but the site is working 10 times slower than without it...any suggestions?

**Comment by 101sam** [comment] 2020-08-18 22:29
We have a similar problem, but we are working with the NGINX server. What we saw that the new version remove all our settings, and we need to reconfigure all the parameters (we are still trying to figure out where, if its real problem or just configuration)

**Comment by hellofromtonya** [comment] 2020-08-18 22:52
@aniatanasova Hmm, I'm not sure why or what. But we'd like to dig into it further with you. Could you please open a Support ticket? We'll write you back to give you a safe way to share credentials with us.

**Comment by 101sam** [comment] 2020-08-18 22:53
> We have a similar problem, but we are working with the NGINX server. What we saw that the new version remove all our settings (in WordPress), and we need to reconfigure all the parameters (we are still trying to figure out where, if its real problem or just configuration)
After a few rounds, we found out that the only way to go back to the same speed is to set up the parameters manually and not import/export - why I'm not sure, but its work on two different sites using NGINX.

**Comment by hellofromtonya** [comment] 2020-08-18 22:56
@101sam Hmm that's interesting. The update "shouldn't" have removed settings. However, you experienced something that did just that. Hmm, I'm not sure why. But I'm definitely want to know. 

If you'd like, feel free to open a Support ticket. We can dig into with you.

**Comment by aniatanasova** [comment] 2020-08-18 23:03
> @aniatanasova Hmm, I'm not sure why or what. But we'd like to dig into it further with you. Could you please open a Support ticket? We'll write you back to give you a safe way to share credentials with us.
i did open a new issue and i also emailed at support.

**Comment by 101sam** [comment] 2020-08-18 23:25
> @101sam Hmm that's interesting. The update "shouldn't" have removed settings. However, you experienced something that did just that. Hmm, I'm not sure why. But I do want to know.
> 
> If you'd like, feel free to open a Support ticket. We can dig into with you.

It's happening on two different servers, so I'm sure we can replicate it. But I need time for the client to come down. The problem we had as soon as the crash happens, we couldn't return to WordPress. WP command line not works, we had to delete the wp-rocket folder. Maybe this was not the optimal way, but that's the only way we manage to recover the site from the crash.  We didn't want to login to the MySQL as WooCommerce has a database update during the update. It was risky to play with the wp_options at that stage.

**Comment by sknight80** [comment] 2020-08-19 01:55
@101sam what tool or tools did you use for speed measure?

**Comment by 101sam** [comment] 2020-08-19 13:11
We notice the speed changes from monitor we have on the site using:

https://gtmetrix.com

We verify it with:

https://developers.google.com/speed/pagespeed/insights/

To debug and verify its coming from we-rocket 
We add the following lines and use Query Monitor to verify its not other plugin or WooCommerce updates.
```
ini_set('display_errors','On');
ini_set('error_reporting', E_ALL );
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true);
define( 'WP_DEBUG_LOG', '/tmp/log/wp-errors.log' );
define( 'SCRIPT_DEBUG', true );
```

**Comment by hellofromtonya** [comment] 2020-08-19 13:13
@101sam Have you found it to be the settings in WP Rocket? Or something else?

**Comment by 101sam** [comment] 2020-08-19 13:42
Can't tell, it looks like a combination of situations:
Trying to update WooCommerece + crash happens, and  WooCommerece database update was on the way. 

Or one of our crontab tried to kick in the middle of updates or while we upgrade.

Or it was Wordfence blocking changes of code.
