### ISSUE TITLE
Remove critical CSS once the page is fully loaded

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#698] opened 2018-01-11 00:42 UTC
To prevent display issues, we should remove the critical CSS `<style>` block once the page is fully loaded, since at that point the stylesheets are loaded the critical CSS is no longer needed.

**Comment by GeekPress** [comment] 2020-03-06 17:03
I re-open this issue as it hasn't been implemented.

**Comment by GeekPress** [comment] 2020-05-12 22:12
Duplicate of https://github.com/wp-media/wp-rocket/issues/2635

**Closed by GeekPress** 2020-05-12 22:12 UTC
Labels: module: file optimization, needs: testing, priority: medium, type: enhancement
