### ISSUE TITLE
PHP Warning:  Attempt to read property "id" on bool in /wp-rocket/inc/Engine/Preload/Database/Queries/Cache.php on line 257

### ISSUE THREAD

**Issue by nowarah** [wp-media/wp-rocket#5455] opened 2022-09-20 12:28 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version 
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
----
this warning is fill out my erro_log PHP Warning:  Attempt to read property "id" on bool in /wp-rocket/inc/Engine/Preload/Database/Queries/Cache.php on line 257

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2022-09-20 12:36
Hello @Noarah thanks for creating the issue. It's already fixed in 3.12.1 version:
https://github.com/wp-media/wp-rocket/issues/5332

However, it's available for 25% of our customers. You'll soon receive the update. I'm going to close the issue, if the problem is still there after the update, please feel free to reopen #5332

**Closed as completed by piotrbak** 2022-09-20 12:36 UTC
