### ISSUE TITLE
RUCSS Compatibility with Flatsome's flickity slider

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5087] opened 2022-05-26 13:41 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Flickity slider is used in Flatsome, the following class needs to be safelisted:
`(.*).flickity-(.*)`

The condition file to trigger the safelist is this file:
`/wp-content/themes/flatsome/assets/js/chunk.vendors-slider.(.*).js`

However, this is not working when added as [compatibility in the RUCSS backend](https://github.com/wp-media/nodejs-treeshaker/issues/117), because the condition file Is added as a pre-fetched link at first, and then processed by Flatfsome to load and use the file.

Per @mostafa-hisham :
> if the <script> tag is added to the dom after you scroll to a certain section on the page in the sass server we stop the coverage once the page is loaded  we are not waiting for any events (scroll, click,....) after the load to make page loading process fast (under 10 sec)

So, the file is not detected by the SaaS and the safelist is not applied. 
Only, adding `(.*).flickity-(.*)` to the safelist via WP Rocket UI solves the issue.
 
**To Reproduce**
1. On a Flatsome site add a Flickity based slider
2. Generate Used CSS
3. Even with the backend compatibility, the sliders will be broken
4. Manually add the compatibility to the site Safelist
5. the Flickity classes will be preserved and the sliders will be fixed

**Expected behavior**
In our 3rd compatibility file, we should safelist `(.*).flickity-(.*)` using the `rocket_rucss_safelist` filter. 
To do that, we'll need to detect if the condition file is present: `/wp-content/themes/flatsome/assets/js/chunk.vendors-slider.(.*).js`

**Additional context**
Ticket:
https://secure.helpscout.net/conversation/1889616387/343840/

Slack Discussion:
https://wp-media.slack.com/archives/C029G1B5HD2/p1653470602619319

video about Scroll coverage: 
https://wp-media.slack.com/archives/C029G1B5HD2/p1653473849690979

RUCSS Backend Safelist
https://b.rucss.wp-rocket.me/rucss-safelist/edit/L3dwLWNvbnRlbnQvdGhlbWVzL2ZsYXRzb21lL2Fzc2V0cy9qcy9jaHVuay52ZW5kb3JzLXNsaWRlci4oLiopLmpz
https://github.com/wp-media/nodejs-treeshaker/issues/117

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by alfonso100** [comment] 2022-05-26 13:44
@piotrbak this one requires a file detection in PHP probably, and QA, so I can't create a PR

**Comment by jeawhanlee** [comment] 2022-06-10 09:46
### Reproduce the problem
Reproduced online

### Identify the root cause
In regards to what @mostafa-hisham stated when the issue was reported - we are not waiting for events to fire after the load.

### Scope a solution
I think I can see 2 solutions here.

**First one**
- We can add a second argument to the filter which is the buffer output $html.
https://github.com/wp-media/wp-rocket/blob/a512176d98b22459ac12177842ba49cd7aece961/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L216
- Then we hook the `rocket_rucss_safelist` filter to a new method here `WP_Rocket\ThirdParty\Themes\Flatsome::get_subscribed_events`
- In this new method we do a preg_match and get the link urls then check for this `/wp-content/themes/flatsome/assets/js/chunk.vendors-slider.`
- Then we append `.flickity-(.*)` to the safelist array if we find a match.
- Then probably update unit test here `WP_Rocket\Tests\Unit\inc\Engine\Optimization\RUCSS\Controller\Test_Treeshake`

**Second one**
- We can just hook the `rocket_rucss_safelist` filter to a new method here `WP_Rocket\ThirdParty\Themes\Flatsome::get_subscribed_events`
- Then we append `.flickity-(.*)` to the safelist array.

I think the first is more precise in regards to @alfonso100 expected behaviour  over the second that just safelists whether the file is present or not.

### Estimate the effort
[S] => First
[XS] => Second

What do you think @Tabrisrp @engahmeds3ed

**Comment by engahmeds3ed** [comment] 2022-06-14 09:20
@mostafa-hisham I believe this will be solved when you finish the part of DOM conditions, right?
I believe we need to wait till Mostafa finishes this issue so it'd be solved.

**Comment by mostafa-hisham** [comment] 2022-06-14 09:27
@engahmeds3ed 
it should be solved by backend DOM conditions
but if it is urgent we can do the third-party solution and then remove it when the backend DOM conditions solution is done and tested
also, we need to check the other third-party if it can be fixed by backend DOM conditions we should remove them
@piotrbak  what do you think?

**Comment by piotrbak** [comment] 2022-06-14 10:38
@mostafa-hisham @engahmeds3ed Yes, let's wait for the DOM conditions to be available.

**Comment by piotrbak** [comment] 2022-08-01 15:23
@alfonso100 This one can be solved with the backend now.

**Comment by piotrbak** [comment] 2022-08-04 16:48
Resolved here:
https://b.rucss.wp-rocket.me/rucss-safelist/edit/L2ZsYXRzb21lL2Fzc2V0cy9qcy9mbGF0c29tZS5qcyYmZGF0YS1mbGlja2l0eS1vcHRpb25zPQ%3D%3D

**Closed as completed by piotrbak** 2022-08-04 16:48 UTC
Labels: type: enhancement, 3rd party compatibility, priority: medium, effort: [S], module: remove unused css
