### ISSUE TITLE
PHP Warning:  Error while sending QUERY packet. when visit page after clearing cache 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3640] opened 2021-03-04 15:12 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Error while sending QUERY packet. added to the log file when visit post page after undo spammed comment and clear cache

**To Reproduce**
Precondition:
- WPR installed and activated 
- post with a spammed comment is cached

1. From Dashboard->comments -> undo spam action 
2. Open WPR settings -> clear cache
3. Hard refresh post 
4.  Check to debug.log

`PHP Warning:  Error while sending QUERY packet. PID=42714 in /var/www/rocketlabsqa.ovh/htdocs/wp-includes/wp-db.php on line 2056`

**Expected behavior**
No error in debug.log 

**Screencast**
https://user-images.githubusercontent.com/76941962/109983878-eda41d80-7d0b-11eb-9cb3-e0002b2594cf.mp4

**Additional context**
- Database at WPR optimizations are disabled
- Theme is Twenty twenty-one, the website is https://rocketlabsqa.ovh/
- Sometimes we need to clear the cache again with/without hard refresh after step 3 to see the error
- Question: shouldn't we automatically recreate cached files with undo spam action?

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment] 2021-03-22 17:46
After checking with @Mai-Saad we can't reproduce this now and we may try on rocketlabs OVH when it returns back, so I will close this issue for now and feel free opening it if you were able to reproduce it.

**Closed as completed by engahmeds3ed** 2021-03-22 17:46 UTC
Labels: type: bug, can't reproduce, priority: low, severity: minor
