### ISSUE TITLE
3.0 Alpha - Dashboard - Refresh Button

### ISSUE THREAD

**Issue by edenpulse** [wp-media/wp-rocket#845] opened 2018-03-14 09:46 UTC
Refresh button should have some improvements. 

- :Hover should be blue, not orange
- On Ajax Requests Success, we should replace the "refresh icon" with a "success icon" ✅ quickly, to show the user it worked. (cross if failed)

**Comment by arunbasillal** [comment] 2018-03-14 13:05
Nice to have: Spin the refresh spinner during the Ajax Request so that the user knows its working and will naturally wait for the spinner to finish.

**Comment by Tabrisrp** [comment] 2018-03-14 13:45
duplicate of #809, you can transfer the comments there

**Closed by Tabrisrp** 2018-03-14 13:45 UTC
Labels: duplicate
