### ISSUE TITLE
New post (on publish) display JSON

### ISSUE THREAD

**Issue by mintaras** [wp-media/wp-rocket#708] opened 2018-01-16 17:44 UTC
Once in a while, more often then I would want, new published post on my blog shows some custom strange JSON code instead of post content. After a while it goes away. I have Googled it and there are 10 pages of sites with same issue.

My site: https://ibb.co/gYHexR
Other sites with same problem: https://ibb.co/ea2CHR

Is this is something you can help me out?

Thanks

**Comment by Tabrisrp** [comment] 2018-01-16 17:50
This is a known issue and duplicate of https://github.com/wp-media/wp-rocket/issues/529

You can add your case there if you like, any information can help us & Jetpack understand why it's happening

**Closed by Tabrisrp** 2018-01-16 17:50 UTC
Labels: duplicate
