### ISSUE TITLE
Trigger preload after terms or links are created/edited/deleted

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2513] opened 2020-04-02 22:24 UTC
We're clearing the whole cache in various scenarios, for example, when category term is updated, when the link is added or updated, and others:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/common/purge.php#L12-L17

After updating a single category term, the whole cache is purged and not preloaded.

**To Reproduce**
1. Go to the Post > Categories
2. Update category
3. Confirm that the whole cache was purged and not preloaded

**Expected behavior**
Clear only pages that are necessary or trigger the preload after the whole cache is purged.

Feedback from Jonathan: https://github.com/wp-media/wp-rocket/issues/2513#issuecomment-610793550

> We won't change the actual behavior, but we should trigger the preload after purging the cache.

**Comment by Tabrisrp** [comment] 2020-04-06 18:50
This is by design from the start:
- When a term or link is created/edited/deleted, we can't really know where it is used on the frontend of the site
- If we want to keep things up to date, our only choice is to clean the whole domain
- No preload is triggered on those actions, it never has been

@GeekPress @arunbasillal Do we want to change the behaviour there? If yes, what are the expectations?

Also to note that changing any of this will require to change our related helper plugin, and most likely break backward compatibility with users already having the helper.

**Comment by GeekPress** [comment] 2020-04-08 07:17
@piotrbak As @Tabrisrp explained, we can't really know where the terms are located. This is why we decided to clear the whole cache.

@Tabrisrp We won't change the actual before, but we should trigger the preload after the purging the cache.

**Comment by jazir5** [comment] 2020-04-18 03:05
Chiming in here, i've noticed the preload feature being very inconsistently triggered and this explains why, definitely would be useful to have preload auto-triggered when changes such as the above are made.

**Comment by crystinutzaa** [comment] 2020-04-27 08:40
**Reproduce the issue** ✅ 
Reproduced on my local test site

**Identify the root cause** ✅ 
The root cause is related to Preload not triggered when `rocket_clean_domain()` function runs.

**Scope a solution** ✅ 
The solution will be to hook the Preload on `after_rocket_clean_domain` :
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/functions/files.php#L874
so that both Desktop and Mobile Preload runs when `rocket_clean_domain()` is called.

**Estimate the effort** ✅ 
Probably @Screenfeed can provide much more insight but I assume it should be an [S]

**Comment by Tabrisrp** [comment] 2020-04-27 13:17
I think we have to be careful with preload, especially hooking it on `after_rocket_clean_domain` is a risk of the preload running way too much and overloading the server.

**Comment by crystinutzaa** [comment] 2020-04-27 19:00
@Tabrisrp , @hellofromtonya I am working on a diagram on how Preload functionality is currently working and how it should work. 
I think at this point this task should be postponed until we define the diagram and the flow of preload / partial preload. 

At this point, if Preload is enabled and all Rocket cache got cleaned, I think that Preload needs to kick in, however this sounds like it may have unexpected results.

**Comment by hellofromtonya** [comment] 2020-04-27 19:39
@crystinutzaa Let's revisit this user story (issue) once you get the diagram and workflow done.

**Comment by hellofromtonya** [comment] 2020-05-26 11:28
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by piotrbak** [comment] 2022-06-21 10:27
The preload is triggered correctly in the new version.

**Closed** 2022-08-30 11:24 UTC
Labels: type: enhancement, module: preload, priority: medium, status: blocked, effort: [S], future
