### ISSUE TITLE
[WIP] Images appear smaller on iPhone devices when Lazyload is enabled, and Foodie Pro theme is used

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2897] opened 2020-07-17 18:55 UTC
[under investigation]

We have noticed some tickets where the images load smaller on iPhones when LazyLoad is enabled. Refreshing the window makes it load fine again.
Switching to a different lazyload script solves the issue.

These sites are using the **[Foodie Pro](https://secure.helpscout.net/conversation/1178526380/168734/)** theme. 

It can be replicated only using a real device. It will load fine if using BrowserStack for example.

This issue only seems to be affecting posts that have been written using the block editor. 
The images of any posts written in the classic editor seem to load fine. 

This is how it looks: https://jmp.sh/Ndb3hgy
A vide, sent by a customer: https://drive.google.com/file/d/11LEETynIOdwIy9P6es2nmfXWpOlPHZBk/view

**Some tickets:** 
https://secure.helpscout.net/conversation/1219007597/178938?folderId=2683093
https://secure.helpscout.net/conversation/1178354096/168696?folderId=2675957 
https://secure.helpscout.net/conversation/1219007597/178938?folderId=2683093
https://secure.helpscout.net/conversation/1211327210/176817/
https://secure.helpscout.net/conversation/1201325622/174687?folderId=2415573

**Comment by NataliaDrause** [comment] 2020-07-22 07:34
One more related ticket. https://secure.helpscout.net/conversation/1231750566/181667/
This is a different food blog theme, but still by the Genesis Framework.
Theme Name: Seasoned Pro. Version: 4.2.3

**Comment by feastdesignco** [comment] 2020-07-22 11:48
A customer linked us to this page - we're the developers for Foodie Pro + Seasoned Pro.

Has anything been identified as causing this issue?

**Comment by feastdesignco** [comment] 2020-07-27 11:02
Just as a follow up, we've been told that one customer had this resolved by adding: 
@media only screen and (max-width: 499px) {
.entry-content .dpsp-pin-it-wrapper {
width: 100% !important;
}}

This appears to be related to another plugin and not our theme specifically.

**Comment by juricazuanovic** [comment] 2020-07-29 12:22
If I'm not mistaken, the CSS code mentioned above is for overriding CSS from [Grow by Mediavine plugin (ex Social pug)](https://wordpress.org/plugins/social-pug/).

**Comment by feastdesignco** [comment] 2020-07-29 12:26
> If I'm not mistaken, the CSS code mentioned above is for overriding CSS from [Grow by Mediavine plugin (ex Social pug)](https://wordpress.org/plugins/social-pug/).

Correct. Could it be the case that the cause of the incorrectly loading thumbnails is the Grow plugin? Was this looked into?

I'm not seeing any live sites with this issue and haven't been looped in on the root cause of this issue. We'd like to push out a fix for it.

**Comment by alfonso100** [comment] 2020-07-29 21:35
Thank you for your input on this case. 
For one of our customers, the fix hasn't worked as expected. 
But we will continue testing this to see if we can narrow it to **Grow by Mediavine plugin** (ex Social pug).

I will report back if can find the exact cause of this. 🙏

**Comment by NataliaDrause** [comment] 2020-07-30 08:06
One of our customer confirmed that they don't use **Grow by Mediavine plugin**, but still have the issue with the images.

**Comment by feastdesignco** [comment] 2020-07-31 09:12
> One of our customer confirmed that they don't use **Grow by Mediavine plugin**, but still have the issue with the images.

Note that "Grow" is also known as "Social Pug" - can you confirm that this plugin is also not installed?

Follow up with another case we're looking into: https://umamigirl.com/slow-roasted-salmon/

In this case, they're using WebP. Is there a consistent pattern of the users with this problem using WebP images?

**Comment by NataliaDrause** [comment] 2020-08-02 07:05
Sorry for not specifying this, but neither Grow by Mediavine plugin, nor Social Pug are used by the customer.

They also let me know that they don't use WebP images.

**Comment by feastdesignco** [comment] 2020-08-02 16:01
Another customer experiencing this issue: https://spicecravings.com/

This is becoming a serious problem. Can you please escalate this to a developer and expedite tracking this issue down?

I will pay for the developer hours if needed.

**Comment by NataliaDrause** [comment] 2020-08-03 06:50
Plugins list used by one of our customers. Sharing with the permission of the customer in case this can be helpful to find the affecting one:

- vaultpress/vaultpress.php
- akismet/akismet.php
- aweber-web-form-widget/aweber.php
- beautiful-and-responsive-cookie-consent/nsc_bar-cookie-consent.php NOT IN USE AT TIME OF PROBLEM
- broken-link-checker/broken-link-checker.php
- code-snippets/code-snippets.php
- customizer-export-import/customizer-export-import.php
- feast-plugin/feast-plugin.php
- genesis-enews-extended/plugin.php
- genesis-simple-hooks/plugin.php
- imagify/imagify.php
- pushalert-web-push-notifications/pushalert.php
- really-simple-ssl/rlrsssl-really-simple-ssl.php
- regenerate-thumbnails/regenerate-thumbnails.php
- simple-social-icons/simple-social-icons.php
- tasty-pins/tasty-pins.php
- widget-importer-exporter/widget-importer-exporter.php
- wordpress-seo-premium/wp-seo-premium.php
- wp-cloudflare-page-cache/wp-cloudflare-super-page-cache.php
- wp-file-manager/file_folder_manager.php
- wp-lazy-loading/wp-lazy-loading.php -- this is a current replacement for WP Rocket LazyLoad feature.
- wp-recipe-maker-premium/wp-recipe-maker-premium.php
- wp-recipe-maker/wp-recipe-maker.php
- wp-rocket/wp-rocket.php

**Comment by NataliaDrause** [comment] 2020-08-10 15:59
Piotr was able to fix the issue by adding this code to CSS: 
`@media only screen and (max-width: 499px) { .entry-content .wp-block-image { width: 100% !important; }}`

If this code doesn't break anything in the theme, the theme can be updated accordingly.

**Comment by feastdesignco** [comment] 2020-08-11 20:07
Thanks - we'll push this out and see if there's any further issues.

**Comment by NataliaDrause** [comment] 2021-03-02 09:22
The issue is likely resolved. I am verifying with the customer:
https://secure.helpscout.net/conversation/1437045479/242624/

**Comment by NataliaDrause** [comment] 2021-03-04 07:00
The issue is resolved by the theme: 
https://secure.helpscout.net/conversation/1437045479/242624?folderId=3864740

**Closed by NataliaDrause** 2021-03-04 07:00 UTC
Labels: 3rd party compatibility, status: work in progress
