### ISSUE TITLE
3.0 Alpha - All tabs - Need Help Button:Hover

### ISSUE THREAD

**Issue by edenpulse** [wp-media/wp-rocket#844] opened 2018-03-14 09:37 UTC
Hover on Need Help Buttons should be : 

<img width="258" alt="capture d ecran 2018-03-14 a 10 36 18" src="https://user-images.githubusercontent.com/433393/37394249-976e1768-2773-11e8-8ef0-be602ba8ba0a.png">

**Comment by Tabrisrp** [comment] 2018-03-14 13:46
duplicate of #826 this can't be done with Beacon API 1.0

**Closed by Tabrisrp** 2018-03-14 13:46 UTC
Labels: duplicate
