### ISSUE TITLE
Fatal error caused by Avada compatibility + TranslatePress

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5700] opened 2023-01-19 07:16 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The following error is thrown when using Avada `7.9.1` + TranslatePress + enabling RUCSS 

```
[WP STAGING Shutdown Function][E_ERROR][2023-01-18 22:55:30] Uncaught ArgumentCountError: 3 arguments are required, 2 given in /wp-content/themes/Avada/includes/metaboxes/tabs/tab_page.php:69
Stack trace:
#0 /wp-content/themes/Avada/includes/metaboxes/tabs/tab_page.php(69): sprintf('#!trpst#trp-get...', '#!trpst#trp-get...')
#1 /wp-content/themes/Avada/includes/metaboxes/metaboxes.php(269): avada_page_options_tab_page(Array)
#2 /wp-content/themes/Avada/includes/class-fusion-dynamic-css-from-options.php(160): PyreThemeFrameworkMetaboxes->get_options()
#3 /wp-content/themes/Avada/includes/class-fusion-dynamic-css-from-options.php(126): Fusion_Dynamic_CSS_From_Options->init('PO')
#4 /wp-includes/class-wp-hook.php(308): Fusion_Dynamic_CSS_From_Options->dynamic_css_array_filter_po(Array)
#5 /wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#6 /wp-content/themes/Avada/includes/lib/inc/class-fusion-dynamic-css-helpers.php(390): apply_filters('fusion_dynamic_...', Array)
#7 /wp-content/themes/Avada/includes/lib/inc/class-fusion-dynamic-css.php(306): Fusion_Dynamic_CSS_Helpers->get_dynamic_css()
#8 /wp-content/themes/Avada/includes/lib/inc/class-fusion-dynamic-css-helpers.php(252): Fusion_Dynamic_CSS->generate_final_css()
#9 /wp-content/themes/Avada/includes/lib/inc/class-fusion-dynamic-css.php(361): Fusion_Dynamic_CSS_Helpers->dynamic_css_cached()
#10 /wp-content/themes/Avada/includes/lib/inc/class-fusion-dynamic-css-inline.php(109): Fusion_Dynamic_CSS->make_css()
#11 /wp-includes/class-wp-hook.php(308): Fusion_Dynamic_CSS_Inline->add_inline_css_wp_head('')
#12 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#13 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#14 /wp-includes/general-template.php(3043): do_action('wp_head')
#15 /wp-content/themes/Avada/header.php(21): wp_head()
#16 /wp-includes/template.php(783): require_once('/home/staging...')
#17 /wp-includes/template.php(718): load_template('/home/staging...', true, Array)
#18 /wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#19 /wp-content/themes/Avada/100-width.php(15): get_header()
#20 /wp-includes/template-loader.php(106): include('/home/staging...')
#21 /wp-blog-header.php(19): require_once('/home/staging...')
#22 /index.php(17): require('/home/staging...')
#23 {main}
  thrown - File: /wp-content/themes/Avada/includes/metaboxes/tabs/tab_page.php Line: 69 | Is it Fatal Error? Yes | Is it Thrown by WP STAGING? No
```

There is no direct link to WP Rocket, but commenting the following line fixes the issue in the compatibility file: 

https://github.com/wp-media/wp-rocket/blob/0ba299ba30f3cedf8601f8e29d6b8ddc5f256a0f/inc/ThirdParty/Themes/Avada.php#L42

Which refers to the method where we deactivate the CSS and JS compilers: 

https://github.com/wp-media/wp-rocket/blob/0ba299ba30f3cedf8601f8e29d6b8ddc5f256a0f/inc/ThirdParty/Themes/Avada.php#L144-L148

**To Reproduce**
1. Use Avada + TranslatePress
2. Enable RUCSS
3. Visit a translated page

**Expected behavior**
Avada + TranslatePress + RUCSS should work with no issues out of the box. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2102640474/390146/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment] 2023-01-20 05:40
The customer will leave the staging site active until the issue is fixed. 
Instructions on testing on staging are left on the ticket as a note.

**Comment by mostafa-hisham** [comment] 2023-01-20 08:14
the translation of the string inside the sprint function had an unescaped `%` in it (**100%**)
in this file `/wp-content/themes/Avada/includes/metaboxes/tabs/tab_page.php`

``` Controla el color de fondo de la página. Cuando el valor del color se establece en cualquier valor inferior a 100% de opacidad, el color se superpondrá a la imagen de fondo si se carga una. Código hexadecimal, por ejemplo: #000. %s```

**Comment by DahmaniAdame** [comment] 2023-01-20 09:59
Found the culprit: Defining `define('FUSION_DISABLE_COMPILERS', true);` breaks TranslatePress even if WP Rocket is not activated.

There is nothing that can be done on our end to prevent it if the constant has to be changed, in our case, on the compatibility file when Remove Unused CSS is activated to prevent conflicts. 

I guess the most we can do is add a notification to warn users about it when TranslatePress + Avada + Remove Unused CSS are activated.

**Comment by piotrbak** [comment] 2023-01-25 15:30
@DahmaniAdame I'm not able to reproduce it on our Mega Avada website. I added translated pages here:
`/avada/fr/translation-test`
`/avada/translation-test`

Please note, that Avada is 7.9.2. Are there any additional steps? 🤔

**Comment by DahmaniAdame** [comment] 2023-01-26 08:01
@piotrbak I couldn't replicate it on Mega Avada. 
Both sites run the same version of Avada + TranslatePress. 
The difference is that the site has the paid version of TranslatePress and an additional addon on Avada. 
The staging is still up and the issue is still there if you want to have a look.

> Are there any additional steps?

The only detail that I didn't mention is that it needs to be a sub-page and not the translation root page. But that doesn't trigger the issue on Mega Avada though.

**Comment by piotrbak** [comment] 2023-08-01 13:42
There are no tickets related to this problem at all, going to close it. Feel free to reopen if it reappears

**Closed as completed by piotrbak** 2023-08-01 13:42 UTC
Labels: type: bug, waiting for feedback, 3rd party compatibility, can't reproduce, priority: medium, severity: moderate
