### ISSUE TITLE
v3.7.2 Does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by jmslbam** [wp-media/wp-rocket#3182] opened 2020-10-05 10:17 UTC
**Describe the bug**
Running `composer install --optimize-autoloader --no-scripts --no-dev` fails when running composer install with --optimize-autoloader flag.

**To Reproduce**
1. composer require at least WP Rocket 3.7.2
2. then run ` composer install --optimize-autoloader --no-scripts --no-dev`
3. Watch the errors

**Expected behavior**
Succesfull composer install.

**Additional context**
```
Deprecation Notice: Class WP_Rocket\Subscriber\Admin\Settings\Beacon_Subscriber located in ./public/wp-content/plugins/wp-rocket/inc/deprecated/subscriber/admin/Settings/class-beacon-subscriber.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///Users/digitalpassenger/dotfiles/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_Rocket\Subscriber\Optimization\Minify_HTML_Subscriber located in ./public/wp-content/plugins/wp-rocket/inc/deprecated/subscriber/admin/Optimization/class-minify-html-subscriber.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///Users/digitalpassenger/dotfiles/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_Rocket\Engine\Optimization\QueryString\RemoveSubscriber located in ./public/wp-content/plugins/wp-rocket/inc/deprecated/Engine/Optimization/QueryString/RemoveSubscriber.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///Users/digitalpassenger/dotfiles/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_Rocket\Engine\Optimization\QueryString\Remove located in ./public/wp-content/plugins/wp-rocket/inc/deprecated/Engine/Optimization/QueryString/Remove.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///Users/digitalpassenger/dotfiles/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment] 2020-10-05 11:00
@Tabrisrp Would you please take a look and comment?

**Comment by Tabrisrp** [comment] 2020-10-06 15:55
It can be fixed by updating our autoloader configuration in `composer.json`

**Comment by ethanclevenger91** [comment] 2020-11-16 18:41
Is WP Rocket actually dependent on the autoloader working properly? Or can we safely update to Composer 2.0 w/o breaking things?

**Comment by Tabrisrp** [comment] 2020-11-18 14:40
### Reproduce the problem
Reproduced with the current master

### Identify the root cause
Those classes are not following the PSR-4 autoloading standard, because their namespace and actual filepaths don't match

### Scope a solution
In `composer.json`, add to the `autoload/classmap` section the following `inc/deprecated`. This will let those classes be handled by the classmap manager instead of the PSR-4 manager in composer, and avoid the notice.

### Estimate the effort
Effort `[XS]`

**Closed** 2020-11-25 20:24 UTC
Labels: effort: [XS], priority: low, type: bug
