### ISSUE TITLE
Cached requests to the REST API should be saved as json

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#291] opened 2017-01-06 22:15 UTC
It's currently saved as HTML, and returning an incorrect content-type which is breaking some applications expecting an application/json type strictly.

**Comment by iruzevic** [comment] 2019-01-14 16:22
Are there any updates on this ticket?

**Comment by hippocampestudio** [comment] 2020-04-15 08:56
I have the same problem. Is there a solution ?

**Comment by GeekPress** [comment] 2020-04-21 19:56
Duplicate of 2542

**Comment by GeekPress** [comment] 2020-04-21 19:56
Duplicate of #2542

**Closed by GeekPress** 2020-04-21 19:56 UTC
Labels: module: cache, severity: minor, type: enhancement
