### ISSUE TITLE
3.0 Alpha - Add-on - Modify Options does not take us to Cloudflare sub-tab

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/wp-rocket#848] opened 2018-03-14 10:07 UTC
No matter CF options is on/off Modify options button is visible and it does not take us to Cloudflare sub-tab section - https://app.hyfy.io/share/abhHyLBt35n/

**Comment by Tabrisrp** [comment] 2018-03-14 13:43
duplicate of #823

**Closed by Tabrisrp** 2018-03-14 13:43 UTC
Labels: duplicate
