### ISSUE TITLE
Feature Request - Allow WP-Rocket to run on woocommerce pages such as cart and checkout by disabling caching on those pages so we can use the other optimization functions of WP Rocket

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4275] opened 2021-08-23 04:38 UTC
**Is your feature request related to a problem? Please describe.**
I would love it if you could implement changes that would allow wp-rocket to work on the checkout page, except with caching disabled so I can benefit from all the other features.

**Describe the solution you'd like**

That way I could still benefit from minification, concentation, lazyload, delay js. 

The checkout is the most important page in my store because it's the actual conversion point. I would make more sales immediately if I could make the checkout page faster.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by remyperona** [comment] 2021-08-23 18:11
Duplicate of #2713

**Closed as completed by remyperona** 2021-08-23 18:11 UTC
Labels: duplicate
