### ISSUE TITLE
Helper plugins no longer work inconjunction with eachother. No cache for admins and common cache for all users

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [wp-media/wp-rocket#7179] opened 2024-12-11 10:06 UTC
EDITED
**Describe the bug**

We are using the following unoffical helper plugin to server the same cache to both logged in users and guest users.
https://github.com/sanderdekroon/WP-Rocket-Guest-Cache

It relies on 2 official helper plugins for wp-rocket

No cache for admins
Common cache for all users

Unfortunately we now get the following warning message:
![Image](https://github.com/user-attachments/assets/c6d743d1-4378-489b-af36-8c4a1833977e)

This means that using the helper plugin, admins are being served the same cache as guests because the two helper plugins are not compatible anymore.

Not only this but admins then dont see the black dashboard bar at the top of the page.

**Can you provide either an update so these plugins can work in conjunction with eachother again?**

OR

**A code snippet so that they work in conjunction with eachother again?**

We are going to use this setup inconjunction with the disable cache clearing official helper plugin and then dynamically update our stock and pricing using Ajax. Therefore the site is 100% cached 100% of the time.

Due to the scale of our site the cache clearing to update stock values is too agressive that wp-rocket is not scalable.
On large sites where multiple orders are placed per minute or every 10 minutes - **It means no user is seeing the cache causing TTFB score issues and a complete fail in pagespeed insights.**

So by allowing signed in users to have the same cache as guests but dynamically grab the price and stock we are making our site perminently cached.

**Please can you look at the questions in bold and provide a solution?**

Otherwise we are going to have to look for another cachinge plugin or caching system to deal with this problem.

**Comment by thinkjarvisdesignandmarketing** [comment] 2024-12-11 10:09
Please consider this a high priority issue.

**Comment by piotrbak** [comment] 2024-12-11 10:21
Hello @thinkjarvisdesignandmarketing this is a duplicate of:
https://github.com/wp-media/wp-rocket/issues/1997

Have you already contacted our support team so we could check if we can provide you with the helper plugin solution?

**Closed as not planned by piotrbak** 2024-12-11 10:21 UTC

**Comment by thinkjarvisdesignandmarketing** [comment] 2024-12-11 10:29
@piotrbak 
Why have you closed the issue? This is not the same issue as #1997 

I have not contacted support because I thought this was the place to raise the issue.

Are you asking me to contact support with this issue? If so please ask me to rather than closing the issue.

Please re-open the issue it is not a duplicate.

**Comment by thinkjarvisdesignandmarketing** [comment] 2024-12-11 12:37
@piotrbak 
Having had a response on one of my other questions I now understand how these two plugins work with eachother.

It appears that the no cache for admins is designed to stop admins getting their own user cache not specifically stopping admins from seeing any cache. So using the solution created here https://github.com/sanderdekroon/WP-Rocket-Guest-Cache works how it does.

I had assumed a plugin called no cache for admins would literally be that. But its not its actually no cache for admins - when user cache is enabled.

Appologies for getting irritated by the closing of this issue within minutes of me raising it.

**Comment by piotrbak** [comment] 2024-12-11 12:39
@thinkjarvisdesignandmarketing The Support Team is the correct place to contact in this situation. We'll check what we can do with the helpers. If there's an issue on the core side, we'll fix it. However, please keep in mind that the helper plugins are enhancing the core and we can't take responsability for the code written by 3rd-parties.

`This is not the same issue as https://github.com/wp-media/wp-rocket/issues/1997`
It's the same issue, it can be closed when implementing 1997.

**Comment by thinkjarvisdesignandmarketing** [comment] 2024-12-11 12:49
Thanks @piotrbak 
I have raised the same messages via support but have no way of taking them back now. Doh.

When support investigate this hopefully they will see our closing comments!

Serving cache to logged in users has been vital on the site linked below because the queries are huge!
https://abalonegraphics.com/shop/clothing/t-shirts-polos-vests/t-shirts-clothing/womens-tridri-contrast-panel-performance-t-shirt/
The biggest one has 600 - 1000 variations that have to be grabbed into a grid. So without caching it literally takes 30 - 100 seconds per pageload.

We are looking to develop an add-on for our woocomemrce sites that dynamically refreshes the stock and pricing. So there is therefore no need to clear the cache at all. TTFB scores are all over the place on another site we manage that does £1m+ per year in sales. This is because of the order frequency and WP-Rocket clearing caches after each sale.

So this setup is a key part of keeping the site 100% cached for everyone.
