### ISSUE TITLE
CDN: Automatically exclude Quantcast /choice.js from CDN feature

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3933] opened 2021-05-20 09:36 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Our CDN feature replaces Quantcast /choice.js:
`var url = 'https://quantcast.mgr.consensu.org‘ .concat('/choice/', ‚xxxxxxxxxxx', '/', host, '/choice.js')
`
by:
`var url = 'https://quantcast.mgr.consensu.org‘ .concat('/choice/', ‚xxxxxxxxxxx', '/', host, ‚https://cdn.cname.com/choice.js')`

**Expected behavior**
This relative URL should be preserved.

**Additional context**
Some relative tickets: 
- https://secure.helpscout.net/conversation/1517489202/265037/
- https://secure.helpscout.net/conversation/1321309574/206105/
- https://secure.helpscout.net/conversation/1221480312/179554/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2021-05-20 10:21
Duplicate of #2849

@wp-media/php Do you confirm?

**Comment by remyperona** [comment] 2021-05-20 18:17
Yes I confirm, it's the same issue

**Closed as completed** 2023-06-06 11:45 UTC
Labels: type: bug, module: CDN, priority: low, severity: moderate
