### ISSUE TITLE
 PowerPress Feeds Getting Cached

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#62] opened 2016-07-06 14:05 UTC
Sample ticket: https://secure.helpscout.net/conversation/162671678/10426/?folderId=377611
Customer using PowerPress plugin says his feeds are cached. But, since WP Rocket 2.6, they shouldn't be.....

**Comment by arunbasillal** [comment] 2020-05-12 13:41
I tested this on our Mega site and the generated [feed url](http://mega.wp-rocket.me/feed/podcast/) didn't have any issues. It redirected to the latest podcast, hopefully that is by design. We also do not have any further reported cases for this on HelpScout. 

I recommend we close this one. (cc: @GeekPress)

**Comment by GeekPress** [comment] 2020-05-12 21:40
Closing this issue as recommended by @arunbasillal

**Closed by GeekPress** 2020-05-12 21:40 UTC
Labels: 3rd party compatibility, can't reproduce, module: cache, priority: low
