### ISSUE TITLE
minify lazyload script

### ISSUE THREAD

**Issue by shaytoder** [wp-media/wp-rocket#1792] opened 2019-06-12 15:28 UTC
Hi, 
the lazy load script (begins with <script>window.lazyLoadOptions) 
is NOT minified 
even if i minify the HTML, the lazy load script is probably insert after the html minification, so it's still not minified. 
please minify it yourself or at least give us a way to minify it. 

Thanks, 
Shay

**Comment by arunbasillal** [comment] 2019-07-02 11:58
Duplicate of #1804

**Closed** 2019-07-02 14:05 UTC
Labels: duplicate
