### ISSUE TITLE
Incorrect match of https://s.adroll.com/j/roundtrip.js by the CDN rewriting process

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3103] opened 2020-09-16 07:48 UTC
RocketCDN is rewriting

`<script async="true" type="text/javascript" src="https://s.adroll.com/j/roundtrip.js"></script>`

to:

`<script async="true" type="text/javascript" src="https://s.adroll.comhttps://xxxxxxx.rocketcdn.me/j/roundtrip.js"></script>`

Note the broken URL ".comhttps://"
Ticket: https://secure.helpscout.net/conversation/1282362308/194841/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by WordPresseur** [comment] 2021-04-16 09:57
Related ticket: https://secure.helpscout.net/conversation/1485260410/256529?folderId=4075497

**Comment by remyperona** [comment] 2021-11-24 20:25
I don't know how this issue happened for this one user, but I can't replicate it when using the same script and the CDN rewritting. The URL is not picked-up at all by the RegEx.

**Comment by piotrbak** [comment] 2022-05-31 15:44
Going to close this one, since we can't reproduce it and we don't have any negative feedback from customers.

**Closed by piotrbak** 2022-05-31 15:44 UTC
Labels: type: bug, module: CDN, can't reproduce, priority: low, severity: moderate
