### ISSUE TITLE
PHP 8.2.4 warnings

### ISSUE THREAD

**Issue by Asdrubale8888888** [wp-media/wp-rocket#5851] opened 2023-04-03 09:25 UTC
WP Rocket version: 3.13
WordPress version 6.2
PHP: 8.2.4

I tried to switch from php 7.4 to 8.2.4 and the following errors warnings:
In my opinion,  they depend on WP rocket.

`Warning: Undefined variable $rucss_status in /home/customer/www/xxx.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Admin/Settings/Page.php on line 599

Warning: Trying to access array offset on value of type null in /home/customer/www/xxx.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Admin/Settings/Page.php on line 599`

**Comment by jeawhanlee** [comment] 2023-04-03 15:34
@Asdrubale8888888 I'm not able to reproduce this problem, Any extra step taken aside the above will much appreciated.

**Comment by Asdrubale8888888** [comment] 2023-04-03 15:51
This is a screenshot of Page.php on line 599

https://postimg.cc/phQVJc3f

It can be useful?

**Comment by 0xWeverton** [comment] 2023-04-03 15:54
I also had this error too, to solve it I commented the line: 

```php
// if ( $rucss_status['disable'] ) {
// $css_section_helper[] = $rucss_status['text']; 
// }
```

and added: 
```php
if (isset($rucss_status) && is_array($rucss_status) && $rucss_status['disable']){ 
$css_section_helper[] = $rucss_status['text'];
 }
```

**Comment by Asdrubale8888888** [comment] 2023-04-04 08:29
> I also had this error too, to solve it I commented the line:
> 
> ```
> // if ( $rucss_status['disable'] ) {
> // $css_section_helper[] = $rucss_status['text']; 
> // }
> ```
> 
> and added:
> 
> ```
> if (isset($rucss_status) && is_array($rucss_status) && $rucss_status['disable']){ 
> $css_section_helper[] = $rucss_status['text'];
>  }
> ```

Thanks. I added the code you gave me, but nothing changed.
https://postimg.cc/LgphwgMK

**Comment by jeawhanlee** [comment] 2023-04-04 08:55
> > I also had this error too, to solve it I commented the line:
> > ```
> > // if ( $rucss_status['disable'] ) {
> > // $css_section_helper[] = $rucss_status['text']; 
> > // }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and added:
> > ```
> > if (isset($rucss_status) && is_array($rucss_status) && $rucss_status['disable']){ 
> > $css_section_helper[] = $rucss_status['text'];
> >  }
> > ```
> 
> Thanks. I added the code you gave me, but nothing changed. https://postimg.cc/LgphwgMK

@Asdrubale8888888 Please can I get a screenshot of 20 lines above Line 590 to see what you have there.

**Comment by Asdrubale8888888** [comment] 2023-04-04 08:59
> > > I also had this error too, to solve it I commented the line:
> > > ```
> > > // if ( $rucss_status['disable'] ) {
> > > // $css_section_helper[] = $rucss_status['text']; 
> > > // }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and added:
> > > ```
> > > if (isset($rucss_status) && is_array($rucss_status) && $rucss_status['disable']){ 
> > > $css_section_helper[] = $rucss_status['text'];
> > >  }
> > > ```
> > 
> > 
> > Thanks. I added the code you gave me, but nothing changed. https://postimg.cc/LgphwgMK
> 
> @Asdrubale8888888 Please can I get a screenshot of 20 lines above Line 590 to see what you have there.

https://postimg.cc/GHT2j1Tn

**Comment by jeawhanlee** [comment] 2023-04-04 09:06
@Asdrubale8888888 Thanks, there seem to be some irregularities, as you can see [here](https://github.com/wp-media/wp-rocket/blob/ce9d862f279ee636503fa8367cc4ce6d09812be9/inc/Engine/Admin/Settings/Page.php#L589-L616), Line 590 reads differently compared to what you currently have.
I'd advise exporting your current WP Rocket settings, then do a fresh install of the latest version and import your settings.
I hope that helps.

**Comment by jeawhanlee** [comment] 2023-04-04 09:20
Closing this now...

**Closed as completed by jeawhanlee** 2023-04-04 09:20 UTC
Labels: type: enhancement, can't reproduce, priority: medium, module: remove unused css
