### ISSUE TITLE
Add support to platform.sh to our allowed list of staging and development environments

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3465] opened 2021-01-07 10:40 UTC
**Is your feature request related to a problem? Please describe.**
platform.sh is a hosting provider using the following for staging/dev environments: 
**staging-xxx-yyy.xxx-#.platformsh.site
dev-xxx-yyy.xxx-#.platformsh.site**
Using WP Rocket in any of these will count as a license.

**Describe the solution you'd like**
Allow **.platformsh.site** as part of WP Rocket list of staging and development environments.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DahmaniAdame** [comment] 2021-01-07 10:40
Related ticket - https://secure.helpscout.net/conversation/1386853866/228648

**Comment by steffen25** [comment] 2021-01-08 09:16
Hi WP-rocket 

Thanks 👍

**Comment by arunbasillal** [comment] 2021-01-08 16:45
Closing this one since it is on the wp-rocket.me repo and will be done on the website end.

**Comment by GeekPress** [comment] 2021-01-08 16:50
@arunbasillal I re-open it as we have a list of staging domains inside WP Rocket to maintain too: https://github.com/wp-media/wp-rocket/blob/82b99b9b15e9b1144e2e24f06993d05c825fb8a4/inc/functions/api.php#L118

**Comment by arunbasillal** [comment] 2021-01-08 17:00
My bad. Thanks @GeekPress

**Comment by crystinutzaa** [comment] 2021-01-18 20:21
### Reproduce the issue ✅ 
Issue reproduced

### Identify the root cause ✅ 
**.platformsh.site** is missing from WP Rocket $staging environments:
https://github.com/wp-media/wp-rocket/blob/82b99b9b15e9b1144e2e24f06993d05c825fb8a4/inc/functions/api.php#L118-L132

### Scope a solution ✅ 
Add **.platformsh.site**  to $staging list:
https://github.com/wp-media/wp-rocket/blob/82b99b9b15e9b1144e2e24f06993d05c825fb8a4/inc/functions/api.php#L118-L132

### Estimate the effort ✅
Effort `[XS]`

**Comment by arunbasillal** [comment] 2021-01-18 21:33
@Tabrisrp This is a good candidate to be assigned to L2. Please do so if you agree. If not, this can be removed from current sprint.

**Comment by jorgemartine00** [comment] 2021-01-19 15:32
@arunbasillal @Tabrisrp I'll help with this one

**Comment by piotrbak** [comment] 2021-01-27 17:00
@GeekPress It's ready on the plugin side, the `.platformsh.site` still looks to be counted in the license validation process though. Should I create an issue on the website repo?

**Closed** 2021-01-27 18:59 UTC
Labels: 3rd party compatibility, effort: [XS], priority: low, type: enhancement

**Comment by GeekPress** [comment] 2021-01-29 18:45
@piotrbak The domain has been added on the website since few weeks => https://github.com/wp-media/wp-rocket.me/issues/2108#issuecomment-758008221
