### ISSUE TITLE
Notice: Trying to access array offset on value of type null (PHP 7.4, WP Rocket 3.5.1)

### ISSUE THREAD

**Issue by manuelRod** [wp-media/wp-rocket#2466] opened 2020-03-23 11:50 UTC
I've just updated my Staging Site to PHP 7.4 on WPEngine.
I've updated WP Rocket to version 3.5.1

I'm getting the following Notice:
Notice: Trying to access array offset on value of type null in /nas/content/live/xxx/wp-content/plugins/wp-rocket/inc/classes/optimization/class-abstract-optimization.php on line 66

I see there was a similar notice happening in another class and it was solved and closed:
https://github.com/wp-media/wp-rocket/issues/2185

**Comment by Tabrisrp** [comment] 2020-03-24 12:37
Hi @manuelRod,

Thank you for the report!

This is most likely caused by the call to `$file['path']` on line 66, which might be empty, and now outputs a notice with PHP 7.4.

The good news is that this will be solved in PR #2392, I added an early check for this in the method.

**Comment by manuelRod** [comment] 2020-03-25 11:32
Awesome :)

**Comment by GeekPress** [comment] 2020-03-27 09:01
As this issues will be fixed by another PR / issues, I'm closing this one.

**Closed by GeekPress** 2020-03-27 09:01 UTC
Labels: duplicate, module: file optimization, type: bug
