### ISSUE TITLE
Minify + mandatory cookies

### ISSUE THREAD

**Issue by timersys** [wp-media/wp-rocket#1650] opened 2019-04-17 13:03 UTC
When using the mandatory cookies function from a third party such as [GeotargetingWP ](https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/plugins/geotargetingwp.php) the cache on the first-page load fails until the cookies are set. That's right, for page cache, but minified scripts and assets should still work as is not compromised by cookies.

**To Reproduce**
1. Enable any third party plugin with required cookies
2. Get a clean browser and do a first load of page
3. Cache is disabled and files are not minified

**Expected behavior**
Cache is still disabled but js and css are minified

**Comment by mariamishenina** [comment] 2019-04-18 09:26
+1 for this issue, kindly waiting for the solution

**Comment by GeekPress** [comment] 2021-02-10 08:55
Duplicate of #2713

**Closed by GeekPress** 2021-02-10 08:55 UTC
Labels: duplicate, feature request
