### ISSUE TITLE
3.17: Footer hash isnot added to LRC DB table

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6903] opened 2024-08-23 13:48 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => feature/lrc
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When accessing the page with `<footer>`,we are adding hash in the source but not adding it to DB as an eligible element

**To Reproduce**
1. Clear performance hints
2. Visit an uncached page like https://new.rocketlabsqa.ovh/lrc_similive1 
3. Check LRC Cache => search for footer hash

**Expected behavior**
Footer hash added to DB 

**Screenshots**

**Additional context**
- Related slack https://wp-media.slack.com/archives/CUT7FLHF1/p1724411623325629
- Other templates are needed to handle different states of the footer

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- Footer hash added to DB if it's eligible element i.e below threshold and not child to other hash, if it's child then the parent hash added
- Footer hash not added to DB if it's not in threshold or have child inside threshold (in that case child hash only added to DB)

**Comment by MathieuLamiot** [comment] 2024-08-23 16:15
Seems to be fixed with #6891 
To be re-tested and confirmed.

**Comment by MathieuLamiot** [comment] 2024-08-24 08:54
https://github.com/user-attachments/assets/d3cf6a9d-9b25-4692-9d28-1382dbc5ac57

**Comment by Mai-Saad** [comment] 2024-08-26 10:36
- on feature/lrc now commit fb50ef3b9db98b09b4b90797f5c16117a1560435
1- The footer hash is added to DB 
=>  If below the fold and within threshold and parent => only parent hash added
=> If Above the fold and has children within threshold => blocked due to https://wp-media.slack.com/archives/CUT7FLHF1/p1724663912662179 (can have separate GH if needed)
=> If below the fold , within threshold and child => footer hash is not added but it's parent (if nesting > 2 , we have this problem https://github.com/wp-media/wp-rocket/issues/6910)
2- If the footer is totally above the fold and threshold => hash is not added to DB

**Closed as completed** 2024-09-17 11:30 UTC
Labels: type: bug, priority: high, severity: major, module: ALR
