### ISSUE TITLE
WPR cannot be deactivated because the deactivation modal is not present on the plugins page 

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#5137] opened 2022-06-10 14:50 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
**- Made sure you’re on the latest version**
- Yes, WP Rocket 3.11.3 installed
**- Used the search feature to ensure that the bug hasn’t been reported before**
No previous issues related.

**Describe the bug**
When WP Rocket is activate in Plugins page, cannot be deactivated clicking on Deactivate link. Only right-clicking the ling and selecting "Open in a new tab" can deactivate it. Clicking on Deactivate, you will get the warning related to missing modal:
https://i.imgur.com/ebktUZP.png

Video here:
https://vimeo.com/719104238/53983dd3f1

**To Reproduce**
1. Go to Plugins page
2. Click on Deactivate on WP Rocket

**Expected behavior**
WP Rocket is deactivated only clicking on Deactivate link

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1907420940/346360?folderId=2952229
Slack thread here: https://wp-media.slack.com/archives/C43T1AYMQ/p1654869102084319

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment] 2022-06-13 04:00
### Reproduce the problem
I was not able to reproduce this issue.

testing on m local setup the modal shows up correctly also the warning in the image shows
![image](https://user-images.githubusercontent.com/29744252/173275939-16b8f082-a6e6-43fb-b827-be2d32e468a9.png)

the warning in this image and video should not prevent the Model from showing up
> https://i.imgur.com/ebktUZP.png
> Video here:
> https://vimeo.com/719104238/53983dd3f1

After reviewing the [slack thread ](https://wp-media.slack.com/archives/C43T1AYMQ/p1654869102084319) 
I was able to fix the js error found by @alfonso100 on the customer website by modifying the 
[assets/admin/js/admin-scripts.js](https://adaptconsulting.com.au/wp-content/themes/dfd-ronneby/assets/admin/js/admin-scripts.js?ver=6.0)
but the Modal did show up after the fix and there are no errors in the js console

My modification
https://www.diffchecker.com/RXQYEGJs

**Comment by engahmeds3ed** [comment] 2022-06-14 08:55
@mifrero 
The problem mainly is a conflict with a plugin called [WordPress REST API Authentication](https://wordpress.org/plugins/wp-rest-api-authentication/)

The problem mainly in this plugin is they have an opened div without having a closing one for it here:

https://plugins.trac.wordpress.org/browser/wp-rest-api-authentication/trunk/admin/partials/support/class-mo-api-authentication-feedback.php#L27

so nothing to be done from our side, I created an issue there on the plugin

https://wordpress.org/support/topic/missing-closing-div-does-a-conflict-with-any-other-modals/

**Comment by engahmeds3ed** [comment] 2022-06-14 08:57
@piotrbak need ur input to remove from the sprint as it's not our problem, what do u think?

**Comment by piotrbak** [comment] 2022-06-14 09:05
@engahmeds3ed Yes, and let's see the future feedback. This happened to me too, but it was also caused by 3rd party.

**Comment by Mai-Saad** [comment] 2023-01-19 07:54
- probably related to https://github.com/wp-media/wp-rocket/issues/4990
- using 3.12.5.1 on  a single site, deactivation works although the modal not displayed in the following scenarios (tested on new labs and the modal will appear if we activated WPR again then tried to deactivate it)
1- new install of WPR after removing previous WPR (using snooze option)
2- change settings then deactivate WPR

**Comment by piotrbak** [comment] 2024-06-27 12:13
We did not have any feedback from customers about this issue.

**Closed as not planned by piotrbak** 2024-06-27 12:13 UTC
Labels: type: bug, waiting for feedback, priority: low, severity: moderate, module: user interface
