### ISSUE TITLE
3.4.0.5: CDN exclusions when using Remove Query Strings/Minify not working

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2043] opened 2019-10-16 17:36 UTC
In one of the patch updates to 3.4 this fix stopped working: 
https://github.com/wp-media/wp-rocket/pull/1878

Can be reproduced in 3.4.0.5

**Expected behaviour**: file excluded from the CDN is still optimized but served from original domain

**What's happening**: file excluded from the CDN still needs to be excluded from file optimization options as well. In this way it will be served from the original domain but no longer optimized. 

Related ticket: https://secure.helpscout.net/conversation/977671542/126377?folderId=377611

**Comment by arunbasillal** [comment] 2019-10-16 21:22
Closed because it's a duplicate of #306 and as suggested by Remy.

**Closed by arunbasillal** 2019-10-16 21:22 UTC
Labels: duplicate
