### ISSUE TITLE
Cache file not generated when the page's name is longer than 255 characters

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2615] opened 2020-05-05 06:49 UTC
URLs in Thai, and in other non-latin languages, are URL encoded.

The title of a post/page can get over the 255 characters limit. Users install plugins like [Long URL maker](https://wordpress.org/plugins/long-url-maker/) to overcome WordPress's restrictions regarding the length of the title.

In such a case, the server won't create the folder in `/cache/wp-content/`, resulting in a non-cached page.

For example, the following page's title length is 307 characters:
![](https://i.vgy.me/0qSoUt.jpg)
https://xn--12cacsb2iodd2eucb2og6gdev3ed.com/%e0%b8%88%e0%b8%ad%e0%b8%87%e0%b8%97%e0%b8%b5%e0%b9%88%e0%b8%9e%e0%b8%b1%e0%b8%81%e0%b8%a5%e0%b9%88%e0%b8%ad%e0%b8%87%e0%b9%81%e0%b8%81%e0%b9%88%e0%b8%87%e0%b8%a5%e0%b8%b3%e0%b8%99%e0%b9%89%e0%b8%b3%e0%b9%80%e0%b8%82%e0%b9%87%e0%b8%81%e0%b8%9e%e0%b8%b4%e0%b8%a9%e0%b8%93%e0%b8%b8%e0%b9%82%e0%b8%a5%e0%b8%81/

**To Reproduce**
1. Install the [Long URL maker](https://wordpress.org/plugins/long-url-maker/) plugin
2. Create a post with this title: http://snippi.com/raw/hhfhse8
2. Check the `/wp-content/cache/` folder. The page will not be cached.

**Expected behavior**
The page should be cached regardless of the length of the URL.

**Related ticket**
https://secure.helpscout.net/conversation/1151812330/161942?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2020-05-07 13:25
@vmanthos I'm closing this one as it's a duplicate of #2440

**Closed by GeekPress** 2020-05-07 13:25 UTC
