### ISSUE TITLE
Elements that pop out of their sections are cut off due to LRC

### ISSUE THREAD

**Issue by mfwd** [wp-media/wp-rocket#7010] opened 2024-10-03 17:37 UTC
**Describe the bug**
The elements that extend beyond their sections (via CSS margins etc.) are cut off due to lazy rendering.

**Screenshots**

**Normal:**
![normal](https://github.com/user-attachments/assets/38b003f6-8b0d-475c-a54c-c04dcb58bac0)

**Lazy Rendered:** (notice the orange button and the person's head)
![cutoff](https://github.com/user-attachments/assets/0769f31e-fc1f-4fd0-a050-5b7dad44bdca)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 129
 
**Additional context**

For lazy rendering of the elements, WP Rocket is using **CSS `content-visibility: auto;`** which I think uses fixed heights and makes it seem like overflow is hidden.

**Comment by piotrbak** [comment] 2024-10-04 09:11
Hello @mfwd thanks for creating the issue. It seems to be a duplicate of:
https://github.com/wp-media/wp-rocket/issues/6959

Please reach our support team to confirm this.

**Closed as not planned by piotrbak** 2024-10-04 09:11 UTC
