### ISSUE TITLE
Add "Clear Used CSS of this URL" option on Edit screen 

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5251] opened 2022-07-19 14:39 UTC
`Clear Used CSS of this URL` top menu option is currently not available if you are on the Edit screen.

![image](https://user-images.githubusercontent.com/60236665/179776643-3e8b7f41-172e-4566-9f16-482203c5d781.png)
Full-screen image: https://i.imgur.com/GTKnKU0.png

The option is only available when you are logged-in and viewing URL:

![image](https://user-images.githubusercontent.com/60236665/179777062-05e59892-201c-4bf5-b522-3fc0f92e0886.png)
Full-screen image: https://i.imgur.com/eXvMizW.png

This can be confusing for some users as they don't see an option to clear Used CSS for a specific URL.

**Describe the solution you'd like**
Add `Clear Used CSS of this URL ` option to the top menu on Edit screen.

Related ticket: https://secure.helpscout.net/conversation/1943904513/354757?folderId=3864740

**Comment by remyperona** [comment] 2022-08-01 15:09
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
It's happening because the method adding this admin bar item has a check for `is_admin()` and bails-out if true.

### Scope a solution ✅ 
Remove the check for `is_admin()` in `RUCSS\Controller\UsedCSS::add_clear_usedcss_bar_item()`

### Estimate the effort ✅
Effort `[XS]`

**Comment by GeekPress** [comment] 2022-08-25 07:18
Correct me if I'm wrong, but we must delete the Used CSS when we update the page, right?

If so, we don't need this link.

For which we would like/need to clear the Used CSS on one page if it has not been updated?

**Comment by piotrbak** [comment] 2022-08-31 10:59
@GeekPress Yes, you're right here. That's the same behaviour with `Clear this Post` in the backend editor 🤔  maybe we should consider removing that one, since updating the post is obviously, clearing the cache

**Comment by GeekPress** [comment] 2022-09-07 13:10
> maybe we should consider removing that one, since updating the post is obviously, clearing the cache

Yes we could

**Comment by GeekPress** [comment] 2022-10-06 13:01
Closing this one as we don't do it.

**Closed as completed by GeekPress** 2022-10-06 13:01 UTC
Labels: type: enhancement, wontfix, priority: low, effort: [XS], module: remove unused css, module: user interface
