### ISSUE TITLE
[Feature Request] Please re-add the old delay js opt-in feature as the new one has many bugs

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#3940] opened 2021-05-22 05:13 UTC
**Is your feature request related to a problem? Please describe.**
The new delay js breaks multiple functionality on my site, which leaves me having to stay reverted to 3.8.8. I cannot utilize the new remove unused css feature at all because the new delay js breaks my site, and there is no option to use the older opt-in method.

**Describe the solution you'd like**
The old opt-in method to be re-implemented as an option to use in the meantime until the new method is fixed.

**Describe alternatives you've considered**
Staying reverted to an older version of wp-rocket, or using flying scripts until the new method is fixed.

**Additional context**
I would really like to take advantage of the remove unused css feature, but don't want to lose the benefits of delay js because the new method is currently buggy

**Comment by remyperona** [comment] 2021-05-22 11:51
Duplicate of #3930

**Closed as completed by remyperona** 2021-05-22 11:51 UTC
Labels: duplicate
