### ISSUE TITLE
Add Option to Delay JS for a Fixed Amount of Time

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4135] opened 2021-07-06 21:08 UTC
**Is your feature request related to a problem? Please describe.**

> The ads on mobiles, especially the top one, are loaded only when the user interacts with the page, this causes a large delay and most of the time the top ad is missed by the user as he scrolls down.

**Describe the solution you'd like**
The Delay JavaScript execution feature could have the sub-option to set the execution of the scripts for a fixed amount of time (seconds).

**Describe alternatives you've considered**
To set the sub-option in the Delay JavaScript execution feature UI so customers can choose if they want to delay until user interaction or for X seconds.

**Additional context**
Ticket here: https://secure.helpscout.net/conversation/1561914752/276609?folderId=2675957

**Comment by gevcen** [comment] 2021-07-06 22:02
Isnt this the same/duplicate of https://github.com/wp-media/wp-rocket/issues/3938 ?

**Comment by GeekPress** [comment] 2021-07-06 23:36
Duplicate of #3938

**Closed as completed by GeekPress** 2021-07-06 23:36 UTC
Labels: duplicate
