### ISSUE TITLE
Clear Critical Images of this URL is displayed on URLs it shouldn't when RUCSS is disabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6338] opened 2023-12-18 07:32 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version checked with `feature/lcp-above-the-fold-optimization`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

When the Remove Unused CSS is disabled `Clear Critical Images of this URL` is displayed on WP Rocket's dashboard, WordPress's dashboard, etc:
![image](https://github.com/wp-media/wp-rocket/assets/193660/94e567db-fea6-4e98-acf9-e0cd2fc03484)

**To Reproduce**

1. With `3.16` disable Remove Unused CSS.
3. Visit WP Rocket's dashboard and check the admin bar menu items. 
4. Both clearing items are displayed.

**Expected behavior**

The `Clear Critical Images of this URL` admin bar menu item should only be displayed when visiting a non-admin URL in the back end.

**Screenshots**

.![image](https://github.com/wp-media/wp-rocket/assets/193660/b7980c00-6993-4afb-a7a4-08c2315c36b1)

**Additional context**

The issue is there with #6334 as well.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Miraeld** [comment] 2024-03-11 03:28
Is this issue still be one? I can't reproduce, 
When `Remove used CSS` is disable, on an admin page this is what I got:


![Image](https://github.com/wp-media/wp-rocket/assets/14993267/9fa6c70f-9e68-4372-bd4d-e165c5b0d4e1)

**Comment by jeawhanlee** [comment] 2024-03-18 07:23
@Miraeld You are right, it's already been fixed during the previous implementation [here](https://github.com/wp-media/wp-rocket/pull/6334) @MathieuLamiot I think we can close this issue.

**Closed as completed** 2024-03-18 07:26 UTC
