### ISSUE TITLE
Emply Woocommece store page with preloading active on main language

### ISSUE THREAD

**Issue by bwafels** [wp-media/wp-rocket#3781] opened 2021-04-10 16:40 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: All plugins and wordpress updated to the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using the option "preload sitemap" on a woocommerce store with more than one language (WPML). The primary language shop page is empty. The problem appears after updating Yoast to a new version. This doesn't happen everytime as I suspect preloading is not active every time the site loads. It also never happens when changing to the secondary language.

**To Reproduce**
1. Install Woocommerce, WPML, Yoast & use WP-Rocket preloading sitemap. 
2. Update Yoast to a new version

**Expected behavior**
The main woocommerce shop page should always show the products.

**Screenshots**
cached page:
![image](https://user-images.githubusercontent.com/76993541/114277530-dd2e4380-9a2b-11eb-865f-02eac984161e.png)

Non-cached page:
![image](https://user-images.githubusercontent.com/76993541/114277516-cf78be00-9a2b-11eb-87b1-fca969472489.png)

**Additional context**
Even with an empty store page the products appear when clicking on a product category. Disabling Preloading fixes the issue for now.
Issue reported on Yoast wordpress support page: 
https://wordpress.org/support/topic/after-every-update/
https://wordpress.org/support/topic/shop-page-empty-after-update-to-15-5/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by bwafels** [comment] 2021-04-12 09:15
Recommendation from Yoast:

In regards to sitemaps, can you please confirm whether you have created the rules described here to exclude the sitemap from preloading?

You can add these rules by going to Settings > WP Rocket > Advanced Rules > Never Cache URL(s) and exclude the following:

/(.*)sitemap(.*).xml
/(.*)sitemap.xsl

**Comment by vmanthos** [comment] 2021-04-12 09:21
@bwafels You'll receive a reply from me to your ticket very soon.

**Update**

**Related ticket:** https://secure.helpscout.net/conversation/1480136909/255043

**Comment by piotrbak** [comment] 2022-09-05 09:34
Closing it, since we didn't hear from you in the support ticket and the issue is not related to preload at all.

**Closed as completed by piotrbak** 2022-09-05 09:34 UTC
Labels: type: bug, community, 3rd party compatibility, module: preload, needs: grooming
