### ISSUE TITLE
Auto-formatting (*) to (.*) on excluded options to avoid other rules to not work

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#700] opened 2018-01-11 08:28 UTC
We allow using regex on our advanced options to exclude page from the cache, cookie, etc.

In case of having these values to excluded some pages from the cache:
`/member/(*)`
`/message/`
`/astrology-oracle/astrology-oracle-reading/`
`/astrology/chinese-astrology/fortune-cookie/message/`

`/member/(*)`will stop the rule exclusion for all other pages.

To fix that we have to replace `(*)` by `(.*)`

So to avoid this kind of issues, we can formate before saving the option `(*)` by `(.*)`

**Comment by Tabrisrp** [comment] 2020-06-04 16:28
**Reproduce the issue** ✅ 
Reproduced on local

**Identify the root cause** ✅ 
`(*)` is a malformed regular expression, which will prevent it from working when we perform the checks.

**Scope a solution** ✅ 
In `rocket_sanitize_textarea_field()`, we can add an additional formatting to automatically replace `(*)` by `(.*)` if it's found in the value currently being sanitized.

**Estimate the effort**  ✅ 
Effort `[S]`, need to write tests for the function

**Comment by Tabrisrp** [comment] 2020-06-12 20:19
Duplicate of #1917 

This was resolved in the PR associated with the above issue, I completely forgot about it.

**Closed** 2020-06-12 20:19 UTC
Labels: duplicate
