### ISSUE TITLE
3.0 Not Caching Pages - For Site's Using an SSL

### ISSUE THREAD

**Issue by Volnus** [wp-media/wp-rocket#919] opened 2018-04-03 15:59 UTC
I updated a client site to the 3.0 version of WPRocket and their site stopped caching pages all together I left it with the same options user caching. After rolling the site back I realized it still wasn't working but the "SSL Cache wasn't enabled" after enabling this option the cache was working again. 

The option was removed in 3.0 and the reason that this occurred was that the website, didn't declare that it was HTTPS in general settings under site address & WordPress address. 

They were using some redirection plugin to handle it which I hadn't realized. 
plugin in question is: Easy HTTPS (SSL) Redirection https://wordpress.org/plugins/https-redirection/

I managed to fix it by setting it as HTTPS under the site address & wordpress address.  (like it should have been)

**Comment by glueckpress** [comment] 2018-04-05 14:36
@Volnus Thanks for reporting this issue!

@Tabrisrp Confirmed, just had another customer with this same issue. 
It happens when `$rocket_cache_ssl` isn’t declared in the config file, because the SSL hadn’t been active before 3.0. In that case, process.php exits here:

https://github.com/wp-media/wp-rocket/blob/5b5e1a1271d3a401044cd9029656aa0c2c3dd825/inc/front/process.php#L112

**Comment by Tabrisrp** [comment] 2018-04-16 17:10
This is fixed with the re-introduction of the SSL option in 3.0.3

**Closed by Tabrisrp** 2018-04-16 17:10 UTC
Labels: bug, minor
