### ISSUE TITLE
Update Browser Cache Expiration Value for Cloudflare Add-on

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#1811] opened 2019-06-28 18:45 UTC
**Description**
The Browser Cache Expiration in Cloudflare Cache settings recommendation is 1 year after a short Slack discussion, here: 

https://wp-media.slack.com/archives/C08N8J6VC/p1561483391107800 

**To Reproduce**
1. Enable Cloudflare Add-on 
2. Enable Recommended Settings
3. Check Cloudflare's Browser Cache Expiration value, currently it's 1 month.
4. The Browser Cache Expiration value should be **1 year**.

**Expected behavior**
The Browser Cache Expiration in Cloudflare Cache setting is 1 year.

**Suggestion**
https://github.com/wp-media/wp-rocket/blob/35533b0069b2f1313e30c2b310856daf47fd9880/inc/admin/options.php#L175
We would need to change from `2678400` to `31536000` .

**Comment by arunbasillal** [comment] 2019-07-02 12:02
Just noticed that this is a duplicate of #1697 
Will leave it up to Remy to decide which one to close.

**Comment by Tabrisrp** [comment] 2019-07-02 14:05
Duplicate of #1697

**Closed by Tabrisrp** 2019-07-02 14:05 UTC
Labels: duplicate
