### ISSUE TITLE
Report a bug in the rocket and jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#3990] opened 2021-06-03 10:45 UTC
There is a query in the jet woobuilder plugin called recently visited products. When the rocket plugin is active, this query can no longer be used and it is severely bugged.
I raised this issue with the developers of jet woobuilder, they say the problem is with the rocket plugin.
Please check this bug and fix it if possible.

Thank you

**Comment by GeekPress** [comment] 2021-06-03 12:16
Hi @79ho3ein 

Thanks for the report.

Please update your original message by following our issue template :


**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by 79ho3ein** [comment] 2021-06-03 12:52
@GeekPress 
ok thanks

**Comment by GeekPress** [comment] 2021-09-02 16:12
Closing the issue as we are missing infos.

@79ho3ein Feel free to complete your initial message if you want us to be able to work on this problem.

**Closed as completed by GeekPress** 2021-09-02 16:12 UTC
Labels: invalid
