### ISSUE TITLE
UTF-8 special characters mismatch when these query requests are in URL

### ISSUE THREAD

**Issue by rasti-at-webkinder** [wp-media/wp-rocket#523] opened 2017-09-22 08:43 UTC
https://github.com/wp-media/wp-rocket/blob/fdee41ec2db637d2d4afc1dbd75f5b739b73661f/inc/front/process.php#L82-L106

If any of these request strings is present in the URL, the special characters (like german öäü) are not displayed correctly, even if the database AND document charsets are set correctly. (Even with the fix from official KB: http://docs.wp-rocket.me/article/64-fix-utf-8-issue-with-special-characters (CORRECTION: This fix works for all query strings except gclid))

Live examples:
https://www.rederp.ch/?utm_expid=r4nd0m4lph4n00m3r1c4lstr1n9
https://www.luporter.ch/?gclid=r4nd0m4lph4n00m3r1c4lstr1n9

Try any of those queries (except gclid on rederp/we had to remove it) and you'll get the same result.

**Comment by Screenfeed** [comment] 2018-07-31 14:07
@rasti-at-webkinder Hi. Do you still have this issue? I couldn't reproduce it. Thanks.

**Comment by Screenfeed** [comment] 2018-07-31 20:55
Thanks a lot :)

**Comment by GeekPress** [comment] 2020-05-21 12:13
Hi @rasti-at-webkinder 🤚

We haven't back from you since @Screenfeed asked you a question, so I'm closing this issue. However, if you still need our help, just reply here and we will re-open the issue.

Best

**Closed by GeekPress** 2020-05-21 12:13 UTC
Labels: community, module: cache, waiting for feedback
