### ISSUE TITLE
[WIP] FOUC issue when Optimize CSS Delivery and RUCSS are both enabled

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4078] opened 2021-06-21 11:10 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.0.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
The issue is created to track and further investigate the following problem:
FOUC happens when both options _Optimize CSS delivery_ and _Remove Used CSS_ enabled. 

- Issue happens on all pages.
- Generating page-specific CPCSS doesn't resolve the issue.
- No issues are present if only **one** of the options is enabled at a time.
- No stylesheets are being excluded from OCD.
- All the CSS was processed and all the unused CSS was removed.
- CPCSS was generated and added to the source code of the page as expected.
- Just in case checked the following: Deactivating all other options in _File Optimization_ tab and leaving only OCD + RUCSS doesn't fix the issue.
- Customer had Rocket Loader from Cloudflare enabled. Disabling it didn't help.

**Expected behavior**
No FOUC when both options are activated.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1548557209/272980/
Screen recording in the note of the ticket.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2021-06-21 12:18
@NataliaDrause What about excluding `wprRemoveCPCSS`  from being delayed? It could be good to try to exclude this pattern from the Delay JS option.

**Comment by NataliaDrause** [comment] 2021-06-21 13:47
Thank you @GeekPress. I deactivated Delay JS totally and it, unfortunately, didn't help.
Do you think excluding only  `wprRemoveCPCSS` from being delayed is still worth a try?

**Comment by GeekPress** [comment] 2021-06-21 13:48
> Thank you @GeekPress. I deactivated Delay JS totally and it, unfortunately, didn't help.
> Do you think excluding only `wprRemoveCPCSS` from being delayed is still worth a try?

No, it confirms that the problem isn't related the Delay JS option if you still have the problem when this option is off.

**Comment by javiergutierrezchamorro** [comment] 2021-06-22 05:59
Confirmed the issue here too. With only one of the two enabled everything works fine. With both the problem happens.

**Comment by NataliaDrause** [comment] 2021-07-06 09:38
Same issue: https://secure.helpscout.net/conversation/1560710154/276337/
With only one of the two enabled there is no FOUC.
Disabling Delay JS didn't help.

**Comment by NataliaDrause** [comment] 2021-07-18 13:01
Related: https://secure.helpscout.net/conversation/1565064049/277702/

**Comment by NataliaDrause** [comment] 2021-07-20 08:40
Related: https://secure.helpscout.net/conversation/1576528928/281233/

**Comment by javiergutierrezchamorro** [comment] 2021-07-24 15:34
Don't have access to helpscout.net, but can confirm that disabling delayed Javascript does not help neither.

**Comment by vmanthos** [comment] 2021-07-29 05:08
LIkely related: https://secure.helpscout.net/conversation/1560969558/276395?folderId=2135277

**Comment by javiergutierrezchamorro** [comment] 2021-07-29 05:42
Since the issue is still opened since more than a month ago, indeed since the 3.9.0 release, is there any possible workarround?

**Comment by nicomollet** [comment] 2021-07-29 13:06
I am on WP Rocket 3.9.1.1.

Setup: CSS Minify + Optimize Delivery + Remove Unused + Delay JS + Defer JS

I am seing a FOUC "blue links" on https://www.saintmalogolf.com/ even with my critical path CSS having colored links `a{color:#b19263;text-decoration:none}`.
This means my critical CSS is not loaded before the page is loaded, I don't get the purpose of critical path if it is not supposed to remove the FOUC.
Maybe related to this issue.

**Comment by GeekPress** [comment] 2021-07-29 15:14
For everybody facing this problem, please note that you don't need to have Optimize CSS Delivery and Remove Unused CSS if you update WP Rocket to 3.9.1.1 (if it's available on your account).

This will result in a better LCP & CLS and no FOUC issue anymore.

I'm closing it as we won't recommend anymore using both options at the same time.

**Closed as completed by GeekPress** 2021-07-29 15:14 UTC
Labels: wontfix, module: critical path css, module: remove unused css

**Comment by nicomollet** [comment] 2021-07-29 15:30
I followed @GeekPress advice and I now have a better pagespeed score + no more FOUC!

**Comment by javiergutierrezchamorro** [comment] 2021-07-29 18:24
> For everybody facing this problem, please note that you don't need to have Optimize CSS Delivery and Remove Unused CSS if you update WP Rocket to 3.9.1.1 (if it's available on your account).
> 
> This will result in a better LCP & CLS and no FOUC issue anymore.
> 
> I'm closing it as we won't recommend anymore using both options at the same time.

Are you sure about that? Just added Jetpack Boost which implements a kind of Optimized CSS delivery and enabled RUCSS in Rocket. Having both got slightly better results that having only RUCSS.

**Comment by GeekPress** [comment] 2021-08-04 09:37
> Are you sure about that? Just added Jetpack Boost which implements a kind of Optimized CSS delivery and enabled RUCSS in Rocket. Having both got slightly better results that having only RUCSS.

Yes. But as you may know in performance, there is no rule that can be affirmed working the same way for 100% of websites.

**Comment by javiergutierrezchamorro** [comment] 2021-08-04 09:57
> > Are you sure about that? Just added Jetpack Boost which implements a kind of Optimized CSS delivery and enabled RUCSS in Rocket. Having both got slightly better results that having only RUCSS.
> 
> Yes. But as you may know in performance, there is no rule that can be affirmed working the same way for 100% of websites.

Probably they will be some more users in same situation. So I guess would be nice if RUCSS could be work together with CPCSS avoiding them the need of third party plugins.
