### ISSUE TITLE
Crawl sitemep.xml's if it's not formatted via a plugin like YoastSEO and other SEOplugins

### ISSUE THREAD

**Issue by wpsumo** [wp-media/wp-rocket#4058] opened 2021-06-16 10:46 UTC
**To Reproduce**
Just preload sitemap and insert the sitemap url in WP Rocket.
Doesn't crawl standard sitemep.xml's if it's not formatted via a plugin like YoastSEO and other SEOplugins

`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>https://domain.com/example-slug/</loc>
		<lastmod>2021-06-15T15:10:55+00:00</lastmod>
		<image:image>
			<image:loc>https://domain.com/wp-content/uploads/image.jpg</image:loc>
			<image:caption><![CDATA[Some text here.]]></image:caption>
		</image:image>
	</url>
	<url>
		<loc>https://domain.com/example-slug-2/</loc>
		<lastmod>2021-06-15T15:11:55+00:00</lastmod>
		<image:image>
			<image:loc>https://domain.com/wp-content/uploads/image-2.jpg</image:loc>
			<image:caption><![CDATA[Text here.]]></image:caption>
		</image:image>
	</url>
	<url>
		<loc>https://domain.com/example-slug-3/</loc>
		<lastmod>2021-06-15T15:14:05+00:00</lastmod>
		<image:image>
			<image:loc>https://domain.com/wp-content/uploads/image.jpg</image:loc>
			<image:caption><![CDATA[text here]]></image:caption>
		</image:image>
	</url>
</urlset>`

Formatted here:
https://pastebin.com/DwT80Gjm

**Expected behavior**
To crawl sitemaps and not do homepage crawl.

**Additional context**
Haven't tested with and without WPML.

**Comment by remyperona** [comment] 2021-06-22 19:53
Tested this sitemap on my installation. It was correctly parsed by the sitemap preload, the formatting of the sitemap itself doesn't seem to be the root cause here.

**Comment by wpsumo** [comment] 2021-07-22 14:07
It would be easier if we had a debugging function which way a URL cache was generated and found. It seems to work normally, the issue seems more be related to that it stops and due to timeouts and too much load on the server due to the crawls via sitemap. As most sitemaps are huge and one big sitemap for all pages. If WPR could crawl it in more batches in a background process, it would be better.

**Comment by piotrbak** [comment] 2021-11-09 14:56
Hello @wpsumo we were not able to reproduce the issue and we haven't received any complains about sitemap not being preloaded.
**>the issue seems more be related to that it stops**
Background process will work till the timeout and later it will be resumed by the wp cron.

**>too much load on the server due to the crawls via sitemap**
You can slow down the preload and reduce the load with this [filter](https://docs.wp-rocket.me/article/8-how-the-cache-is-preloaded#crawl-interval)

**>It would be easier if we had a debugging function which way a URL cache was generated and found**
You can easily log the value of `$item` [here](https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Engine/Preload/AbstractProcess.php#L201) using `error_log` function. It will show you what URLs were visited by our log and also whether it was a sitemap or homepage preload. Also you'll see whether it was a mobile or desktop visit.

I'm going to close this issue. Please note, that we won't be fixing any issues related to Preload module until the introduction of completely new system.

**Closed as completed by piotrbak** 2021-11-09 14:56 UTC
Labels: module: preload, can't reproduce
