### ISSUE TITLE
Add use.typekit.com to default exclusions on Defer JavaScript 

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#4730] opened 2022-02-11 19:01 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On some sites, typekit fonts are being downloaded from `use.typekit.com` and not from `use.typekit.net`. 

**To Reproduce**
Check this thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1644601856411879

**Expected behavior**
The domain `use.typekit.com` is excluded by default from the feature Load JavaScript deferred

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ x] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment] 2022-02-12 05:31
It was already posted :) https://github.com/wp-media/wp-rocket/issues/4706

**Comment by piotrbak** [comment] 2022-02-14 11:37
@mifrero closing this issue as it's a duplicate of https://github.com/wp-media/wp-rocket/issues/4706

**Closed as completed by piotrbak** 2022-02-14 11:37 UTC
Labels: 3rd party compatibility
