### ISSUE TITLE
rocket_init() server callback taking 0.0672s

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2227] opened 2019-12-30 23:25 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
Everything up-to-date.

**Describe the bug**
After investigation with my hosting provider to analyse the slow server response time on uncached pages of my site, we've found out that one rocket_init() callback in wp-rocket/inc/main.php:26 is taking 0.0672s, which is obviously a too high value.

**To Reproduce**
Execute a simulation of the loading times using the WordPress built-in command-line interface.

**Expected behavior**
As per the instruction of my hosting provider, any value above 0.00XX is too high and must be addressed.

**Screenshots**
![image](https://user-images.githubusercontent.com/51261962/71604673-ead7f680-2b63-11ea-80b4-9aa485b7430e.png)

**Additional context**
N/A

**Comment by Tabrisrp** [comment] 2020-01-14 16:20
@hellofromtonya I assigned this to you, to have a look at, as it's most likely the same thing as we had on Imagify. I don't think the issue is in `rocket_init` itself, but in the `load()` method of `WP_Rocket\Plugin`, where there is a couple of `array_merge` uses.

**Comment by hellofromtonya** [comment] 2020-01-14 17:33
@Tabrisrp This one is part of our Performance initiatives, i.e. to measure and optimize the time (PHP runtime/execution) and space (memory usage) of the plugin.

**Comment by piotrbak** [comment] 2023-06-02 11:32
Going to close it. The `array_merge` were reduced in the past. We haven't had any feedbacks about that problem since then.

**Closed by piotrbak** 2023-06-02 11:32 UTC
Labels: type: enhancement, performance
