### ISSUE TITLE
On kinsta hosting enable WP Rocket CDN automatically

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3272] opened 2020-11-05 20:26 UTC
**Is your feature request related to a problem? Please describe.**
In sites that are hosted on Kinsta, they are using by default kinsta CDN so some WP Rocket functionality that uses `rocket_url_to_path` function like JS/CSS combine.
So if CDN is not active this will make a conflict and won't return the file paths.

**Describe the solution you'd like**
Enable WPR CDN automatically with kinsta hosting.

**Comment by arunbasillal** [comment] 2020-11-06 06:29
This is a duplicate of #2046 it seems? Please correct me otherwise. Going to copy your note to the other issue.

**Closed by arunbasillal** 2020-11-06 06:29 UTC

**Comment by engahmeds3ed** [comment] 2020-11-06 11:44
@arunbasillal Yes, it's duplicated, thanks.
