### ISSUE TITLE
Uncaught Error: Class 'WP_Rocket\Dependencies\Database\Query' not found in /bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php

### ISSUE THREAD

**Issue by Vpvladimirov** [wp-media/wp-rocket#4496] opened 2021-11-10 11:33 UTC
**Describe the bug**
After installing the WP Rocket successfully I click "Activate Plugin" and the entire Wordpress stops working because of the error
Fatal error: Uncaught Error: Class 'WP_Rocket\Dependencies\Database\Query' not found
in /bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 10

However when I navigate to the WP_Rocket\Dependencies\Database\Query I can see the Query.php file exists there.

**To Reproduce**
1. Go to Add Plugins
2. Select Upload Plugin
3. Upload the zip of WP Rocker and wait for installation to complete
4. Click Activate Plugin
5. See error and can no longer use anything Wordpress

**Expected behavior**
To activate the plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/12891861/141105633-e37641c7-ccc5-4419-a90e-184e6d105cbc.png)

**Additional context**
I have tried to uninstall and install the plugin couple of times but the result is the same every time.

**Comment by piotrbak** [comment] 2021-11-10 11:48
Hello @Vpvladimirov thanks for your report. In the error log there's a mention of `duplicate-post` plugin.

Could you disable it and try installing a fresh zip archive of WP Rocket from our [website](https://wp-rocket.me/account)? That might be useful in debugging process.

**Comment by Vpvladimirov** [comment] 2021-11-10 12:08
Hello @piotrbak after disabling the duplicate-post plugin I hit the same error with another plugin so for now I have disabled 4 plugins. Now the error is with 
```
include()
/bitnami/wordpress/wp-content/plugins/wordpress-seo/vendor/composer/ClassLoader.php:571
Composer\A\includeFile()
/bitnami/wordpress/wp-content/plugins/wordpress-seo/vendor/composer/ClassLoader.php:428
```
but I don't see a "wordpress-seo" plugin in the list.

Also I will need the 4 disabled plugins so even if it works at some point do you think I will be able to activate them later on?

**Comment by piotrbak** [comment] 2021-11-10 12:10
@Vpvladimirov There seem to be a problem with your installation. Do you use WP Rocket downloaded from our website or from GitHub?

**Comment by Vpvladimirov** [comment] 2021-11-10 12:14
@piotrbak I use the one from the website. I just paid for the License and downloaded the zip.
After couple of more install WP Rocket -> Activate -> Uninstall -> Deactivate the plugin mentioned in the error I am now at the following error:

```
 Fatal error: Uncaught Error: Class 'WP_Rocket\Dependencies\Database\Query' not found
in /bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 10

Call stack:

include()
/bitnami/wordpress/wp-content/plugins/wp-rocket/vendor/composer/ClassLoader.php:571
Composer\A\includeFile()
/bitnami/wordpress/wp-content/plugins/wp-rocket/vendor/composer/ClassLoader.php:428
Composer\A\ClassLoader::loadClass()
spl_autoload_call()
class_exists()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Definition/Definition.php:211
WP_Rocket\D\L\C\D\Definition::resolve()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Definition/DefinitionAggregate.php:94
WP_Rocket\D\L\C\D\DefinitionAggregate::resolve()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php:157
WP_Rocket\D\L\C\Container::get()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/ServiceProvider.php:62
WP_Rocket\E\O\R\ServiceProvider::register()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/ServiceProvider/ServiceProviderAggregate.php:102
WP_Rocket\D\L\C\S\ServiceProviderAggregate::register()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php:172
WP_Rocket\D\L\C\Container::get()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Preload/ServiceProvider.php:56
WP_Rocket\E\P\ServiceProvider::register()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/ServiceProvider/ServiceProviderAggregate.php:102
WP_Rocket\D\L\C\S\ServiceProviderAggregate::register()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php:172
WP_Rocket\D\L\C\Container::get()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/Plugin.php:115
WP_Rocket\Plugin::load()
/bitnami/wordpress/wp-content/plugins/wp-rocket/inc/main.php:48
rocket_init()
wp-includes/class-wp-hook.php:303
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:327
WP_Hook::do_action()
wp-includes/plugin.php:470
do_action()
wp-settings.php:441
require_once()
/bitnami/wordpress/wp-config.php:215
require_once()
wp-load.php:50
require_once()
wp-admin/admin.php:34
require_once()
wp-admin/plugins.php:10
```

I guess this could help.

**Comment by piotrbak** [comment] 2021-11-10 12:29
@Vpvladimirov Could you open a support ticket here https://wp-rocket.me/support/ and send us WordPress/SFTP credentials?

Our Support Team is aware of this problem with your instance and your case will be treated as priority. It seems that the `Query.php` content might not be correct. For now, I'm closing the issue and if it turns out that the problem is related to the code itself, rather than corrupted archive, we'll reopen it. Thank you and apologies for the problems you're experiencing.

**Closed as completed by piotrbak** 2021-11-10 12:29 UTC
Labels: wontfix, waiting for feedback
