### ISSUE TITLE
Duplicate post and pages with Slug finish with "/"

### ISSUE THREAD

**Issue by jtorr3s** [wp-media/wp-rocket#3845] opened 2021-04-26 09:25 UTC
Hello,

When install WP-ROCKET the last version in my WordPress all URLs finished with slug "/" all its ok, but if try go to same url without finished slug "/" no redirect to correct slug.  Only redirect in firefox, not redirect in Chrome or Safari

Example:  

Type https://viajaros.com/blog  in firefox and redirect to https://viajaros.com/blog/  but in Chrome or Safari if type https://viajaros.com/blog not redirect to  https://viajaros.com/blog/

Any solution for not duplicate because https://viajaros.com/blog without "/" or https://viajaros.com/blog/ with "/" work but is duplicate for google.

Thank you.

**Comment by remyperona** [comment] 2021-04-26 15:38
Duplicate of #1392

**Closed as completed by remyperona** 2021-04-26 15:38 UTC
Labels: duplicate
