### ISSUE TITLE
Delay JS compatibility with Sparxpres for WooCommerce

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5109] opened 2022-06-02 11:43 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version `3.11.2`
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
[Sparxpres for WooCommerce](https://wordpress.org/plugins/sparxpres-for-woocommerce/) widget is not properly displayed on the product page when Delay JavaScript execution is enabled.

It is necessary to exclude this dependency of the Powerkit Justified gallery:
`/wp-includes/js/imagesloaded.min.js
`

**To Reproduce**
1. Add a widget to a product page + minify JS without any exclusions
2. See error

**Expected behavior**
The widget should work without requiring any exclusions.

**Screenshots**
Display issue:
![Image 2022-06-01 at 3 50 33 PM](https://user-images.githubusercontent.com/26235782/171620480-b20fc3c2-1874-4639-b688-f07ea2c70358.jpg)
Full-size image: https://share.getcloudapp.com/yAu1W0bR

How it should look like:
![Image 2022-06-02 at 1 21 22 PM](https://user-images.githubusercontent.com/26235782/171620576-71c3e993-bd2b-49b6-93b9-23d616f5c122.jpg)
Full-size image: https://share.getcloudapp.com/yAu1o8Q6

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1896992111/345019/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1654163358298909

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2022-06-06 09:38
We'll need a separate compatibility class here. Let's resolve the following one within the same PR:
https://github.com/wp-media/wp-rocket/issues/5108

**Comment by jeawhanlee** [comment] 2022-06-09 12:30
### Reproduce the problem
I was not able to reproduce this because there was something required on the sparxpres plugin called link ID.

### Scope a solution

**For Delay js exclusion**
We can create a Thirdparty class for sparxpress like @piotrbak stated.
- Check if plugin is activated
- We hook to `rocket_delay_js_exclusions` filter then exclude `/wp-includes/js/imagesloaded.min.js`

**For Minify js exclusion as stated here https://github.com/wp-media/wp-rocket/issues/5108**
- We hook to `rocket_exclude_js` filter  then exclude `/sparxpres-for-woocommerce/assets/js/(.*)`

### Estimate the effort
[S]

**Comment by piotrbak** [comment] 2023-04-12 13:34
For the Delay JS, it looks like the dependency is too general. Moving it to the `Minify JS` only

**Comment by alfonso100** [comment] 2023-07-04 19:15
marking as `blocked` until we have the backend field to exclude files from minify JS

**Closed as completed** 2024-07-11 16:24 UTC
Labels: type: enhancement, 3rd party compatibility, status: blocked, effort: [S], needs: r&d, module: minify JS, needs: backend exclusion
