### ISSUE TITLE
Rolling back from 3.10.9 installs the latest available version 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5204] opened 2022-06-30 06:51 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ❌` 3.10.9` should be installed
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When rolling back from `3.10.9` the latest WP Rocket version that's available to the user's account is installed, e.g. `3.11.4` at the moment for me.

**To Reproduce**

1. Install a fresh copy of ` 3.10.9`
2. Click the "REINSTALL VERSION 3.9.4" button in the tools tab.
3. The rollback will install the latest version that's available to your account.

**Expected behavior**

WP Rocket should roll back to `3.9.4`.

**Additional context**

This is different from #3077 where the first rollback works as expected.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by camilamadronero-zz** [comment] 2022-06-30 13:39
Related https://github.com/wp-media/wp-rocket/issues/5177

**Comment by Mai-Saad** [comment] 2022-07-04 12:35
Using the 3.11.4 zip if we roll back then refresh the rollback [page](https://new.rocketlabsqa.ovh/wp-admin/admin-post.php?action=rocket_rollback&_wpnonce=3f3225313e), we will install the latest version i.e 3.11.4 instead of 3.10.9

**Comment by remyperona** [comment] 2022-07-05 19:29
Duplicate of #3077

**Comment by jeawhanlee** [comment] 2022-07-11 18:37
### Reproduce the problem ✅
### Scope a solution
I believe we already have a solution here as @engahmeds3ed stated in https://github.com/wp-media/wp-rocket/issues/3077#issuecomment-689893560 but this time we will only implement this fix on our current version, https://github.com/wp-media/wp-rocket/tree/v3.9.5.1 and https://github.com/wp-media/wp-rocket/tree/v3.10.10.1 as checked with @Tabrisrp and @engahmeds3ed 

What do you think @piotrbak @GeekPress 
Estimate the effort
[M]

**Closed as completed** 2022-08-03 19:43 UTC
Labels: type: bug, module: tools, priority: high, effort: [M], severity: moderate
