### ISSUE TITLE
WP Rocket caches temporary errors on the site, like database errors, and continues to display them after they are fixed

### ISSUE THREAD

**Issue by amityweb** [wp-media/wp-rocket#1004] opened 2018-05-24 08:39 UTC
Here is the scenario...

We had a server with high resource usage which would crash the database sometimes (e.g. OOM). We have an automated system on our servers to restart the database if it detects it as down. So the database would be down for like 10 seconds or something. Then the database and site comes back, on its own. Its a short term failsafe until we can fix the OOM issues in the long term. 

If a visitor visits an uncached page in these 10 seconds, WP Rocket caches the database error page. In the background that error may be fixed quickly, but WP Cache is showing the cached error page for the duration of the cache time (in our case 24 hours). 

To fix the issue we have to login and clear the cache then it works OK. But the error can occur anytime, 24/7, so its not possible to clear the cache immediately when this occurs. Customers are often emailing us saying their database is down, but the database is not down, its a cache page. 

This is not good behaviour, to cache errors. WP Rocket should not cache a page if it returns an error (or have a choice for users to set this behaviour). I can imagine most people would not want this behaviour. 

Thanks

**Comment by Volnus** [comment] 2018-05-24 16:18
While I agree with the idea of it not caching error pages why don't you have it clear the cache when the web server is restarted. 

There is a doc using it with a cron job you should be able to adapt it to your current solution, however, having the database crash is an even bigger issue ~
https://docs.wp-rocket.me/article/494-how-to-clear-cache-via-cron-job

**Comment by Tabrisrp** [comment] 2018-05-24 18:00
Valid point, but this is a duplicate of #239 which will be fixed by PR #579, probably merged in 3.1

**Closed by Tabrisrp** 2018-05-24 18:00 UTC
Labels: duplicate

**Comment by amityweb** [comment] 2018-05-25 09:04
@Volnus with many servers and many sites I dont think its reasonable to expect website administrators to do this. To write some script to detect when Apache is restarted and then call some WP Cache clear script. We dont want the cron to run periodically (thats why there is a setting to 1 day in the cache settings). Otherwise it will be running every 5 minutes to ensure no errors, which defeats the object of using cache. And then what about all the millions of WP users who cant write scripts... not fair on them for WP Rocket to show errors when there are none.
