### ISSUE TITLE
External CSS file is cached but @font-face inside it has still a relative path

### ISSUE THREAD

**Issue by Vizz85** [wp-media/wp-rocket#3173] opened 2020-09-30 13:00 UTC
WP version 5.5.1, tried also with 5.4
WP-Rocket version 3.7.1.1

**Describe the bug**
Some font urls are not resolved because they are loaded from an external file (from fast.fonts.net) which get cached to mydomain/assets/cache/min/1/4d5b97324d2018b73fc01b7ea430fc0f.css but @font-face path are still relative to the external domain.
How to exclude this file from pre-fetching and concatenation? Seems to be active by default, as the Combine CSS files option isn't active and the file's domain should be excluded.
Visiting mydomain.com/?nowprocket everything works fine.

**Expected behavior**
Concatenation isn't active or at least file is excluded.

<img width="687" alt="Bildschirmfoto 2020-09-30 um 14 50 49" src="https://user-images.githubusercontent.com/13699434/94687278-5d147c00-032c-11eb-8c9e-630b097cdf41.png">

**Comment by arunbasillal** [comment] 2020-10-20 08:45
@Vizz85 Thanks for the report. 

To fix the issue, adding the domain `fast.fonts.net` to the `Excluded CSS files` text area (as shown in your screenshot), should do it right? Did that help?

**Comment by Vizz85** [comment] 2020-10-20 09:34
Hi @arunbasillal !

just entering the domain like in my screenshot didn't worked.

A couple of days ago I did some more tests with WP-Rocket 3.7.2 and still experienced the same issue which I think is a caching problem due to a misconfiguration between WP-Rocket and Cloudflare (for which I have no credentials at the moment).

However I was able to trick it adding the path twice, with and without domain:
<img width="1181" alt="Bildschirmfoto 2020-10-20 um 11 23 28" src="https://user-images.githubusercontent.com/13699434/96567794-7e331180-12c7-11eb-88a8-d06330b52c2a.png">

For reference, we hadn't such a problem with WP-Rocket version 3.5.0.3 (reverting to it fixed the issue as well).

**Comment by arunbasillal** [comment] 2020-10-20 10:35
@Vizz85 The change happened in 3.7 because of https://github.com/wp-media/wp-rocket/issues/2810

However, by design simply entering the domain name should exclude the CSS file from minification and being locally hosted. Seems to be a bug if that is the case. 

@Tabrisrp Would you please advise? Shouldn't adding the domain in the `Excluded CSS files` text area prevent those files from being locally hosted as well?

**Comment by arunbasillal** [comment] 2020-10-21 14:43
Hello again @Vizz85 

There is a bug that is preventing this from working as described in the UI note - https://github.com/wp-media/wp-rocket/issues/3118

Sorry about the confusion.

**Comment by Vizz85** [comment] 2020-10-22 06:52
@arunbasillal for the moment we will stick with this workaround.
Thank you for keeping updating!

**Comment by GeekPress** [comment] 2021-02-05 20:46
I'm closing this issue and we fixed #3118. Excluding the domain should now work as expected.

**Closed by GeekPress** 2021-02-05 20:46 UTC
Labels: invalid, module: minify CSS, priority: low, type: bug
