### ISSUE TITLE
The group "rocket-rucss" does not exist.

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5537] opened 2022-10-29 09:37 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.2.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A couple of cases where RUCSS was stuck on pending had the following error: 

```
RUCSS: No pending jobs are there.
The group "rocket-rucss" does not exist.
```
The group is there on the database. 

Trailing where the message came from: https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L219

Full result of $exception - https://gist.github.com/DahmaniAdame/cb53f509cd06bff076a3df2e469aef08

Going to where the error message comes from:
https://github.com/woocommerce/action-scheduler/blob/fa2bc6a09a1e2bb549ec78eaec547a49d4b2023d/classes/data-stores/ActionScheduler_wpPostStore.php#L715-L718

AS uses `term_exists()` to check if the taxonomy `action-group` has the term `rocket-rucss`. The term exists and is associated to an action if you check the Scheduled Actions page. 

But it still returns false when logged for some reason 🤔

The consequence is that `rocket_rucss_job_check_status` doesn't run and ends up failing. RUCSS is stuck pending.

Re-installing WP Rocket fixed the issue in two cases.

**To Reproduce**
Couldn't replicate it.

**Expected behavior**
The RUCSS shouldn't get stuck on pending. 

**Screenshots**

**Additional context**
Tickets: 

https://secure.helpscout.net/conversation/2041343955/375608/ (fixed by reinstall)
https://secure.helpscout.net/conversation/2047879460/377016/ (fixed by reinstall)
https://secure.helpscout.net/conversation/2006498141/367846/ (older case [discussed on Slack](https://wp-media.slack.com/archives/C029G1B5HD2/p1663173421342779), likely related)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by camilamadronero-zz** [comment] 2022-11-08 20:35
Related https://secure.helpscout.net/conversation/2047164871/376888?folderId=2675957
https://jmp.sh/NdUbcpKd
Re-installing WP Rocket helped too

**Comment by DahmaniAdame** [comment] 2022-11-24 10:39
Related - https://secure.helpscout.net/conversation/2076358699/383851/
Re-installing fixed the issue.

**Comment by camilamadronero-zz** [comment] 2022-11-28 18:56
New case: https://secure.helpscout.net/conversation/2064391726/380873?folderId=2675957
Reinstalling fixed it, too.

**Comment by CrochetFeve0251** [comment] 2022-12-15 14:08
##  Reproduce the problem
I tried to reproduce the problem by deleting directly inside the Database but the group recreates automatically.
Due to that and the fact i don't have more information about user env, I can't reproduce the problem.

**Comment by piotrbak** [comment] 2023-04-14 14:05
It seems that the issue is not reproducible and we don't have any feedback since 6 months. Going to close it.

**Closed as completed by piotrbak** 2023-04-14 14:05 UTC
Labels: type: bug, can't reproduce, priority: low, severity: moderate, module: remove unused css
