### ISSUE TITLE
Delay JS - RegEx error when there are spaces in the </script> tag

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3083] opened 2020-09-10 11:52 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When there are spaces in the `</script>` tag, like `</script >` the RegEx in `preg_replace_callback()`:
```PHP
return preg_replace_callback( '/<script\s*(?<attr>[^>]*)?>(?<content>.*)?<\/script>/Uis', [ $this, 'replace_scripts' ], $html );
```
 will select the content until the next script tag, that doesn't have spaces.

If in that content there are scripts from our default delay JavaScript list, the whole content will be replaced, and the page can break.

You can see the RegEx issue here: [https://regex101.com/r/hZiXud/1/](https://regex101.com/r/hZiXud/1/)

**To Reproduce**

1. Add the following code on a page: http://snippi.com/raw/2uaob82
2. Enable **Delay JS**
3. Check the source code of the cached page for one of the classes in the snippet, e.g. `#thrive`
4. The code will not be there

**Expected behavior**

Properly pick up the closing script tag regardless of whether it includes spaces or not.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1277671782/193430?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment] 2020-12-16 14:18
### Reproduce the issue ✅ 
The issue is reproduced on the provided regex101 link

### Identify the root cause ✅ 
Our current RegEx doesn't plan for spaces inside the closing `</script>` tag, so the match is done on the next matching element instead of the expected one.

### Scope a solution ✅ 
Update the regex as follow: https://regex101.com/r/hZiXud/2

Add a test case with the closing tag contain spaces, to prevent any regression

### Estimate the effort ✅
effort `[XS]`

**Closed** 2021-02-25 17:02 UTC
Labels: effort: [XS], good first issue, module: delay JS, priority: low, severity: moderate, type: bug
