### ISSUE TITLE
Updating WPR options from page edit isnot reflected with single update click while preload is active

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4051] opened 2021-06-15 09:05 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => yes
- Used the search feature to ensure that the bug hasn’t been reported before => 3.9.0.2

**Describe the bug**
Edited WPR options from page edit are not reflected with a single click on the update button. it requires updating twice to see the option reflection.

**To Reproduce**
- Preload is activated
- delayjs , RUCSS, minify js are on
1. Go to home page edit
2. disable delay js and click update
3. check the home page source
4. delay script is still in source

**Expected behavior**
A single click on update shall reflect options on the site

**Screenshots**

https://user-images.githubusercontent.com/76941962/122024571-d83d9580-cdc8-11eb-9df0-4c14dd198f2d.mp4

**Additional context**
- While preload is disabled, options reflected with a single update click normally
- Used settings: http://snippi.com/s/1qwuti3
- Already on trunk

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2022-08-30 12:46
@Mai-Saad It seems to be resolved with 3.12, I'm not able to reproduce it. Feel free to reopen it if there's still something.

**Closed as completed by piotrbak** 2022-08-30 12:46 UTC
Labels: type: bug, module: preload, priority: low, severity: moderate
