### ISSUE TITLE
3.0 Alpha - File Optimization - Make “Safe Mode” default for deferred JS

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#888] opened 2018-03-19 17:35 UTC
In 3.0-alpha5 _Safe Mode_ doesn’t seem to be enabled by default when I enable _Load JavaScript deferred_:

<img width="1091" alt="screen shot 2018-03-19 at 18 25 31" src="https://user-images.githubusercontent.com/308422/37611680-4a7e4e9e-2ba3-11e8-8bf9-a353271513a3.png">

From our collective support experience, that would be a ticket magnet. The overwhelming majority of sites we deal with relies on inline jQuery, so the jQuery file itself must be loaded render-blocking. 

If the thinking behind _not_ making _Safe Mode_ a default is PSI grades, I suggest we work our support replies into the option label somehow.

**Comment by Tabrisrp** [comment] 2018-03-19 18:04
duplicate of #863

**Closed by Tabrisrp** 2018-03-19 18:04 UTC
Labels: duplicate
