### ISSUE TITLE
UI is a little broken due to WP screen options button

### ISSUE THREAD

**Issue by MaximeCulea** [wp-media/wp-rocket#3389] opened 2020-12-06 16:26 UTC
The screen options is pushing all the UI, which cause that some buttons are not displayed well:
![before](https://user-images.githubusercontent.com/5576409/101285820-94e5e700-37e7-11eb-95af-cee8e55c9d35.png)
I am on a screen of 1280*689 with Chrome (Version 86.0.4240.198) using WP Rocket 3.7.5.

After I remove the screen options button, it works well:
![after](https://user-images.githubusercontent.com/5576409/101285822-97e0d780-37e7-11eb-99ca-3592326f86e1.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment] 2020-12-07 10:36
Hello @MaximeCulea 

I hope you are referring to `Screen Options` of WordPress (the drop down deck on the top right). Kieran (from the team) and I checked this independently and we didn't have the `Screen Options` for our WordPress installs on the WP Rocket page. 

![image](https://user-images.githubusercontent.com/5751474/101340495-d9d05300-38a5-11eb-876f-4e71af75026b.png)

Not sure if you are using a plugin that forces this. Nevertheless, the UI needs some love and we are planning to do that in 2021. 

If this isn't a pressing issue, I will close it for now once I have feedback from you. Please let me know if it happens on all your installs.

**Comment by MaximeCulea** [comment] 2020-12-16 10:18
Yeah that's exactly that, the screen options of WordPress ^^
I have checked with no plugin activated and 2020 theme, same issue.

**Comment by piotrbak** [comment] 2023-06-06 07:58
We didn't receive any further feedback about that problem. I'm not able to reproduce it. Feel free to reopen if the issue still persists, steps to reproduce woul dbe appreciated.

**Closed by piotrbak** 2023-06-06 07:58 UTC
Labels: waiting for feedback
