### ISSUE TITLE
Importing settings can throw fatal Cloudflare error

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#240] opened 2016-11-21 16:52 UTC
In some circumstances, importing settings throws a fatal error. Sometimes it can be resolved by enabling the Cloudflare tab first, but not always. 
Sample tickets: 
https://secure.helpscout.net/conversation/279526648/26966/?folderId=377611

https://secure.helpscout.net/conversation/277219624/26622/?folderId=377611

**Comment by Tabrisrp** [comment] 2018-07-25 20:19
Probably duplicate of #1020

**Closed by Tabrisrp** 2018-07-25 20:19 UTC
Labels: duplicate
