### ISSUE TITLE
Respect site's trailing slash settings 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1392] opened 2018-11-28 21:08 UTC
Some customers believe having a trailing slash, or not, is important. We know that it's not a real SEO issue since Google uses the canonical and does not index content with a slash in addition to the version without a slash. 

However, would it be possible to detect a site's permalink settings and add the necessary htaccess rules automatically, to prevent complaints?

It appears to be an approach used by Comet Cache: 
https://github.com/websharks/comet-cache/issues/554#issuecomment-229243833

Caveat: multisite is a bit different and I think requires a different set of rules, so we would have to test carefully for that.

hs tag: `trailing slash`

**Comment by alfonso100** [comment] 2019-06-21 13:31
A customer with trailing slashes disabled is having issues when he adds **Cache Query String(s)
**. 

WP Rocket is creating a separate directory for each version of the same page, the versions are not under the "parent" page, and then rocket_clean_files() fails to clear the versions:

![image002](https://user-images.githubusercontent.com/229406/59925514-a7f7d200-940e-11e9-83f9-10c003d97417.png)

Slack combo: 
https://wp-media.slack.com/archives/C43T1AYMQ/p1560367173060300

Related ticket: 
https://secure.helpscout.net/conversation/871197418/110497?folderId=2683093

**Comment by kierantaylorio** [comment] 2020-10-08 13:01
Related ticket: https://secure.helpscout.net/conversation/1302652926/200364

**Comment by vmanthos** [comment] 2020-10-09 04:46
Slack discussion about this 👆: https://wp-media.slack.com/archives/C43T1AYMQ/p1602157272164400

**Comment by webtrainingwheels** [comment] 2020-10-28 15:11
Just an FYI to @arunbasillal  and @GeekPress 
We have a lot more cases than are listed on this issue. As of today, we have 44 tickets from this year. 
https://secure.helpscout.net/search/?query=tag%3Atrailing%20slash%20after%3A2020-01-01

**Comment by arunbasillal** [comment] 2020-11-05 09:15
Thanks @webtrainingwheels I have added it to a sprint. Let's see how feasible it is.

**Comment by engahmeds3ed** [comment] 2020-11-24 15:01
## Grooming

- [x] **Reproduce the problem**

Reproduced locally by setting the permalink with trailing slash and trying to open any site page without putting this trailing slash and the page doesn't redirect me to the trailing slash page.
Then I deactivated WPR plugin and I can see the redirection happens

- [x] **Identify the root cause**

Wordpress is using `template_redirect` action with priority `10` to manage this canonical redirection
https://github.com/wordpress/wordpress-develop/blob/1856d0fe2ad01b53daaf8338a4250088367ac948/src/wp-includes/default-filters.php#L533

and we use `template_redirect` action with priority `2`
https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Optimization/class-buffer-subscriber.php#L35

So we serve the cache before WP does the redirection.

- [x] **Scope a solution**

Our solution will consist of two parts:-

1. add WP redirection with priority 1 to serve sites without rewrite rules or first cached pages

Here:
https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/subscriber/Optimization/class-buffer-subscriber.php#L35

Add
```
'template_redirect' => [
	[ 'redirect_canonical', 1 ],
	[ 'start_content_process', 2 ],
]
```
and create on this class new method `redirect_canonical` to call wordpress `redirect_canonical` one.

2. add htaccess rule that we already use part of it on our helper if the site has trailing slash or not using this WP function [user_trailingslashit](https://developer.wordpress.org/reference/functions/user_trailingslashit/)

- [x] **Estimate the effort**

[S] Small

**Comment by alfonso100** [comment] 2021-09-14 19:04
another question here: https://secure.helpscout.net/conversation/1629230254/294259?folderId=2683093

**Comment by piotrbak** [comment] 2022-05-03 16:18
Closing it in favour of #5003. 

@engahmeds3ed 
```
add WP redirection with priority 1 to serve sites without rewrite rules or first cached pages
```

This one is not happening, since we're serving cache files before WordPress is loaded.

**Closed by piotrbak** 2022-05-03 16:18 UTC
Labels: type: enhancement, module: cache, priority: medium, effort: [S]
