### ISSUE TITLE
There is way to stop preload

### ISSUE THREAD

**Issue by kevin25** [wp-media/wp-rocket#1308] opened 2018-11-07 14:36 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
Yes, i'm on 3.2
**Describe the bug**
I checked the server log access and found out that the site was being preloaded. However, i couldn't see where to stop it.

<img width="786" alt="screen shot 2018-11-07 at 21 33 51" src="https://user-images.githubusercontent.com/2909982/48137646-1dc28980-e2d5-11e8-8a87-50000c8ba191.png">

**Comment by kevin25** [comment] 2018-11-07 14:39
I also found something strange with the preload. Why it tried to preload the 

https://domain.com/shop/index.htm and the gzip file ?

<img width="1448" alt="screen shot 2018-11-07 at 20 53 55" src="https://user-images.githubusercontent.com/2909982/48137834-785be580-e2d5-11e8-913b-9da98694c85d.png">

**Comment by arunbasillal** [comment] 2018-11-08 11:38
Hey @kevin25 

This seems like an issue specific to your website. Please open a support ticket: http://wp-rocket.me/support/ and send us the WordPress + FTP logins so that our developers can check this out. 

I am going to go ahead and close this issue since it's not a confirmed bug that can be reproduced. You can simply link to this issue in your ticket so that you do not have to write everything again. 

Cheers.

**Closed by arunbasillal** 2018-11-08 11:38 UTC
