### ISSUE TITLE
Detect if WP Super Cache is active to prevent breaking WP Admin

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#1783] opened 2019-06-10 21:45 UTC
When WP Super Cache is active, and the user tries to install WP Rocket, they get a missleading error message from **WP Super Cache**, so is logical for our customers to think the issue is coming from WP Rocket: 

`Warning!
The file /home/xxx/public_html/rocket2/wp-content/advanced-cache.php already exists. Please manually delete it before using this plugin.`

Then, the WP Admin becomes unusable, if I manually remove advanced-cache.php, WP Rocket recreates it, so the only solution is to manually delete one of the caching plugins 
I saw no warnings of incompatible plugins during my tests. 

Could it be possible to disable WP Super Cache upon activation? Or prevent WP Rocket activation if WP Super cache is enabled? 

Related tickest: 
https://secure.helpscout.net/conversation/874727329/0/?folderId=273761
https://secure.helpscout.net/conversation/874595990/110913/

Video: 
http://recordit.co/hKf7v9eRc7

**Comment by arunbasillal** [comment] 2019-07-03 08:21
The cause is indeed from WP Super Cache - https://github.com/Automattic/wp-super-cache/blob/3a476cc1312754d151a5c7c4afff6e2e00128d01/wp-cache.php#L2610
But the end result is a bad experience when trying to use WP Rocket. 

- We could check if Super Cache is active before changing the contents of `advanced-cache.php`
- Show an admin notice with a link to deactivate WP Super Cache.
- Write into `advanced-cache.php` after deactivation.

**Comment by GeekPress** [comment] 2019-07-06 09:47
Another ticket => https://secure.helpscout.net/conversation/896714317/114736/

@arunbasillal Why don't directly deactivate WP Super Cache when we activate WP Rocket? And then the same for all other conflicted caching plugin.

The user doesn't have to use two caching pluigns. By deactivate it automatically, it's avoid an extra compatibility step for the use.

**Comment by arunbasillal** [comment] 2019-07-11 16:00
This was discussed in the 3.3.6 meeting. 

- Since [WP Super Cache uses](https://github.com/Automattic/wp-super-cache/blob/3a476cc1312754d151a5c7c4afff6e2e00128d01/wp-cache.php#L2610) `wp_die`, there isn't much we can do in terms of notices. 
- We could try and automatically disable WP Super Cache on WP Rocket activation. But we are here trying to fix a problem that is not our own. (This had mixed reactions and we talked about consulting with the support team on the impact and potential issues.)
- As a first step, we could try to have this resolved at WP Super Cache's end. By opening an issue on their public GitHub or sending a PR. 

Either way, we are going to leave this out of 3.3.6

**Comment by GeekPress** [comment] 2020-06-15 12:07
I'm back on this one 👯 

> But we are here trying to fix a problem that is not our own. (This had mixed reactions and we talked about consulting with the support team on the impact and potential issues.)

I'm agree about the fact we are trying to fix something which isn't our fault. For users, it's confused and they don't know the situation. If we can help them automatically, it will be a better user experience for them.

As a first step, we can go further by automatically disable all plugins listed in the default list.

Why?
Most of them are caching plugins, or conflicting plugins which can cause a fatal error on front-end.

We can display a notice to warn the users these plugins has been deactivated to avoid conflicts. Swift Performance is doing that during their onboarding process.

I'm going to close this one and open a new one with this suggestion.

**Comment by iCaspar** [comment] 2020-07-06 19:24
We will be working on this in relation to #2844

**Comment by GeekPress** [comment] 2020-07-24 08:20
I'm closing this one as it's now a duplicate of #2844

**Closed by GeekPress** 2020-07-24 08:20 UTC
Labels: 3rd party compatibility, module: cache, type: bug
