### ISSUE TITLE
High CPU usage related to 3.12 in dashboard only

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5354] opened 2022-08-26 16:11 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
It looks we have kind of loop in dashboard caused by incompatibility with 3rd parties.  Notices are displayed in a loop until the timeout/fatal error happens.

**To Reproduce**
We still don't know how to reproduce it. For now suspected conflicts are:
- Ninja Forms
- WPML
- Extra Product Options for WooCommerce

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/186947401-40bc036d-ef04-433f-87b1-ea03a845b452.png)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment] 2022-08-26 16:12
Potentially related tickets:
https://secure.helpscout.net/conversation/1990980854/364366?folderId=273761
https://secure.helpscout.net/conversation/1990990089/364369?folderId=273761
https://secure.helpscout.net/conversation/1991065735/364385?folderId=273761
https://secure.helpscout.net/conversation/1990685406/364292?folderId=7043481
https://secure.helpscout.net/conversation/1991045594/364381?folderId=273761

**Comment by alfonso100** [comment] 2022-08-26 19:03
Another one: 
https://secure.helpscout.net/conversation/1991254565/364418?folderId=273761

**Comment by alfonso100** [comment] 2022-08-26 19:44
Another case, is related to Ninja Forms. 
Disabling ninja forms, or WP Rocket fixes the issue
After enabling WP Rocket, there is a timeout followed by a 524 error from cloudflare

https://secure.helpscout.net/conversation/1988914598/363935?folderId=2683093

update: the proposed fix worked on this case

**Comment by alfonso100** [comment] 2022-08-26 19:49
This can be reproduced by installing **WP Rocket 3.12.0.3** and **Ninja Forms** 
https://wordpress.org/plugins/ninja-forms/

![QO960oE](https://user-images.githubusercontent.com/229406/186980621-d9fc22de-c9ff-409d-8104-5d5596391c7f.png)

https://i.imgur.com/QO960oE.png

**Comment by alfonso100** [comment] 2022-08-26 20:42
Another one, related to Ninja Forms:
https://secure.helpscout.net/conversation/1990404557/364233?folderId=273761

**Comment by piotrbak** [comment] 2022-08-26 21:10
Problem seems to be related to those specific lines, commenting them out fixes it:
https://github.com/wp-media/wp-rocket/blob/c09453b151d7e94289a2d07bcedae249dd7212ad/inc/Engine/Preload/Admin/Subscriber.php#L47-L48

Solution proposed by @Tabrisrp is to change those lines to:
```
 [ 'maybe_display_preload_notice' ],
 [ 'maybe_display_as_missed_tables_notice' ],
```

It fixes the problem, we need further investigation why it happens only on a very small minority of users.

**Comment by DahmaniAdame** [comment] 2022-08-27 09:03
Related - https://secure.helpscout.net/conversation/1990404062/364232/
Fixed by updating https://github.com/wp-media/wp-rocket/blob/c09453b151d7e94289a2d07bcedae249dd7212ad/inc/Engine/Preload/Admin/Subscriber.php#L47-L48 as provided by the PHP.

**Comment by alfonso100** [comment] 2022-08-27 16:05
Related https://secure.helpscout.net/conversation/1991065735/364385?folderId=273766

**Comment by engahmeds3ed** [comment] 2022-08-29 08:38
Starting from those two lines:

https://github.com/wp-media/wp-rocket/blob/fd8afafcc6c0ab105184febc937ab7f7e59d781b/inc/Engine/Preload/Admin/Subscriber.php#L46-L49

So when we add the subscriber in the event manager class here:

https://github.com/wp-media/wp-rocket/blob/0aed8bdcc0e25845aa0a3f45c49d2a1b9e502e9f/inc/classes/event-management/class-event-manager.php#L45

and will pass the following values
```
  ["subscriber"] => string(41) "WP_Rocket\Engine\Preload\Admin\Subscriber"

  ["hook_name"] => string(13) "admin_notices"

  ["parameters"] => array (
    0 => 'maybe_display_preload_notice',
    1 => 'maybe_display_as_missed_tables_notice',
  )
```

Then it'll get into the following condition

https://github.com/wp-media/wp-rocket/blob/0aed8bdcc0e25845aa0a3f45c49d2a1b9e502e9f/inc/classes/event-management/class-event-manager.php#L112

and based on that, the values that will be passed to add_callback method are as follows:-
```
$hook_name => admin_notices

$callback => [subscriber, 'maybe_display_preload_notice']

$priority => 'maybe_display_as_missed_tables_notice'

$accepted_args => default value is 1
```

Notice that this priority has a string value and this should be number and this is the problem.

the problem is on this line from WP core

https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-hook.php#L85

**So the question is why with some plugins we see this problem like ninjaforms?**
the answer took me a lot of time to know as below:

I logged the `admin_notices` callbacks from WP core and I found as in the following screenshot

![image](https://user-images.githubusercontent.com/15707971/187160218-7f38a46a-84e8-4258-a0f3-7d3b32579601.png)

this callback has more than 25500 lines and this is extremely big number
the problem with ksort, it takes a lot of time when the keys are not numbers as in this case
if u want to make sure of what I mentioned, simply change this line to be any number

https://github.com/wp-media/wp-rocket/blob/fd8afafcc6c0ab105184febc937ab7f7e59d781b/inc/Engine/Preload/Admin/Subscriber.php#L48

Also as @Mai-Saad mentioned, the issue is happening only with PHP >= 8

I'm going to create a PR for this now.

**Comment by alfonso100** [comment] 2022-08-29 13:51
related: https://secure.helpscout.net/conversation/1990990089/364369/

**Closed as completed** 2022-08-29 15:53 UTC
Labels: priority: 🔥critical, severity: critical, module: user interface
