### ISSUE TITLE
Minified JS files are generated and deleted right away the first time "Minifiy Javascript files" is enabled

### ISSUE THREAD

**Issue by Davidacu** [wp-media/wp-rocket#2973] opened 2020-08-07 18:15 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
The first time "Minify Javascript files" is enabled, if you navigate to the home page, and open the page source, you'll notice the links point to the `wp-content/cache/min/` directory, however when you click on the URL it returns 404, the file does not actually exist.

**Preconditions:**
1. Start with "Minify Javascript files" disabled.
2. A site with JS files

**To Reproduce**
1. Go to WP Rocket Settings -> File Optimization
2. Enable "Minify Javascript Files" and click "Save Changes"
3. Navigate to the site home page
4. Open the page source
5. Scroll to where the script is located
6. Click on the URL pointing to the cached file.

**Expected behavior**
It should open the minified JS file.

**Actual behavior**
Page is not found.
https://screencast-o-matic.com/watch/cYjioCGIVZ

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jazir555** [comment] 2021-02-02 06:40
Should be considered a major bug, anything related to the homepage is critical

**Comment by Mai-Saad** [comment] 2021-02-25 15:48
Scenarios to be checked once this issue is fixed:
Scenario1 => Reproduce steps:
1- nothing enabled in file optimization + CDN enabled
2- clear cache
3- enable minify js
4- visit the home page -> check min folder in cache "js files added in 1 folder"
5- change CDN and save -> here the js files in min/1 are deleted
6- hard refresh the home page
7- Check cache/min/1 -> js files not added

Scenario 2 => steps:
1- minify js enabled + CDN not enabled
2- visit the home page and check min/1 folder "js files are there"
3- enable CDN and check min/1 folder "js files removed"
4- visit the home page and check min/1 folder " js files still not added"

**Comment by remyperona** [comment] 2021-02-25 19:17
### Reproduce the issue ✅ 
Reproduced on dev install

### Identify the root cause ✅ 
The issue is coming from the code in this function: https://github.com/wp-media/wp-rocket/blob/5db4357e030936938828aa2edb890e038f486a0f/inc/admin/options.php#L19

The order of events is causing it: 
- first we preload the homepage
- Then we remove the minify JS files if the option changed
- The minify files are created and removed right away
- 404 when checking the homepage

The issue is only happening when changing the value of the minify JS option, exclude JS, or the CDN/CDN cnames

### Scope a solution ✅ 
We should extract the part related to the minify JS clearing to its own subscriber, like we did for the CSS: https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/Minify/CSS/AdminSubscriber.php

- Create `Engine\Optimization\Minify\JS\AdminSubscriber`
- Replicate the `CSS\AdminSubscriber`, adapting it to the JS context
- Add automated tests for the methods
- Instantiate & load the new Subscriber

### Estimate the effort ✅
Effort `[S]`

**Comment by Mai-Saad** [comment] 2021-04-29 10:48
Another scenario to consider:
Nothing enabled in optimization tab
steps:
1- enable minify & combine then save
2- Open home page and check console => error 404 in the console for the combined file
Note: in order to work, we need to enable minify 1st and save then enable combine and save

**Comment by remyperona** [comment] 2021-04-29 22:09
This scenario will also be fixed by the above solution

**Comment by Khadreal** [comment] 2024-01-22 14:02
@CrochetFeve0251 is it safe to assume that this PR https://github.com/wp-media/wp-rocket/pull/4909 resolve this ?

**Comment by CrochetFeve0251** [comment] 2024-01-22 14:10
> @CrochetFeve0251 is it safe to assume that this PR #4909 resolve this ?

It is not totally fresh and so it needs to  be checked to see if it is still working but to answer your question yeah it was written to solve this issue.

**Comment by Mai-Saad** [comment] 2024-02-13 15:33
Waiting feedback here https://wp-media.slack.com/archives/CUT7FLHF1/p1707834278358939?thread_ts=1707828082.142109&cid=CUT7FLHF1

**Comment by MathieuLamiot** [comment] 2024-02-14 14:38
Can't reproduce

**Closed by MathieuLamiot** 2024-02-14 14:38 UTC
Labels: type: bug, waiting for feedback, priority: medium, effort: [S], severity: major, module: minify JS
