### ISSUE TITLE
Used CSS - 404 error with chinese encoded URI CSS

### ISSUE THREAD

**Issue by Hunting4you** [wp-media/wp-rocket#4154] opened 2021-07-13 12:44 UTC
Apache will reply 404 when there is woocommerce product with chinese slug

**Comment by piotrbak** [comment] 2021-07-13 12:55
Most likely related:
https://github.com/wp-media/wp-rocket/issues/3968

**Comment by GeekPress** [comment] 2021-07-16 16:03
Closing, a duplicate of #3968

**Closed as completed by GeekPress** 2021-07-16 16:03 UTC
Labels: duplicate, module: remove unused css
