### ISSUE TITLE
Delay JS (user interaction) breaks website in latest firefox

### ISSUE THREAD

**Issue by tommy83** [wp-media/wp-rocket#4007] opened 2021-06-06 09:11 UTC
Install latest version of firefox.
latest wordpress
latest elementor pro
PHP 7.4
Activate WP Rocket 3.9.1
Caching all pages.

1. Open website with elementor post grid.
2. Move the mouse: the JS is not running and style of grid is broken.
3. After 10 tests only 3 times it was working correct.
In Chrome its working fine.

See also attached via for testing via firefox and chrome:
https://streamable.com/tudzro

We cant tell our visitor to use only firefox because we are using wp rocket and the default elementor post grid widget. ;-)
Adding this line to exclude section also not help:
(?:wp-content|wp-includes)((.*)
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
js-(before|after)

**Comment by piotrbak** [comment] 2021-06-07 12:27
It's the same issue as this one:
https://github.com/wp-media/wp-rocket/issues/4004

Firefox seems to work different when accessing directly the URL (or refreshing the page) than it works when clicking on the link.

**Comment by GeekPress** [comment] 2021-06-07 13:38
Duplicate of #4004

**Closed as completed by GeekPress** 2021-06-07 13:38 UTC
Labels: duplicate
