### ISSUE TITLE
Exclude Usercentrics Domain from Minify JavaScript files

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4734] opened 2022-02-16 00:00 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Yes
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
Minify JavaScript files prevents the cookie banner from being shown

**To Reproduce**
1. Activate Minify JavaScript files on a site
2. Integrate [usercentric's](https://usercentrics.com/) cookie banner 
3. See the site
4. The cookie banner is not shown: https://jmp.sh/r9MyERu. There is no console error.
5. We have to exclude app.usercentrics.eu from Minify JavaScript files for the banner to be visible.

**Expected behavior**
The usercentric's domain is automatically excluded from Minify JavaScript files, and the banner is visible: https://jmp.sh/kAP9vcv.

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1644526736618349
Ticket: https://secure.helpscout.net/conversation/1781440143/324864/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2022-04-12 17:29
Duplicate of #4898

**Closed as completed by remyperona** 2022-04-12 17:29 UTC
Labels: duplicate
