### ISSUE TITLE
Fatal Error: Argument #3 ($code) must be of type int, string given

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6714] opened 2024-06-10 15:56 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
The following error is logged sometimes. In both cases we have, it was for version 3.16:

`Fatal error: Uncaught TypeError: WP_Rocket\Engine\Common\Database\Queries\AbstractQuery::update_message(): Argument #3 ($code) must be of type int, string given, called in /home/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Common/JobManager/Managers/AbstractManager.php on line 204 and defined in /home/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Common/Database/Queries/AbstractQuery.php:578`

Full trace here - https://secure.helpscout.net/conversation/2621067830/496192#thread-7885680013

In the related files, I see the 3rd argument with default set as `int` in one case:
https://github.com/wp-media/wp-rocket/blob/d4319347ba6f301ab52ebfe6d1154fef7708dc8c/inc/Engine/Common/Database/Queries/AbstractQuery.php#L578

While here I see it as `string`:
https://github.com/wp-media/wp-rocket/blob/d4319347ba6f301ab52ebfe6d1154fef7708dc8c/inc/Engine/Common/JobManager/Managers/AbstractManager.php#L199

**To Reproduce**
Unfortunately, I'm not completely sure how to reproduce it.

**Expected behavior**
We should protect against this kind of error.

**Additional context**
Ticket1 - https://secure.helpscout.net/conversation/2621067830/496192
Ticket2 - https://secure.helpscout.net/conversation/2606889904/493486/#thread-7840276870
Slack - https://wp-media.slack.com/archives/C43T1AYMQ/p1718027695573349

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment] 2024-06-21 13:30
Might be a duplicate of https://github.com/wp-media/wp-rocket/issues/6395

**Comment by johan-las** [comment] 2024-07-09 16:27
HelpScout similar tickets:
https://secure.helpscout.net/conversation/2647601826/501808/
https://secure.helpscout.net/conversation/2627965189/497805/

**Comment by Tabrisrp** [comment] 2024-07-17 13:18
There is an issue in our code related to the `update_message()` methods:
-https://github.com/wp-media/wp-rocket/blob/ae4f3d4c408f38b0dd7180f9d937712b3c3c30cc/inc/Engine/Common/JobManager/Managers/AbstractManager.php#L199
- https://github.com/wp-media/wp-rocket/blob/ae4f3d4c408f38b0dd7180f9d937712b3c3c30cc/inc/Engine/Common/Database/Queries/AbstractQuery.php#L582
First method `$error_code` type is `string`. Second method `$code` type is `int`

**Comment by joejoe04** [comment] 2024-07-26 16:10
Related:
https://secure.helpscout.net/conversation/2663017874/504691/

**Comment by alfonso100** [comment] 2024-08-12 21:10
related https://secure.helpscout.net/conversation/2677458637/507259/

**Comment by joejoe04** [comment] 2024-08-16 16:32
Related: https://secure.helpscout.net/conversation/2681617659/507933/

**Comment by alfonso100** [comment] 2024-08-16 19:09
related https://secure.helpscout.net/conversation/2681755693/507950

**Comment by joejoe04** [comment] 2024-08-19 13:32
Related: https://secure.helpscout.net/conversation/2682126241/507985

**Comment by Adrianadla** [comment] 2024-08-19 15:35
Related:
https://secure.helpscout.net/conversation/2683561186/508253/

**Comment by joejoe04** [comment] 2024-08-21 16:28
Related: https://secure.helpscout.net/conversation/2685335823/508532/

**Comment by Miraeld** [comment] 2024-09-02 08:55
## Reproduce the problem
Well, there isn't a proper way to reproduce the issue, however, we could hard code a string in `$job_details['code']` here https://github.com/wp-media/wp-rocket/blob/2b2243e08aecf0d7618179106c2a133749762e47/inc/Engine/Optimization/RUCSS/Strategy/Strategies/DefaultProcess.php#L108
This would ensure to get the same error as reported.

## Identify the root cause
The issue is that a `string` is given in the `update_message` method while it's waiting for an `int`.

## Scope a solution
To solve the issue we could force the cast of`$job_details['code']` to an `int` . So in case this is a `string` with an actual number it would output its `int` version otherwise it would return `0`. 
To do that, we can modify [this line](https://github.com/wp-media/wp-rocket/blob/2b2243e08aecf0d7618179106c2a133749762e47/inc/Engine/Optimization/RUCSS/Strategy/Strategies/DefaultProcess.php#L108) by : 
`$this->used_css_query->update_message( $row_details->id, (int) $job_details['code'], $job_details['message'], $row_details->error_message );`

Also, 
We can modify the parameter `$error_code` in [this function](https://github.com/wp-media/wp-rocket/blob/7cab3aa6e7a3d8566e4f8abb7e575f7f9d4c4a50/inc/Engine/Common/JobManager/Managers/AbstractManager.php#L199) in order to typehint as an `int`. 



## Effort estimation: 
S
## Is a refactor needed in that part of the codebase?
No

**Comment by remyperona** [comment] 2024-09-03 13:49
@Miraeld Shouldn't there also be some standardization of the typehint for both `update_message()` methods, so that they both expect a `int`, instead of one expecting a `string` and the other a `int`?

**Comment by Miraeld** [comment] 2024-09-23 10:21
Updated grooming

**Comment by Miraeld** [comment] 2024-09-26 14:05
Draft PR: 
https://github.com/wp-media/wp-rocket/pull/6992

**Closed as completed** 2024-09-27 08:25 UTC
Labels: type: bug, effort: [S], module: OCI
