### ISSUE TITLE
RUCSS may break layout on customized pages which URL contains query string

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4964] opened 2022-04-25 15:52 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.0.5
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When URL containing a query string like `https://example.com/shop/?rv-products=1234` has a different layout from the `https://example.com/shop/` Remove Unused CSS will break the layout of the page when caching and optimization are forced with the **Cache Query String** option.

This is happening because we are sending `https://example.com/shop?nowprocket=1` to our SaaS here:
https://github.com/wp-media/wp-rocket/blob/6f905396f43c1831c370848e9c36bf14e72ab545/inc/Engine/Optimization/RUCSS/Frontend/APIClient.php#L28
regardless of the query string value.

When `https://example.com/shop?nowprocket=1` doesn't contain some CSS files, it is not possible to safelist the selectors and the layout will look totally or partially broken depending on how many stylesheets or inline CSS are missing.

**To Reproduce**
Reproduced on a customer's site where products are created with URLs with query strings.

**Expected behavior**
We need to take into account the query string value when URL is sent to SaaS.

**Screenshots**
In the note of the ticket: 
https://secure.helpscout.net/conversation/1859344376/339056/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment] 2022-09-13 07:10
https://secure.helpscout.net/conversation/2001306081/366806 (same website)

@piotrbak the issue is that we don't process RUCSS for URLs with query strings. We just send the RUCSS built for the URL without the query string to any matching URL. 

It's not common to have that, but it's still a scenario that we should consider and accommodate to.

Maybe a filter to use when appropriate?

**Comment by DahmaniAdame** [comment] 2022-09-13 07:42
It can be temporarily sorted out by excluding the problematic query strings from Remove Unused CSS using https://github.com/wp-media/wp-rocket-helpers/tree/fb56cec80e6ef5c21fd2538e1b4726d2bc9b2518/rucss/wp-rocket-conditionally-disable-remove-unused-css

**Comment by GeekPress** [comment] 2022-10-26 08:25
I think it's going to be hard to find a solution here.

We can send a query string to SaaS, but how will we know the right value of the query string?

**Comment by GeekPress** [comment] 2023-06-22 08:47
Closing this one as no solution can be find.

**Closed as completed by GeekPress** 2023-06-22 08:47 UTC
Labels: type: enhancement, wontfix, 3rd party compatibility, priority: low, module: remove unused css
