### ISSUE TITLE
License data not available when cloning to staging server

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2456] opened 2020-03-19 14:40 UTC
**Describe the bug**
After enabling WP Rocket on a production site, and generating a staging website WP Rocket can't be activated because there is no license data available

**To Reproduce**
1. Install WP Rocket on production site
2. Clone to a staging site
3. Verify if the license is active or can be activated

**Expected behavior**
When cloning from production to staging, the WP Rocket license information should be kept.

**Screenshots**
![Captura de pantalla 2020-03-19 a las 11 32 45](https://user-images.githubusercontent.com/229406/77078720-bbec5680-69d5-11ea-8ce4-6c01e8958f33.png)

**Additional context**
Slack convo: https://wp-media.slack.com/archives/C08N8J6VC/p1584556692193700
I have created a staging site using WP Staging. Cloned from production https://rocket.alfonsocatron.com/
to staging
https://rocket.alfonsocatron.com/staging/
at the staging environment, I can’t activate WP Rocket because the license data is empty.
Reuploading the **license-data.php** file allows activating WP Rocket

These seem relevant: 
- https://github.com/wp-media/wp-rocket/issues/2456#issuecomment-604410958
- https://github.com/wp-media/wp-rocket/issues/2456#issuecomment-660229555

**Comment by vmanthos** [comment] 2020-03-20 06:07
Another ticket: https://secure.helpscout.net/conversation/1114379818/152705?folderId=2135277

**Comment by GeekPress** [comment] 2020-03-20 20:57
@alfonso100 During the migration, does the database has been migrated?

**Comment by alfonso100** [comment] 2020-03-26 12:46
@GeekPress yes, the DB is automatically migrated by the plugin. in this case, the staging database shares the same DB, just changing the prefix

**Comment by GeekPress** [comment] 2020-03-27 09:04
This is weird, if we have the license info in the DB, it shouldn't cause this issue.

@Tabrisrp Do you have an idea?

**Comment by vmanthos** [comment] 2020-03-27 10:36
I used the [WP Staging – DB & File Duplicator & Migration](https://wordpress.org/plugins/wp-staging/) plugin to create a staging site for a test I was running.

I didn't get the issue as Alfonso did.

The **license-data.php** wasn't there, but WP Rocket was properly activated on the staging site.

WP Rocket 3.5.1 was installed on the production site.

**Comment by arunbasillal** [comment] 2020-07-17 17:07
I had one of these issues where the prefix was different on staging and production. Exactly as this one - https://github.com/wp-media/wp-rocket/issues/2456#issuecomment-604410958

@vmanthos In your test, was the staging and the production using different prefixes?

**Comment by vmanthos** [comment] 2020-07-20 04:31
@arunbasillal I don't remember. 😟

Let me know if you want me to check this again.

**Comment by Tabrisrp** [comment] 2020-12-17 20:28
@arunbasillal This seems very difficult to fix without significant change to the interface to allow input of the license data directly from the UI.

The plugin is relying on either the presence of the `licence-data.php` file, the constants somewhere (likely in `wp-config.php`), or the values being saved in the database.

If the database is not correctly transferred during cloning, we can't really do anything about it.

**Comment by arunbasillal** [comment] 2020-12-21 07:05
@Tabrisrp In this comment - https://github.com/wp-media/wp-rocket/issues/2456#issuecomment-604410958 Alfonso noted that the DB prefix was different between the staging and the production. Do you think this could be a reason?

**Comment by engahmeds3ed** [comment] 2021-02-04 12:37
@wp-media/productrocket 

We are searching firstly on the constants here

https://github.com/wp-media/wp-rocket/blob/5434080ccd89b36f3312846e4288a50c9d6b7c3e/inc/classes/admin/class-options-data.php#L64-L68

and then if not found, it will get them from DB so Db prefix change doesn't make such issue as we are using the WP options API so we are searching for license details on options table, option_name = `wp_rocket_settings`

so I see that we can check with wpstagecoach why this license-data.php file is not transferred at all?

**Comment by GeekPress** [comment] 2021-02-04 13:59
> so I see that we can check with wpstagecoach why this license-data.php file is not transferred at all?

@engahmeds3ed  The license-data.php is deleted after the first activation since 3.6

**Comment by engahmeds3ed** [comment] 2021-02-04 15:10
So the license data should be migrated with the DB and in case the settings/DB wasn't migrated properly and constants are not there, so we don't have anything to do here.

@alfonso100 if u have any input here.

**Comment by piotrbak** [comment] 2023-06-05 11:11
Closing it, since it's a duplicate of:
https://github.com/wp-media/wp-rocket/issues/2804

**Closed by piotrbak** 2023-06-05 11:11 UTC
Labels: type: bug, priority: low, needs: grooming, severity: major
