### ISSUE TITLE
Help beacon is hidden after enable Short Pixel AI plugin 

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4393] opened 2021-09-28 14:55 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.4.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Help beacon icon is not displayed if Short Pixel AI is enabled 

**To Reproduce**
1. Install and activate Short Pixel AI (LL settings enabled) v2.3.3
2. Open any tab in the WPR settings
3. No Help Beacon

**Expected behavior**
Help Beacon is there even if Short Pixel AI is activated

**Screenshots**
![Screenshot from 2021-09-28 14-06-23](https://user-images.githubusercontent.com/76941962/135111710-8972aba8-fe54-466c-b64b-fd9d7c5f15ec.png)

**Additional context**
- If we opened any more info link => we won't be able to close thread till refresh the page

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment] 2021-10-05 19:30
### Reproduce the issue ✅ 
Reproduced the issue on testing site

### Identify the root cause ✅ 
This is happening because Shortpixel AI is loading their admin CSS on all admin pages, and they have custom rules for Beacon that are hidding the button (among others).

### Scope a solution ✅ 
This should be reported and fixed on ShortPixel AI side, they are not taking into consideration conflicts by loading their CSS this way.

**Comment by piotrbak** [comment] 2023-06-06 13:28
It's working as expected now.

**Closed as completed by piotrbak** 2023-06-06 13:28 UTC
Labels: type: bug, 3rd party compatibility, Module: dashboard, module: Beacon, priority: low, severity: moderate
