### ISSUE TITLE
wp rocket slow down ajax in elementor.

### ISSUE THREAD

**Issue by Michaelgimii** [wp-media/wp-rocket#5284] opened 2022-07-29 14:58 UTC
**Describe the bug**

I design a store website using elementor, jet plugins (jet woobuilder, jet smart filters & jet compare & wishlist) and hello elementor theme. In fact, adding to cart, applying filters, adding to favorites and comparing are done in Ajax.
When wp rocket is active, Ajax speed will be between 2 and 4 seconds. But when I disable wp-rocket, ajax speed is super fast. It even works in less than a second.
Please check this issue. As you know, elementor is the biggest WordPress page builder. In addition, jet plugins are very popular. So this topic can include many of your users.

thank you

**Comment by piotrbak** [comment] 2022-07-29 15:00
Hello @Michaelgimii isn't it a duplicate of this issue?
https://github.com/wp-media/wp-rocket/issues/5245

**Comment by Michaelgimii** [comment] 2022-07-29 15:36
hello @piotrbak , No, I don't think so. This is related to Ajax request. It seems that the cause of this problem may be that wp-rocket is not compatible enough with jet plugins. Because Ajax is widely used in two plugins, Jet woobuilder and Jet Smart Filters. Please check these if possible Maybe you need to pay more attention to jet plugins
Anyway, thank you

**Comment by 79ho3ein** [comment] 2022-07-29 15:37
I can confirm this too. wp-rocket really slows down ajax in elementor and jet plugins.

**Comment by jazir555** [comment] 2022-07-31 03:14
I have the same issue with woolentor

**Comment by pmochine** [comment] 2023-09-22 12:49
Not sure if this is relevant, but I noticed that jet smart filters is using the POST admin-ajax.php link to fetch the data. However, the setting of heartbeats in WP-Rocket is delaying the use of admin-ajax.php. So I just deactivated the setting.

**Comment by piotrbak** [comment] 2024-06-27 12:46
The issue is not relevant anymore. If it reappears, we'll reopen it.

**Closed as not planned by piotrbak** 2024-06-27 12:46 UTC
