### ISSUE TITLE
Compatibility Issue with WPEngine

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#281] opened 2017-01-03 15:33 UTC
Sometimes the config updater does the following

```
define('WP_DEBUG', false);

# That's It. Pencils down
if ( !defined('ABSPATH') )
define('ABSPATH', dirname(__FILE__) . '/');
require_once(ABSPATH . 'wp-settings.php');

$_wpe_preamble_path = null; if(false){}


define('WP_CACHE', true); // Added by WP Rocket
```

Causing the minify to never work

**Comment by glueckpress** [comment] 2017-04-29 16:54
@pcfreak30 Can that behaviour be reproduced?

**Comment by pcfreak30** [comment] 2017-04-30 08:29
its random unfortunately. I have not found any test case yet to narrow, just that on some sites, when initially installing it happens and I have learned to check.

**Comment by arunbasillal** [comment] 2019-01-29 05:07
Have you ever seen this since @pcfreak30 ?

**Comment by pcfreak30** [comment] 2019-01-30 20:23
I have not worked on WPEnginbe for a while now, so I can not say.

**Comment by arunbasillal** [comment] 2019-03-25 16:26
Since we have a good number of WP Engine users and haven't spotted this issue lately, I suppose its best to close this now and revisit if we ever see this again. 

@Tabrisrp Inviting your judgement.

**Comment by GeekPress** [comment] 2020-05-21 09:32
I'm closing this one as we don't seem to have any bugs reported by other customer since all this time.

**Closed by GeekPress** 2020-05-21 09:32 UTC
Labels: 3rd party compatibility, module: cache, needs: testing
