### ISSUE TITLE
[WIP] WooCommerce Multilingual currency switcher compatibility code is not stable

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5012] opened 2022-05-05 12:58 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**

When WooCommerce Customer Location is set to Geolocate [our code](https://github.com/wp-media/wp-rocket/blob/6f905396f43c1831c370848e9c36bf14e72ab545/inc/3rd-party/plugins/ecommerce/woocommerce-multilingual.php#L72-L75) should be setting mandatory cookie `wcml_client_country`.

In some circumstances, the value of the condition `apply_filters( 'wcml_geolocation_is_used', false )` is changing every few minutes from `true` to `false` and so on. This also causes our `wp-rocket-config` to be regenerated at every change every few minutes. Sometimes it adds the mandatory cookie, sometimes - not, depending on what value of the filter got registered last.

The problem seems to be happening within `isUsed` function here: `/plugins/woocommerce-multilingual/classes/multi-currency/geolocation/geolocation.php`

This GH is created to monitor similar cases.

Possibly our compatibility code needs a more reliable condition.

**To Reproduce**
Reproduced on a customer's site and on the staging site when a default theme is used and non-related plugins are deactivated.
WP StageCoach Staging site: https://secure.helpscout.net/conversation/1847038257/337338?folderId=3864740#thread-5515723784

**Expected behavior**
Mandatory cookie `wcml_client_country` should be set in `wp-rocket-config` when WooCommerce Customer Location is set to Geolocate.

**Additional context**
Error logs: https://secure.helpscout.net/conversation/1847038257/337338?folderId=3864740#thread-5501815925
Slack: https://wp-media.slack.com/archives/C08N8J6VC/p1651071791738309

Thanks to @piotrbak for help with this case.

We are already in touch with @strategio regarding the case.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by strategio** [comment] 2022-05-06 18:24
Hi @NataliaDrause,

I've managed to reproduce the issue with the customer's dump and I believe it's an edge depending on initial settings.

You can try the following patch. Edit the file `wp-content/plugins/woocommerce-multilingual/inc/currencies/class-wcml-multi-currency.php` on line 332 and replace:

```php
if ( $save_to_db ) {
```

with:

```php
if ( $save_to_db && is_admin() ) {
```

I could verify it's actually fixing the problem on the client's dump and I believe it's an harmless change for us.

We are about to release a major new version for WooCommerce Multilingual and if our QA pipeline does not detect any problem, this fix will be included (I'll update here otherwise).

Thanks,
Pierre

**Comment by NataliaDrause** [comment] 2022-05-08 15:11
thank you @strategio !

This resolved the problem on the staging site I have.
I am checking with the customer, if it is also resolved for them (I don't have access any longer). I will update when I hear from them.

**Comment by NataliaDrause** [comment] 2022-05-10 07:24
@strategio the fix is working on the customer's staging site. It looks like it is good to go!

**Comment by Sh4d0wHunt3rX** [comment] 2022-09-19 08:34
Hi @strategio and @NataliaDrause . Few days ago I was working on a client's site and I noticed, in first load, the wp rocket is not working and when refresh the page, the wp rocket works. I noticed the client has "WooCommerce Multilingual & Multicurrency with WPML" and the cookie of "wcml_client_country" is empty, that was the reason. Client had last version of all plugins. 

So, have you fixed this issue? Because seems it still exists.

Thanks

**Comment by strategio** [comment] 2022-09-19 20:55
Hi @amiremami,

This issue has been fixed in WCML 5.0.0 released in May (now 5.0.2).
I cannot close this ticket (@NataliaDrause should do so now).

@amiremami, could you please create another ticket?

**Comment by Sh4d0wHunt3rX** [comment] 2022-09-19 20:57
Thanks. Ok, the client was using 5.0.2 and the issue was still there. I will create another ticket.

**Comment by piotrbak** [comment] 2022-09-20 10:58
Hello @amiremami thanks for your comment. The behaviour you described here:
`Few days ago I was working on a client's site and I noticed, in first load, the wp rocket is not working and when refresh the page, the wp rocket works`

Is expected behaviour when mandatory cookies are used. Please check the following documentation article:
https://docs.wp-rocket.me/article/1313-create-different-cache-files-with-dynamic-and-mandatory-cookies

If you have any further questions or concerns, please reach our Support Team.

**Closed as completed by piotrbak** 2022-09-20 10:58 UTC
Labels: type: bug, 3rd party compatibility, module: cache, priority: medium, severity: moderate
