### ISSUE TITLE
Combine Google Fonts breaks JetMenu data-menu-options

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2561] opened 2020-04-21 12:02 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Tested with WP Rocket 3.5.2 and JetMenu Version 2.0.3

**Describe the bug**
When a Google font is used in **Jetmenu** settings, and **Combine Google Fonts** is enabled at WP Rocket, JetMenu will add its own google font tag. If the theme already has another google font tag, the combined file will get injected twice at the HTML, the usual injection and another one inside JetMenu _data-menu-options_ object, breaking the menu functionality.

**To Reproduce**
1. Go to JetMenu settings
2. Choose a Google Font
3. Enable Combine Google Fonts
4. The menu won't work anymore.

**To Reproduce (if you don't have a copy of JetMenu)**
1. Add these font tags to the head: http://snippi.com/s/g2eavfz
2. Add this menu markup to the body: http://snippi.com/s/xk7sha8
3. Enable Combine Google Fonts
4. The menu markup will be rewritten, including the Combined Google Font link.

**Expected behavior**
Enabling Combine Google Fonts shouldn't break the menu functionality

**Screenshots**
![Screenshot at abr  21 09-00-39](https://user-images.githubusercontent.com/229406/79863802-c328ca80-83ae-11ea-8259-53f72efd5ae3.png)

**Additional Information**
Related HS Ticket: https://secure.helpscout.net/conversation/1141442668/159225?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment] 2020-04-27 10:53
**Reproduce the issue** ✅ 
Identified this issue on localhost.

**Identify the root cause** ✅ 
The root cause is that JetMenu contains SVG which contains `<title></title>` and Google Fonts is appended after `</title>` in here:
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/Engine/Optimization/GoogleFonts/Combine.php#L79

**Scope a solution** ✅ 
The solution will be to exclude the replace when <title> tag is inside a <svg> tag.

**Effort** ✅ 
Effort `[S]`

@hellofromtonya , @Tabrisrp any other ideas on how to exclude it in here?

**Comment by Tabrisrp** [comment] 2020-04-27 13:19
There is also the possibility to use `preg_replace` instead of `str_replace` and use the `limit` attribute to perform the insertion only once.

Since we want to target the `</title>` tag in the `<head>`, it's very unlikely that another closing tag would be before the one for the page.

**Comment by hellofromtonya** [comment] 2020-04-27 13:39
As @Tabrisrp said, we need to target within the `<head>` element only. How can we do that?

1. Use `DomDocument` to get the `<head>` and then insert after the `<title>` element.
2. Build regex that targets `</title>` within the `<head></head>`.

Either approach should work.

**Comment by crystinutzaa** [comment] 2020-04-27 18:56
Because in here there are multiple ways of doing this I was checking on how it should be done.
I would go on targeting with regex `</title>` withing `<head></head>`.

Does this sound good?

**Comment by Tabrisrp** [comment] 2020-04-27 19:01
thatt's the best approach I think yes

**Comment by hellofromtonya** [comment] 2020-04-27 19:42
For now, we'll stick with regex. I'm starting a R&D project to investigate using `DomDocument` with regex fallback for malformed HTML. But until we have that design built and tested, let's stick with regex.

**Closed** 2020-05-13 13:14 UTC
Labels: 3rd party compatibility, effort: [S], priority: medium, type: bug
