### ISSUE TITLE
Precompress static files with gzip

### ISSUE THREAD

**Issue by radeno** [wp-media/wp-rocket#1213] opened 2018-10-01 00:32 UTC
**Is your feature request related to a problem? Please describe.**
Based on tests, there is not so much significant change for small sites, but sites with medium or more traffic it should be some nice difference because dynamic gzipping should increase CPU load.
I think this should be interesting feature for newcoming and out-of-cache visitors.
Scripts and Styles are created at once for long time. No need to compress constantly every request.

Many Wordpress sites handles tens or hundreds of thousands visits per month without CDN.
This should optimize some server resources.

https://royal.pingdom.com/2018/08/15/can-gzip-compression-really-improve-web-performance/
https://css-tricks.com/brotli-static-compression/

**Describe the solution you'd like**
Precompress generated cache files with GZIP.
To be complatible with NGINX there must be suffix `.gz` for example `file.css.gz`.

**Comment by radeno** [comment] 2019-11-27 10:45
Even with Brotli. #1524

**Comment by vmanthos** [comment] 2020-01-08 05:47
Another request about this:
https://secure.helpscout.net/conversation/1047434108/139419/

**Comment by Tabrisrp** [comment] 2020-04-21 19:59
Duplicate of #2465

**Closed by Tabrisrp** 2020-04-21 19:59 UTC
Labels: duplicate
