### ISSUE TITLE
Delay JS - the inline script prevents some JavaScript from firing

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3934] opened 2021-05-20 12:39 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9`
- Used the search feature to ensure that the bug hasn’t been reported before - #3926 is probably related, but it's too specific.

**Describe the bug**

In some cases, despite excluding all files/inline JavaScript from **Delay JavaScript execution**, some JavaScript is not executed until there is interaction with the page.

**screencast:** https://youtu.be/ZuQj-KiNxNk

Removing the inline JavaScript we add in the `<head>` resolves the issue, of course.

**To Reproduce**

There isn't something solid currently. 

On a customer's website, the following `DOMContentLoaded` script didn't fire :
https://snippi.com/s/8emx5tk

**Expected behavior**

Non-delayed scripts should be executed.

**Additional context**

**Tickets:**
https://secure.helpscout.net/conversation/1497405310/259918/ - credentials to a staging site inside
https://secure.helpscout.net/conversation/1518901270/265435/

Probably related: #3926

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2021-05-20 13:09
This one should be related too: https://github.com/wp-media/wp-rocket/issues/3931

**Comment by gayanchandrab** [comment] 2021-05-22 14:56
This is my understanding. I'm not a JS pro. Despite excluding inline/external JavaScript from Delay JavaScript execution, some JavaScript is not executed if the excluded code depends on events like DOMContentLoaded, load or readystatechange. Because these events are delayed from firing by the new Delay JS script. This is how it works and not a bug. But many themes and plugin code depends on these events for correct functionality. I wonder why this was not taken to consideration during development. It's pity because this issue prevents me from using the 3.9 version on client sites to take advantage of very useful Remove unused CSS feature.  I hope you fix this issue soon. Thanks.

**Comment by GeekPress** [comment] 2021-05-23 09:12
@gayanchandrab This is already fixed on our side and we will release a new minor version containing the fix next week.

**Comment by gayanchandrab** [comment] 2021-05-23 10:01
> @gayanchandrab This is already fixed on our side and we will release a new minor version containing the fix next week.

Thanks. I am looking forward to test it.

**Comment by NataliaDrause** [comment] 2021-05-24 05:49
Likely related: https://secure.helpscout.net/conversation/1520454709/265960?folderId=3864740

**Comment by vmanthos** [comment] 2021-05-24 12:35
Related ticket: https://secure.helpscout.net/conversation/1522280871/266329?folderId=2135277

**Comment by jorgemartine00** [comment] 2021-05-26 18:01
Related ticket: https://secure.helpscout.net/conversation/1521233567/266106/

**Comment by NataliaDrause** [comment] 2021-05-30 08:21
Related: https://secure.helpscout.net/conversation/1521265456/266114/

**Comment by NataliaDrause** [comment] 2021-05-30 11:20
Related: https://secure.helpscout.net/conversation/1522588801/266438/

**Comment by juricazuanovic** [comment] 2021-06-01 14:56
Related ticket: https://secure.helpscout.net/conversation/1524168791/266841/

**Closed as completed** 2021-06-02 12:39 UTC
Labels: type: bug, priority: high, severity: major, module: delay JS
