### ISSUE TITLE
Specific CPCSS generation again, 5th time this has happened.

### ISSUE THREAD

**Issue by jazir555** [wp-media/wp-rocket#4274] opened 2021-08-22 11:24 UTC
**Describe the bug**
Specific CPCSS generation will work correctly, and then all of a sudden it will fail continously. It will spontaneously begin working within a day or two

**To Reproduce**
1. Generate specific cpcss
2. The generation will either display a success message or not display a message at all, and cpcss is not actually generated on the frontend, scores do not improve whatsoever to the known improved scores when it does work.

**Expected behavior**
Specific CPCSS generating correctly.

**Additional context**
This is happening constantly. Can you please fix whatever the issue is on your CPCSS server? This is really frustrating.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by androidacy-user** [comment] 2021-08-23 15:50
Do you use cloudflare? When I was having this issue, the WAF was blocking most of the generation requests.

**Comment by remyperona** [comment] 2021-08-23 18:25
Duplicate of #4237

**Closed as completed by remyperona** 2021-08-23 18:25 UTC
Labels: duplicate

**Comment by jazir555** [comment] 2021-08-23 22:43
@androidacybot 

Yes I do use the cloudflare WAF! Is there a a way to whitelist wp-rocket css generation?

Edit: Think I found it: https://docs.wp-rocket.me/article/1267-troubleshooting-critical-css-generation-issues
