### ISSUE TITLE
LazyLoad Youtube videos sometimes require two clicks to start playing

### ISSUE THREAD

**Issue by dropthehate** [wp-media/wp-rocket#1732] opened 2019-05-17 15:21 UTC
**Bug description**
Not everytime, but sometimes, when you click on lazyloaded youtube video, it loads but you need to click play again to start the video. 

At first I thought the problem is on my side, but I updated the plugin to the latest version and it didn't helped. There are no errors in the console too when this happens.
Then I found out that other websites that are using WP Rocket are having the same issue. 
For example, the Elementor website.

Here's a demonstration of how it looks when it happens:
https://www.loom.com/share/1244d12a8bb54fbaa4be3d10a47826fd

**To Reproduce**
Go to https://elementor.com/getting-started/ multiple times using incognito mode and start playing videos until the issue appear. 
You might need some patience though to reproduce it.

**Comment by Tabrisrp** [comment] 2019-07-26 15:17
This is a normal behaviour for mobile, Youtube doesn't allow autoplay on it.

I was not able to replicate the issue on desktop with the example URL provided.

**Comment by arunbasillal** [comment] 2019-09-09 20:00
I am able to reproduce this on a desktop - https://jmp.sh/NXd7UOm

**Comment by Tabrisrp** [comment] 2019-09-09 20:07
See #1934 for desktop, this is new behaviour for Chrome. It's fixed in the standalone plugin, it will be too in 3.5 for WP Rocket.

**Comment by Tabrisrp** [comment] 2019-11-23 16:03
Duplicate of #1934

**Closed by Tabrisrp** 2019-11-23 16:03 UTC
Labels: duplicate
