### ISSUE TITLE
PageSpeed Warning: Need to make fonts.gstatic.com preconnect optional

### ISSUE THREAD

**Issue by mdrejhon** [wp-media/wp-rocket#3636] opened 2021-03-02 08:53 UTC
My business uses a WP Rocket license on a **custom Wordpress theme we created** by @jorimt to accelerate the Blur Busters website.  

But there's some weirdness going on.  I host all fonts via my CDN (paid CloudFlare) instead of Google because I am using certain fonts that (appears) to be infrequently loaded by our users. There were found situations where there was fewer FOUT issues when we used the combination of CloudFlare+Argo Routing (their 79 terabit/sec backbone!) with certain less-frequently-used used font (Patua One).  

WP Rocket insists on an unnecessary preconnect to fonts.gstatic.com that I cannot disable.

1. Run [PageSpeed test on blurbusters.com](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblurbusters.com) 

2. Scroll down "Passed Audits", expand the section, and see the unnecessary preconnect:

> ![image](https://user-images.githubusercontent.com/59981975/109622264-8b77cc80-7b01-11eb-8316-d0aa730fa2ca.png)

3. I have traced this problem to **hardcoded stuff** in WP Rocket's source code at
 `/wp-rocket/inc/Engine/Optimization/GoogleFonts/Subscriber.php`

```
        public function preconnect( array $urls, $relation_type ) {
                if ( ! $this->is_allowed() ) {
                        return $urls;
                }

                if ( 'preconnect' !== $relation_type ) {
                        return $urls;
                }

                $urls[] = [
                        'href' => 'https://fonts.gstatic.com',
                        1      => 'crossorigin',
                ];

                return $urls;
        }

```

**Expected behavior**
Provide an option to avoid preconnecting to gstatic if I'm not loading fonts from Google's CDN.  I use font preloading and optimizations that eliminates the need for any preconnects.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment] 2021-03-02 09:27
Duplicate of #3219

**Closed as completed by GeekPress** 2021-03-02 09:27 UTC
Labels: duplicate, community, module: google fonts
