### ISSUE TITLE
Htaccess corrupted on update

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#928] opened 2018-04-05 21:23 UTC
A few customers report that on occasion, typically when updating, the htaccess file is regenerated with only with our rules and nothing else, creating 404 errors. 
It doesn't seem to happen every time and seems almost impossible to reproduce, yet we have several reports now. 
Is there anything we can do to make sure that at least the default WP rules are placed back into the file?
HS tags: `htaccess`, `update fail`, `error 404`
Intercom report: https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/46787/conversations/15589780670

**Comment by blogtutor** [comment] 2018-08-09 22:48
This just happened again on one of my clients' sites, updating from 3.0.5.1 to 3.1.

The .htaccess file was left with only the WP Rocket 3.1 directives, stripping out other redirects and the standard WordPress .htaccess code.

As a result, every page on her site was a 404 error, except her homepage, resulting in downtime of about two hours until it was reported to us and fixed.  :(

**Comment by blogtutor** [comment] 2018-08-09 22:49
I know this is tough to reproduce, but we really need a solution here.  Maybe every time WP Rocket makes edits to the .htaccess file, it can make a local backup, and then compare the new/old files, and then take action if the code outside of the WP Rocket code has changed?

**Comment by ecotechie** [comment] 2018-08-10 21:28
Same problem here. Today is the fourth time this happens to one of the sites I maintain. Same as above, I updated to 3.1.1 and all directives were removed except the WP Rocket and WordPress ones. Seems like a problem with the code updating the file from previous versions.

**Comment by blogtutor** [comment] 2018-08-14 14:38
@ecotechie Are you sure the WordPress directives weren't removed? I think Cloudways may have already added that back in by the time you got to it.  In the past when I've encountered this issue, only the WP Rocket code was there - everything else was gone.

**Comment by ecotechie** [comment] 2018-08-14 17:58
@blogtutor that may have been the case as there were many fingers on that file when the site stopped loading correctly.

**Comment by blogtutor** [comment] 2018-08-22 21:53
OMG. Yet another client just ran into this issue!  It's a good thing we've got backups of their .htaccess files...

This used to only happen very rarely... this latest update seems to have a much higher rate of occurrence.  :(

**Comment by Tabrisrp** [comment] 2018-08-22 22:16
Are they all hosted on the same hosting provider?

The only function that write to the htaccess is this one https://github.com/wp-media/wp-rocket/blob/master/inc/functions/htaccess.php#L13

And the part that is doing a removing of content is this `$ftmp = preg_replace( '/# BEGIN WP Rocket(.*)# END WP Rocket/isU', '', $ftmp );`

For some reason, it might be that this regex is not working as expected, removing all content instead of only the content between the WP Rocket markers.

a good test to determine if it's indeed the issue would be to check for the regex matching against one of the htaccess affected, on a site like https://www.phpliveregex.com/ for example.

**Comment by blogtutor** [comment] 2018-08-22 22:48
HI @Tabrisrp - thanks for jumping in on this.

Most (maybe all) of the sites where we've encountered this are hosted on Cloudways, either Vultr or Linode servers.

And yep, it sure does sound like that preg_replace function is stripping everything out.

I just tried tinkering with the phpliveregex.com site, but couldn't get it to work quite right.  Here's one of the .htaccess files that was corrupted, maybe you can test it? (I had to rename it to upload here.)
[htaccess.txt](https://github.com/wp-media/wp-rocket/files/2312216/htaccess.txt)

Also, and forgive me if this is a silly question, but why are there a leading slash / and trailing "/isU"  in the preg_replace command?

**Comment by Tabrisrp** [comment] 2018-08-23 15:45
Yes indeed it works correctly for this htaccess file. The issue might be later in function.

Are you able to reproduce the issue everytime if you update/rollback between versions, or is it happening randomly?

**Comment by blogtutor** [comment] 2018-08-23 16:29
Thanks @Tabrisrp. 

We haven't attempted to reproduce the issue on any sites (since these are live sites, after all, and we just wanted to get them working again).  If it happens again on another site, though, we can give that a quick try. 

At this point my hunch is that it's either (1) related to a specific server setting, and/or (2) the method in which the update is run.  (Batch updates page vs. plugins page -- and if other updates are run at the same time).  I just emailed the two most recent clients to see if they remember exactly how they ran the updates.

Also, I just emailed some more sample .htaccess files to Vasilis, per his request. Though there's not too much customization stuff in them, and they're very similar to many other clients who haven't had issues (such as http->https redirects).

**Comment by blogtutor** [comment] 2018-08-23 22:36
Heard back from one client about her upgrade process:

> I did the updates from the Dashboard> Updates. I did update several plugins at once, they were: Wp Rocket, SEO by Yoast and Social Warfare (I remember these exactly). Also Social warfare pro had update but it did not work. So out of 4 plugins, 3 updated and WP Rocket messed up.

**Comment by Tabrisrp** [comment] 2018-08-24 21:28
Currently I'm leaning toward server related issue as, AFAIK, all the cases we had for this were on Cloudways. 

The resulting htaccess does contain the WP Rocket rules, but the rest is stripped out, correct?

**Comment by blogtutor** [comment] 2018-08-24 21:33
All of the recent cases have definitely been on Cloudways. The ones that happened weeks/months ago I don't remember for sure, but odds are good they were also Cloudways.

And yep, the resulting.htaccess contains the new WP Rocket rules (with the newest version number), and that's it.

**Comment by blogtutor** [comment] 2018-08-29 22:03
This just happened again to another client. Same exact situation. She's on Cloudways hosting. She updated to 3.1.3 and ended up with an .htaccess file that had only the WP Rocket stuff -- everything else was stripped out.  Attached are before/after .htaccess files.

She said: "I was on the 'All Plug-ins' page. I updated one plug-in first (I can't remember which) after checking the first box on the UpDraft pop-up. Then I updated the WP Rocket plug-in, but first unchecked the box on the pop-up so I didn't have to wait for additional backup to run."

(So it sounds like she ran plugin updates one-at-a-time, and everything updated correctly, so it seemed.)

[htaccess_original.txt](https://github.com/wp-media/wp-rocket/files/2333801/htaccess_original.txt)
[htaccess_broken-by-update.txt](https://github.com/wp-media/wp-rocket/files/2333811/htaccess_broken-by-update.txt)

**Comment by blogtutor** [comment] 2018-09-04 15:43
@Tabrisrp The problem seems to be getting worse. Over the holiday weekend this happened again on (at least) two more client sites when they updated WP Rocket. Both are on Cloudways. 

Not sure if this info helps, but: One is running:

- Apache/2.4.10 (64-bit #1 SMP Debian 3.16.51-3+deb8u1)
- PHP 7.0.31-1~dotdeb+8.1
- MySQL 5.6.41. 

The other site was running:

- Apache/2.4.10  ( 64-bit #1 SMP)
- PHP 7.2.9-1+0~20180901081207.4+jessie~1.gbpdaac35
- MySQL 5.6.41

We are now desperate for a solution and/or workaround here... how can I help get this resolved?

At the very least, can WP Rocket save a backup of the .htaccess file locally, before making the edits?  Then at least restoring will be much quicker/easier.

Thanks!

**Comment by Tabrisrp** [comment] 2018-09-05 18:27
I'm talking with Cloudways about this too, but they are not able to reproduce this on their side for now. I believe it would be really helpful if you also contact them, and provide them the list of websites where it's happening, because the only recent reports of this issue on our side are coming from you.

**Comment by blogtutor** [comment] 2018-09-05 21:52
Thanks Remy.  I will reach out to them -- with whom have you been talking? I'll try to connect to the same person.

(It also just happened on another client's site.)

Hey, might it be a file permissions issue?  On Cloudways, the master user on the server is something like master_xndjwemw -- but WordPress runs under its own user (whatever the "application" username is).  I run into hassles a lot when the WordPress user creates files (such as when installing a plugin from the repo) that are then owned by the application user name -- and then when I use FTP, logged in with the master_ account, the master_ account doesn't have sufficient permissions to edit those files.  Maybe that has something to do with all this?

**Comment by blogtutor** [comment] 2018-11-09 17:16
Unfortunately, this continues to be a significant problem; it happened again on another clients' site yesterday, and again this morning on a different site. 

Both Cloudways support and I have not been able to replicate the problem with any consistency. 

We need to find some fix, or at least a workaround, for this. This problem takes down sites completely (except for the homepage). Many of my clients are very high-traffic sites and downtime costs them hundreds of dollars an hour in lost revenue. 

At this point, since we can't isolate the root cause of the problem, can you please at least add some error-checking so that in case it happens, there's an automatic solution in place?

**Comment by blogtutor** [comment] 2018-11-16 15:09
This happened again on another client's site this morning - I hadn't seen this site affected before.  Also on Cloudways. I guess I'll just start adding another comment on this thread every time it happens.

**At this point, since we can't isolate the root cause of the problem, can you please at least add some error-checking so that in case it happens, there's an automatic solution in place?**

**Comment by vmanthos** [comment] 2018-11-20 09:56
A customer has a site on Cloudways. I've updated WP Rocket from 3.1.4 to 3.2.2 without an issue. 

However, when Iopened the _htaccess_ file using Notepad++ I saw this:

![image](https://user-images.githubusercontent.com/193660/48764948-bedc1780-ecb9-11e8-885c-a9b87f92b54b.png)

Above the `NUL`s there were WP Rocket's htaccess rules.

I removed the `NUL`s, saved it to a new file and diff checked the two _htaccess_ files using Meld:

![image](https://user-images.githubusercontent.com/193660/48765083-18444680-ecba-11e8-9f4f-fa882f3b26ae.png)

The original _htaccess_ can be downloaded from this link:
https://mega.nz/#!SpVUnS5S!42C5hVJlEXhL5EssO6QtDtKIc2Z_cho2UiRlykIDlK0

This may or may not be related to this particular issue. However, it's very strange and that's why I'm reporting it here.

**Related ticket:**
https://secure.helpscout.net/conversation/711583715/86840?folderId=2135277

**Comment by webtrainingwheels** [comment] 2018-11-27 15:41
Possible case: https://secure.helpscout.net/conversation/717560494/88121?folderId=273761

**Comment by blogtutor** [comment] 2019-01-29 15:53
Thank you!!  😃

**Comment by blogtutor** [comment] 2019-04-26 23:10
Just had another client on Cloudways with this issue.  It's been happening less often, but clearly it's still a problem.

😢

**Comment by blogtutor** [comment] 2019-05-10 04:26
Yep, just happened again with a different site. Client updated, and boom, the .htaccess file lost everything except the (new) WP Rocket code.

**Comment by blogtutor** [comment] 2019-05-19 01:59
...and it's still happening.  Another client on Cloudways updated from v3.3.3 to v3.3.3.1 ... same exact problem.

@webtrainingwheels any other ideas?

**Comment by blogtutor** [comment] 2019-05-19 02:01
@webtrainingwheels @Tabrisrp Can you please reopen this ticket? It's definitely not solved, unfortunately.

**Comment by blogtutor** [comment] 2019-05-20 01:43
Just happened again on another site. Also hosted on CLoudways.

**Comment by blogtutor** [comment] 2019-05-20 16:34
...and just happened again, on another site that was updated via Staging Pilot.

This was the third site to have this issue on the most recent 3.3.3.1 update.

**Comment by ecotechie** [comment] 2019-05-20 16:36
Hi @Tabrisrp seems like the commit that closed this issue is only checking for the standard WordPress copy in the .htaccesss file and not any of the custom code that gets stripped. Is this correct? If so, it won't solve this issue. Also I just had a .htaccess file stripped on another site and it took all the directives with it except the WP Rocket ones.

**Comment by vmanthos** [comment] 2019-10-15 05:48
A case which seems similar:
https://secure.helpscout.net/conversation/977417384/126315/

This was on **Dreamhost**.

**Comment by blogtutor** [comment] 2020-03-27 22:54
This is still a problem. We just updated a client from 3.4.4 to 3.5.1. Checked the site after the update and all seemed fine. A couple of hours later she emailed us because only her homepage was working. Sure enough, the .htaccess file had been stripped of everything except the WP Rocket code.

Happened on another site last week as well.

**Comment by goddas** [comment] 2020-03-31 15:13
I've just had a similar issue that might be related to this. My client contacted me with the website being down and only the homepage working. I've checked the htaccess file and it was missing about bottom-500 of the 1000-something lines. So the first 500 or so lines contain the WP Rocket code and some redirects, while the other half containing more redirects and wordpress directives was missing.  The website is hosted on cloudways/digital ocean server

**Comment by mifrero** [comment] 2020-06-15 21:02
Related ticket: https://secure.helpscout.net/conversation/1192263109/172159/

**Comment by ecotechie** [comment] 2020-06-18 17:53
Similar issue with another site. .htaccess was 636 lines, but the update stripped all but the first 134. Left behind the new WP Rocket directives and some `Redirect 301` lines. This seems kinda new, since it used to strip ALL directives except the new WP Rocket ones, but this left some lines behind, like what happened to @goddas above.

Happy to email the files if wanted....

**Comment by webtrainingwheels** [comment] 2020-10-03 02:20
https://secure.helpscout.net/conversation/1297510459/198847?folderId=377611
It's happened to this customer for the last 2 updates. Hosted on 02switch.
It's never reproducible after the first update attempt. Rolling back and updating again will be successful. 
So, what's happening in the very first update routine for each version?

**Comment by vmanthos** [comment] 2020-10-07 03:14
@blogtutor Reported this is still occurring for them:
https://secure.helpscout.net/conversation/1302688547/200372?folderId=3326173

**Comment by vmanthos** [comment] 2020-10-28 09:55
**Possibly related ticket:** https://secure.helpscout.net/conversation/1319380832/205461/
The site is hosted on OVH.

**[WIP]** I'm investigating a similar case that took place on OVH: https://secure.helpscout.net/conversation/1302165472/200249/#thread-3776342425

Please the customer's comment and my findings in the note here: https://secure.helpscout.net/conversation/1319380832/205461/#thread-3804061230

**Comment by vmanthos** [comment] 2020-11-03 06:15
**Update:** I heard back from one of the customers ([ticket](https://secure.helpscout.net/conversation/1302165472/200249/#thread-3820281463)). 

I had prevented WP Rocket from writing to the `htaccess` file on their site. Despite that, the file was corrupted after a few weeks.
Other plugins were writing in that file. 

Most likely this was related to the host, OVH in this case. 
If a process takes too long, it may timeout, and that can corrupt the file.

**Comment by DahmaniAdame** [comment] 2020-11-19 06:35
Possibly related - https://secure.helpscout.net/conversation/1335422175/211113/

**Comment by vmanthos** [comment] 2020-12-15 09:17
**Possibly related:** https://secure.helpscout.net/conversation/1366892923/223063/

**Comment by NataliaDrause** [comment] 2020-12-16 10:18
happened for customer again when updated to 3.8: https://secure.helpscout.net/conversation/1368024563/223391

**Comment by blogtutor** [comment] 2020-12-16 16:30
This is continuing to happen for our clients on Cloudways servers.  I cannot emphasize enough how problematic this is!  It takes the entire site (save the homepage) offline, and leads to an extremely panicked site owner, often requiring emergency response/support at off-hours.

PLEASE PLEASE PLEASE FIX THIS!  I BEG YOU.

**Comment by blogtutor** [comment] 2020-12-16 16:39
Also, have you actually talked with Cloudways about this?  Clearly there's something unique about their setup -- even it is "just" nginx in front of apache... Their frontline support isn't going to be helpful, but perhaps you could work with one of their senior techs or developers?  

I have emailed with a couple of Customer Success Managers and Associate Vice Presidents there -- happy to send along their contact info if that would be helpful.

**Comment by vmanthos** [comment] 2020-12-21 06:46
**Related ticket:** https://secure.helpscout.net/conversation/1366892923/223063/

**Comment by vmanthos** [comment] 2020-12-22 07:13
**Related ticket:** https://secure.helpscout.net/conversation/1374886981/225451?folderId=3326173
**Host:** Hetzner.

**Comment by vmanthos** [comment] 2021-01-11 07:37
**Related ticket:** https://secure.helpscout.net/conversation/1389568405/229477?folderId=2135277
**Host:** Dreamhost

**Comment by NataliaDrause** [comment] 2021-01-13 07:58
**Related ticket:** https://secure.helpscout.net/conversation/1391871951/230082?folderId=3864740
**Host:** WPopt, which uses Litespeed web server

**Comment by NataliaDrause** [comment] 2021-01-13 08:31
**Related ticket:** https://secure.helpscout.net/conversation/1392031396/230125?folderId=3864740
**Host:** OVH

**Comment by vmanthos** [comment] 2021-01-22 07:47
**Potentially related ticket:** https://secure.helpscout.net/conversation/1401738049/232928/

**Comment by vmanthos** [comment] 2021-01-26 10:47
**Related ticket:** https://secure.helpscout.net/conversation/1404506358/233660?folderId=2135277

**Host:** Variomedia AG

**Comment by DahmaniAdame** [comment] 2021-02-19 15:22
Related ticket - https://secure.helpscout.net/conversation/1429056639/240402/
Bluehost - PHP 7.2.34

**Comment by remyperona** [comment] 2021-02-23 20:16
New approach to this issue:

### Scope a solution ✅ 
Use [insert_with_markers()](https://developer.wordpress.org/reference/functions/insert_with_markers/) to handle the writing of our rules in `flush_rocket_htaccess()`. This function is from WP core, and is a more advanced version of what we were doing (including some locking on the file).

The new function would look something like this:

```
function flush_rocket_htaccess( $remove_rules = false ) { // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals
	global $is_apache;

	/**
	 * Filters disabling of WP Rocket htaccess rules
	 *
	 * @since 3.2.5
	 * @author Remy Perona
	 *
	 * @param bool $disable True to disable, false otherwise.
	 */
	if ( ! $is_apache || ( apply_filters( 'rocket_disable_htaccess', false ) && ! $remove_rules ) ) {
		return false;
	}

	if ( ! function_exists( 'get_home_path' ) ) {
		require_once ABSPATH . 'wp-admin/includes/file.php';
	}

	if ( ! function_exists( 'insert_with_markers' ) ) {
		require_once ABSPATH . 'wp-admin/includes/misc.php';
	}

	$htaccess_file = get_home_path() . '.htaccess';
	$insertion     = '';

	if ( ! $remove_rules ) {
		$insertion = get_rocket_htaccess_marker();
	}

	// Update the .htaccess file.
	return insert_with_markers( $htaccess_file, 'WP Rocket', $insertion );
}
```

This change was tested as part of some R&D, and is working well on a local installation.

This also should be done as part of our refactor of the htaccess related code (#2759), and unit/integration tests added for it.

### Estimate the effort ✅
For this specific part, effort is `[S]`

**Comment by NataliaDrause** [comment] 2021-03-04 10:38
Likely related: https://secure.helpscout.net/conversation/1443506061/244478/

**Comment by vmanthos** [comment] 2021-03-16 12:11
**Probably related:** https://secure.helpscout.net/conversation/1453543452/247525

**Comment by webtrainingwheels** [comment] 2021-04-02 21:05
https://secure.helpscout.net/conversation/1472418626/252775?folderId=377611

**Comment by vmanthos** [comment] 2021-06-04 08:59
https://secure.helpscout.net/conversation/1533549436/269214/

**Comment by viobru** [comment] 2021-11-09 13:35
Likely related: https://secure.helpscout.net/conversation/1689883663/306382/

**Comment by DahmaniAdame** [comment] 2021-11-10 10:35
Related - https://secure.helpscout.net/conversation/1692317594/306872/

**Comment by girlie** [comment] 2021-11-16 19:36
Possibly related: https://secure.helpscout.net/conversation/1698187133/308160/

**Comment by viobru** [comment] 2021-11-19 15:37
Likely related: https://secure.helpscout.net/conversation/1700810367/308709/

**Comment by vmanthos** [comment] 2022-02-22 06:49
Likely related: https://github.com/wp-media/wp-rocket/issues/928

**Comment by vmanthos** [comment] 2022-03-11 13:22
Likely related: https://secure.helpscout.net/conversation/1812727658/330905?folderId=2135277

**Comment by NataliaDrause** [comment] 2022-03-24 12:30
Related: https://secure.helpscout.net/conversation/1800185693/328586/

**Comment by girlie** [comment] 2022-04-26 15:11
Possibly related: https://secure.helpscout.net/conversation/1860578815/339247/

**Comment by NataliaDrause** [comment] 2022-04-27 09:57
Related: https://secure.helpscout.net/conversation/1861813545/339437?folderId=3864740
The customer clarified that the issue is happening when posts are being saved/updated.

**Comment by DahmaniAdame** [comment] 2022-05-20 08:05
Related - https://secure.helpscout.net/conversation/1888771471/343723

As per the customer's feedback, the following two lines were duplicated: 

```
</IfModule>
# END WordPress
```

In another update, WP Rocket added its HTACCESS rules in double.

**Comment by ghost** [comment] 2022-05-27 08:09
Over the past months, i had few sites aswell that got the same issue.
The only temporary fix i have for now is to set `.htaccess` to 444 permissions, but it's quite problematic as you can guess.
Host: **O2switch** _(which use LiteSpeed Web Server)_

**Comment by girlie** [comment] 2022-07-17 18:47
Related: https://secure.helpscout.net/conversation/1950922043/356255/

**Comment by webtrainingwheels** [comment] 2022-08-11 21:52
https://secure.helpscout.net/conversation/1972938073/360746?folderId=377611

**Comment by DahmaniAdame** [comment] 2022-09-01 09:45
Related - https://secure.helpscout.net/conversation/1995090338/365198/

**Comment by MathieuLamiot** [comment] 2023-08-08 13:53
To be added to the next sprint, to try and target next major release if possible by QA availability.

**Comment by DieWebmacherin** [comment] 2023-10-06 08:38
Still happening in in the current version. But as far as I see you are already working on a fix. :)

**Comment by bwafels** [comment] 2023-10-27 08:58
I don't know if it is related, but over the years I have had to click on "update permalinks" often when I update multiple plugins (WPML) and WP-Rocket. Before there are 404 issues and sometimes and empty store on the secondary language.

**Closed** 2024-04-29 19:49 UTC
Labels: type: bug, module: htaccess, priority: high, effort: [S], severity: critical
