### ISSUE TITLE
Fatal error on Rollback from 3.11.3 version to 3.10.9

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5104] opened 2022-06-01 10:25 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
The following fatal error comes up on rollback from 3.11.3 to 3.10.9:

```
[01-Jun-2022 09:47:54 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_Lock' not found in .../wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php:29
Stack trace:
#0 .../wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(103): ActionScheduler::lock()
#1 .../wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->maybe_dispatch_async_request('')
#2 .../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 .../wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 .../wp-includes/load.php(1100): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in .../wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler.php on line 29
```

**To Reproduce**
1. Have version 3.11.3 installed and activated
2. Use Tools tab option to Rollback to 3.10.9
3. The fatal error will be logged

**Expected behavior**
No errors should be logged

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1905508352/346096/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment] 2022-06-01 10:27
a similar issue was reported here: https://github.com/wp-media/nodejs-treeshaker/issues/41

**Comment by engahmeds3ed** [comment] 2022-06-01 10:40
This may happen when an action is working on the background and u try rollback so I believe we can cancel all active Action Scheduler actions when rollback.

**Comment by NataliaDrause** [comment] 2022-06-01 10:44
I also reproduced it with a fresh 3.11.3 copy (no Remove Unused CSS is enabled, only default settings), and no pending AS actions from us: https://i.imgur.com/wewUNWG.png

**Comment by piotrbak** [comment] 2022-06-01 13:06
@NataliaDrause does it cause site being inaccessible? Or just fatal error is logged? 🤔

**Comment by NataliaDrause** [comment] 2022-06-01 13:43
@piotrbak only the error in the log and only once. After that, it seems to be working fine with no errors.

**Comment by jeawhanlee** [comment] 2022-06-06 13:49
@piotrbak I wasn't able to reproduce this issue perhaps there are other factors to consider to reproduce it @NataliaDrause ?

**Comment by piotrbak** [comment] 2022-06-06 14:05
@jeawhanlee Could you try it on a bigger site? Like:
1. Disable Preload completely, make sure that there are no RUCSS entries in DB 
2. Enable RUCSS 
3. Enable sitemap preload (to preload at least 100 URLs)
4. Wait around 1 minute and rollback

**Comment by jeawhanlee** [comment] 2022-06-06 14:10
> I also reproduced it with a fresh 3.11.3 copy (no Remove Unused CSS is enabled, only default settings), and no pending AS actions from us: https://i.imgur.com/wewUNWG.png

@piotrbak  Ok will do that
I was just considering what @NataliaDrause natalia stated here about Removed Unused CSS being disabled. 🙂

**Comment by jeawhanlee** [comment] 2022-06-07 13:24
### Reproduce the problem
I was able to reproduce the error on a much larger site as recommended by @piotrbak with the steps given.

### Identify the root cause
As stated by @engahmeds3ed This happened because there was a running action before trying to rollback and since 3.10.9 does not introduce `AS` just yet, the class is undefined and an error is thrown.

### Scope a solution
I think we can add a new filter here maybe `rocket_cancel_rucss_queues` before this line
https://github.com/wp-media/wp-rocket/blob/95d626766fe72bdb1a49f39070bd9846598181d9/inc/admin/admin.php#L211

then here `WP_Rocket\Engine\Optimization\RUCSS\Admin` we can hook the cancel_queues method.

What do you think? @Tabrisrp

### Estimate the effort
[xs]

**Comment by remyperona** [comment] 2022-06-07 15:27
The idea is good, I created a new filter in this PR, you can re-use to do this change https://github.com/wp-media/wp-rocket/pull/5105/files#diff-36ba3dfbe3bfc24e0e008d6506a06f4b35ae273b89234eebb5948c96ba0b6e26

**Comment by piotrbak** [comment] 2022-07-04 12:27
We are still having this issue with 3.11.4. @wp-media/php do you think we have any option to guard against it in a reliable way?

**Comment by Mai-Saad** [comment] 2022-07-04 12:37
Notes for a retest: we need to check using a zip file while PHP 7.4 and PHP 8.1.7

**Comment by jeawhanlee** [comment] 2022-08-01 11:55
Closing until issue resurfaces.

**Closed as completed by jeawhanlee** 2022-08-01 11:55 UTC
Labels: type: bug, module: tools, priority: medium, severity: major
