### ISSUE TITLE
Delay JS add compatibility exclusions for Sassy Social Share plugin on WP Rocket core

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#4339] opened 2021-09-08 18:43 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
WP Rocket 3.9.3 ✔
- Used the search feature to ensure that the bug hasn’t been reported before
Exclusions are added on the [Delay JS compatibility exclusions article](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#sassy-social-share), but it would be useful checking if they must be added on the core. 

**Describe the bug**
When the feature Delay JS is enabled, the social share buttons for Twitter, Facebook, etc. (buttons that opens a pop up) doesn't work. 

**To Reproduce**
1. Install and enable the plugin [Sassy Social Share](https://wordpress.org/plugins/sassy-social-share/) 
2. Enable Delay JS execution on WP Rocket
3. Go to a post and try to share it in Facebook, twitter or any other social network that opens a pop up (Pinterest does'nt open a pop up. 

**Expected behavior**
Adding the scripts listed on de compatibility exclusions article solve the issue. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment] 2021-09-09 11:37
Note: couldn't reproduce on the test site using the free Sassy Social Share plugin.

**Comment by piotrbak** [comment] 2023-02-14 11:12
Will be fixed in the 3.13 backend

**Comment by piotrbak** [comment] 2023-04-05 11:54
Handled in 3.13 using dynamic lists

**Closed as completed by piotrbak** 2023-04-05 11:54 UTC
Labels: type: enhancement, 3rd party compatibility, module: delay JS
