### ISSUE TITLE
Update lazyLoad to 17.4

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [wp-media/wp-rocket#4365] opened 2021-09-20 16:04 UTC
**Is your feature request related to a problem? Please describe.**
Bundled LazyLoad script is 16.1 while since some time ago we have 17.4.

**Describe the solution you'd like**
Update it from: https://github.com/verlok/vanilla-lazyload/releases/tag/17.4.0

**Comment by remyperona** [comment] 2021-09-20 18:29
Duplicate of #3510

**Closed as completed by remyperona** 2021-09-20 18:29 UTC
Labels: duplicate
