### ISSUE TITLE
Make Cache Lifespan to purge Cloudflare Cache Everything cache

### ISSUE THREAD

**Issue by mviniciosbarreto** [wp-media/wp-rocket#6407] opened 2024-01-23 15:00 UTC
**Is your feature request related to a problem? Please describe.**

In the current implementation of the Cloudflare Add-On, we are not handling Cache Lifespan synchronization to clear Cloudflare Cache Everything Cache when the files are expired.

**Describe the solution you'd like**
Once WP Rocket Cache Lifespan clears the expired cache, it should clear the cache on the Cloudflare Cache Everything as well.

**Additional context**
This was a question by a customer in this ticket: https://secure.helpscout.net/conversation/2483701338/469638/ which makes total sense and it is really expected. And we have a similar request for Cloudflare APO here: https://github.com/wp-media/wp-rocket/issues/6170

Slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1705938390789079

**Comment by piotrbak** [comment] 2024-06-28 15:03
It's potentially a duplicate of:
https://github.com/wp-media/wp-rocket/issues/6170

We'll fix them together

**Closed as not planned by piotrbak** 2024-06-28 15:03 UTC
Labels: type: enhancement, 3rd party compatibility, module: cloudflare, priority: low
