### ISSUE TITLE
RocketCDN campaign name display only if is_discount_active and end_date are valid

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#3033] opened 2020-08-27 08:50 UTC
Currently RocketCDN will display the campaign name if the campaign is filled and do not take into consideration the `end_date` and `is_discount_active`.

So we end up in the situation when the campaign is expired or not active, however in WP Rocket the Campaign Name is still displayed only because this field is filled. 

The issue is in here because it checks only the campaign_name. Instead it should check also that the campaign is active and end_date is still valid.
https://github.com/wp-media/wp-rocket/blob/7e8d54aaf5ad8ddffda404d7011931f1a43f3a53/views/settings/rocketcdn/cta-big.php#L20

**Comment by Tabrisrp** [comment] 2020-08-27 10:51
Duplicate of #2854 ?

**Comment by Tabrisrp** [comment] 2020-11-03 17:15
### Scope a solution
In `NoticesSubscriber`, check for `is_discount_active` and `end_date` before populating the value for the promotion campaign name.

### Estimate the effort
Effort `[XS]`

**Closed** 2020-11-04 15:37 UTC
Labels: effort: [XS], module: rocketcdn, priority: low, type: bug
