### ISSUE TITLE
CSS Variables getting 0px replaced with 0

### ISSUE THREAD

**Issue by hogash** [wp-media/wp-rocket#2083] opened 2019-10-30 06:15 UTC
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When using CSS variables, if they're having `0px` it's trimmed to `0` causing css `calc()` or other operations to break.

**To Reproduce**
##### Uncompressed:
```
:root {
  --some-variable: 0px;
}
:root[data-custom-value="1"] {
  --some-variable: 20px;
}
.some-class {
  height: calc( 100vh - var(--some-variable) );
}
```
##### Compressed:
```
:root {
  --some-variable: 0;
}
...
```
In this example if the html tag doesn't have the `data-custom-value` attribute, the `some-class` height calc operation will fallback on the the first declaration, which had, which breaks because the `calc` operation needs the `0px` , not `0` without the unit. 
The magic of CSS variables is obvious in this example. I don't have to redeclare chained classes to meet the conditions.

**Expected behavior**
The patterns are obvious to trim px in 0px declarations (which do make a lot of sense). Would be great to ignore CSS variables, or to have some sort of flag, eg: !wprocket-ignore;

**Comment by ScottTravisHartley** [comment] 2019-11-07 19:19
Related issue: https://github.com/wp-media/wp-rocket/issues/1554

**Comment by Tabrisrp** [comment] 2019-11-23 09:51
This seem to be a bug in the minify library we are using: [Minify](https://github.com/matthiasmullie/minify)

Unfortunately the maintainer doesn't seem to update it anymore, so we have to consider the different options we have going forward to improve the minification and resolve some bugs we have.

**Comment by hogash** [comment] 2019-11-23 09:56
@Tabrisrp hope there are alternatives. Or at least the maintainer to accept pull requests.

Anyway, for this particular issue, if anyone is seeking a fix, replacing `0px` with `0.001px` should trick the minifier.

**Comment by Tabrisrp** [comment] 2019-11-23 10:06
There are alternative solutions available if we still get nothing from the library maintainer. This will require some planning on our side to switch, but this is absolutey doable.

**Comment by DahmaniAdame** [comment] 2021-03-25 07:05
Related - https://secure.helpscout.net/conversation/1463024658/250308

The minification library seems to have fixed it - https://github.com/simondud/minify/commit/556e5d1640684fb7397ceff549acbb52503ff438

**Comment by DahmaniAdame** [comment] 2022-08-16 12:08
@piotrbak reopening this one because the issue is still there. 

Tested by adding `:root {--test-margin-offset: 0px}` and minifying it. 

It returned: `:root{--test-margin-offset:0}`.

Ticket - https://secure.helpscout.net/conversation/1978873460/361870/

**Comment by piotrbak** [comment] 2022-08-16 12:25
@DahmaniAdame It seems that library doesn't process this CSS correctly when it's in one line:
```
:root {
 --test-margin-offset: 0px
}
```
In the above example the `px` is preserved correctly, in the below not at all:
```
:root {--test-margin-offset: 0px}
```

**Comment by piotrbak** [comment] 2022-08-16 12:34
It's fixed in the library here:
https://github.com/matthiasmullie/minify/issues/397

**Comment by DahmaniAdame** [comment] 2022-08-17 05:01
@piotrbak yes, it seems indeed it's only happening when there is no return to the line!

**Comment by DahmaniAdame** [comment] 2022-08-18 05:21
Tested the updated regex by replacing the following line:

https://github.com/wp-media/wp-rocket/blob/95912c3f648820dfd04119d4fe187834a552ebee/inc/Dependencies/Minify/CSS.php#L743

With: 

```
'/(?<=^|[;}{])\s*(--[^:;{}"\'\s]+)\s*:([^;{}]+)/m',
```

It's working! The unit is preserved.

**Closed** 2023-01-20 14:29 UTC
Labels: type: bug, community, 3rd party compatibility, priority: medium, severity: moderate, module: minify CSS
