### ISSUE TITLE
PHP Deprecated : ip_in_range.php on line 108

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2430] opened 2020-03-16 17:55 UTC
Dear,

I'm receiving many errors in my debug.log file with the below description. There seem to be a deprecation in WP Rocket 3.5.0.4 under PHP 7.4.

[16-Mar-2020 17:24:39 UTC] PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/customer/www/DOMAIN/public_html/wp-content/plugins/wp-rocket/inc/vendors/ip_in_range.php on line 108

Can you please fix it?
Thanks

**Steps to reproduce**
- PHP 7.4
- Website on Cloudflare
- IPv6

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by gevcen** [comment] 2020-03-16 18:01
This is causing hundreds of error lines in my debug.log

Could you make a fix for this in a minor release, as soon as possible please?

Thanks

**Comment by webtrainingwheels** [comment] 2020-03-19 21:29
Another case here: https://secure.helpscout.net/conversation/1110611252/151918?folderId=273761

**Comment by webtrainingwheels** [comment] 2020-03-20 17:05
Another one: https://secure.helpscout.net/conversation/1115385833/152915?folderId=273761

**Comment by camilamadronero** [comment] 2020-03-21 14:50
Another one:
https://secure.helpscout.net/conversation/1115385833/152915/

**Comment by GeekPress** [comment] 2020-03-23 07:33
**Steps to reproduce**
- PHP 7.4
- Cloudflare add-on enabled

**Comment by Tabrisrp** [comment] 2020-03-23 13:16
**Reproduce the problem** ✅ 
We would need a website with PHP 7.4, Cloudflare, and someone who uses IPv6 to reproduce ourselves. We have a good number of tickets to see that the issue is reproduced though.

**Identify the root cause** ✅
This is happening because starting with PHP 7.4, `base_convert()` sends a notice when invalid characters are used for its first parameter. Before, it was ignoring them silently.

**Scope a solution** ✅
A solution is to sanitize the value passed to `base_convert()` beforehand, to only preserve valid characters. Those are `[0-9a-fA-F]` since IPv6 uses a base 16 format (hexadecimal).

**Estimate the effort** ✅
effort: `[S]`, need tests for `rocket_ip2long6()`

**Comment by Tabrisrp** [comment] 2020-03-24 13:35
An update on this one.

I discovered that there is an official package from Cloudflare to handle IP checking and rewriting: https://github.com/cloudflare/cf-ip-rewrite

It's an updated and tested version of the code they had in the old version of the Cloudflare plugin, from which we extracted some parts, notably the one in `ip_in_range.php`.

Using this package can simplify and improve our own codebase.

**New solution proposed**:
- Deprecate functions in `inc/vendors/ip_in_range.php`
- Deprecate functions in `inc/common/cloudflare-flexible-ssl.php`
- Add the `cloudflare/cf-ip-rewrite` package as a dependency
- Do the check contained in `rocket_fix_cf_flexible_ssl` directly in `inc/main.php`, by using the available method `isCloudFlare()` from the package

**Comment by hellofromtonya** [comment] 2020-03-24 13:41
@Tabrisrp We eliminated our dependency on 3rd party CF packages in 3.5. But we missed refactoring this particular file. 

I'm concerned that moving to this 3rd party package _may_ introduce new problems. We would need a thorough vetting process to validate every part of it.

Instead I'd suggest:

1. Discover the root cause of the problem. Fix it.
2. Move this file to our Cloudflare package.
3. And then for a future improvement, we could evaluate this 3rd party package to improve our implementation(s).

**Comment by hellofromtonya** [comment] 2020-03-24 14:06
>We would need a website with PHP 7.4, Cloudflare, and someone who uses IPv6 to reproduce ourselves. We have a good number of tickets to see that the issue is reproduced though.

@Tabrisrp I just upgraded knowthecode.dev on SiteGround to PHP 7.4.3.

**Comment by mifrero** [comment] 2020-04-13 14:50
Another case: 
https://secure.helpscout.net/conversation/1135292505/157623?folderId=273761

**Comment by GeekPress** [comment] 2020-04-13 14:52
**Customer to follow up after release:**
- https://secure.helpscout.net/conversation/1110611252/151918?folderId=273761
- https://secure.helpscout.net/conversation/1115385833/152915?folderId=273761
- https://secure.helpscout.net/conversation/1109856608/151742/
- https://secure.helpscout.net/conversation/1106092504/150567/
- https://secure.helpscout.net/conversation/1115385833/152915/
- https://secure.helpscout.net/conversation/1135292505/157623?folderId=273761

**Closed** 2020-04-17 14:24 UTC
Labels: community, effort: [S], priority: high, type: bug
