### ISSUE TITLE
RUCSS progress bar

### ISSUE THREAD

**Issue by bwafels** [wp-media/wp-rocket#6111] opened 2023-08-18 06:34 UTC
**Is your feature request related to a problem? Please describe.**
It seems like my site never fully processes for RUCSS. It is however very difficult to troubleshoot as there is no way to verify how much of the site has been processed and on what pages it is blocked.

**Describe the solution you'd like**
I would like a progress bar or a page hosted by WP-Rocket to check on the RUCSS function of my site.

**Describe alternatives you've considered**
WP-Rocket support has been assisting, but a reason could not be found yet. I prefer to continue troubleshooting.

**Comment by webtrainingwheels** [comment] 2023-08-21 18:03
Duplicate of: https://github.com/wp-media/wp-rocket/issues/5413

**Closed as completed** 2023-08-28 09:48 UTC
Labels: duplicate
